- packages/local-cli/.watchmanconfig
- packages/local-cli/core/index.js
- packages/local-cli/util/Config.js
- packages/local-cli/util/findReactNativePath.js
CLI still depends on some files from React Native (two, to be specific) and we require them for now. This should be refactored in the future, but I am limiting changes until now to bare minimum.
> Support requring React Native paths outside of the CLI

- packages/local-cli/package.json
- yarn.lock
`@babel/core` should be in deps, not deve deps, as it's necessary for `@babel/register`
> fix: move @babel/core to deps

- packages/local-cli/server/middleware/getDevToolsMiddleware.js
- packages/local-cli/server/server.js
Opening `dev tools` was causing opening of `chrome` browser on a wrong URL.
Dev tools are opened on default `port` and `host`. Default `port` is `8081` and `host` is `localhost`.
If you want to change the default behavior, you can do it by providing `--host` and `--port` cmd arguments.
> fix: Fix opening dev tools

- packages/global-cli/package.json
- packages/local-cli/package.json
This makes it easier to find the new repo of these packages through npm (it's becomes a link at https://www.npmjs.com/package/react-native-cli).
> Add repository URLs to package.json files

- packages/local-cli/server/runServer.js
We didn't pass the port to the middleware manager which is needed by the `getDevToolsMiddleware` to launch chrome dev tools.
> Fix launching chrome dev tools

- packages/local-cli/link/__tests__/__snapshots__/getDependencyConfig-test.js.snap
- packages/local-cli/link/__tests__/getDependencyConfig-test.js
- packages/local-cli/link/__tests__/link-test.js
- packages/local-cli/link/getDependencyConfig.js
- packages/local-cli/link/link.js
- packages/local-cli/link/unlink.js
Make `packageName` required in `link` command.
Fixes: #48
> imp: Make package name a required argument in link

- .gitignore
- packages/local-cli/runAndroid/__tests__/runOnAllDevices.test.js
- packages/local-cli/runAndroid/getAdbPath.js
- packages/local-cli/runAndroid/runAndroid.js
- packages/local-cli/runAndroid/runOnAllDevices.js
- packages/local-cli/runAndroid/tryLaunchAppOnDevice.js
- packages/local-cli/runAndroid/tryRunAdbReverse.js
Fixes #32.
Extracting bunch of functions to its own files too + adding tests.
For not being a breaking change, default behavior (without passing `--appFolder`) will be just to call `installDebug`.
> fix: --appFolder should only install specific app on Android.

- packages/global-cli/index.js
Fixes #42
Tested on a new project:
- `init` using global cli (`../react-native-cli/packages/global-cli/index.js init RNtest`)
- `start` using local cli (`yarn start`)
- `start` using global cli (`../../react-native-cli/packages/global-cli/index.js start`)
> chore: update global-cli paths

- packages/local-cli/link/__fixtures__/android/patchedBuild.gradle
- packages/local-cli/link/__tests__/android/isInstalled-test.js
- packages/local-cli/link/__tests__/android/makeBuildPatch-test.js
- packages/local-cli/link/__tests__/link-test.js
- packages/local-cli/link/android/patches/makeBuildPatch.js
Fixes #43
- Improved the Regex to be more forgiving in terms of spacing and `implementation`/`compile` names with variants and configs
- add more thorough test
- cleanup makeBuildPatch test to not test implementation details
- cleanup link test so it doesn't output to stdout unnecessarily
- tested on a project I had issues with duplicates (resolved with this diff)
cc @ferrannp
> fix: android duplicates in linked packages

- packages/local-cli/runIOS/findMatchingSimulator.js
`findMatchingSimulator` could crash if the simulator's name is custom (renamed in Xcode) for ex: `iPhone6v11`.
After this fix it doesn't crash and the correct custom named simulator is chosen.
> Prevent crash in findMatchingSimulator

- packages/local-cli/util/loadMetroConfig.js
Metro depends on some private React Native files when starting the server. We are using "require.resolve", which does not work when we actually run CLI from within React Native master (there's no "react-native" package in "node_modules").
I wanted to avoid hacking around "require.resolve" and paths to support that particular use-case. Doing that might become brittle in the future when we add PnP support etc., where "node_modules" awareness might become a problem.
I consider this a temporary hack and hopefully we can do better in the future, e.g. by creating a special package, such as: "react-native-bundler-compat", so that other bundles, such as Webpack can also use these files.
To make this working in React Native, the following "metro.config.js" has to be created:
``` …
```
> Fix metro config when running from source

- packages/local-cli/link/link.js
- packages/local-cli/link/linkAll.js
- packages/local-cli/link/linkAssets.js
- packages/local-cli/link/linkDependency.js
Deprecate `react-native link` without specifying `packageName`.
Tests:
1. Init new project with `react-native init $project_name`
2. Install a couple of native dependencies that need to be linked
3. Invoke `link` command
```
node path/to/cli/packages/local-cli/cli.js link
```
Modules are linked correctly but we get deprecation notice.
> build: deprecate link all behavior

- packages/local-cli/init/init.js
The initial version of the package.json file does not contain a newline at the end. This means that the first time a user modifies the file using either an IDE that inserts trailing newlines or using Yarn, the last line will be changed and visible in version control. This is not a big deal, but it is annoying and shows a lack of polish.
I tested this by manually patching this file in a current version of React Native because there is currently no way to test the master of RN and RN cli together.
> fix: add newline in package.json

- packages/local-cli/link/__fixtures__/android/patchedBuild.gradle
- packages/local-cli/link/__tests__/android/isInstalled-test.js
- packages/local-cli/link/android/patches/makeBuildPatch.js
Looking at expo uni modules I've noticed `api` usage in gradle, more on this here: https://medium.com/mindorks/implementation-vs-api-in-gradle-3-0-494c817a6fa
This PR adds support to `api` next to `implementation` and `compile`.
> fix: make link understand 'api project'

- packages/cli/package.json
- packages/cli/src/link/__tests__/android/makeSettingsPatch-test.js
- packages/cli/src/link/android/patches/makeSettingsPatch.js
- yarn.lock
Summary:
---------
Fixes #129
Test Plan:
----------
I added a test that simulates Windows on POSIX machines, because we don't run our tests on Windows.
@cherniavskii can you test this on a Windows machine?
> fix: normalize paths for Gradle on Windows

- packages/cli/src/runIOS/runIOS.js
Summary:
---------
This PR adds `schema` folder to the ios build path
to resolve issue https://github.com/facebook/react-native/issues/20497
Test Plan:
----------
1. Setup a different scheme with different environment variables for the same app. ex) exampleApp, exampleAppDev
2. run `react-native run-ios --scheme exampleApp`
3. should install and run exampleApp with `a` variable
4. run `react-native run-ios --scheme exampleAppDev`
5. should install and run exampleAppDev with `b` variable
> fix: schema option on run-ios not installing and loading the right bundle

- .flowconfig
- packages/cli/src/cliEntry.js
- packages/cli/src/core/getPlatforms.js
- packages/cli/src/runIOS/runIOS.js
- packages/cli/src/util/errors.js
- packages/cli/src/util/logger.js
Fixes #107 
Summary:
---------
Bugs fixed:
- "CFBundleIdentifier" printed every time "run-ios" fails, shadowing the real cause for the problem
- "run-ios" running a previous/cached version of an app (usually when there was an error during build step that was ignored)
Changes made:
- Decided to turn Flow and ESLint and apply all the changes as I am working on it. I know the diff might be strange at first sight, but if you look closely, it's just cosmetics to satisfy various rules
- I also extracted some blocks to separate utilities for better readability
- I also removed a no longer needed check for CRNA which is deprecated (and IMO, is not needed)
- Converted few functions to "async" form for better readability
- Started capturing the "stderr" of "xcodebuild" and started relying on its …
> fix: improve overall run-ios experience and get rid of CFBundleIdentifier

- packages/cli/src/runAndroid/runAndroid.js
Fixes #126 
We need to change this approach, issue tracking in #140.
> fix: run-android not finding scripts to overwrite

- packages/cli/package.json
- packages/cli/src/bundle/buildBundle.js
- packages/cli/src/cliEntry.js
- packages/cli/src/core/types.flow.js
- packages/cli/src/init/init.js
- packages/cli/src/runAndroid/runAndroid.js
- packages/cli/src/server/runServer.js
- packages/cli/src/util/loadMetroConfig.js
- yarn.lock
Summary:
---------
This PR fixes `require.resolve` logic for looking up React Native location. It will now resolve React Native from the current working directory, instead of __dirname. Thanks to this subtle change, we don't need `react-native` to be a dev dependency of CLI. We will now load React Native from the "node_modules" of a project we are testing CLI on.
It also allows to overwrite path to `react-native` when require.resolve does not provide good results. For example, we can pass a location to React Native repository (when we have it cloned) to run CLI on master of React Native (case: checking compatibility without releasing a new version) or to run RNTester example app (where there is no React Native package in node_modules).
Partially addresses #143. I will send another …
> feat: allow setting different React Native path

- packages/cli/src/generator/copyProjectTemplateAndReplace.js
- packages/cli/src/generator/printRunInstructions.js
- packages/cli/src/generator/templates.js
- packages/cli/src/init/init.js
- packages/cli/src/logAndroid/logAndroid.js
- packages/cli/src/logIOS/logIOS.js
- packages/cli/src/runAndroid/runAndroid.js
- packages/cli/src/runAndroid/runOnAllDevices.js
- packages/cli/src/runAndroid/tryLaunchAppOnDevice.js
- packages/cli/src/runAndroid/tryRunAdbReverse.js
- packages/cli/src/runIOS/runIOS.js
- packages/cli/src/server/middleware/copyToClipBoardMiddleware.js
- packages/cli/src/server/middleware/getDevToolsMiddleware.js
- packages/cli/src/server/middleware/systraceProfileMiddleware.js
- packages/cli/src/server/util/debugger-ui/debuggerWorker.js
- packages/cli/src/server/util/jsPackagerClient.js
- packages/cli/src/server/util/launchChrome.js
- packages/cli/src/server/util/messageSocket.js
- packages/cli/src/server/util/webSocketProxy.js
- packages/cli/src/upgrade/upgrade.js
- packages/cli/src/util/copyAndReplace.js
- packages/cli/src/util/yarn.js
- packages/global-cli/index.js
Summary:
---------
Based on #95, replaced `console.(log|warn|error)` by `logger.(info|warn|error)`.
Used regular expressions but everything seems to be working as should.
Test Plan:
----------
All tests are passing, no other change was required.
> refactor: Unify logging

- packages/cli/src/runIOS/findMatchingSimulator.js
Summary:
---------
In Xcode 10.2, the output of `xcrun simctl list --json devices` has changed to include a namespace within each version group. This commit makes a backwards-compatible adjustment to account
for this change in format.
To illustrate:
```
{
"devices": {
"iOS 10.0": [
...
]
}
}
```
```
{
"devices": {
"com.apple.CoreSimulator.SimRuntime.iOS-10-0": [
...
]
}
}
```
This is a trivial change that, by human inspection, should clearly be backwards-compatible with the previous code. The question, then, is whether this change addresses the problem of the `run-ios` command not being able to find any simulators on a machine with Xcode 10.2.
Below is the actual output of running `xcrun simctl list --json devices` on my device (running MacOS 10.14.3 and Xcode 10.2 Beta):
```
{
"devices" …
```
> fix: xcode 10.2 compatibility for `run-ios` command

- babel.config.js
- package.json
Summary:
---------
After #150 (thanks @sidferreira and @Trancever) we're finally able to use lazy module evaluation for additional perf! 
Before:
```
0.70 real         0.64 user         0.12 sys
```
After:
```
0.19 real         0.16 user         0.03 sys
```
Which gives us roughly 0.5s (~72%) improvement in startup time. With 0.2s startup time most commands feel instant now.
Test Plan:
----------
No new tests added.
> feat(perf): use lazy module evaluation

- CONTRIBUTING.md
Summary:
Added section in `CONTRIBUTING.md`, explaining how to run `init` command localy. This might also be helpful in potential integration testing.
> docs: init command localy

- packages/cli/jest.config.js
- packages/cli/src/util/logger.js
- packages/cli/testSetup.js
Summary:
---------
Disable annoying logs in a `test` environment.
Test Plan:
----------
```
➜  react-native-cli git:(master) ✗ yarn test
yarn run v1.13.0
$ jest
PASS  packages/cli/src/runIOS/__tests__/findMatchingSimulator-test.js
PASS  packages/cli/src/util/__tests__/findSymlinkedModules-test.js
PASS  packages/cli/src/server/util/debugger-ui/__tests__/DeltaPatcher-test.js
PASS  packages/cli/src/core/__tests__/findPlugins-test.js
PASS  packages/cli/src/link/__tests__/android/makeSettingsPatch-test.js
PASS  packages/cli/src/link/__tests__/ios/getHeaderSearchPath-test.js
PASS  packages/cli/src/core/__tests__/ios/findProject-test.js
PASS  packages/cli/src/core/__tests__/android/getProjectConfig-test.js
PASS  packages/cli/src/bundle/__tests__/getAssetDestPathAndroid-test.js
PASS …
```
> refactor: disable logger in tests

- packages/cli/src/generator/printRunInstructions.js
- packages/cli/src/generator/templates.js
- packages/cli/src/init/init.js
- packages/cli/src/util/logger.js
Summary:
---------
Test Plan:
----------
Tested it initializing new project using a custom template.
Here are logs. They are quite lengthy.
<details>
```
➜  projects react-native init xxx --template mobx --version 0.69.0
This will walk you through creating a new React Native project in /Users/kacper/projects/xxx
Using yarn v1.13.0
Installing react-native@0.69.0...
yarn add v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native@0.69.0" has unmet peer dependency "react@16.6.3".
warning "react-native > @react-native-community/cli@10.0.0" has incorrect peer dependency "react-native@^0.57.0".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency …
```
> refactor: use PackageManager and improve init logging

- packages/cli/src/cliEntry.js
- packages/global-cli/index.js
Summary:
---------
This PR adds the default behaviour of calling the CLI without any args to be the `--help` command.
Fixes #158.
Test Plan:
----------
Run the following:
```bash
node path/to/the/react-native-cli/packages/cli/build/index.js
node path/to/the/react-native-cli/packages/global-cli/index.js
```
> feat: show help when no arguments are provided

- packages/cli/src/runAndroid/adb.js
- packages/cli/src/runAndroid/runAndroid.js
- packages/cli/src/runAndroid/runOnAllDevices.js
Fixes #132
- Works well with `enableSeparateBuildPerCPUArchitecture`, `universalApk` options.
- Even if it is already installed, it works normally. (Added -r option to `adb install`)
I hope this helps.
> Fix: problem on run-android with deviceId

- packages/cli/src/cliEntry.js
- packages/cli/src/generator/printRunInstructions.js
Summary:
---------
This fixes few of the issues that I've encountered working in a React Native repository.
When you pass a wrong command or provide no command at all (say, you want to print `--help`) and your CLI works by setting `--projectRoot` or `--reactNativePath` (in React Native repository, this is a must), you end up with a "Unrecognised option" error.
This PR changes that, so that it works and is accepted.
It also fixes a missing path to a inited application that is a regression introduced in https://github.com/react-native-community/react-native-cli/commit/72c3dd4282996891442c3ec779e99d989a74c440#diff-d9b7abe65a1a1a0e0b19ec93292008eaR16. We wrongly assumed `process.cwd()` remains the directory the command has been run from. Turns out, it's modified by the init script.
> fix: improve cli interface

- packages/cli/src/util/loadMetroConfig.js
Summary:
---------
This fixes the 2nd issue as described here: https://github.com/react-native-community/react-native-releases/issues/79#issuecomment-463394781
Test Plan:
----------
As indicated on https://github.com/react-native-community/react-native-releases/issues/79#issuecomment-463394781 - without this change various errors occur due to missing globals, with this change applied these errors no longer occur on my local project tested with Detox:
> Return full file path for `InitializeCore` incl. extension

- packages/cli/src/util/loadMetroConfig.js
Summary:
---------
This PR addresses the first issue described in [this comment](https://github.com/react-native-community/react-native-releases/issues/79?#issuecomment-463394781).
**Example usage before CLI was moved**: 
See https://github.com/ueno-llc/react-native-starter/blob/master/metro.config.js
**Example usage after move + this PR:**
```js
// metro.config.js
const { resolve } = require('path');
const { mergeConfig } = require('metro-config');
const { getDefaultConfig } = require('@react-native-community/cli/build/util/loadMetroConfig');
const root = __dirname;
const reactNativePath = resolve(root, './node_modules/react-native');
const config = {
resolver: {
sourceExts: ['js', 'json', 'ts', 'tsx', 'css', 'scss'],
},
transformer: {
babelTransformerPath: …
```
> Export `getDefaultConfig` for custom configurations

- packages/global-cli/README.md
Summary:
---------
Current README of `react-native-cli` is outdated and totally not user friendly. We already have a contributing guide on how to run it locally, so there's no point in keeping this one. I took this opportunity to write a proper README.
cc @kelset
> fix: update react-native-cli README

- packages/cli/src/core/android/findManifest.js
Summary:
---------
Due to changes in Android, we have 2 AndroidManifest.xml files in RN template, one in the main and another in debug. Manifest in debug has no package name, so that developer has to edit only AndroidManifest.xml in main if they want to change package name.
But it's causing link failure like below, so it's best to not look into debug for AndroidManifest.xml files.
```js
info Run "react-native --help" to see a list of all available commands.
error No package found. Are you sure this is a React Native project?
error Package name not found in
<redacted>/android/app/src/debug/AndroidManifest.xml
```
Test Plan:
----------
Try to link any module with 0.59RC template, it'll fail. but after this patch it'll work.
> exclude debug folder from findManifest command

- packages/cli/src/cliEntry.js
Summary:
---------
The logic for printing an unknown command was always a hack and the one for printing a help when no command provided never worked.
I did a research and found out there's a recommended (Commander way) of doing this.
It also fixes a regression I've noticed in https://github.com/react-native-community/react-native-releases/issues/79#issuecomment-463933483
Test Plan:
----------
Run w/o command, run with wrong command.
> fix: printing error and unknown command messages when unnecessary

- packages/cli/README.md
document the --simulator argument for the react-native run-ios command to allow user to launch their app on a specific iOS simulator based by its official name
Regarding the #169 issue
cc @thymikee
> docs: document the run-ios command

- README.md
- packages/cli/src/cliEntry.js
- packages/cli/src/core/getCommands.js
- packages/cli/src/core/getPlatforms.js
- packages/cli/src/core/types.flow.js
- packages/cli/src/index.js
- packages/cli/src/install/install.js
- packages/cli/src/install/uninstall.js
- packages/cli/src/link/__tests__/link-test.js
- packages/cli/src/link/getDependencyConfig.js
- packages/cli/src/link/getProjectDependencies.js
- packages/cli/src/link/link.js
- packages/cli/src/link/linkAll.js
- packages/cli/src/link/linkAssets.js
- packages/cli/src/link/linkDependency.js
- packages/cli/src/link/unlink.js
- packages/cli/src/runAndroid/tryLaunchAppOnDevice.js
- packages/cli/src/server/runServer.js
- packages/cli/src/upgrade/upgrade.js
- packages/cli/src/util/assertRequiredOptions.js
- packages/cli/src/util/loadMetroConfig.js
- packages/cli/src/util/logger.js
Summary:
---------
Attempt No. 2 after https://github.com/react-native-community/react-native-cli/pull/178. Turned out I passed empty array as `platforms` argument to link, while I should pass `undefined`. We could actually add `--platforms` support to `install`/`uninstall` now, what do you think?
Test Plan:
----------
Uninstalling:
Installing:
> feat: refactor install to use link directly instead of spawning it

- packages/cli/src/link/link.js
- packages/cli/src/link/linkAll.js
- packages/cli/src/link/linkAssets.js
Summary:
---------
Fix `linkAll` to link root assets.
@sijad can you test link with those changes?
> fix: fix link all

- packages/cli/src/server/server.js
Summary:
---------
In previous versions, the default "host" parameter was empty. I didn't dig to much into it, but I assume it transformed to the equivalent of starting a server listening for `0.0.0.0`. Now the default value is `localhost`, which in my case do not allow me establish a connection between Metro ( on my laptop ) and my external device ( an iPad ), even if they are on the same network. This do not allow me to Reload or debug remotely. 
Test Plan:
----------
- Run the Metro Bundler on your machine.
- Try to connect to it from any other device on the same network ( i.e, 192.168.0.9:8081 ), which will refuse the connection.
- Try to run the Metro Bundler again, but this time with `--host 0.0.0.0`, and try to connect again from an external device. Now it should connect. That …
> fix: server should listening for all incoming requests by default

- packages/cli/src/generator/templates.js
Hi everyone,
This pull request contains a small fix for the issue that caused template dev dependencies to be installed as regular dependencies.
Test Plan:
----------
Went with the guide in the CONTRIBUTION.md document, installed Verdaccio, released a new version of React Native to it and used it to create a new project with a template that has dev dependencies to check if the dependencies are still being installed as regular dependencies.
> fix: install template dev dependencies as such

- package.json
- packages/cli/src/commands/runAndroid/runOnAllDevices.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
Change `pvinis/rn-diff-purge` -> `react-native-community/rn-diff-purge`
Test Plan:
----------
Tests green, also tested integration locally
> fix: change diff links for upgrade command

- packages/cli/src/commands/eject/eject.js
Summary:
---------
`eject` had wrong paths (pointing to old RN directories), so this PR fixes that.
Fixes #207 	
Test Plan:
----------
1. Init new project RN 0.59+
2. Remove `android` and/or `ios`
3. Use the `eject` command to generate ios/android projects
> Correct paths for eject command

- packages/cli/src/cliEntry.js
Summary:
---------
Fixes #214 
`noHelp` doesn't work because we override `printHelpInformation` and we need to handle `description` (that can be undefined) manually
> chore: remove unnecessary option for a command

- packages/cli/src/commands/init/init.js
Summary:
---------
I'm aware @Esemesek works on revamping `init`, but in the meantime we can remove these extra checks.
Fixes https://github.com/react-native-community/react-native-cli/issues/14.
Test Plan:
----------
No test plan
> chore: remove unnecessary checks for react peer dep

- CONTRIBUTING.md
Summary:
---------
Fix incorrect path to cli index.js in Contributing documentation.
> docs: fix cli path in contributing doc

- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
Fix path to React Native `InitializeCore` module in default metro config.
For some reason, this path was modified when moving the `loadMetroConfig.js` file in new `tools` directory.
In current released version (v1.3.2) of the cli, the path is the correct one, as seen in the [loadMetroConfig.js](https://github.com/react-native-community/react-native-cli/blob/%40react-native-community/cli%401.3.2/packages/cli/src/util/loadMetroConfig.js#L52) of v1.3.2.
Test Plan:
----------
Was trying out `react-native run-ios` / `run-android` commands, after a fresh `react-native init` with current master branch of the cli, and was facing following metro bundler error:
```
error: bundling failed: Error: Cannot find module '/Users/blemair/Code/foo/node_modules/react-native/Libraries/tools/ …
```
> fix: path to InitializeCore module in default metro config

- packages/cli/src/commands/link/__tests__/android/makeBuildPatch-test.js
- packages/cli/src/commands/link/android/patches/makeBuildPatch.js
- packages/cli/src/commands/link/android/unregisterNativeModule.js
Summary:
---------
This PR fixes a regression introduced in https://github.com/react-native-community/react-native-cli/commit/c6c34a2a6e0d5898a62bc10b7c2936cadba3e071 where only `implementation` type dependencies would be unlinked correctly. Previously linked `compile` dependencies would not be fully unlinked. This issue has been discussed also in #43, #81 and [here](https://github.com/facebook/react-native/pull/21043).
This PR augments the Android `makeBuildPatch` to accept the path of the Gradle build configuration as a second parameter so that the correct patch string can be detected instead of returning the hardcoded `implementation` variant.
The path to the Gradle file is optional and if none is provided, `makeBuildPatch` will return the default  `implementation` patch string as it …
> Fix Android unlink regression

- CONTRIBUTING.md
Summary:
---------
Because `verdaccio` was not installed locally to the directory but globally (in previous step), through `yarn global`, the `verdaccio` command should not be prefixed by `yarn`, otherwise resulting in an error.
> docs: fix verdaccio command in contributing doc

- packages/cli/src/cliEntry.js
- packages/cli/src/core/findPlugins.js
Summary:
---------
[hasteImpl](https://github.com/facebook/react-native/blob/7c73f2bb5a0f97902f469bc043681e79e161aac3/jest/hasteImpl.js#L28) in RN 0.59 still uses private APIs that recently changed (files were moved around).
This is the only way we can easily iterate on 1.x release without breaking RN stability.
Also exported `findPlugins` from `cliEntry` so RN is able to consume it properly.
Test Plan:
----------
None
> fix: re-export findPlugins under cli/core for backcompat with RN 0.59

- packages/cli/package.json
Summary:
---------
CLI v1.x is designed to work with ^0.59.0. 
Test Plan:
----------
No peer dep warning
> fix: set proper peer dependencies

- packages/cli/src/commands/server/middleware/MiddlewareManager.js
Summary:
---------
Missed this one while moving files around in https://github.com/react-native-community/react-native-cli/pull/201.
Fixes https://github.com/react-native-community/react-native-cli/issues/225
Test Plan:
----------
Verified locally on a clean project.
> fix: debugger-ui incorrect path

- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
Improved error and success handling, so it accounts for https://github.com/react-native-community/react-native-cli/issues/230.
What changed:
- check if `git status -s` returns anything before saying that "most files were upgraded successfully", while they didn't
- don't incorrectly warn after empty patch 
- changed links to be underlined and dimmed
- moved "You may find release notes helpful" message with useful links to the very bottom right before failing the command
Test Plan:
----------
Updated tests, but feel free to give it a shot on any test project.
Failing to apply some changes:
Git apply fails badly:
> fix: refine upgrade error handling

- packages/cli/package.json
- packages/cli/src/commands/link/android/copyAssets.js
- yarn.lock
Summary:
---------
Fixes https://github.com/react-native-community/react-native-cli/issues/228 introduced by removing `fs-extra`. Brought it back and left a todo when we move to Node 10.
Test Plan:
----------
Green CI (need to covert this in e2e tests once we set them up)
> fix: linking assets on Android

- packages/cli/src/cliEntry.js
- yarn.lock
Summary:
---------
Turns out we need `minimist` for now. Left a proper comment on why we need it.
Hopefully we'll figure out a cleaner way soon.
Test Plan:
----------
works for me
> fix: reactNativePath and projectRoot not being parsed by commander

- packages/cli/src/commands/bundle/buildBundle.js
Summary:
---------
This pull request adds a new error message to the `react-native bundle` command that will throw an error if an invalid platform is passed to the `--platform` command, instead of failing with cryptic Haste errors.
The error message looks like this:
```
> react-native bundle --entry-file index.js --platform foo --bundle-output test.jsbundle
Invalid platform (foo) selected.
Available platforms are:
ios, android, native
If you are trying to bundle for an out-of-tree platform, it may not be installed.
error Invalid platform selected.
```
Test Plan:
----------
If you provide a platform that is not installed to `react-native bundle`, it will throw this error. If you provide a valid platform, it will continue bundling without issue.
> Throw an error if an invalid platform is passed to the bundler

- packages/cli/src/cliEntry.js
- packages/cli/src/commands/link/android/copyAssets.js
- packages/cli/src/commands/link/android/patches/applyPatch.js
- packages/cli/src/commands/link/android/patches/revokePatch.js
- packages/cli/src/commands/link/android/unlinkAssets.js
- packages/cli/src/commands/link/getProjectConfig.js
- packages/cli/src/commands/link/ios/addToHeaderSearchPaths.js
- packages/cli/src/commands/link/ios/copyAssets.js
- packages/cli/src/commands/link/ios/registerNativeModule.js
- packages/cli/src/commands/link/ios/removeFromHeaderSearchPaths.js
- packages/cli/src/commands/link/ios/unlinkAssets.js
- packages/cli/src/commands/link/ios/unregisterNativeModule.js
- packages/cli/src/commands/link/link.js
- packages/cli/src/commands/link/pods/addPodEntry.js
- packages/cli/src/commands/link/pods/readPodfile.js
- packages/cli/src/commands/link/pods/removePodEntry.js
- packages/cli/src/commands/link/pods/savePodFile.js
- packages/cli/src/commands/link/pods/unregisterNativeModule.js
- packages/cli/src/tools/logger.js
Summary:
---------
This PR addresses #96 and:
* Adds the `--verbose` flag to enable `DEBUG` logs
* Adds `setVerbose(boolean)` to `tools/logger.js` so that it can enable/disable `DEBUG` logs
* Adds debug logs for the (un)link commands
* Adds Flow typings to `commands/link/android/unlinkAssets.js`
I haven't added `DEBUG` logs to other parts of the CLI because:
* I'm not that familiar with the other CLI commands
* I'd like some feedback on what I've done so far before going on
Also, would it be better to add debug logs in chunks, say one PR per command? I suspect this PR would become too big otherwise.
Test Plan:
----------
These additions do not change any implementations but I ran the tests anyway, all green.
I also ran it against two existing projects and a freshly created one: no changes …
> Add verbose logging flag, debug logging for (un)link commands

- packages/cli/src/cliEntry.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/install/install.js
- packages/cli/src/commands/install/uninstall.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
- packages/cli/src/tools/PackageManager.js
- packages/cli/src/tools/__tests__/PackageManager-test.js
- packages/cli/src/tools/generator/templates.js
- packages/cli/src/tools/yarn.js
Summary:
---------
Removed nasty `class`, and replaced it with grouped methods.
`projectDir` is always the same in `cli` lifecycle, so we set it once on the start. Based on the presence of `yarn.lock` we decide either to use yarn or not to use it. `preferYarn` is overriding this behavior, and can later be used in `init` command which lacks correct `projectDir`.
Test Plan:
----------
> Refactor: Rework PackageManager implementation

- packages/cli/src/commands/server/middleware/getSecurityHeadersMiddleware.js
Some chrome extensions like this would [add custom origin](https://github.com/vitvad/Access-Control-Allow-Origin/issues/45) which break debug.
> Add hint for browser extensions that may break debug

- packages/cli/src/commands/init/init.js
- packages/cli/src/tools/generator/copyProjectTemplateAndReplace.js
Summary:
---------
The goal of this PR is to enable `eslint` checks in the projects generated by `react-native init` command. I added `eslint` and `@react-native-community/eslint-config` as dependencies. Also there is a new script in generated `package.json` called `lint`.
PR to update template in `react-native` repo: https://github.com/facebook/react-native/pull/23901
Test Plan:
----------
Follow setup from https://github.com/react-native-community/react-native-cli/blob/master/CONTRIBUTING.md
```bash
react-native init TestProject --template eslint-integration
cd TestProject && yarn lint
```
> Add `eslint` to react native project template.

- packages/cli/src/commands/server/runServer.js
- packages/cli/src/tools/loadMetroConfig.js
Despite https://github.com/react-native-community/react-native-cli/pull/234 the `--projectRoot` argument is ignored when running the `react-native start` command as reported in https://github.com/react-native-community/react-native-cli/issues/246. The root of the issue is probably that the value is called multiple things like `root` and `projectRoot`. This PR fixes the immediate issue, but seems to be ripe for a refactor as tracked in https://github.com/react-native-community/react-native-cli/issues/246.
> fix: pass `--projectRoot` argument to Metro

- packages/cli/src/commands/init/init.js
Fixes https://github.com/react-native-community/react-native-cli/issues/260 and https://github.com/facebook/react-native/issues/24103 by setting project directory on PackageManager which is needed to check for yarn.lock file.
Summary:
---------
I'm not sure how to test this but creating new projects fail with the exception 
```
info Adding required dependencies
internal/validators.js:125
throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
at validateString (internal/validators.js:125:11)
at Object.join (path.js:1147:7)
at isProjectUsingYarn (/path/to/app/node_modules/@react-native-community/cli/build/tools/yarn.js:101:51)
at shouldUseYarn …
```
> fix: set project directory to install packages in init command

- .flowconfig
- e2e/__tests__/install.test.js
- e2e/__tests__/uninstall.test.js
- e2e/helpers.js
- e2e/jest.config.js
- flow-typed/npm/execa_v1.0.x.js
- package.json
- packages/cli/README.md
- packages/cli/src/commands/upgrade/upgrade.js
- yarn.lock
Summary:
---------
This diff introduces a working setup for e2e tests, happily ported from Jest codebase :). As an example I decided to add tests (and documentation, because why not) for `install` and `uninstall` commands. We'll add more testing in a followup.
Fixes #134 	
Test Plan:
----------
Added some, doh!
> chore: setup e2e tests

- packages/cli/src/commands/runIOS/findMatchingSimulator.js
Summary:
---------
Fixes the simulator not found error prompted after Xcode 10.2 upgrade.
Test Plan:
----------
Tested on on Xcode: 10.1/10B61 and new version Xcode: 10.2/10E125
> [General] [Fixed] - Fixes Xcode 10.2 simulator not found issue

- flow-typed/npm/jest_v24.x.x.js
- packages/cli/package.json
- packages/cli/src/commands/info/__tests__/info.test.js
- packages/cli/src/commands/info/info.js
- yarn.lock
Summary:
---------
Upgrading `evninfo` to v7. Looks like [in 6.0 they removed `clipboard` option](https://github.com/tabrindle/envinfo/releases/tag/6.0.0) because it was unreliable, so I removed it as well.
The biggest change I can see on my machine is actually printing Android SDKs, which is nice.
Apart from that I added `@react-native-community/cli` to the output, because it's pretty relevant now.
Not marking it as breaking change as I don't believe the `--clipboard` was used anywhere.
Test Plan:
----------
Added a test which needs to go to e2e, so I left some todos
> feat: upgrade envinfo for better output of info command

- .eslintrc.js
- package.json
- packages/cli/src/tools/isPackagerRunning.js
- yarn.lock
Summary:
---------
Upgrading deps.
Test Plan:
----------
Green CI
> chore: update deps to avoid security warnings

- packages/cli/package.json
Summary:
---------
Setting correct peer dep for 2.x
Test Plan:
----------
Proper peer warning :D
> fix: set correct peer dep of RN 0.60 for CLI@2.x

- packages/cli/src/commands/server/debugger-ui/DeltaPatcher.js
- packages/cli/src/commands/server/debugger-ui/__tests__/DeltaPatcher-test.js
Summary:
---------
Context: https://github.com/facebook/metro/issues/380, https://github.com/facebook/react-native/issues/23955
Fixes a discrepancy between the order of modules in the source map and in the actual bundle, caused by a change in Metro (see details in https://github.com/facebook/metro/issues/380#issuecomment-478633831). Consequently fixes React Native remote JS debugging.
Test Plan:
----------
1. Made the same change in my checkout of the repro code from https://github.com/facebook/metro/issues/380 and verified debugging works.
2. Added unit tests.
> Sort modules in debugger delta patcher to match source map order

- .circleci/config.yml
- e2e/jest.config.js
- e2e/testSetup.js
- jest.config.js
- package.json
- packages/cli/src/commands/info/__tests__/info.test.js
- packages/cli/src/commands/link/__tests__/android/makeSettingsPatch-test.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/tools/__tests__/PackageManager-test.js
- packages/cli/src/tools/__tests__/makeCommand-test.js
- packages/cli/testSetup.js
- yarn.lock
Summary:
---------
While working on #241 we discovered some flaky tests. This diff aims to fix those. It also updates Jest to 24.6 which comes with pretty nice perf improvements.
Test Plan:
----------
Green CI
> fix: flaky tests; upgrade Jest to 24.6

- packages/cli/src/cliEntry.js
Summary:
---------
Our command error handler eats error stack and leaves the user with only a message. Example: https://github.com/react-native-community/react-native-cli/issues/273
I don't think we need to put stacks in every error out there, but we should enable them in `--verbose` mode.
Test Plan:
----------
> feat: point to --verbose when command fails

- e2e/__tests__/uninstall.test.js
- e2e/helpers.js
Summary:
---------
You're gonna like it @grabbou :D
Test Plan:
----------
> chore: add better error handling for failing e2e tests

- .prettierrc.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
Resolves #271 
Test Plan:
----------
1. Init a react native app on an old version at the root of a repo
2. Upgrade to latest rn version and check if it worked as expected (to avoid regression)
3. Discard upgrade changes and move the app to a subfolder
4. Try to upgrade again
I did test that between 0.59.0 and 0.59.2
> bug: apply upgrade patch in subdirectory if necessary

- packages/cli/src/tools/copyAndReplace.js
Summary:
---------
Right now the `debug.keystore` file isn't properly copied when creating a new app from source. This PR fixes it.
Test Plan:
----------
Created an app from master with this patch in place and I didn't have to manually copy the `.keystore` file.
> Copy `.keystore` files as binary extensions.

- packages/cli/src/commands/upgrade/__tests__/__snapshots__/upgrade.test.js.snap
- packages/cli/src/commands/upgrade/__tests__/sample.patch
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/types.flow.js
- packages/cli/src/tools/merge.js
- packages/platform-android/src/config/index.js
Summary:
---------
We can infer package name (for Android) and project name (for iOS) from the config.
This should produce better results than current solution, because we don't need to make assumptions about project name to be synced with package.json.
Supersedes and closes https://github.com/react-native-community/react-native-cli/pull/276
Closes https://github.com/react-native-community/react-native-cli/issues/190
cc @Krizzu, mind testing this branch on your project?
Test Plan:
----------
Added a test
> feat: infer package and project name for upgrade from config

- packages/cli/src/commands/bundle/buildBundle.js
Summary:
---------
I've noticed that the `max-workers` CLI flag is not behaving as expected for the bundle command.
We need it in one of our CI builds where the container is a bit memory-starved and the default of `numberOfWorkers = numberOfCores` isn't always accurate in a virtualized environment.
This fix ensures the flag makes it to the server config and that the number of node processes reflect the number provided + 1.
Test Plan:
----------
I made a reproduction repo: https://github.com/sterlingwes/rn-cli-repro
The values in the "expected output" reflect the fact:
* i already have a node process running for an unrelated task
* the number of node processes should be `maxWorkersValue + 1`, since there's a parent node process that spawns the child workers
So in the success case, …
> fix: pass maxWorkers arg to server

- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.js.snap
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/index.js
Summary:
---------
Thanks to this change, CLI will not add default React Native configuration when one is present. I can now go to React Native, add the configuration and release it and CLI will pick that one.
The below temporary workaround allows us to run on 0.59, where config is not yet present.
> chore: don't apply RN config automatically

- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.js.snap
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
- packages/tools/src/errors.js
Summary:
---------
Some packages can have invalid configuration. Our convention was to throw an error in that case. It is very likely some packages can have invalid configuration (since it was super wild and never standardised), so it's better to simply ignore them and print an appropriate warning. 
Test Plan:
----------
Do a broken configuration for any of your dependencies and run `config`. Package should be excluded.
> Do not throw on invalid packages

- packages/cli/src/cliEntry.js
Summary:
---------
There is a problem with the line break of command help as below.
Test Plan:
----------
Not required.
> fix: add new line to the help message

- packages/cli/README.md
Summary:
---------
Added documentation for following commands:
- `link`
- `unlink`
- `start`
- `upgrade`
Relates to https://github.com/react-native-community/cli/issues/103
> chore: add documentation on link, unlink, start, upgrade

- packages/cli/src/commands/server/runServer.js
- packages/cli/src/commands/server/server.js
Summary:
---------
**This pull request adds support for loading `assetPlugins` through flags to the CLI `start` command.**
This option is probably unknown to you because I don't think anybody uses it except Expo and it happens behind the scenes 😆. In Expo projects we depend on the `assetPlugins` configuration option for the asset system in order to inject the md5 hash for each asset into the asset metadata within AssetRegistry. In the meto versioned used by react-native@0.57, support for `assetPlugins` in the query param for bundles was broken along with a refactor for configuration. In order to ship SDK 31 we patched our fork of react-native to make local-cli always include this plugin (https://github.com/expo/react-native/commit/d41bc86fd9fec9c55ae72bd4cdc1508097f7796b) but now that …
> Add support for assetPlugins argument to start command

- packages/platform-ios/native_modules.rb
- packages/platform-ios/src/link-pods/findLineToAddPod.js
- packages/platform-ios/src/link-pods/findMarkedLinesInPodfile.js
- packages/platform-ios/src/link-pods/findPodTargetLine.js
- packages/platform-ios/src/link-pods/registerNativeModule.js
Summary:
---------
Right now, when Podfile doesn't have a market text or the target name is different, link fails with a cryptic message. This adds an explicit error message.
Fixes #273 
Test Plan:
----------
Use a Podfile w/o market text and change the name of the target. See the error happen.
> fix: give a better error message when CocoaPods linking fails

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
If we run `react-native run-android` while it's already installed, it will fail with the following error.
```bash
info Installing the app on the device (cd android && adb -s emulator-5554 install app/build/outputs/apk/debug/app-x86-debug.apk
adb: failed to install app/build/outputs/apk/debug/app-x86-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install me.mycake without first uninstalling.]
```
In the development phase, I think using adb's install options below is much more efficient.
```
-r : Reinstall an existing app, keeping its data.
-d : Allow version code downgrade.
```
Test Plan:
----------
Not required.
> fix: prevent run-android failure when updating APK

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
```bash
react-native run-android --deviceId=emulator-5554
```
If the build fails, the APK that was built before is installed and executed.
```bash
BUILD FAILED in 5s
320 actionable tasks: 5 executed, 315 up-to-date
error Could not build the app, read the error above for details.
info Running /Users/snow/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
error Not found the correct install APK file!
Could not install the app on the device, read the error above for details.
info Starting the app on emulator-5554 (/Users/snow/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -n me.mycake/me.mycake.MainActivity)...
Starting: Intent { cmp=me.mycake/.MainActivity }
Warning: Activity not started, its current task has been …
```
> fix: prevent unnecessary actions if build failed

- packages/platform-ios/package.json
Summary:
---------
We forgot to put it in publish list in #256 
Test Plan:
----------
`npm pack` sees it now
> fix: publish native_modules.rb file

- packages/cli/src/cliEntry.js
- packages/cli/src/tools/config/schema.js
- packages/platform-android/src/commands/runAndroid/index.js
- packages/platform-ios/src/commands/runIOS/index.js
- types/index.js
Summary:
---------
I was pretty sure this has landed, but turns out - I've never merged the PR: https://github.com/react-native-community/cli/pull/287/files#diff-97059d274ee5d7bbcc5730ddee2a98daR126 
This change is needed to support functions as defaults (lazily called with config to get a default value) - we will need that in other commands in the future.
I am also moving current `getDefaultUserTerminal` to be executed lazily. That way, the value of `default` is a function and it passes the validation.
> Support functions in default

- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
- packages/cli/src/tools/config/schema.js
- types/index.js
Summary:
---------
React Native (and other packages) can define commands and platforms to be picked by the CLI. When running from source, they are treated as `project`, not as a `dependency`, hence `platforms` are ignored.
This adds support for `platforms` to be defined on per `project` basis too.
Added `stripUnknown` so they can co-exist.
TLDR; Nothing changes, but `Joi` validator will not strip it out now.
> feat: support platforms that ship with project 

- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.js.snap
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
- types/index.js
Summary:
---------
While doing new configuration, we've decided we can actually infer `haste` config as it's just repeated information in 99,9% use-cases.
Unfortunately, `react-native-dummy` (and could be others in the future), defines just [that](https://github.com/react-native-community/react-native-dummy/blob/master/package.json). As a result, React Native tests break.
This PR uses `haste` value and when empty, it infers the values. To be changed in the future.
> fix: read `haste` configuration from legacy config

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
In the previous PR(#323), the code was modified with the following comment.
```
@Krizzu
You can also combine arguments -rd, but it's up to you
```
But, I realized that this arguments does not work.
```bash
adb -s ce021712cad7e8990c install -rd test.apk
adb: failed to install test.apk:
Exception occurred while dumping:
java.lang.IllegalArgumentException: No argument expected after "-rd"
```
So, I modified it to divide the arguments.
Test Plan:
----------
Not required.
> fix: modify wrong install arguments

- packages/platform-ios/src/commands/runIOS/index.js
Summary:
---------
This PR fixes #330, it checks if `ios-deploy` is installed or not before it actually starts building.
Test Plan:
----------
- Run `npm uninstall -g ios-deploy`;
- Run the CLI with `--device` argument and wait for it to fail;
- Run `npm i -g ios-deploy`;
- Run the CLI again and see it working.
cc @thymikee
---
> Check `ios-deploy` installation before proceeding to build on device

- packages/platform-android/native_modules.gradle
Summary:
---------
Gradle 5 no longer supports the `<<` syntax - swapped to the non-shorthand syntax of `doLast {}`
Test Plan:
----------
Builds successfully with the updated syntax and `PackageList.java` file generated
> fix: [android][linking] Remove deprecated task syntax

- packages/platform-android/native_modules.gradle
Summary:
---------
The previous CLI config use to return names with `/`'s replaced with `_`'s - it no longer does this so I've moved the replacing logic into the auto-linking build script so as to avoid breaking on Gradle 5+:
Test Plan:
----------
After change build no longer fails:
> [android] remove forward slashes from package name

- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/readConfigFromDisk.js
Summary:
---------
`"react-native"` key already exists in userspace and is used by Metro to resolve source files of published React Native modules. That's why we cannot use it to store config values insead of `"rnpm"`. I'm not a fan of having configs in package.json, so I got rid of that entirely and rely only on `react-native.config.js` file from now on. 
Test Plan:
----------
Added a test and updated existing ones.
> fix: stop resolving "react-native" from package.json as a config 

- docs/autolinking.md
- docs/configuration.md
- docs/dependency.md
- docs/linking.md
- docs/platforms.md
- docs/plugins.md
- packages/cli/src/cliEntry.js
- packages/cli/src/commands/bundle/bundleCommandLineArgs.js
- packages/cli/src/commands/bundle/ramBundle.js
- packages/cli/src/commands/init/index.js
- packages/cli/src/commands/library/library.js
- packages/cli/src/commands/link/link.js
- packages/cli/src/commands/server/server.js
- packages/cli/src/commands/upgrade/upgrade.js
- packages/cli/src/tools/assertRequiredOptions.js
- packages/cli/src/tools/config/schema.js
- packages/platform-android/src/commands/runAndroid/index.js
- packages/platform-ios/src/commands/runIOS/index.js
- types/index.js
Summary:
---------
I am trying to describe some of the new (and old, but undocumented) features of the CLI to make it easier for developers to use CLI and hack with its great features.
This PR is a WIP as I am working on it. 
ETA is next 2 to 3 hours - I want to finish and ship it before next RC of React Native so that we can announce this at the same time.
> docs: initial documentation of the basic features

- README.md
- docs/commands.md
- docs/init.md
- packages/cli/src/commands/init/init.js
Adding documentation for `init` command.
> docs: add init documentation

- docs/platforms.md
Summary:
---------
Adds a basic description of a platform documentation
> feat: add `platforms` doc

- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
We were relying on github to generate diffs and patches for us. This worked fine when we had one branch for all the releases, but this is not enough anymore with a branch per release. We still use github's compare view, but for patches we grab the ones we generate on the [purge repo](https://github.com/react-native-community/rn-diff-purge).
Test Plan:
----------
More or less the same as https://github.com/react-native-community/react-native-cli/pull/176.
Create a RN project, and try upgrading like so.
Having conflicts still causes the upgrade to not leave files for the user to resolve.
> chore: change `upgrade` to use new diff files approach

- packages/cli/package.json
- packages/cli/src/tools/copyAndReplace.js
- yarn.lock
Summary:
---------
Since we plan to add `Pods` to the template, we need to improve handling binary files.
Test Plan:
----------
1. Initialise new project.
2. Check if `*.png` files are not corrupted.
3. Check if `gradle wrapper` works by invoking `./gradlew clean` from `android` directory.
cc @cpojer @thymikee
> feat: improve copying binary files in `init`

- docs/autolinking.md
- packages/platform-ios/native_modules.rb
Summary:
---------
```sh
▲ ios  $ yarn react-native config
yarn run v1.12.3
$ /Users/ortatherox/Downloads/Autolinking/node_modules/.bin/react-native config
{
"root": "/Users/ortatherox/Downloads/Autolinking",
"reactNativePath": "/Users/ortatherox/Downloads/Autolinking/node_modules/react-native",
"dependencies": {
"@react-native-community/cli": {
"root": "/Users/ortatherox/Downloads/Autolinking/node_modules/@react-native-community/cli",
"name": "@react-native-community/cli",
"platforms": {
"ios": null,
"android": null
},
"assets": [],
"hooks": {},
"params": []
},
},
// [snip]
"project": {
"ios": {
"sourceDir": "/Users/ortatherox/Downloads/Autolinking/ios",
"folder": "/Users/ortatherox/Downloads/Autolinking",
"pbxprojPath": "/Users/ortatherox/Downloads/Autolinking/ios/Autolinking.xcodeproj/p …
```
> [ios] Ensure that the right cwd is set up for auto-linking dependencies

- docs/commands.md
- docs/init.md
- packages/cli/src/commands/init/__tests__/templateName.test.js
- packages/cli/src/commands/init/templateName.js
- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.js.snap
- packages/cli/src/tools/config/__tests__/index-test.js
Summary:
---------
Adds support for installing templates from tarballs (with `.tgz` extension because that's what `npm pack` outputs).
Test Plan:
----------
```sh
npm pack
node ../oss/react-native-cli/packages/cli/build/ init FromTarball --template file:///abs/path/react-native/react-native-1000.0.0.tgz
```
Tested with both yarn and npm.
> feat: init from tarball

- packages/cli/package.json
- packages/cli/src/commands/init/__tests__/editTemplate.test.js
- packages/cli/src/commands/init/__tests__/template.test.js
- packages/cli/src/commands/init/editTemplate.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/template.js
- packages/cli/src/tools/copyAndReplace.js
- packages/cli/src/tools/copyFiles.js
- yarn.lock
Summary:
---------
Copy all files during `init` using read/write streams so it doesn't matter if it's a binary file or not.
Reverts #353
Test Plan:
----------
doing it
> feat: copy all files in `init` through streams

- README.md
Adds `maintainers` section following other repositories in the RNC.
> docs: add `maintainers` section

- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
The `loadConfig` function in `metro-config` reads the `reporter` option
from the second argument (`defaultConfigOverrides`) instead of the
first argument (`argv`), so we need to pass it in that object to
make the `customLogReporterPath` CLI option work.
Test Plan:
----------
1. Created a file `reporter.js` with the following contents:
```js
class JsonReporter {
update(event) {
console.log(JSON.stringify(event));
}
}
module.exports = JsonReporter;
```
2. Ran this command and inspected that the output was JSON:
```
node ~/Projects/react-native-cli/packages/cli/build/index.js start --customLogReporterPath ~/Projects/react-native-cli/reporter.js
```
> fix: reporter config option

- docs/commands.md
- packages/cli/src/tools/copyFiles.js
- packages/platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.js
- packages/platform-android/src/commands/runAndroid/adb.js
- packages/platform-android/src/commands/runAndroid/index.js
- packages/platform-android/src/commands/runAndroid/runOnAllDevices.js
- packages/platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.js
- packages/platform-android/src/commands/runAndroid/tryRunAdbReverse.js
Summary:
---------
- cleanup run-android implementation to remove duplication
- unify and simplify error messages, put details into verbose mode
- provide more helpful messages for common cases when installing with Gradle
- rename flag `installDebug` -> `task`
Fixes #251
Example messages:
Test Plan:
----------
Adjusted tests accordingly.
> feat: improve `run-android` error messages; rename "installDebug" -> "task"

- packages/cli/package.json
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/printRunInstructions.js
- packages/cli/src/tools/installPods.js
- packages/cli/src/tools/packageManager.js
- yarn.lock
Summary:
---------
This PR fixes #368 of which checks if CocoaPods is installed and runs `pod install`.
Test Plan:
----------
Run `node /path/to/cli/packages/cli/build/index.js init --template /path/to/react-native AwesomeProject`
Looks like this now when user doesn't have CocoaPods installed:
With CocoaPods installed:
---
> feat: automatically run `pod install` when running `init` command

- packages/platform-android/native_modules.gradle
- packages/platform-ios/native_modules.rb
Summary:
---------
Since `@react-native-community/cli` is not declared as template dependency, there is a possibility for Node to not be able to resolve it. It may happen because package managers can put the package inside `react-native/node_modules/` behind a symlink (like `npm` does in some scenarios) which is invisible to `require.resolve`. 
This diff changes autolinking scripts to use `config` command directly from `react-native` binary instead, as `react-native` is a direct dependency of any template.
Because running node binaries differs between package managers (e.g. Yarn in PnP mode doesn't have `node_modules/` so no `node_modules/.bin/` as well), the best thing we can do is to directly run the command through a package manager. For now Yarn and npm are supported, I'm happy to …
> fix: run "config" from react-native binary in autolinking scripts

- packages/cli/src/tools/installPods.js
Summary:
---------
This PR adds the CocoaPods documentation link to the prompt question when running `init`.
Test Plan:
----------
1. Run `sudo gem uninstall cocoapods` (or without sudo);
1. Run `react-native init`.
> Improve CocoaPods prompt question when running  `init`

- packages/cli/package.json
- packages/cli/src/tools/config/readConfigFromDisk.js
- packages/cli/src/tools/config/schema.js
- yarn.lock
Summary:
---------
Joi moved to `@hapi` namespace.
Test Plan:
----------
CI green
> chore: upgrade joi to @hapi/joi to remove npm warnings

- packages/cli/src/tools/loadMetroConfig.js
> fix: config.reporter undefined bug

- packages/cli/src/commands/init/initCompat.js
- packages/cli/src/tools/installPods.js
Summary:
---------
This PR is related to #368 and adds `installPods` to the legacy init.
Test Plan:
----------
Follow https://github.com/react-native-community/cli/blob/master/CONTRIBUTING.md#testing-init-command.
> Add `installPods` to legacy init

- packages/cli/src/tools/installPods.js
Summary:
---------
This PR shows a different message if `cocoapods` installation takes more than 30 seconds.
Test Plan:
----------
1. `sudo gem uninstall cocoapods`;
1. Put `await execa('sleep', ['30']);`[here](https://github.com/lucasbento/cli/blob/5eb25ea43788a280266f3659ce1ec11f54525168/packages/cli/src/tools/installPods.js#L59).
---
> feat: Show message if CocoaPods installation takes long

- __e2e__/__snapshots__/init.test.js.snap
- __e2e__/init.test.js
- docs/commands.md
- packages/cli/src/cliEntry.js
- packages/cli/src/commands/init/index.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/tools/installPods.js
Summary:
---------
This PR fixes #110 by adding the possibility of specifying the folder path of the project when running the `init` command.
This changes the `fs.mkdirSync` to run with `recursive: true` which is only available on Node.js > 10, I'm open for opinions on how to throw a nice error to the user if the path doesn't exist yet and is not possible to create without `recursive`.
Test Plan:
----------
```sh
npx react-native init AwesomeApp --directory ../
npx react-native init AwesomeApp --directory path/that/does/not/exist/yet
```
I also added a test for this on `init.test.js` that I would love some feedback on!
cc @thymikee maybe you can review this :)
---
---
> feat: support `init` with custom project directory

- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
Summary:
---------
Fixes #346
Test Plan:
----------
Tests are green, so `rnpm` config is still respected.
> Improve RNPM warnings

- docs/dependencies.md
- packages/cli/src/tools/config/schema.js
- packages/platform-ios/src/config/index.js
- types/index.js
Summary:
---------
This change allows dependencies to specify a custom name of the podspec to use when linking / auto-linking ([used here in auto-linking](https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb#L44))
Test Plan:
----------
> feat: allow `dependencyConfig` to override `podspec` name

- docs/configuration.md
- docs/dependencies.md
- docs/init.md
- docs/platforms.md
- docs/plugins.md
- docs/projects.md
- packages/platform-android/src/config/index.js
- types/index.js
Summary:
---------
The `dependencies[dep].platfors.android.manifest` entry of the `config` command can be quite lengthy, as it keeps the whole AndroidManifest.xml parsed. We don't make any use of it and it makes the output of `config` unnecessarily big, which can make some terminals stall
Test Plan:
----------
Run `config` command and observe less clutter
> feat: remove manifest from config output

- packages/cli/src/cliEntry.js
- packages/platform-ios/src/commands/runIOS/index.js
- packages/platform-ios/src/link-pods/registerNativeModule.js
- packages/tools/src/errors.ts
- packages/tools/src/isPackagerRunning.ts
Summary:
---------
Hiding the stack trace behind `debug` log level was not a good idea, as it turned out users are not using `--verbose` flag when sending bug reports.
This PR changes the approach to always show the stack if available. The stack may not be available if it was removed, e.g. by the `CLIError` which removes it when the `originalError` parameter is not passed, since we assume that the failure is known and expected so stack trace is not necessary.
Test Plan:
----------
Dimmed stacktrace shows every time a generic, non `CLIError` happens
> feat: log error stacktrace by default

- .circleci/config.yml
Summary:
---------
The main motivation behind this PR is to add test coverage for Node LTS (Node 10 as of today). In the interest of avoiding duplication, I migrated the existing config to Circle 2.1.
Circle's 2.1 schema allows for config reuse through the commands and executor keywords. 
The CLI's smaller scope serves as a good way to try out 2.1 before attempting to further modernize the core RN repo's Circle CI config.
Test Plan:
----------
Ran on Circle CI on my fork: https://circleci.com/workflow-run/545bcf9c-c6ee-42f6-b841-04f84ab1f47f
> [CI] Migrate to Circle 2.1, add Node LTS tests

- packages/cli/src/commands/server/debugger-ui/index.html
Summary:
---------
This structurally sets up the Chrome debugger not to have CORS issues if the bundle URL domain differs from the Chrome debugger page domain. This bug was initially fixed in https://github.com/facebook/react-native/pull/17720 and regressed in https://github.com/react-native-community/cli/pull/194. This commit fixes the original bug without changing the behavior introduced in #194.
This commit makes the debugger page use its own URL origin when loading the bundle URL. This addresses the case where the native client may have a bundle URL with a domain like xip.io. Fundamentally, unless the development server allows cross-origin requests, the bundle URL's domain must match the domain used by the Chrome debugger page, which is what this commit achieves.
Test Plan:
---------- …
> fix: Ensure that bundle URL origin matches debugger page origin

- packages/platform-android/native_modules.gradle
Summary:
---------
This fixes a bug when trying to add additional packages that are not automatically linked, `Arrays.asList` returns a fixed size List, therefore, preventing further ReactPackages being added to it. 
Wrapping it in an `ArrayList` makes it a variable-size List and fixes the issue.
Test Plan:
----------
Created a new template project, applied the changes locally, added a custom native module:
```java
@Override
protected List<ReactPackage> getPackages() {
@SuppressWarnings("UnnecessaryLocalVariable")
List<ReactPackage> packages = new PackageList(this).getPackages();
// additional non auto detected packages can still be added here:
packages.add(new ReactNativeFirebaseAppPackage());
return packages;
}
```
App builds and starts successfully:
(redbox confirms additional custom …
> [android] Fixed a crash when adding non-autolinked custom `ReactPackages`

- CONTRIBUTING.md
Summary:
---------
I've been struggling to get CLI working locally, especially using a combination of init, start, and run-android commands. I figured out in the end the steps necessary for it and thought it might be maybe useful for others to have them as well.
> chore(docs): update CONTRIBUTING.md

- packages/platform-ios/src/commands/logIOS/index.js
Summary:
---------
The `findAvailableDevice()` method can only return `null` or `Object`
```js
function findAvailableDevice(devices) {
for (const key of Object.keys(devices)) {
for (const device of devices[key]) {
if (device.availability === '(available)' && device.state === 'Booted') {
return device;
}
}
}
return null;
}
```
So this code
```js
if (device === undefined) {
_cliTools().logger.error('No active iOS device found');
return;
}
```
is useless at the moment
Test Plan:
----------
Before fix:
After fix:
> fix: no active iOS device case in `logIOS`

- packages/platform-ios/src/commands/runIOS/findMatchingSimulator.js
Summary:
---------
Installing the Xcode 11 beta changes the result of isAvailable to `true` and `false` when searching for a simulator by name. 
E.g. 
```
{ 
state: 'Shutdown',
isAvailable: true,
name: 'iPhone X',
udid: 'xxx' 
},
{ 
state: 'Shutdown',
isAvailable: false,
name: 'iPhone Xs',
udid: 'xxx',
availabilityError: 'runtime profile not found'
},
```
This fix adds a `&& simulator.isAvailable !== true` check to the existing simulator.isAvailable value checks.
Test Plan:
----------
1) run `react-native run-ios`
2) confirm working ✅
3) Install Xcode 11 beta
4) run `react-native run-ios`
5) confirm working ✅
> Add a simulator.isAvailable check for true value

- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
We are removing `hasteImpl` related stuff in https://github.com/facebook/react-native/pull/24811. However, the cli always passes a hasteImpl on to Metro and on to `jest-haste-map`. If a path to file that doesn't exist is passed, Metro will fail.
This changes the default config to detect whether there is a `hasteImpl.js` file available inside of RN and to only pass it when it is. This makes the cli compatible both with RN <0.60 and >0.61.
Test Plan:
----------
I patched the cli locally and it seemed to work when `hasteImpl` was removed.
> feat: Only pass `hasteImplModulePath` if the `hasteImpl` file is available in RN

- packages/cli/src/commands/server/middleware/getDevToolsMiddleware.js
Summary:
---------
No need for this code to be there anymore.
Test Plan:
----------
None really, removing dead branches
> chore: remove deprecated entries in DevTools middleware

- .circleci/config.yml
- docs/commands.md
- packages/cli/src/commands/link/__tests__/link-test.js
- packages/cli/src/commands/link/link.js
- packages/cli/src/commands/link/linkAll.js
- packages/cli/src/commands/link/linkAssets.js
- packages/cli/src/commands/link/linkDependency.js
- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.js.snap
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/__tests__/makeHook-test.js
- packages/cli/src/tools/config/makeHook.js
- packages/cli/src/tools/config/readConfigFromDisk.js
- packages/platform-ios/src/link/copyAssets.js
- types/index.js
Summary:
---------
Change the default behavior of `link` to only link assets.
Since autolinking, manual linking of packages is quickly becoming obsolete, however there's no easy way to autolink assets (can be automated with CocoaPods podspecs, but not sure about Gradle cc @Salakar. EDIT: should be doable, @Salakar is on it). That's why I think it makes sense to default `link` to process assets only, unless the `--all` flag is passed explicitly.
Additional changes that accumulated while testing: 
- fix linking hooks failing to execute
- fix handling assets from legacy "rnpm" config
- overhaul linking logs and error messages
- disable flaky e2e tests in lts-tests phase
Test Plan:
----------
Run `link`, `link --all`, `link package-name` on sample projects.
> feat(breaking): link only assets by default; add `--all` flag

- packages/platform-android/src/commands/runAndroid/runOnAllDevices.js
Hello!
Over on the RN repo, I recently merged a PR to make the dev server port configurable on Android:
https://github.com/facebook/react-native/pull/23616
A change needs to be made to the CLI in order to pass this port information over to the Android build as a gradle build argument.
This PR includes that change. Although I'm having some trouble testing it since, what looks like, changes for a 2.0 release of this project.
From what I'm seeing, the `run-android` command appears to be missing when I link this repo directly:
Would it be better to send this out against the 1.0 branch?
> feat: Pass along CLI port configuration for Android

- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
That should fix a validation error coming from Metro.
```
error ● Validation Error:
Option "server.port" must be of type:
number
but instead received:
string
Example:
{
"port": 8080
}
```
Test Plan:
----------
cc @kelset
> fix: make sure the port passed to Metro is a number

- packages/cli/src/commands/server/middleware/MiddlewareManager.js
- packages/cli/src/commands/server/middleware/logToConsoleMiddleware.js
Summary:
---------
In development, React Native on master now sends all `console` calls to the CLI/Metro. This means we can show logs directly in the terminal, which means debugging simple things a ton easier.
Test Plan:
----------
> Log `console` invocations to the terminal.

- packages/platform-ios/src/commands/runIOS/index.js
Summary:
---------
I talked to @grabbou few days ago, I met a `CFBundleIdentifier problem`, I give it a look, and the reason is `-derivedDataPath` not work as expected. Leads to `app` file not found. 
I can reproduce it on latest `cli` and `react-native`, Xcode 10.2.1. I may think it's a `xcodebuild` command bug. 
Related issue: https://github.com/facebook/react-native/issues/25259
Test Plan:
----------
`react-native run-ios` can works as expected.
> fix: Add fallback path check when not found app file for iOS

- docs/init.md
Summary:
---------
Hi everyone,
I am liking the new CLI changes a lot, really good work there, thank you all for the effort! 👍
While [refactoring the TS template to be compatible with the new CLI](https://github.com/emin93/react-native-template-typescript/issues/38), I saw there are a few things documented differently than the actual implementation.
In this PR I changed the documentation to match the current implementation. It's likely, that the implementation has to be changed as well in order to support both ways.
Test Plan:
----------
Created a new project with the template config as described in the docs. As this failed, I had a look at the current implementation and found out:
- Template config file name shouldn't have a `.js` extension: …
> chore: update init docs to be more descriptive

- jest/setupUnitTests.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
From the git manual:
```
--allow-binary-replacement, --binary
Historically we did not allow binary patch applied without an explicit permission from the user, and this flag was the way to do so. Currently we always allow binary patch application, so this is a no-op.
```
However it's necessary when running `git apply --check` to actually accept binary files. Maybe a bug in git? 
Fixes #422 	
Test Plan:
----------
Upgrade to RN 0.59.9 works with minor conflicts (`git apply` succeeds)
> fix: allow upgrading with binary files in the diff

- package.json
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/tools/releaseChecker/getLatestRelease.js
- yarn.lock
Summary:
---------
Bump Flow to [0.101](https://github.com/facebook/flow/releases/tag/v0.101.0) for latest fixes and improvements.
> chore: bump Flow to 0.101

- packages/platform-android/native_modules.gradle
Summary:
---------
- Fix https://github.com/react-native-community/cli/issues/434
- Also remove the redundant semicolon after package imports
Test Plan:
----------
It fixes #434.
Try to modify `node_modules/@react-native-community/cli-platform-android/native_modules.gradle` in https://github.com/robertying/autolink-issue-example and it can build succesfully now!
> Add import for `applicationId.R` class in generated `PackageList.java`

- package.json
- packages/cli/src/tools/__tests__/packageManager-test.js
- packages/cli/src/tools/packageManager.js
- yarn.lock
This is an attempt made to reduce redundant code.
> chore: refactor packageManager.js for less redundancy

- packages/cli/src/commands/link/linkAll.js
Summary:
---------
_Note: this diff targets `1.x` branch_
Related: https://github.com/react-native-community/cli/issues/48
Test Plan:
----------
No warning when running `react-native link`.
> chore: get rid of link without package name message

- packages/platform-android/native_modules.gradle
Summary:
---------
As the issue #438 suggested, `R` and `BuildConfig` are located using `packageName` rather than `applicationId`.
I figured out a way to get `packageName` from `AndroidManifest.xml` and use it to replace `applicationId`.
- This pull request will close #438
Test Plan:
----------
Change your `applicationId` in `app/build.gradle` different from `packageName` in `app/src/main/AndroidManifest.xml` and build failed due to `R` and `BuildConfig` not found.
Even if you change `applicationId` in `app/build.gradle` to be whatever, generated `PackageList.java` always `import packageName.R`.
> Use `packageName` instead of `applicationId` in gradle script

- docs/autolinking.md
- packages/cli/src/tools/config/index.js
- packages/platform-android/native_modules.gradle
- types/index.js
Summary:
---------
There are packages (like [appcenter](https://github.com/microsoft/appcenter-sdk-react-native/) or [react-native-fbsdk](https://github.com/facebook/react-native-fbsdk#usage)) that are not able to support autolinking on Android just yet, because of too complicated setup. This diff documents how we can disable certain platform of a package to not be autolinked.
By the way I've adjusted some types (please double check). The types naming is pretty confusing even after all this time :|
Test Plan:
----------
Tested on `appcenter` and `react-native-fbsdk`.
Related issue in appcenter: https://github.com/microsoft/appcenter-sdk-react-native/issues/613
> docs: document how to disable autolinking for unsupported packages

- packages/platform-android/native_modules.gradle
- packages/platform-ios/native_modules.rb
Summary:
---------
I've added support for Yarn resolution to support PnP mode. However, RN is far from supporting PnP at the moment. It also turns out that developers use different versions of Yarn that may e.g. spawn some Node deprecation warnings on some environments. Hence removing spawning commands through Yarn, we're only using Node for now. PnP support can be added once RN core is ready.
Fixes #448 
Test Plan:
----------
Autolinking works.
> fix: don't use yarn for spawning 'config' command

- README.md
- docs/configuration.md
- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
Summary:
---------
One warning with all deprecated packages seems nicer and less intrusive. Also added links to the packages home pages for user convenience when informing maintainers.
Also added a migration guide to the configuration docs.
cc @satya164 @turnrye 	
Test Plan:
----------
Nope
> chore: group deprecated rnpm warnings, add migration guide

- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
Fixes 
```
error Trying to upgrade from newer version "0.59.9" to older "0.59.10"
```
🤦‍♂ Spotted while upgrading to `0.59.10`
Test Plan:
----------
Added a test case
> fix: incorrect condition for upgrade newer version check

- docs/autolinking.md
- packages/platform-android/native_modules.gradle
Summary:
---------
A lot of library maintainers and some app users may find themselves in a project with custom structure, like this:
```
root/
node_modules
example/
android/
ios/
```
Setting a custom root for Gradle project kinda worked, but it was brittle and hard to set. In cooperation with @Salakar we made setting the custom root in a similar fashion to iOS code:
```groovy
// example/android/settings.gradle
applyNativeModulesSettingsGradle(settings, "../..")
```
```groovy
// example/android/app/build.gradle
applyNativeModulesAppBuildGradle(project, "../..")
```
Adjusted the iOS docs to be more descriptive as well.
Test Plan:
----------
Tested in a monorepo and default structure.
> feat: simplify passing root to gradle autolinking

- docs/autolinking.md
- docs/projects.md
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/index.js
- packages/cli/src/tools/config/readConfigFromDisk.js
- packages/cli/src/tools/config/schema.js
- types/index.js
Summary:
---------
Currently autolinking doesn't support local libraries out of the box. However, we can leverage CLI configuration to make it "see" the React Native libraries that are not part of our 3rd party dependencies. This diff turns on taking user `dependencies` config as a part of initial user config. So essentially we're able to link our local libs that are not defined in package.json, but e.g. in `/root/libraries` and `/root/some/wild-libs` in this case:
```js
dependencies: {
'local-lib': {
root: '/root/libraries'
},
'local-lib-2': {
root: '/root/libraries'
},
'wild-lib': {
root: '/root/some/wild-libs'
},
},
};
```
This may also handy for "example" projects in RN libraries in a monorepo setup.
Test Plan:
----------
Added a test.
> feat: support local RN libraries in autolinking

- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
Makes the `upgrade` command a bit more helpful by:
- not failing with "Patch failed to apply for unknown reason"
- group files that are in the template but not in project
- group files that git failed to "apply"
- point to Upgrade Helper
- move "git apply" error output to the verbose mode
Example upgrade failure scenario:
Test Plan:
----------
Tests adjusted
> feat: improve `upgrade` when patches fail to apply

- __e2e__/legacyInit.test.js
- packages/cli/src/cliEntry.js
- packages/platform-android/native_modules.gradle
- packages/platform-ios/native_modules.rb
- packages/tools/src/logger.ts
Summary:
---------
This PR introduces `enable` and `disable` methods to logger, so that we can disable logging when calling `config`, which should only output valid JSON.
Fixes:
- fixes https://github.com/react-native-community/cli/issues/465 (running config on Windows)
- multi-line warnings breaking config JSON output on iOS 
Test Plan:
----------
Tested on a local project
> fix: config on Windows & warnings breaking config JSON output on iOS

- packages/platform-android/package.json
- packages/platform-android/src/commands/logAndroid/index.js
- yarn.lock
Summary:
---------
This PR was actually trying to fix #459 for logkitty@0.4.1 but since 0.4.2 is out (to revert back) and release 0.5.0 (for the new breaking change), this PR is more to update to the latest one.
Test Plan:
----------
Follow [testing-init-command](https://github.com/react-native-community/cli/blob/master/CONTRIBUTING.md#testing-init-command) locally and use the new [init](https://github.com/react-native-community/cli/blob/master/docs/init.md):
```sh
mkdir testlog && cd testlog
yarn init && yarn add react-native@${RN_VERSION} && yarn react-native init testlog
react-native log-android
```
> fix: log-android not working. update logkitty.

- packages/cli/src/cliEntry.js
- packages/cli/src/commands/info/__tests__/info.test.js
- packages/cli/src/commands/info/info.js
- packages/cli/src/commands/server/runServer.js
- packages/cli/src/tools/releaseChecker/index.js
Summary:
---------
We run release checker with every command. This is unnecessary and especially dangerous when running `config`, since we hit network and it may not resolve in time. 
Let's run it when it makes sense: 
- during development (`start` command) 
- when preparing an issue report (`info` command)
Fixes one of the issues haunting Windows: https://github.com/react-native-community/cli/issues/470
Test Plan:
----------
Run with `--verbose` and observe version check only triggers during mentioned 2 commands.
> fix: run release checker only after `start` and `info` command

- packages/platform-android/native_modules.gradle
Summary:
---------
This fixes #470. 
I changed the `config` command to one that works on Windows and replaced `cmdProcess.waitFor` with directly reading from the processes `InputStream` so the `buffer` is continuously cleared preventing a deadlock.
Test Plan:
----------
I tested this on a new project created using `react-native init` and making necessary edits to `native_modules.gradle` This works on Windows without a hitch. I did not test it on Linux or macOS but it _should_ work.
> Fix autolinking bug on Windows

- packages/cli/src/tools/config/index.js
Summary:
---------
When a package config is overwritten by user's `react-native.config.js`, and it outputs the "rnpm" warning, it happens that the entries are duplicate. Let's make sure we only iterate on unique package names.
> fix: duplicate entires in rnpm warning

- packages/platform-ios/src/commands/runIOS/index.js
Summary:
---------
Successful run (for each build output part we append a dot):
Failed run (we dumped whole output + error):
Test Plan:
----------
TBD
> feat: make run-ios output leaner

- packages/platform-android/native_modules.gradle
Summary:
---------
This is mainly for performance benefits. Using StringBuffer is much more efficient than direct string manipulation. For reference [look at this comparison](https://www.javaworld.com/article/2076072/stringbuffer-versus-string.html).
Test Plan:
----------
Tested on a new project in Windows.
> Use StringBuffer when getting config

- README.md
Summary:
---------
I added **updating guide** and cleared up the area related to facts and confusions in **About**.
Test Plan:
----------
Irrelevant
> chore: add updating guide & improve about

- README.md
Add Table of Contents for better navigation experience.
> feat(docs): Add Table of Contents

- packages/platform-android/native_modules.gradle
Summary:
---------
Fixes #467 - confirmed working on this issue. This adds support for 'this' being an Application instance or a ReactNativeHost instance when passed to the PackageList class constructor. 
Test Plan:
----------
> [android] Optionally support an Application instance in PackageList constructor

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
This is a temporary fix for #484 until [this PR](https://github.com/facebook/react-native/pull/25517) get approved in RN repo and a new RN version is released. It should be removed afterwards.
I basically replace the content of `launchPackager.bat` to its fixed version. Everything runs smoothly afterwards.
Test Plan:
----------
Tested this on a new project created using `react-native init` and manually editing the appropriate files to implement the fix. It seems to be working on my Windows machine. Should be tested before merge though.
> Fix Metro Bundler crashing on run-android on Windows

- packages/platform-ios/src/commands/runIOS/__tests__/findMatchingSimulator-test.js
- packages/platform-ios/src/commands/runIOS/findMatchingSimulator.js
Summary:
---------
react-native cli --simulator option is not working with some default simulator name in Xcode 10.2.1.
(e.g. "iPad Pro (9.7-inch)" )
Changed the regex in `findMatchingSimulator.js` to parse --simulator option string to find version number only (e.g. "iPad Pro (9.7-inch) (12.2)" )
Test Plan:
----------
> Fixed iOS simulator naming problem (name with brackets) in latest Xcode update

- packages/cli/src/commands/init/__tests__/templateName.test.js
- packages/cli/src/commands/init/templateName.js
Summary:
---------
Fixes init command to work with scoped template names that don't have a version suffix. A regex issue was causing template names like this to return an empty string as the template name:
`@react-native-firebase/template`
Test Plan:
----------
Added a unit test and also tried running init.
> fix: fix init command to work with scoped templates without version

- packages/cli/src/commands/server/runServer.js
- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/492 by not overriding user's `metro.config.js`. The `ctx.root` is always set to `process.cwd()` currently, so it didn't make sense anyway.
cc @janicduplessis 	
Test Plan:
----------
Verified on a sample project.
> fix: don't set `projetRoot` for Metro

- CONTRIBUTING.md
Hi,
My only change was a change in CONTRIBUTING.md file.
I think there was a typo mistake in instructions. 
Regards,
Michał Ciechanowicz
> contribution readmy fix

- docs/autolinking.md
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/344
Test Plan:
----------
N/A
> chore: add more information to autolinking guide

- packages/platform-ios/native_modules.rb
Summary:
---------
I've changed `native_modules.rb` to use relative path to package instead of absolute one. Fixes #488 
Test Plan:
----------
I've tested the changes manually by adding `react-native-community/@geolocation` via yarn to local project and running `pod install` to generate `Podfile.lock`. I've also changed one of the tests to take into account new path.
> feat: use relative paths in podfile lock

- packages/platform-ios/native_modules.rb
Summary:
---------
fix: use_native_modules! displays a descriptive warning and then skips any dependency packages without a podspec (#506)
Test Plan:
----------
1. Create a new react-native project using react-native v0.60.0
2. Install a dependency into `node_modules/` which the `react-native config` command will return a `platform.ios.podspecPath` value of `null/empty`. (e.g. `react-native-text-input-mask` https://github.com/react-native-community/react-native-text-input-mask).
3. Run the `pod install` command from the `ios/` folder.
**Expected Behavior:** The `use_native_modules!` function no longer attempts to load a podspec file using the `nil` `podspec_path` value causing the error message described in #506. The `use_native_modules!` function now skips the dependency without a …
> fix: use_native_modules! warns and skips dependencies without a podspec

- docs/commands.md
- docs/init.md
- packages/cli/src/commands/init/__tests__/templateName.test.js
- packages/cli/src/commands/init/templateName.js
Summary:
---------
This only work with `latest` tag on packages (see more details in #483) and hence cause confusion. For now, only full npm package names are supported. We can introduce some shorthand syntax, but under different flag. Legacy `init` is not affected, users can still use shorthand (and only that) notation there.
Test Plan:
----------
Updated tests.
> chore: remove unstable `init --template` shorthand support

- packages/cli/src/commands/install/uninstall.js
- packages/cli/src/commands/link/unlink.js
Summary:
---------
Add support for `--platforms` flag to `unlink`, same as in `link`.
This is helpful when a package can't support autolinking on a single platform. With `unlink --platforms android` we can only unlink Android if that's not supported. 
Related issue: https://github.com/kmagiera/react-native-gesture-handler/issues/671#issuecomment-509110370
Test Plan:
----------
No tests added. Verified this on a sample project, existing e2e tests should cover regressions.
> feat: support `unlink --platforms` 

- packages/cli/src/commands/init/printRunInstructions.js
> Add `xed ios` for opening Xcode to instructions

- packages/cli/package.json
- packages/cli/src/commands/init/init.js
- packages/cli/src/tools/installPods.js
- packages/cli/src/tools/loader.js
- yarn.lock
Summary:
---------
Added `pod repo update` command call after CocoaPods installation to
avoid issues with pod command being unable to find specification for
dependency (as per #487 ).
Added loader to CocoaPods installation step for consistency with other
steps of init and better DX, removed logger info after 30s timeout
because of redundancy with loader.
Changed loader method before prompt for CocoaPods installation from
`stop` to `info` for better prompt visibility.
Resolves #487 
Test Plan:
----------
Tested manually by uninstalling cocoapods gem, removing `~/.cocoapods` and running init command.
> fix: run `pod repo update` after installing CocoaPods

- packages/cli/package.json
- packages/platform-android/package.json
- packages/platform-ios/package.json
- packages/platform-ios/src/commands/runIOS/index.js
- packages/tools/package.json
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/516
Additionally:
- bumps chalk to latest for all packages
- Adds missing license fields to all packages.
Test Plan:
----------
CI
> fix: add chalk as dependency of cli-platform-android

- packages/cli/src/tools/config/index.js
Summary:
---------
When accessing `config.project` multiple times, there's no need to recalculate the `projectConfig()`, hence caching it. Dramatically improves performance of `warnAboutManuallyLinkedLibs` when running RNTester in `react-native` repo.
Test Plan:
----------
Nope
> fix: cache lazy project getter for perf when accessed repeatedly

- packages/platform-android/src/config/findPackageClassName.js
Summary:
---------
Regex that is used for finding class name of ReactPackage doesn't support custom formatting and implementation of more than one interface
Current regex doesn't work for code like this:
```kotlin
class ReactNativeSamplePackage: ReactPackage {
}
```
because there is no whitespace between `ReactNativeSamplePackage` and `:`
Module is not linked also when package class implements other interface before ReactPackage one
```kotlin
class ReactNativeSamplePackage: SomeInterface, NextInterface, ReactPackage {
}
```
Test Plan:
----------
Green tests
Try autolink module with package class like below
```kotlin
class ReactNativePackage
: 
ReactPackage {
override fun createViewManagers(reactContext: ReactApplicationContext): MutableList<ViewManager<View, ReactShadowNode<*>>> {
return …
```
> fix: better package class name regex on Android

- docs/commands.md
- packages/platform-android/package.json
- packages/platform-android/src/commands/runAndroid/index.js
- yarn.lock
Summary:
---------
Telling people to run `jetifier` seems to be less effective than just running it.
People can opt-out using `--no-jetifier` flag if needed.
cc @satya164 @mikehardy 	
Test Plan:
----------
> feat: run `jetifier` before `run-android`

- packages/cli/src/tools/installPods.js
fix minor bug where shouldInstallCocoaPods is falsy by default
Summary:
---------
when i run this cli for the first time with no cocoapods, the prompt asks me to install with a "Y/n" but when i hit enter it is taken as falsy and so it shows "No". but then it goes on to install anyway. seems like a weird quirk with `inquirer`
Test Plan:
----------
> fix: make "install CocoaPods" step in `init` true by default

- packages/cli/src/commands/init/editTemplate.js
Summary:
---------
In https://github.com/facebook/react-native/commit/65eea9d1f82215f7dd10241a3cc1045b6ac3918a, the prettier config for ESLint has been extracted to a .prettierrc file.
It was however not added to the React Native `template` folder and this was causing linting issues in newly generated RN apps.
In that [PR](https://github.com/facebook/react-native/pull/25478) to `react-native`, a `_prettierrc.js` file was added to the `template` folder, however, a newly generated project would have the file still underscored (see https://github.com/facebook/react-native/pull/25478#issuecomment-511452946)
This commit addresses that issue by adding `prettierrc.js` to the list of underscored files that need to be renamed to dotfiles.
Test Plan:
----------
Inside freshly cloned `react-native`: …
> feat: support `.prettierrc.js` dotfile in legacy `init` templates

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
Jetifier spawns workers to parallelize computations. By requiring it, the parent process is not waiting for children to finish. We can change that using `child_process` API and run `jetifier` directly as a binary.
Fixes #534 	
Test Plan:
----------
cc @Titozzz
> fix: run jetifier as executable to avoid race conditions

- packages/cli/src/tools/installPods.js
Summary:
---------
Just noticed this minor typo and fixed it in this PR 😄.
Test Plan:
----------
No wizard magic used here 🧙.
> chore: fix typo in init messages

- packages/platform-android/package.json
- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
Hopefully this resolves Windows issues. cc @theweavrs 	
Fixes https://github.com/facebook/react-native/issues/25667
Test Plan:
----------
Works on Windows
> fix: use execa to spawn jetifier

- packages/cli/src/tools/releaseChecker/getLatestRelease.js
- packages/cli/src/tools/releaseChecker/printNewRelease.js
Summary:
---------
It would be useful to see the diff changes before committing to an upgrade.  This adds the diff url to the weekly latest version check.  It will always show the diff from the current version to whatever the latest version is.
Some discussions here: https://github.com/react-native-community/cli/issues/189
Test Plan:
----------
Use cli commands on a project that uses an old version of React-Native and you'll see the diff url.
> feat: print web diff url when retrieving the latest release

- packages/platform-ios/native_modules.rb
Summary:
---------
Previous implementation assumed `node_modules` being somewhere in the
path to podspec file and relied on it to create relative path, which
broke monorepos (since `config` lists real filepaths instead of, as
I assumed previously, symlinks). New implementation subtracts project
root path from absolute path to podspec file for the purpose of generating
relative path.
Resolves #537
Test Plan:
----------
Tested changes manually to verify correct paths in `Podfile.lock`, adjusted existing tests
> fix: remove reliance on `node_modules` in paths to podspecs

- packages/cli/src/commands/init/init.js
Summary:
---------
Fixes issues regarding [this comment](https://github.com/react-native-community/cli/issues/448#issuecomment-512796812) on [#448](https://github.com/react-native-community/cli).
Test Plan:
----------
Create a new project with the `init` command. It should no longer delete the project folder if the project creation process fails.
> fix: preserve project folder after init failure

- packages/cli/src/commands/server/runServer.js
- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
#496 by @thymikee fixed projectRoot from metro config got overriden by ctx.root. I think the real error was taking the root from ctx instead of args. previously, an option '--projectRoot' was enabled. the projectRoot from args should override the metro config, if it exists, like the other options of the cli. this PR makes the `--projectRoot` option work again. and, if not specified will use the config option.
Notify:
----------
this should also help with storybook that previously used the `--projectRoot` option to start metro from the storybook root folder, instead of including it in your app (which is very non optimal and the recommendation as of now ). @shilman, @Gongreg is that right?
Test Plan:
----------
create a react native project. set a projectRoot option in …
> fix: bring `--projectRoot` argument back to `start`

- packages/cli/src/commands/server/runServer.js
Summary:
---------
At Facebook we have a hotkey hooked up to the ability to reload all connected devices and simulators. This is incredibly useful! However, we make this work by deploying an app to everyone's laptop that listens for a global hotkey to tell metro to reload. Since it isn't feasible to do that in open source, this seems like a reasonable approach. 
This PR adds the ability to hit the server host /reload, for example: `http://localhost:8081/reload` and metro will send a command to reload all connected apps.
Personally, I plan on wiring up a hotkey with better touch tool to curl this endpoint. I imagine people can set up alfred workflows or wire it into other apps too.
Test Plan:
----------
> Add ability to reload all connected devices and simulators

- packages/cli/src/commands/server/runServer.js
Summary:
---------
Backports https://github.com/react-native-community/cli/pull/574 to 1.x.
Test Plan:
----------
Copy this change manually into a 0.59 project and reload devices by hitting the endpoint.
> feat: backport reload endpoint to 1.x

- packages/cli/src/commands/link/linkAll.js
Summary:
---------
Fixes #584 by moving the asset linking task outside the dependency linking tasks.
Test Plan:
----------
> fix: link project assets when not linking deps

- packages/platform-android/src/config/__fixtures__/android.js
- packages/platform-android/src/config/__tests__/findPackageClassName-test.js
- packages/platform-android/src/config/findPackageClassName.js
Summary:
---------
Current regex doesn't support code like this:
```kotlin
class SomePackage() : ReactPackage {}
```
but kotlin does ;)
In this PR i added support for this
Test Plan:
----------
Try autolinking for Andorid with package class like this:
```kotlin
class SomePackage() : ReactPackage {
override fun createNativeModules(reactContext: ReactApplicationContext): MutableList<NativeModule> {
return Collections.emptyList()
}
override fun createViewManagers(reactContext: ReactApplicationContext): MutableList<SimpleViewManager<View>> {
return Collections.emptyList()
}
}
```
> fix: Package class name regex tweaks on Android

- packages/cli/src/commands/config/config.js
Summary:
---------
Fixes issues building for android when `react-native.config.js` has packages with `platforms` filter
Test Plan:
----------
With the latest version of `cli` create/modify the `react-native.config.js` with a package and any platform as such:
```js
dependencies: {
'interactable': {
platforms: {
ios: null, 
},
},
'appcenter': {
platforms: {
android: null,
},
},
}
}
```
The cli will build without throwing the error `TypeError: Cannot convert undefined or null to object at Function.keys () at isValidRNDependency`
> fix: safe check for `config` command

- packages/cli/src/commands/init/printRunInstructions.js
Summary:
---------
We introduced a regression where Workspace file was not found. This fixes it.
Test Plan:
----------
Local for now
> fix: init run instructions to show workspace

- docs/commands.md
- packages/cli/src/commands/server/server.js
Summary:
---------
Following my PR from yesterday #572 , I forgot to include the --projectRoot option descriptor in the PR, which makes it non usable or documented in --help. This PR fixes it.
i also went ahead and added path.resolve to the parsing of it, and of --watchFolders.
Test Plan:
----------
try using the cli start with custom project root set in metro config, it should load from the custom root. try using the cli start with --projectRoot that point to another directory (you can also check for relative path), it should override the metro config. try using the cli with a --watchFolders with relative paths, the folders you specified should be resolved and merged to those in the metro config.
> adding projectRoot to options and resolve it

- packages/platform-android/src/commands/runAndroid/index.js
Summary:
---------
It may happen, that the terminal detected by CLI or passed by the user is wrong and not really an executable. A good example is `vscode`, which sets `TERM_PROGRAM` env var to `vscode`, which is neither a command, nor a macOS app name. This PR introduces a fallback behavior for such cases, so that the terminal will be opened by a default `open` program. If that doesn't work, we produce a warning with directions on what to do now:
Test Plan:
----------
Packager should start in new terminal window, when running `run-android` from `vscode` or any other terminal.
> fix: fallback to default terminal if wrong one passed

- packages/platform-android/native_modules.gradle
Summary:
---------
Projects written in kotlin is not able to resolve `PackageList.java` (see #600)
Resolves #600
Test Plan:
----------
Tested in newly initialised project: 
`react-native init test && cd test && react-native run-android`
Also tested in kotlin project where android fails to build prior to this change
> fix: corrects sourcedir to be compatible with kotlin projects

- packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
This fixes [RN Issue #25904](https://github.com/facebook/react-native/issues/25904) where CLI gets stuck on `Starting JS Server...` in Windows.
This was due to using the `sync` command of `execa` which doesn't allow multiple commands to run side by side. In the issue, if you close the Metro Bundler, the `run-android` command continues.
Test Plan:
----------
Tested on a new RN Project
cc @thymikee
> fix: CLI stuck on "Starting JS server" on Windows

- packages/cli/src/commands/server/debugger-ui/index.html
Summary:
---------
Automatically set the appearance based on the global system dark mode, and remove the manual Dark Theme toggle.
Test Plan:
----------
Set macOS Appearance to Light and Dark in System Preferences -> General and watch the debugging UI background change from white to black. Tested myself in Chrome 76 and Safari 12.1.2 on macOS 10.14.6.
> feat: Add prefers-color-scheme dark mode

- __e2e__/init.test.js
- __e2e__/legacyInit.test.js
- package.json
- packages/cli/src/commands/init/__tests__/editTemplate.test.js
- packages/cli/src/commands/init/__tests__/templateName.test.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/template.js
- packages/cli/src/commands/init/templateName.js
- packages/cli/src/tools/__tests__/copyFiles.test.js
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/findAssets.js
- yarn.lock
Summary:
---------
This fixes all the failing tests on Windows.
Test Plan:
----------
Ran `yarn test` on Windows and everything passed.
> Fix tests on windows

- __e2e__/init.test.js
- __e2e__/legacyInit.test.js
- package.json
- packages/cli/package.json
- packages/cli/src/commands/init/__tests__/editTemplate.test.js
- packages/cli/src/commands/init/__tests__/templateName.test.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/template.js
- packages/cli/src/commands/init/templateName.js
- packages/cli/src/tools/__tests__/copyFiles.test.js
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/config/findAssets.js
- packages/cli/src/tools/replacePathSepForRegex.js
Summary:
---------
An attempt to fix the tests on Windows.
Test Plan:
----------
Green CI
> chore: fix tests on Windows

- packages/cli/src/commands/server/middleware/indexPage.js
Summary:
---------
Content-Type HTTP header is not set for index page. Chrome renders the page as plain text and Safari triggers download of Unknown.dms file instead.
Test Plan:
----------
Start server, open server index page in web browser and see the page is rendered as HTML not plain text (or doesn't trigger download in case of Safari).
| Before | After |
|--- | --- |
| <img width="804" alt="Screenshot 2019-08-05 10 49 14" src="https://user-images.githubusercontent.com/546887/62451745-22867200-b76f-11e9-84da-459a3789c25a.png"> | <img width="804" alt="Screenshot 2019-08-05 10 50 54" src="https://user-images.githubusercontent.com/546887/62451751-24e8cc00-b76f-11e9-8018-f90fb96aa88b.png">
> fix: add Content-Type header to index page

- packages/platform-ios/src/link/getHeaderSearchPath.js
> fix: use forward slashes instead of path.sep in iOS link

- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.js
- packages/cli/src/commands/upgrade/upgrade.js
- packages/cli/src/tools/installPods.js
Summary:
---------
Added calls to `installPods` in `upgrade` command to automatically
update pods after applying patch and installing JS dependencies.
Changed `installPods` helper to also accept argument determining whether
`pod repo update` should be ran before `install` and refactored it
slightly.
Added warnings when patch was not successfully applied to remind users
about running `pod install`.
Resolves #212
Test Plan:
----------
Tested changes manually by initialising new project on 0.60.2 and upgrading to 0.60.3 (happy path) and 0.60.4 (applying diff fails), updated snapshots with warning about manually updating pods if upgrade fails.
> feat: install pods after upgrade

- packages/platform-ios/native_modules.rb
Summary:
---------
Previous implementation made assumption that path to podspec contains
path to project root, which is not always the case, for example in
monorepos. This caused incorrect generation of podspec path, since in
that case it would return absolute podspec path prepended with root path.
Used `pathname` class method `relative_path_from` to avoid this issue.
Resolves #537 
Test Plan:
----------
Tested manually in freshly initialised project and on an example mentioned by @sm1th [here](https://github.com/react-native-community/cli/issues/537#issuecomment-513301147). This is still a WIP and I want to test it in other repos to make sure it works as expected.
> fix: change how relative path to podfile is created

- packages/platform-android/package.json
- yarn.lock
Summary:
---------
This should fix a couple of bugs on Windows. See the whole [logkitty changelog here](https://github.com/zamotany/logkitty/releases).
Test Plan:
----------
> Upgrade logkitty to 0.6.0

- packages/cli/src/commands/server/launchDebugger.js
- packages/cli/src/commands/server/launchDefaultBrowser.js
- packages/cli/src/commands/server/middleware/MiddlewareManager.js
- packages/cli/src/commands/server/middleware/getDevToolsMiddleware.js
- packages/cli/src/commands/server/middleware/openURLMiddleware.js
- packages/cli/src/commands/server/webSocketProxy.js
Summary:
---------
It can be annoying for users (like me) who do not have Google Chrome installed to enable 'Remote Debugging' only to receive an error. This rectifies that by falling back to the default installed browser making the whole experience more fluid.
Test Plan:
----------
Tested on a sample app by enabling 'Remote Debugging'.
> feat: fallback to default browser if Chrome is not found

- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
Sets a default `symbolicator.customizeFrame` value. This configuration option was added to Metro in https://github.com/facebook/metro/pull/435.
This is part of a redesign of https://github.com/facebook/react-native/pull/24662.
Test Plan:
----------
Equivalent config change tested as part of https://github.com/facebook/react-native/pull/25839.
> feat: set a default `symbolicator.customizeFrame` value

- packages/cli/src/commands/init/banner.js
Summary:
---------
Updated the banner message to use the same as what we have on the RN website: https://facebook.github.io/react-native/
Test Plan:
----------
yolo
> fix: update init banner message with website tagline

- packages/platform-ios/src/link/__tests__/getHeaderSearchPath-test.js
- packages/platform-ios/src/link/getHeaderSearchPath.js
Summary:
---------
Using `path.posix` for `getHeaderSearchPath-test` to make it pass on Windows.
Test Plan:
----------
Windows CI green
> fix: use posix path.sep in linking of header search path

- packages/cli/src/commands/server/runServer.js
Summary:
---------
I want to customize my Metro server with `server.enhanceMiddleware` in my `metro.config.js`. Currently [runServer.js:82](https://github.com/react-native-community/cli/blob/4a5192479de327b4215b0ae09ba13d82874a8d2e/packages/cli/src/commands/server/runServer.js#L82) overriddes this configuration option. PR enables usage of custom `enhanceMiddleware` from metro configuration for react-native-cli. 
Test Plan:
----------
Add this to your `rn-cli.config.js` or `metro.config.js` to clean react native project:
```js
const assert = require('assert');
/* ... */
server: {
/* ... */
enhanceMiddleware: (middleware, server) => {
assert.equal(typeof middleware, 'function');
assert.equal(server.constructor.name, 'Server');
console.log('Middleware enhanced');
return …
```
> feat: use server.enhanceMiddleware from custom metro configuration

- packages/cli/src/commands/server/debugger-ui/index.html
As per project migration notice at https://github.com/facebook/react-devtools
Summary:
---------
The [react-devtools](https://github.com/facebook/react-devtools) project was moved [into the main React repository](https://github.com/facebook/react/tree/master/packages/react-devtools).
> docs: update link to react-devtools

- docs/commands.md
- docs/init.md
- packages/cli/src/commands/init/__fixtures__/editTemplate/android/com/placeholdername/Main.java
- packages/cli/src/commands/init/__tests__/__snapshots__/editTemplate.test.js.snap
- packages/cli/src/commands/init/__tests__/editTemplate.test.js
- packages/cli/src/commands/init/editTemplate.js
- packages/cli/src/commands/init/index.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/template.js
Summary:
---------
Fixes: #561 
Apart from fixing a bug, I've added the ability to specify title placeholder for custom templates. Additionally, you can specify custom `title` for the project by passing `--title` flag.
Test Plan:
----------
> fix: Change title for newly initialised projects

- packages/cli/package.json
- packages/cli/src/tools/installPods.js
- yarn.lock
Summary:
---------
When a user doesn't have cocoapods installed and doesn't have sudo permissions they were prompted with infinite spinner. To fix that I've added system password prompt.
cc @orta @cpojer 
This is how it looks like:
Or MP4 here: https://dump.video/i/4DnHbM.mp4
Test Plan:
----------
> fix: Infinite spinner when installing cocoapods

- packages/cli/src/commands/doctor/healthchecks/androidHomeEnvVariable.js
- packages/cli/src/commands/doctor/healthchecks/androidNDK.js
- packages/cli/src/commands/doctor/healthchecks/androidSDK.js
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.js
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.js
- packages/cli/src/commands/doctor/healthchecks/nodeJS.js
- packages/cli/src/commands/doctor/healthchecks/watchman.js
- packages/cli/src/commands/doctor/healthchecks/xcode.js
- packages/cli/src/commands/doctor/printFixOptions.js
- packages/cli/src/commands/doctor/runAutomaticFix.js
@thymikee 
Summary:
---------
There were wrong variable (iosDeploy) names in some android js files (androidHomeEnvVariable.js). I fixed this by just exporting default functions directly which makes it cleaner anyway.
Test Plan:
----------
Not needed
> [Doctor] Export default functions directly

- packages/cli/src/commands/doctor/checkInstallation.js
Summary:
---------
The semver check was failing for version numbers that don't fit semver, like for Xcode version 10.3.
> fix semver check was breaking for non-semver versions

- packages/cli/src/commands/doctor/doctor.js
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.js
- packages/cli/src/tools/installPods.js
Summary:
---------
Consolidates how to install CocoaPods in a single function, and added the option to install it from Homebrew.
> feat(doctor): Reuse installCocoaPods() and add Homebrew option

- .flowconfig
- packages/cli/src/commands/doctor/checkInstallation.js
- packages/cli/src/commands/doctor/doctor.js
- packages/cli/src/commands/doctor/healthchecks/androidHomeEnvVariable.js
- packages/cli/src/commands/doctor/healthchecks/androidNDK.js
- packages/cli/src/commands/doctor/healthchecks/androidSDK.js
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.js
- packages/cli/src/commands/doctor/healthchecks/common.js
- packages/cli/src/commands/doctor/healthchecks/index.js
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.js
- packages/cli/src/commands/doctor/healthchecks/nodeJS.js
- packages/cli/src/commands/doctor/healthchecks/packageManagers.js
- packages/cli/src/commands/doctor/healthchecks/watchman.js
- packages/cli/src/commands/doctor/healthchecks/xcode.js
- packages/cli/src/commands/doctor/printFixOptions.js
- packages/cli/src/commands/doctor/runAutomaticFix.js
- packages/cli/src/commands/doctor/types.js
- packages/cli/src/commands/doctor/versionRanges.js
- packages/cli/src/tools/installPods.js
Summary:
---------
- add a generic `HealthCheckInterface` type
- remove redundant `getDiagnosticsAsync`, make `getDiagnostics` async 
- fix type issues
Test Plan:
----------
Flow passes
> doctor: add types

- packages/cli/src/commands/index.ts
- packages/cli/src/commands/info/__tests__/info.test.ts
- packages/cli/src/commands/info/info.ts
Summary:
---------
@thymikee I cribbed your ignore comments from #683. If this is the right approach, I'll claim a few more.
Test Plan:
----------
Green CI
> chore: migrate info command to TS

- docs/autolinking.md
- packages/platform-android/native_modules.gradle
Summary:
---------
This allow customizing configuration for the MainReactPackage.
Right now this is limited to changing how FrescoModule gets initialized
but in the future this can allow changes in behavior for other core modules
Test Plan:
----------
Since this is a template only change, it shouldn't require any tests.
I have verified that this is not a breaking change for existing users.
> feat: Allow passing in MainPackageConfig to PackageList

- packages/cli/package.json
- packages/cli/src/commands/info/info.ts
- packages/cli/src/commands/init/template.js
- packages/cli/src/commands/server/runServer.js
- packages/cli/src/tools/__tests__/copyFiles.test.ts
- packages/cli/src/tools/__tests__/packageManager-test.js
- packages/cli/src/tools/packageManager.js
- packages/cli/src/tools/releaseChecker/getLatestRelease.ts
- packages/cli/src/tools/releaseChecker/index.ts
- packages/cli/src/tools/releaseChecker/printNewRelease.ts
- packages/cli/src/tools/releaseChecker/releaseCacheManager.ts
- packages/cli/src/tools/replacePathSepForRegex.ts
- packages/cli/src/tools/yarn.ts
- yarn.lock
Builds on #685, that should be merged first
Summary:
---------
Migrate releaseChecker, yarn, walk, and replacePathSepForRegex to TS.
Test Plan:
----------
Green CI
> Typescriptify releasechecker

- packages/cli/src/tools/findSymlinkedModules.ts
- packages/cli/src/tools/loadMetroConfig.js
Summary:
---------
Part of #683. 
Test Plan:
----------
`yarn flow-check && yarn test`
> chore: convert findSymlinkedModules to TS

- packages/cli/src/cliEntry.js
- packages/cli/src/commands/index.ts
- packages/cli/src/commands/init/__tests__/template.test.js
- packages/cli/src/commands/init/init.js
- packages/cli/src/commands/init/template.js
- packages/cli/src/commands/install/install.js
- packages/cli/src/commands/install/uninstall.js
- packages/cli/src/commands/upgrade/__tests__/upgrade.test.ts
- packages/cli/src/commands/upgrade/upgrade.ts
- packages/cli/src/tools/__tests__/packageManager-test.js
- packages/cli/src/tools/__tests__/packageManager-test.ts
- packages/cli/src/tools/config/__tests__/index-test.js
- packages/cli/src/tools/generator/templates.js
- packages/cli/src/tools/packageManager.ts
- packages/platform-android/src/link/patches/__tests__/makeSettingsPatch.test.ts
Summary:
---------
Part of #683
Converted `commands/packageManager.ts` to typescript
Test Plan:
----------
`yarn test`
> [#683] Convert commands/packageManager.ts to TS

- packages/cli/src/commands/doctor/checkInstallation.js
- packages/cli/src/commands/doctor/doctor.js
- packages/cli/src/commands/doctor/healthchecks/androidHomeEnvVariable.js
- packages/cli/src/commands/doctor/healthchecks/androidSDK.js
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.js
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.js
Summary:
---------
This adds error messages for failing checks.
> doctor: add error messages for failures

- packages/cli/src/commands/doctor/healthchecks/androidSDK.js
- packages/cli/src/commands/doctor/healthchecks/common.js
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.js
- packages/cli/src/commands/doctor/healthchecks/watchman.js
- packages/cli/src/tools/brewInstall.ts
- packages/cli/src/tools/install.ts
- packages/cli/src/tools/installPods.ts
Summary:
---------
This is part of the `react-native doctor` issue at #694.
It fixes a problem with the `ios-deploy` healthcheck throwing an error without actually putting a _final state_ in the loader, causing it to leak into the next healthcheck:
It also changes some stuff regarding brew installation to keep consistency of what is being shown to the user (e.g. Watchman showing as `Installing watchman` after you choose fix and the others showing without `Installing` prefix).
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> doctor: fix missing `loader.fail()` call before showing how to fix manually on `ios-deploy`

- docs/commands.md
Summary:
---------
Test Plan:
----------
> docs: update commands on generating dev JS bundle for Android release

- packages/platform-android/src/commands/runAndroid/__mocks__/tryLaunchEmulator.ts
- packages/platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
- packages/platform-android/src/commands/runAndroid/index.ts
- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Summary:
---------
This PR resolves #142
TLDR; 
During`react-native run-android` the  first of user's emulators will be launched if there is no any running android device/emulator
`emulator -list-advs` to get a list of emulators
`emulator @FIRST_ON_LIST` to run the first available emulator
Test Plan:
----------
* Generate a project with React-native >60.0
* install CLI from my fork
* run `react-native run-android` without launched emulator -> emulator is launching
* run `react-native run-android` with launched emulator -> nothing new happens
* run `react-native run-android` with device connected -> nothing new happens
* run `react-native run-android` without launched emulator, emulator has saved snapshot -> emulator is launching
> feat: launch emulator during run-android

- packages/cli/src/commands/doctor/doctor.js
- packages/cli/src/commands/doctor/healthchecks/androidNDK.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/doctor/healthchecks/index.js
- packages/cli/src/commands/doctor/healthchecks/index.ts
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.ts
- packages/cli/src/commands/doctor/healthchecks/nodeJS.ts
- packages/cli/src/commands/doctor/healthchecks/packageManagers.ts
- packages/cli/src/commands/doctor/healthchecks/watchman.ts
- packages/cli/src/commands/doctor/healthchecks/xcode.ts
- packages/cli/src/commands/doctor/runAutomaticFix.js
- packages/cli/src/commands/doctor/types.ts
Summary:
---------
Finish the healthchecks migration to TS, continuing the work from #712 and #716 (linked to #683):
* `androidSDK`
* `iosDeploy`
* `nodeJs`
* `packageManagers`
* `watchman`
Test Plan:
----------
> chore: Migrate doctor command to TypeScript (3)

- packages/cli-types/src/index.ts
- packages/cli/src/commands/config/config.ts
- packages/cli/src/commands/index.ts
Summary:
---------
Part of #683 
Converted `commands/config` to typescript
Test Plan:
----------
Green CI
> chore: migrate config command to TS

- packages/cli/src/tools/copyAndReplace.ts
- packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
Summary:
---------
This PR is part of #683 
Converted copyAndReplace to typescript
I saw that this was assigned to @luizcieslak, but I didn't find any PR for it.
It's not my intention to take his/her work, if he/she sends a PR, this one can be ignored ;)
Test Plan:
----------
yarn build:ts
yarn lint
yarn flow-check
yarn test
> chore: convert copyAndReplace to TS

- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/tools/copyFiles.ts
- packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
- packages/cli/src/tools/walk.ts
Summary:
---------
This PR is part of #683 
Converted `walk` to typescript, and removed `ts-ignore` comments of files importing `walk`
Test Plan:
----------
yarn build:ts
yarn lint
> chore: convert walk to TS

- packages/cli/src/commands/doctor/doctor.ts
Summary:
---------
This PR is related to #694, currently the usage section shows even if you have everything correct when running `doctor`, with this change this will no longer happen.
Test Plan:
----------
1. `path/to/cli doctor --fix` (make sure that everything is green)
1. `path/to/cli doctor` - no usage should show up and the process should be terminated successfully
> doctor: only show fix options if there are errors or warnings

- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidHomeEnvVariable.test.ts
- packages/cli/src/commands/info/info.ts
- packages/cli/src/tools/envinfo.ts
Summary:
---------
Started writing tests for the `doctor` healthchecks, starting with `androidHomeEnvVariable`.
Since I needed the `envinfo` output in the test, and I will need it in all the upcomming tests, I moved it to the `tools` folder. Maybe it's not the best place, I'm not sure.
I only wrote one test to have feedback about the way of writing them, feel free to comment.
IMHO since these are unit tests we should mock all the imports and just make sure we call them when expected.
I didn't test the hard-coded SO links because it seems like a detail that wasn't worth testing.
Related to #694
Test Plan:
----------
This is a test so... CI is green? ✅
> [doctor command] Add tests for androidHomeEnvVariable

- packages/cli/src/commands/doctor/checkInstallation.ts
- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidHomeEnvVariable.test.ts
- packages/cli/src/commands/doctor/healthchecks/androidHomeEnvVariable.ts
- packages/cli/src/commands/doctor/healthchecks/androidNDK.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.ts
- packages/cli/src/commands/doctor/healthchecks/watchman.ts
- packages/cli/src/commands/doctor/healthchecks/xcode.ts
- packages/cli/src/commands/doctor/types.ts
Summary:
---------
This PR is related to #694, it adds a `description` field to each health check as discussed on [#672](https://github.com/react-native-community/cli/pull/672#discussion_r322698027), it also refactor a few that were using the `needsToBeFixed` as a `description`.
Test Plan:
----------
1. Uninstall something that's covered by `doctor` (e.g. `sudo gem uninstall cocoapods`);
1. `/path/to/cli doctor`.
> doctor: add health check description field

- packages/cli/package.json
Fix for react-native 0.61.0:
npm WARN @react-native-community/cli@3.0.0-alpha.2 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
> chore: use react-native 0.61.0 as peerDependency

- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/androidHomeEnvVariable.ts
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts
- packages/cli/src/commands/doctor/healthchecks/common.ts
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.ts
- packages/cli/src/commands/doctor/healthchecks/packageManagers.ts
- packages/cli/src/commands/doctor/healthchecks/watchman.ts
- packages/cli/src/commands/doctor/healthchecks/xcode.ts
- packages/cli/src/tools/brewInstall.ts
- packages/cli/src/tools/install.ts
Summary:
---------
This is related to #694, it improves the error messages by maintaining consistency between the health checks with one separated function to log errors.
It also fixes a problem introduced on #743 where it shows `undefined` when the `description` is not provided on a health check.
Test Plan:
----------
1. Make a health check fail;
1. `/path/to/cli doctor`.
> doctor: improve error messages

- docs/commands.md
Summary:
---------
There's a small typo in the Commands section of the docs. This fixes it :)
Test Plan:
----------
N/A
> docs: fix typo in commands section

- packages/platform-android/native_modules.gradle
Use output of subprocess in gradle file instead of input
Summary:
---------
See https://github.com/react-native-community/cli/issues/740.
Test Plan:
----------
Android Studio synchronizes.
> propagate react-native config error stream to logs

- packages/cli/src/commands/init/printRunInstructions.ts
Summary:
---------
Run instructions use projectName
Updated to use projectDir to display correct instruction when using the --direction option
> Update run instructions to use projectDir

- packages/cli/src/commands/server/launchDebugger.js
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/762
Test Plan:
----------
> fix: buggy behaviour when launching debugger on macOS

- docs/commands.md
- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
This is an attempt to solve problem on #739, based on idea provided at https://github.com/react-native-community/cli/issues/739#issuecomment-533904514
This changes the behavior of runIOS when no simulator argument is provided.
When no simulator argument is provided, the cli will look for simulators in the following order
- `iPhone 11`
- `iPhone X`
- `iPhone 8`
Test Plan:
----------
yarn
yarn test 
yarn lint
> feat: add fallback behavior when running a default simulator on iOS

- packages/cli/src/tools/config/readConfigFromDisk.ts
Summary:
---------
Reading configuration outside of the current working directory (in other words, project root), is not supported and can lead to dangerous errors. [I was pretty sure we never supported that](https://github.com/react-native-community/cli/pull/749#issuecomment-537931760), until I've found this out today.
Since I was able to remove this functionality without changing any tests, my recommendation is to not include it until: a) there is such a requirement (validated) from the user-side and that b) we have thoroughly tested this behavior.
Context:
---------
Fixes https://github.com/react-native-community/cli/issues/655).
As per [a comment from the above issue](https://github.com/react-native-community/cli/issues/655#issuecomment-538009106), the configuration is placed at the …
> fix: do not read configuration outside of the root

- packages/cli/README.md
- packages/cli/src/commands/runIOS/runIOS.js
Backports #758 to v1.x.
With Xcode 11.1 and its default set of simulators (which does not include iPhone X):
```console
$ npm install --global react-native-cli
$ react-native init AwesomeProject --version 0.59.10
$ cd AwesomeProject
$ react-native run-ios
error Could not find iPhone X simulator. Run CLI with --verbose flag for more details.
$ node …/packages/cli/build/index.js run-ios
info Launching iPhone 11 (iOS 13.1)...
```
> Backport #758 to v1.x

- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
React Native master (https://github.com/facebook/react-native/commit/cf4d45ec2bcd301be7793d5840de21ec7d02275b) is no longer stripping `YellowBox` and React DevTools stack frames from warnings with the `framesToPop` mechanism, which we will be deprecating and ultimately removing from the default error reporter too. The recommended approach going forward is to rely on Metro's `customizeFrame` for all postprocessing of stack traces.
This commit updates the default Metro config to skip stack frames in `YellowBox` and React DevTools code, thus preserving the old user-visible behaviour. As for compatibility and versioning: It is harmless to run this change against older RN versions, but the next RN release should include this CLI change. (cc @cpojer)
Test Plan:
---------- …
> Collapse YellowBox/DevTools frames in Metro config

- docs/commands.md
- packages/platform-ios/src/commands/runIOS/index.js
Backports #758 to v2.x. Prompted by https://github.com/react-native-community/cli/pull/777#pullrequestreview-300530686.
With Xcode 11.1 and its default set of simulators (which does not include iPhone X):
```console
$ npm install --global react-native-cli
$ react-native init AwesomeProject --version 0.60.6
$ cd AwesomeProject
$ react-native run-ios
error Could not find "iPhone X" simulator. Run CLI with --verbose flag for more details.
$ yarn link @react-native-community/cli-platform-ios
$ react-native run-ios
info Launching iPhone 11 (iOS 13.1)
```
> Backport #758 to v2.x

- packages/cli/src/commands/doctor/healthchecks/__tests__/androidNDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
Summary:
---------
Add unit tests for the healthchecks for `androidSDK` and `androidNDK`
Also removed a `$FlowFixMe` that wasn't removed when the `androidSDK` file was moved to TS.
Related to #694 
Test Plan:
----------
CI is green
> [doctor command] Add tests for androidSDK and androidNDK

- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/androidNDK.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts
- packages/cli/src/commands/doctor/healthchecks/common.ts
- packages/cli/src/commands/doctor/healthchecks/iosDeploy.ts
- packages/cli/src/commands/doctor/healthchecks/nodeJS.ts
- packages/cli/src/commands/doctor/healthchecks/packageManagers.ts
- packages/cli/src/commands/doctor/healthchecks/watchman.ts
- packages/cli/src/commands/doctor/healthchecks/xcode.ts
- packages/cli/src/commands/doctor/printFixOptions.ts
- packages/cli/src/commands/doctor/types.ts
Summary:
---------
This PR is related to #694 and it:
1. Shows the required current and required version for a failed health check;
1. Changes the wording from `to fix all issues` to `to try to fix all issues;
1. Fixes a problem where if you type a character not recognised on the usage it just doesn't listen to the correct characters anymore;
1. Puts the `description` content below the health check name rather than on the right side.
Test Plan:
----------
Run `doctor`.
> doctor: show required versions

- packages/platform-ios/src/link-pods/__fixtures__/PodfileWithInvalidKey.lock
- packages/platform-ios/src/link-pods/__tests__/getDependenciesFromPodfileLock.test.ts
- packages/platform-ios/src/link-pods/getDependenciesFromPodfileLock.ts
Summary:
---------
This PR fixes the issue described at https://github.com/react-native-community/cli/issues/805 where when `Podfile.lock` is an invalid yaml file, the `react-native run ios` command would fail.
To achieve this, I only parse parts of the Podfile we need, which are valid yaml.
Fixes #805
Test Plan:
----------
Unit test insures that error no longer happens and output is correct.
> fix: podfile parsing on invalid yaml

- packages/cli/src/commands/init/printRunInstructions.ts
fix #813, and maybe we avoid #759 by using the local react-native package.
> fix: use npx in `init` run instructions

- CONTRIBUTING.md
- README.md
- package.json
Summary:
---------
I had a little bit of a hard time testing my changes, because I didn't have the reflex to look for the `CONTRIBUTING.md` file.
Also, not sure why, but the method described to `test your changes directly` does not seem to work for me, nothing happens, so I added the way to test it using `yarn link`
Test Plan:
----------
This is documentation only :)
> Updated documentation to make contributing a tiny bit easier

- packages/cli/src/commands/server/middleware/getDevToolsMiddleware.ts
Summary:
---------
When running metro on one machine and a react-native app on another, /launch-js-devtools causes the metro process to launch localhost:8081. However, the hostname can be overridden by the --host parameter to react-native start, which because of the hardcoding of localhost, causes the web debugger to not start, breaking the react-native app.
Test Plan:
----------
Manually verified that the RN app can run when running react-native start with both: no params as well as --host <mymachinename>
> fix: Properly handle --host param for remote debugging

- lerna.json
The `lerna` field is no longer in use. It was made obsolete and removed in Lerna v3.
Reference: https://github.com/lerna/lerna#legacy-fields
> Remove deprecated lerna field

- packages/platform-ios/src/config/findProject.ts
Summary:
---------
Added `Carthage` to excluded directories while finding `.xcodeproj` file.
Test Plan:
----------
Add `Carthage/test.xcodeproj` to `ios` directory in example RN (61.4) project and run `pod install` and check if everything is alright.
> Add Carthage to excluded directories while finding .xcodeproj

- packages/cli/src/tools/config/resolveReactNativePath.ts
- packages/platform-android/native_modules.gradle
Summary:
---------
Gradle may be run from a driectory that's outside of JS project, with a passed project dir (through `-p` flag) like `path/to/app/android/gradlew bundleRelease -p ../app/android/app`. 
```
project/
app/ -> js, android, ios files
scripts/ -> running gradlew from here, e.g. through Fastlane
```
Gradle CWD is usually (maybe always, but they don't give guarantees) set to the directory where it's ran from. This tricks `npx`, which doesn't know where to find `react-native` binary. To account for it, we can spawn `npx` with a CWD passed to it. We don't need an exact path to android project directory, path to the project which holds `@react-native-community/cli` in node_modules is just fine with current config search mechanism.
I'm not 100% sure about this fix, open for …
> feat: run npx from JS app dir

- docs/commands.md
- packages/cli/src/commands/server/runServer.ts
- packages/cli/src/commands/server/server.ts
- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
This PR cleans up "start" command by:
- removing extraneous options that were never actually read (e.g. "transformer" was specified as a flag, but never passed to any line of code. "platforms" was defined, but never read. "providesNodeModules" as well). I am not entirely sure how we ended up in such state, but removing them should help with reducing potential confusion when developers are listing down flags that a command accepts
- removing options that are possible to be defined in a regular Metro configuration and there is no need to repeat support for them ("projectRoots", "assetsExts" and more, I have consulted official Metro website for that)
- renamed "config" to "metroConfig"
For use cases when someone wants to customize "react-native start" on per execution …
> feat: cleaned-up `start` command

- .vscode/settings.json
- package.json
- packages/cli/package.json
- packages/cli/src/commands/server/middleware/MiddlewareManager.ts
- packages/debugger-ui/package.json
- packages/debugger-ui/src/ui/index.html
- packages/debugger-ui/src/ui/index.js
Summary:
---------
- rename module to `@react-native-community/cli-debugger-ui`
- fix "Reload app" 
Test Plan:
----------
Reload button works
> fix: debugger-ui name and reload button

- CONTRIBUTING.md
- packages/cli/package.json
- packages/cli/tsconfig.json
Summary:
---------
Followup PR to https://github.com/react-native-community/cli/pull/767.
If you're curious, iOS and Android platforms are already shipping with `react-native` as default platforms since 0.60: https://github.com/facebook/react-native/blob/v0.60.0/package.json#L83-L85.
Test Plan:
----------
Green CI
> chore: remove platforms from cli dependencies

- packages/platform-android/native_modules.gradle
Summary:
---------
Apparently Gradle returns backslashes on windows for `buildscript.sourceFile.toString()`: https://github.com/react-native-community/cli/commit/a3a70a19e5b12c009deae5c9993ab0af73511cc2#r35970970. We need to account for that
Test Plan:
----------
Both are supported:
```
/node_modules/@react-native-community/cli-platform-android/
\node_modules\@react-native-community\cli-platform-android\
```
> fix: jsAppDir on Windows

- packages/platform-android/native_modules.gradle
Summary:
---------
Regression introduced in #824. Still looking for a better fix, because otherwise we'll need to reopen #793 and #804.
cc @mbios
Test Plan:
----------
> fix: temporary fix for a regression in monorepos

- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/versionRanges.ts
Summary:
---------
This PR fixes an issue with Xcode being shown as `Minimum required version: 10.0.0` even though we officially support `11.x`.
This issue has been reported through https://twitter.com/chakrihacker/status/1196750533224091648.
> fix: update Xcode version range to >= 10; change wording of supported version

- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
This also describes https://github.com/react-native-community/cli/commit/37e5411251fab10eae84a02d001bdc756a9b98bc which was accidently commited already :o
Add react-refresh, the new LogBox, scheduler and RN Timer module to the collapsed stacktraces. Those are all noisy and I think its reasonable to include them here. There is still enough context to know where the error came from without these stack frames. 
Test Plan:
----------
Before:
After:
Before:
After:
> Add react-refresh to collapsed stacktrace frames

- packages/cli/src/commands/server/copyToClipBoard.ts
Summary:
---------
When I run "react-native start" chmod always seems to fail for projects located on an NTFS filesystem under macOS:
```
EPERM: operation not permitted, chmod '.../node_modules/@react-native-community/cli/build/commands/server/external/xsel'
```
Here is the relevent code from copyToClipBoard.js:
```
const xsel = path.join(__dirname, 'external/xsel');
fs.chmodSync(xsel, '0755');
```
Without this the app works just fine. I'm not sure what the clipboard is used for. I think that maybe it's better to ignore this error since it's not critical.
Test Plan:
----------
1. Mount an NTFS volume via osxfuse and ntfs-3g as described at https://github.com/osxfuse/osxfuse/wiki/NTFS-3G
2. Create a project on that volume
3. Run `react-native start`
Without this patch, the command will …
> fix: gracefully handle chmod xsel

- packages/platform-android/native_modules.gradle
Summary:
---------
The `@` characters from npm scoped packages will cause name conflicts with Kotlin because Kotlin complier will generate `.kotlin_module` files base on module name by default.
For example, we have both `@segment/analytics-react-native` and `@matt-block/react-native-in-app-browser` modules installed. Currently they will be turned into Android modules with name `@segment_analytics-react-native` and `@matt-block_react-native-in-app-browser`. And they will both generate `META-INF/-no-jdk.kotlin_module` file because Kotlin complier failed to parse `@` in module name.
Eventually it causes build to fail with error: 
> More than one file was found with OS independent path 'META-INF/-no-jdk.kotlin_module'
Test Plan:
----------
Tested the code change on our project and it will …
> fix: remove @ character from module names

- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/doctor/types.ts
Summary:
---------
This is an attempt to fix the issues that have been noticed with the Android SDK health check when you have multiple versions of it installed.
The way this works is:
1. Android SDK searches for `android/build.gradle` file;
1. Get the value of `buildToolsVersion`;
1. Check if the value specified on `buildToolsVersion` is returned by `envinfo` as an installed version;
1. If it is, pass;
1. If not, fail the check showing the one (or multiple) version(s) installed along with the one required by the project.
Fixes #857
> doctor: change `Android SDK` check to fetch version from `build.gradle`

- packages/cli/src/commands/init/validate.ts
Summary:
---------
Use java keywords as a project name would get error like `Package 'com.xxxx' from AndroidManifest.xml is not a valid Java package name as 'xxxx' is a Java keyword.`
Test Plan:
----------
Use reserved words to init a new project will fail
> Check java keywords when init new project

- docs/autolinking.md
Summary:
---------
There is currently no documentation of how can a library author customise the auto-linking behaviour. This adds an example for the same.
As per schema mentioned here:
https://github.com/react-native-community/cli/blob/e496c2a89c06ad5969608e10a749da17edee6375/packages/cli/src/tools/config/schema.ts#L41-L47
Test Plan:
----------
This was tested by looking and validating the schema reference.
> docs: add example of dependency-level autolinking customisation

- README.md
Updated release cycle.
[3.x](https://github.com/react-native-community/cli/tree/3.x) will stay for React Native 0.61 and will not contain: 
a) Metro bump to 0.57 and 0.58 https://github.com/react-native-community/cli/commit/e496c2a89c06ad5969608e10a749da17edee6375 https://github.com/react-native-community/cli/commit/4f6b28e3e4d8276a0aac4e5a4bd5b08b953da4d5
b) fixed `run-android` with flavor which deprecates `appId` and `applicationId` parameters. This is minor change, but we're sticking to semver which requires us to bump major https://github.com/react-native-community/cli/commit/ada3e497325b5b3d0441f620d6ad276e4d773bd5 https://github.com/react-native-community/cli/commit/c199ecfdd1dcf8602cb10c3cbc55bddc5fc62435
Rather than that, it contains everything that has been released to `master` …
> chore: update release cycle

- README.md
Summary:
---------
Fixed the link in README that was leading to the wrong branch.
Test Plan:
----------
I guess click on the link. 🤷‍♂
> Fix link leading to the version 3.x in README

- packages/platform-android/native_modules.gradle
Summary:
---------
On machines where shebang is not supported, calling `bin.js` directly will not work. There's no reason to not prefix that with `node`.
> fix: machines where shebang doesnt work

- packages/platform-android/native_modules.gradle
- packages/platform-ios/native_modules.rb
Summary:
---------
The string versions of `Runtime.exec` on Android and `IO.popen` don't escape spaces, resulting in failing to resolve correct CLI path in directories containing spaces. Using array version instead to fix issues on both platforms.
> fix: correctly resolve cli path in directories containing spaces

- packages/platform-android/native_modules.gradle
- packages/platform-ios/native_modules.rb
Summary:
---------
See https://github.com/react-native-community/cli/issues/406#issuecomment-586220725 for explanation what happens.
This PR makes use of a fact, that CLI is available under https://github.com/facebook/react-native/blob/master/cli.js, which works regardless of package manager hoisting strategy. It doesn't make us closer to PnP support because we're making assumption we have `react-native` in the node_modules tree without declaring a dependency, but we can fix that later.
Fixes https://github.com/react-native-community/cli/issues/406
Test Plan:
----------
CLI is properly resolved under `npm`.
> fix: resolve CLI through react-native to avoid hoisting issues

- packages/cli/src/commands/init/printRunInstructions.ts
Summary:
---------
When initializing a project in a folder with spaces in the name, the commandline output showed a command which is not working for these folders. In general it is not recommended to create folders with spaces but in a Windows Environment it is quite common e.g. if the username is "John Doe" and you want to initialize a react-native project in a subfolder of the home directory.
To provide a working command id added quotes around the projectDir variable, so the command can be Copy & Pasted.
Test Plan:
----------
1. Create a directory with spaces in the name: `mkdir "my repositories"`
2. Switch to this directory `cd "my repositories"`
3. Run `react-native init testproject`
4. Before this change the following output was generated:
[...]
```
Run instructions for iOS:
• cd …
```
> fix: added quotes for run instructions

- packages/platform-ios/native_modules.rb
Summary:
---------
Abstract targets [don't support script phases](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb#L432), this change skips adding script phases if the current target is abstract.
**Fixes** https://github.com/invertase/react-native-firebase/issues/2800
cc @orta / @alloy for review please, thanks!
Test Plan:
----------
@gabrielbull would you be able to patch package this change in and confirm it now works? https://github.com/invertase/react-native-firebase/issues/2800
---
**script phases continue to work on non abstract targets**:
> fix(ios): skip script phases on abstract targets

- packages/cli/src/commands/doctor/healthchecks/__tests__/androidHomeEnvVariable.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidNDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/types.ts
Summary:
---------
Noticed that locally doctor tests fail on my machine, because it takes too much time to execute `envinfo` in parallel. To address that, I added a slightly bigger timeout and removed some unnecessary callsites.
Test Plan:
----------
^ Up
> chore: simplify doctor tests

- packages/cli/src/tools/config/__tests__/index-test.ts
Summary:
---------
Windows expects paths to be forward-slashed, so using `slash` in our test to achieve that
Test Plan:
----------
Windows config test no longer failing
> chore: fix windows config tests

- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/tools/config/findProjectRoot.ts
Summary:
---------
Windows CI sets `$CWD` to `D:\`, which is not where the project exists. To not alter the source code too much, I mocked the `findProjectRoot` so that it returns a local path. A proper fix would be reading the root (and, in turn, gradle.build path) from the config passed to the command. See #791 for reference
Test Plan:
----------
Green windows CI
> chore: fix windows sdk test

- package.json
- scripts/watch.js
- yarn.lock
Summary:
---------
Use `chokidar` to track file system changes as soon it will throw an
error if the platform does not support `{ recursive: true }`.
Fix also an error where the built file was not being deleted when the
source was removed.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Fix #989
Ref: https://github.com/nodejs/node/pull/29947
Test Plan:
----------
N/A
> fix: make watch work in all platform

- lerna.json
- package.json
- packages/cli-types/package.json
- packages/cli/package.json
- packages/debugger-ui/package.json
- packages/global-cli/package.json
- packages/platform-android/package.json
- packages/platform-ios/package.json
- packages/tools/package.json
Summary:
---------
Per #978, running `yarn link-packages` was failing with the following output:
```
yarn run v1.21.1
$ PACKAGES=('tools' 'platform-ios' 'platform-android' 'cli' 'cli-types' 'debugger-ui') && cd packages && for PACKAGE in "${PACKAGES[@]}"; do cd $PACKAGE && yarn link && cd ..; done
/bin/sh: 1: Syntax error: "(" unexpected
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This PR fixes that using [`yarn workspaces run`](https://classic.yarnpkg.com/en/docs/cli/workspaces#toc-yarn-workspaces-run)
The output now is:
```
$ yarn link-packages
yarn run v1.21.1
$ yarn workspaces run link
> @react-native-community/cli-types
success Registered "@react-native-community/cli-types".
info You can now run `yarn …
```
> fix: script to link all packages

- lerna.json
- package.json
- packages/cli-types/package.json
- packages/cli/package.json
- packages/debugger-ui/package.json
- packages/global-cli/package.json
- packages/platform-android/package.json
- packages/platform-ios/package.json
- packages/tools/package.json
- scripts/linkPackages.js
Summary:
---------
`lerna changed` shows that `global-cli` is ignored, but `lerna publish` ignores it. Falling back to yarn linking with a script then.
Test Plan:
----------
Works for me
> chore: use script to link packages because lerna is buggy

- packages/cli/src/index.ts
Summary:
---------
Follow up of #960 
```bash
react-native inf
error Unrecognized command "inf". Did you mean "init"?
``` 
Set the threshold to 40% such that `info` shows up instead in the above scenario.
> chore: use a better threshold factor to find the closest match

- package.json
- yarn.lock
Summary:
---------
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/
We won't be able to use much of the new syntax (typescript-eslint/typescript-eslint#1465) but the stricter checks etc are 👍
Test Plan:
----------
🍏
> chore: upgrade TS to 3.8

- __e2e__/__snapshots__/default.test.ts.snap
- __e2e__/default.test.ts
Summary:
---------
Test case for default behavior, shows up help information if no arguments were passed.
Test Plan:
----------
Match snapshot.
> chore: test case for default behavior

- package.json
- packages/cli/src/commands/doctor/doctor.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/doctor/types.ts
- packages/cli/src/commands/server/eventsSocket.ts
- packages/cli/src/commands/server/middleware/getDevToolsMiddleware.ts
- packages/cli/src/index.ts
- packages/cli/src/tools/config/readConfigFromDisk.ts
- packages/cli/src/tools/generator/promptSync.ts
- packages/cli/tsconfig.json
Summary:
---------
Noticed that type defs were not built properly for `packages/cli`. The reason was `"include": "../package.json"` in TS config, which resulted in TS happily passing everything. Seems like a bug in TS, present on both 3.7 and 3.8.
Test Plan:
----------
Type defs are there in `build/` dirs
> fix: building TS definitions broken by include package.json

- __e2e__/__snapshots__/default.test.ts.snap
- packages/cli/src/index.ts
Summary:
---------
closes #1012 
Test Plan:
----------
None
> chore: fixup usage misleading information

- __e2e__/unknown.test.ts
Summary:
---------
This is a test case to ensure that an appropriate warning message shows up if an unknown command is passed in.
Test Plan:
----------
Use `toContain()` API available as part of `Jest`.
> chore: test case for passing in unknown command

- .gitignore
- babel.config.js
- jest.config.js
- packages/cli-types/package.json
- packages/cli/package.json
- packages/debugger-ui/package.json
- packages/platform-android/package.json
- packages/platform-ios/package.json
- packages/tools/package.json
- scripts/build.js
Summary:
---------
I really need all the help I can get when coding. Having breakpoints in TypeScript instead of JavaScript is really high on my list. Otherwise I always end up modifying the JS and then erasing all changes in the next build because I was modifying the wrong place 😅
The only way I've found to make this work in this project is by creating sourcemaps.
Here's an example of it running on VS Code:
What it does:
1. Create a valid `.map` for each file in the build process
1. Append `//# sourceMappingURL=FILE.map` to each JS generated file
1. Ignore all `.map` files during the publishing process so the package doesn't increase in size. There were some packages that didn't have a `files` property in `package.json`. I have not ignored in those cases.
To make this work from VS Code …
> Create sourcemaps for easier debugging

- packages/cli/src/commands/server/eventsSocket.ts
Summary:
---------
When using a production build of flipper, the network requests are made from a pre-bundled javascript file, which results in an origin header based on a local file url. In a future we will make sure that this origin is consistent both in prod- and non-prod builds, but for compatibility reasons making sure it will be compatible with the next react-native CLI version as well
Facebook: this corresponds with diff D20001690
Test Plan:
----------
1. Download the latest public release build of Flipper
2. Before this patch, it won't be able to connect, with this patch, it will be
Before:
After:
> Open `/events` for locally served javascript files as well

- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
- packages/cli/src/commands/server/middleware/index.html
- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
https://reactnative.dev is up, so why not
Test Plan:
----------
Checked that links work
> chore: update RN docs links to reactnative.dev

- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
Summary:
---------
Working on #976 I had some issues making the CLI crash when  `build.gradle` is missing.
Test Plan:
----------
> fix: avoid crashing if build.gradle is missing

- .vscode/settings.json
Summary:
---------
Internal only, saving now doesn't conflict with default formatter
> chore: fix vscode "run on save" settings

- packages/cli/src/commands/server/watchMode.ts
Summary:
---------
Moved "Watch mode is not supported in this environment" log to debug level.
Fixes https://github.com/expo/expo-cli/issues/1589
From my testing, no Expo functionality was affected, as CLI is run as a child process and is not a TTY. However, extra log message may have been confusing for the users.
Also, watch mode can be disabled by passing `--no-interactive` flag to the RN CLI.
cc @brentvatne 
Test Plan:
----------
Tested using both latest Expo and CLI alone
> fix: don't log watch mode not supported to stdout (fixes Expo)

- packages/cli/src/commands/info/info.ts
- packages/cli/src/tools/envinfo.ts
Summary:
---------
While working on #976 I saw that I needed to modify the properties requested to `envinfo` and that it was being accessed in a couple different places with different configurations.
This PR changes that to use a single point (and single configuration) to get the info.
> chore: refactor envinfo

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Related: https://github.com/facebook/react-native/issues/21303
Related: https://github.com/facebook/react-native/issues/14423
Test Plan:
----------
I'm getting wrong build target because some pods are also specified a target and this was in xcode env. The grep just matches first but not always the right TARGET. So instead of matching use JSON parsing.
> fix: pick correct TARGET_BUILD_DIR for run-ios

- packages/cli/package.json
Summary:
---------
This will still result in warnings for RC versions, but that's fine
cc @alloy 
Test Plan:
----------
None
> chore: set correct react-native peer dependency

- packages/cli/src/commands/init/init.ts
Summary:
---------
Initializing to the pre-existing directory was all about removing all the files in that directory. This approach doesn't make much sense from user perspective as it might lead to unexpected/accidental removals (even though we ask). From now on, we just fail when the directory exists and we leave it up to the user what to do with that.
> feat: bail out when initializing new project to pre-existing directories

- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
The `react-native/jest/hasteImpl.js` file was removed in 0.61, so we should be safe to remove it.
Test Plan:
----------
Tested on a local project.
> chore: remove setting hasteImplModulePath in Metro config

- packages/cli/src/commands/bundle/assetPathUtils.ts
https://github.com/react-native-community/react-native-svg/issues/1306
https://github.com/facebook/react-native/pull/28266
https://github.com/facebook/metro/pull/529
Summary:
---------
Fix mapping of svg files. They're currently bundled to the drawable folder incorrectly.
Test Plan:
----------
LocalSvg.js
```jsx
import React, {useState, useEffect} from 'react';
import {SvgCss} from 'react-native-svg';
import loadLocalResource from 'react-native-local-resource';
export function LocalSvg({asset, ...rest}) {
const [xml, setXml] = useState(null);
useEffect(() => {
loadLocalResource(asset).then(setXml);
}, [asset]);
return <SvgCss xml={xml} {...rest} />;
}
```
App.js
```jsx
import React from 'react';
import {LocalSvg} from './LocalSvg';
export default () => <LocalSvg …
```
> fix(android): Incorrect mapping of svg files

- packages/cli-types/package.json
Summary:
---------
Currently external plugin authors using TS cannot access the `cli-types` declaration files as they're not published to NPM. This change removes the file exclusion allowing them to be published.
cc @thymikee as discussed on Discord
> fix(cli-types): publish declaration files in npm package

- packages/cli/src/commands/link/__tests__/link.test.ts
- packages/cli/src/commands/link/link.ts
- packages/cli/src/commands/link/linkAll.ts
- packages/cli/src/commands/link/printDeprecationWarning.ts
- packages/cli/src/commands/link/unlink.ts
Summary:
---------
Let's finally deprecate linking commands C:
Test Plan:
----------
Deprecation warning prints correctly.
> chore: add deprecation messages for manual linking

- docs/commands.md
- docs/configuration.md
- packages/cli-types/src/index.ts
- packages/cli/src/commands/server/server.ts
- packages/cli/src/tools/config/__mocks__/index.ts
- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/src/tools/config/__tests__/index-test.ts
- packages/cli/src/tools/config/index.ts
- packages/cli/src/tools/config/readConfigFromDisk.ts
- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
- Haste is no longer used at React Native core, so removing anything Haste-related
- `rnpm` is deprecated since v2, so it's about time to remove it.
- remove `--platform` flag from `start` as it was not used anyway
This forces Windows platform to adapt to new config format.
There's no rush merging that, but I think we should be pretty safe by now.
Test Plan:
----------
Updated tests, but please make sure to test it thoroughly
> chore: remove haste and rnpm

- README.md
Summary:
---------
No point documenting that at the moment as it increases confusion.
Test Plan:
----------
Docs
> docs: remove legacy init from the readme

- packages/platform-android/native_modules.gradle
Summary:
---------
This fixes #1031 (a regression introduced with #910). It also makes sure that the package name contains only an allowed chars.
Theoretically NPM scope name can contain only a lowercase url-safe chars (`a-z 0-9 - _ . ! ~ * ' ( )`). But I did not tried to use those chars as the scope name. I mean the validator does not throw an error but I'm not sure if you can save it actually. I've attached some screenshots from npmjs.org:
On the other hand package name cannot contain these chars: `/ \ : < > " ? * |`. So we definitely need to replace `*` to be 100% sure that the package name is correct. Also I replaced `~ ! ' ( )` too (or I shouldn't do that?).
Test Plan:
----------
I've tried to add `yarn add @bam.tech/react-native-snap-carousel` and build the app.
The app builds …
> fix: scoped packages with `.` produces incorrect package name

- packages/platform-ios/src/commands/runIOS/__tests__/parseIOSDevicesList.test.ts
- packages/platform-ios/src/commands/runIOS/index.ts
- packages/platform-ios/src/commands/runIOS/parseIOSDevicesList.ts
Summary:
---------
Close https://github.com/react-native-community/cli/issues/998
Since Mac Catalyst won't be popular for RN projects anytime soon (I assume), I only changed the code to make it work when specifying a device name. If not, `run-ios` will still fall back to the default iOS simulator.
It seems that Mac will always be the first in the `xcrun` listed devices.
Test Plan:
----------
1. Run `react-native run-ios --device "Rui’s Mac"`
2. Now it does not return "No iOS devices connected" anymore
> feat: support run-ios on Mac target (Catalyst)

- packages/cli/src/commands/bundle/__tests__/getAssetDestPathAndroid-test.ts
- packages/cli/src/commands/bundle/__tests__/getAssetDestPathIOS-test.ts
- packages/cli/src/commands/bundle/getAssetDestPathIOS.ts
Summary:
---------
When an asset is outside of the metro project root, it can lead to relative paths like `/assets/../../node_modules/coolpackage/image.png` as the `httpServerLocation`. This can happen for example when using yarn workspaces with hoisted node_modules.
This causes issues when bundling on iOS since we use this path in the filesystem. To avoid this we replace `../` with `_` to preserve the uniqueness of the path while avoiding these kind of problematic relative paths. The same logic is used when bundling assets in the rn-cli.
RN part of this PR: https://github.com/facebook/react-native/pull/27932
Test Plan:
----------
Tested that an asset in a hoisted node_modules package doesn't show up before this patch and does after in a release build.
> Fix bundling assets with a path outside of the project root

- docs/commands.md
- packages/cli/src/commands/server/server.ts
Summary:
---------
It's not passed to Metro at all.
Test Plan:
----------
CI
> chore: remove unused --assetExts from server

- docs/dependencies.md
- packages/cli-types/src/android.ts
- packages/cli/src/tools/config/schema.ts
- packages/platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
- packages/platform-android/src/config/index.ts
Summary:
---------
#1029 broke Android dependency discovery and `--appId` handling. Fixing it here.
cc @Krizzu
Test Plan:
----------
CI
> followup: fix what #1029 broke

- package.json
- yarn.lock
** Fix Prototype pollution vulnerability**
Summary:
---------
A small PR that forces mkdrip to a release that contains a fix for the prototype pollution venerability can read more about it here  https://github.com/HoLyVieR/prototype-pollution-nsec18/blob/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf
> Update to mkdirp

- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/upgrade/upgrade.ts
- packages/cli/src/tools/installPods.ts
Summary:
---------
Fixes #1060 
Test Plan:
----------
Run `pod install` on outdated repo. Also includes a mechanism to prevent loops in case `pod repo update` didn't fix the error (e.g. invalid version specified).
> feat: run `pod repo update` when `pod install` failed

- docs/dependencies.md
- packages/platform-android/native_modules.gradle
Summary:
---------
Hard importing `${packageName}.R` and `${packageName}.BuildConfig` helps to install React Native modules which use `R` and `BuildConfig` without package prefix (eg. `react-native-code-push`, see https://github.com/react-native-community/cli/pull/435 fixing  https://github.com/react-native-community/cli/issues/434.) `BuildConfig` import has been introduced in https://github.com/react-native-community/cli/pull/258, so right from the beginning (specific commit: https://github.com/react-native-community/cli/commit/64f3f5a3db137c5cee4bbe26b18b26a7c55a205e).
This pull request:
- adds support for interpolating `{{ packageName }}` in `packageImportPath` and `packageInstance`
- adds support for `generatePackageList` task to libraries (imagine a project where its the submodule …
> feat: replace {{ packageName }} in deps' configuration

- packages/cli/src/commands/bundle/saveAssets.ts
Summary:
---------
Based on discussion on #609, `assetsDest` checking can be safely removed in favour of `mkdirp` when copying files.
Test Plan:
----------
None.
> feat: remove assetsDest checking

- packages/cli/src/commands/init/init.ts
Summary:
---------
We're way past 0.60 now, so this check is not necessary anymore. It also prevents from using nightlies, which are tagged with `0.0.0-commithash`.
Test Plan:
----------
In case someone tries initing older versions of RN, which is still not possible, they'll see this error anyway:
cc @alloy @pvinis
> chore: remove >=0.60.0-rc.0 restriction for init

- packages/cli/src/tools/envinfo.ts
Summary:
---------
We are relying quite a lot on CocoaPods so it makes sense to have it when running `react-native info`, will be useful for bug reports.
Test Plan:
----------
1. Run `react-native info`;
1. Be happy 😄
> feat: add CocoaPods to `info` command

- packages/cli/src/commands/init/template.ts
- packages/cli/src/tools/packageManager.ts
Summary:
---------
When creating a new project with `npx react-native init MyApp`, the template installation step fails because there is no `package.json` inside the temp folder. This PR fixes that by running `yarn/npm init -y` before the template installation.
Fixes #1075 
Test Plan:
----------
CI passes
> fix: yarn/npm init before install template (#1603)

- docs/platforms.md
- packages/platform-android/src/config/__tests__/getProjectConfig.test.ts
- packages/platform-android/src/config/index.ts
Summary:
---------
After #1029 the Android config was not correctly resolving the default values for `stringsPath`, `assetsPath` and `mainFilePath`. It was also not returning a value for `packageFolder`. This PR also updates the Android config typedef in the docs.
Test Plan:
----------
Added jest test. Manually linked into existing project and verified that `npx react-native config` was returning the correct values.
> fix: android config returns incorrect paths

- packages/platform-ios/src/commands/runIOS/__tests__/findMatchingSimulator.test.ts
- packages/platform-ios/src/commands/runIOS/__tests__/parseIOSDevicesList.test.ts
- packages/platform-ios/src/commands/runIOS/findMatchingSimulator.ts
- packages/platform-ios/src/commands/runIOS/index.ts
- packages/platform-ios/src/commands/runIOS/parseIOSDevicesList.ts
- packages/platform-ios/src/types.ts
Summary:
---------
This makes it possible to be very specific about what simulator to use in the same way you’d interact with tooling such as `simctl`.
Fixes https://github.com/react-native-community/cli/issues/1078
Test Plan:
----------
Given a device list like:
```
/t/RNTestProject » xcrun instruments -s
Known Devices:
Eloy’s iMac [E163381F-C94E-5B5E-922E-DBB59B685FA6]
Eloy’s iPhone (13.3.1) [00008030-000D19512210802E]
iPhone 11 (13.3) [60E7F277-DC13-46B8-ADFB-7C5C9BC01274] (Simulator)
iPhone 8 (12.4) [0F518318-4C9B-49BA-89B9-1D0E325681BB] (Simulator)
```
```
/t/RNTestProject » ./node_modules/.bin/react-native run-ios
info Found Xcode workspace "RNTestProject.xcworkspace"
info Launching iPhone 11 (iOS 13.3)
info Building (using "xcodebuild -workspace RNTestProject.xcworkspace …
```
> feat: allow selection of iOS sim with `--udid`

- packages/cli/src/commands/server/middleware/getSecurityHeadersMiddleware.ts
Summary:
---------
This change reflects D20526486 by @rickhanlonii  at Facebook: when Running Hermes Debugger from inside Flipper, the origin is localhost, but not the metro port. This fixes https://github.com/facebook/flipper/issues/660#issuecomment-606239984
Test Plan:
----------
* Init fresh project with React Native
* Enable Hermes
* Open Flipper, start the Hermes Debugger. This will generate the error in the metro logs: "Error: Unauthorized request from http://localhost:3000. This may happen because of a conflicting browser extension. Please try to disable it and try again."
* After this change (tested by directly editing in node_modules) and restart metro, the debugger does connect:
> Fix: allow Hermes Debugger to connect from Flipper

- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Ref. discussion in #1085 
Upgrade to CLI v4.4 breaks normal usage of `--appIdSuffix`. Bug was introduced with https://github.com/react-native-community/cli/commit/19ac71f02c0ececa669afb26dce2cb02f0de23f6#diff-b668aefc66b33ed6e984d3467db0abc1R54 where `appIdSuffix` is concatenated to `variant` in order to generate the run task name.
The suffix should probably only be used to launch the correct package, and not for deciding what to build. If the user needs to specify some build type + flavor, the best thing is to put the full variant name in `--variant`.
Test Plan:
----------
1. Create a new React Native project
2. Add an `applicationIdSuffix` to the `debug` buildType in `android/app/build.gradle`:
```gradle
buildTypes {
debug {
applicationIdSuffix ".debug"
signingConfig …
```
> fix: don't use appIdSuffix to generate run task

- yarn.lock
Summary:
---------
Shaves 12MB from our own node_modules, so all contributors can save some space :) 
Tool I'm using: https://github.com/atlassian/yarn-deduplicate
Test Plan:
----------
CI
> chore: run yarn-deduplicate to shrink node_modules

- packages/platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Summary:
---------
Windows uses different `EOL` when `UNIX` systems. We can fix this by using node API: https://nodejs.org/api/os.html#os_os_eol.
Fixes: https://github.com/react-native-community/cli/issues/1084
> fix: split output by EOL

- packages/tools/src/getDefaultUserTerminal.ts
Summary:
---------
User correct `env` variable for opening new terminal on `linux`.
EDIT: This assumes that `linux` users have their `TERM` env variable exported correctly (I think this is the only reliable way to tell what terminals are used on linux systems). On my ArchLinux it was exported with value `xterm-256color` (it should be just `xterm`).
Test Plan:
----------
Tested on ArchLinux
> fix: Use correct terminal on linux systems

- packages/cli-types/src/node-stream-zip.d.ts
- packages/cli/package.json
- packages/cli/src/commands/doctor/healthchecks/__tests__/jdk.test.ts
- packages/cli/src/commands/doctor/healthchecks/index.ts
- packages/cli/src/commands/doctor/healthchecks/jdk.ts
- packages/cli/src/commands/doctor/types.ts
- packages/cli/src/commands/doctor/versionRanges.ts
- packages/cli/src/tools/deleteFile.ts
- packages/cli/src/tools/downloadAndUnzip.ts
- packages/cli/src/tools/envinfo.ts
- packages/cli/src/tools/unzip.ts
- packages/tools/src/fetch.ts
- yarn.lock
Summary:
---------
Install JDK@11 on Windows if missing. I went with 11 because from my tests it was the latest one that was working with Gradle. After it they were all giving me problems.
The documentation mentions that is has to be 8 or later and with that version local installation for the user is painful as there is not a .zip available.
I tried to install it on mac as well but all the options I found in homebrew prompted for a password 😔
You can see it in action (+ python) in this video:
[![YouTube vide to JDK installation](https://user-images.githubusercontent.com/606594/77324576-30740d80-6cd4-11ea-84b3-806f0489e0da.png)](https://youtu.be/tRtBRMxLh6s)
Fix #980
> feat: install JDK automatically if missing

- packages/platform-ios/native_modules.rb
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/865. It's not autolinking React Native, but we have a helper function already called `use_react_native!`. This PR enables `use_native_modules!` to return a configuration it used to set things up, so that CocoaPods can actually read `config["reactNativePath"]` rather than a hardcoded one.
See https://github.com/react-native-community/cli/issues/865#issuecomment-601214973 and https://github.com/react-native-community/cli/issues/865#issuecomment-601272596
> feat: return config from the Ruby function

- CONTRIBUTING.md
Not passing the `--watchFolders` flag to `npx react-native start` when testing changes locally results in a cryptic error "ReferenceError: SHA-1 for file (...)/cli/node_modules/metro/src/lib/polyfills/require.js (...) is not computed".
Let's add a more prominent note about it in the contributor docs to help others avoid this problem.
Summary:
---------
Test Plan:
----------
> docs: add a note about --watchFolders in CONTRIBUTING.md

- babel.config.js
Summary:
---------
Realized we were targeting Node 8.0, while react-native targets 8.3, because it introduces object spread. This results in the `cli` package being 8.5kB uncompressed smaller.
Test Plan:
----------
Green CI
> chore: target not 8.3, not 8.0

- packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
motivation: fix issue described in https://github.com/react-native-community/cli/issues/1100
Test Plan:
----------
works for me locally :D I do not have enough time+context to write an automated test.
Please note that while it works for me, I cannot tell if this will work for everyone, because it seems the current way works for some people: https://github.com/react-native-community/cli/issues/1100#issuecomment-611568602
> fix: do not ignore androidProject.sourceDir option

- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
This small PR updates outdated link to the React Native documentation in the Android app installation error message. Unfortunately in the current version of docs it's not possible to select `React Native CLI` and `Android` tabs using anchors (`#`) in the URL.
Test Plan:
----------
N/A
> chore: update docs link in the Android installation error message

- packages/cli-server-api/src/devToolsMiddleware.ts
- packages/cli-server-api/src/index.ts
- packages/cli-server-api/src/openStackFrameInEditorMiddleware.ts
- packages/cli/src/commands/server/middleware/MiddlewareManager.ts
- packages/cli/src/commands/server/middleware/getDevToolsMiddleware.ts
- packages/cli/src/commands/server/middleware/openStackFrameInEditorMiddleware.ts
- packages/cli/src/tools/loadMetroConfig.ts
- packages/tools/src/launchEditor.ts
Summary:
---------
This PR changes the TS type of `watchFolders` and `projectRoots` arrays to read-only everywhere. These arrays come from the Metro configuration and they've already been treated as immutable and not modified anywhere. The read-only array type signals this: the function doesn't modify the array.
The rationale for this type change is that it helps avoid type errors when `watchFolders` is passed from Metro config to `createDevServerMiddleware`, for example:
```ts
const { middleware, attachToServer } = createDevServerMiddleware({
port: metroConfig.server.port,
watchFolders: metroConfig.watchFolders,
});
```
When `watchFolders` was `Array<string>` , this code resulted in a type error, because `watchFolders` is `ReadonlyArray<string>` in Metro config. (A work-around was to …
> refactor: make watchFolders read-only everywhere

- packages/cli-server-api/src/index.ts
Summary:
---------
Metro `/symbolicate` endpoint requires the request body to be available
in `req.rawBody`, which the `rawBodyMiddleware` adds.
Fixes the following error from `cli-server-api`:
SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at /Users/ville/Projects/react-native-cli/node_modules/metro/src/Server.js:1026:28
Test Plan:
----------
Tested this together with https://github.com/react-native-community/cli/pull/1140, as the `master` branch doesn't have `cli-server-api` enabled yet.
Without the fix, running an app with a `console.warn` or `throw new Error` in the code resulted in the following error printed to the console: `SyntaxError: Unexpected token u in JSON at position 0`. Also the stack traces were not symbolicated, showing Metro bundle …
> fix: read request body for Metro symbolication

- docs/platforms.md
- packages/cli-types/src/index.ts
- packages/cli/package.json
- packages/cli/src/tools/config/schema.ts
- packages/cli/src/tools/loadMetroConfig.ts
- packages/cli/src/tools/metroPlatformResolver.ts
- yarn.lock
Summary:
---------
Currently it is hard to write out of tree platforms that do the right thing, and have a single metro config.  Basically as fallout from the removal of haste, now out of tree platforms contain a full implementation of react-native.  In order to build an out tree platform you have to redirect any `react-native` import into an import into to a different package.
`react-native-macos` and `react-native-windows` do this today by specifying custom extraNodeModules settings on the metro resolver to redirect `react-native` to their respective packages.  But that requires a different metro config to build macos vs building windows.
We have come up with a new solution that uses a custom **resolveRequest** function to rewrite the resolutions at bundle time, at which point we know …
> Allow out of tree platforms to work without custom metro configs

- docs/commands.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Added skip install options mentioned in #1142, this option adds the ability to simply skip the installation of dependencies after the template has been set up
Test Plan:
----------
This option doesn't fundamentally change  any mechanics, I ran every test mentioned in [CONTRIBUTING.md](CONTRIBUTING.md), also tested by creating a project and manually installing the dependencies and checking that everything was in place and worked correctly
> feat: added --skip-install option to init command

- packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
We have manifestPath defined already in Android project, but it was not used in the runAndroid command, so this just fixes that. Old parameters are kept as a fallback, they could be deprecated in future.
Test Plan:
----------
This is needed to test Android in react-native-webview, there's otherwise working code which just needs this change here: https://github.com/jussikinnula/react-native-webview/tree/feat-react-native-0-62-support
> Fix Android project's configuration `manifestPath` is not used by @react-native-community/cli-platform-android #1159

- packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
`manifestPath` should be always available in `run`. If it doesn't exist we throw an Error on `config` creation level - https://github.com/react-native-community/cli/blob/4c8af54e29059af74b7edd813425f4ab0815eeb5/packages/platform-android/src/config/index.ts#L46.
cc. @grabbou @thymikee
> imp: Manifest cleanup

- __e2e__/config.test.ts
- __e2e__/default.test.ts
- __e2e__/init.test.ts
- __e2e__/install.test.ts
- __e2e__/legacyInit.test.ts
- __e2e__/root.test.ts
- __e2e__/uninstall.test.ts
- __e2e__/unknown.test.ts
- jest.config.js
- jest/helpers.ts
- jest/setupE2eTests.js
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/tools/__tests__/copyFiles.test.ts
- packages/cli/src/tools/config/__tests__/findDependencies-test.ts
- packages/cli/src/tools/config/__tests__/findProjectRoot-test.ts
- packages/cli/src/tools/config/__tests__/index-test.ts
Summary:
---------
I'm trying to improve the reliability of Windows CI so I can get #1109 green.
I've found out that `cleanup()` uses `rimraf.sync` underneath. Windows FS is not very... reliable, and sometimes you can end up with `ENOTEMPTY` errors like [this one](https://dev.azure.com/react-native-community/cli/_build/results?buildId=1248&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=417). In fact, [`rimraf`'s documentation](https://www.npmjs.com/package/rimraf#api) calls that out:
> Windows: `EBUSY` and `ENOTEMPTY` - rimraf will back off a maximum of `opts.maxBusyTries` times before giving up, adding 100ms of wait between each attempt. The default `maxBusyTries` is 3.
The problem is the above does not apply when using the sync method:
> If an …
> chore: make `cleanup` async

- packages/platform-android/package.json
- yarn.lock
Upgrade logkitty to 0.7.1 to tackle security issue CVE-2020-8149
> chore: upgrade logkitty to 0.7.1

- __e2e__/__snapshots__/default.test.ts.snap
- packages/cli/src/commands/doctor/index.ts
- packages/cli/src/commands/index.ts
Summary:
---------
Detaching the `doctor` command so it's possible to run without being in react-native project like this:
```sh
npx @react-native-community/cli doctor
npx react-native doctor
```
cc @brentvatne since you brought that up recently
Test Plan:
----------
Tests updated
> feat: detach doctor command

- packages/platform-ios/src/commands/runIOS/index.ts
this PR update iOS simulators descriptions, i think `iPhone 5` it is old so i changed for `iPhone SE`.
> chore: use iPhone SE instead of iPhone 5 in `run-ios` example

- packages/platform-ios/src/commands/runIOS/index.ts
Currently, we have
```
...
Options:
--simulator [string]      Explicitly set simulator to use. Optionally include iOS version betweenparenthesis at the end to match an exact version: "iPhone 6 (10.0)" (default: "iPhone 11")
--configuration [string]  Explicitly set the scheme configuration to use (default: "Debug")
--scheme [string]         Explicitly set Xcode scheme to use
--project-path [string]   Path relative to project root where the Xcode project (.xcodeproj) lives. (default: "ios")
--device [string]         Explicitly set device to use by name.  The value is not required if you have a single device connected.
--udid [string]           Explicitly set device to use by udid
--no-packager             Do not launch packager while building
--verbose                 Do not use xcpretty …
```
> Fix minor typo in run-ios

- docs/autolinking.md
Summary:
this PR remove link `autolinking` when you click in this link appears error 404,  i try to find this file but it doesn´t exists.!
> docs: update link in autolinking.md

- .vscode/settings.json
- packages/cli-types/src/ios.ts
- packages/platform-ios/native_modules.rb
- packages/platform-ios/src/config/__tests__/native_modules.test.ts
Summary:
---------
Small regression introduced by a previous change to the file. `reactNativePath` is absolute (as returned by the CLI configuration) in order to be used in various places.
The path used by `Podfile` has to be relative to its location, hence the change. I am leaving the object as a return value to avoid changing RN files and make it easy to customize in the future.
Context: The output of running `use_native_modules` is used here: https://github.com/facebook/react-native/tree/master/template/ios/Podfile#L9
> fix: Podfile.lock paths are no longer absolute

- packages/cli/src/index.ts
- packages/cli/src/tools/config/errors.ts
- packages/tools/src/errors.ts
Summary:
---------
Fixes #1181 
Throw an error with the correct message when configuration fails to load because of an invalid shape. Before the error was lost and running commands resulted in "Unrecognized command" error. The details were only available with `--verbose` flag and resulted in quite a confusion and poor experience.
Before:
After:
Test Plan:
- 
Use the below invalid config:
```js
project: {
android: {
wrongConfiguration: 'test',
},
},
};
```
- run `react-native config` or any other command requiring config
- The correct error should be shown
> fix: throw a better error when configuration is invalid

- docs/commands.md
- packages/cli/src/commands/init/index.ts
Summary:
---------
I got a bit confused while reviewing https://github.com/react-native-community/cli/pull/1110, so decided to propose some description updates.
> chore: improve desc of `--version` option in `init` command

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Cherry-pick from https://github.com/react-native-community/cli/pull/1032
A fix to `react-native run-ios` was merged into 0.62 but 0.61's `run-ios` command still has the bug, so this PR just backports the fix.
Test Plan:
----------
Ran `react-native run-ios` in our codebase using 0.61 with this patch, and it now works. It was previously broken because `run-ios` was confused by the `TARGET_BUILD_DIR` present in the `React` pod target's build settings (as opposed to our app's build settings)
> [backport from 0.62] fix: pick correct TARGET_BUILD_DIR for run-ios (#1032)

- packages/tools/src/launchEditor.ts
Summary:
---------
There is logic for guessing an appropriate text editor on macOS.  This adds similar logic for windows.  Without this, developers have to manually set the `REACT_EDITOR` environment variable in order to navigate to code from redbox/logbox.
This change roughly aligns with the logic on macOS.  If `REACT_EDITOR` is set we default to using that.  But if the developer is running in order VSCode, SublimeText, Visual Studio, or lastly notepad, then we assume that we should use that editor.
Also fixed an issue where if the linenumber wasn't specified, the workspace would not be passed to vscode, which could cause the file to open in the incorrect vscode window.
Test Plan:
----------
Tested locally on windows with these apps running  / not running or `REACT_EDITOR` set, and …
> Add windows logic to guess the users preferred editor for launchEditor

- packages/tools/src/launchDebugger.ts
On windows, use new chromium based edge if the user is already running it, and is not running chrome
Summary:
---------
I'm still leaving the default as chrome on windows machines.  But if the user is using msedge, and not using chrome, then that will be used instead.
The debugging experience is basically the same with msedge and chrome.  Since windows already has edge, there is no need for users to install chrome to get a good developer experience.  This change makes the CLI use msedge if its running rather than prompting the user to install chrome.
I didn't go farther and change the default to use msedge unless we detect its running, as not all windows machines have it installed.
Test Plan:
----------
Validated on windows with and without chrome/edge running.  If chrome is running it'll …
> [Windows] Use new chrome based edge if the user is already running it

- jest.config.js
Summary:
---------
`jest.seTimeout()` won't work with `setupFiles`, use `setupFilesAfterEnv` instead.
Test Plan:
----------
This PR aims at updating `jest` config.
> chore: update jest config

- packages/cli/package.json
Summary:
---------
v4 supports both 0.62 and 0.63.
Test Plan:
----------
No peer dep warning
> fix: proper range on RN peer dep

- CONTRIBUTING.md
Summary:
---------
I needed to test a fork of the `cli` in a project that uses `yarn` v2 and found that the instructions didn't work. So, to help any others in this situation, I am proposing a change to the `docs`.
Test Plan:
----------
Just a `docs` change so no testing applicable.
> Add linkage instructions for `yarn` v2

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Fix: https://github.com/react-native-community/cli/issues/1208
This behavior
with this envs:
```
PRODUCT_BUNDLE_IDENTIFIER = paz.church;
PRODUCT_NAME = Paz.Church;
```
Test Plan:
----------
```
react-native run-ios --simulator="iPhone 11 Pro Max"
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
- react-native-code-push (to unlink run: "react-native unlink react-native-code-push")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read …
```
> fix: 🐛 executableFolderPath to run app name in iOS 14.0

- packages/tools/src/launchDebugger.ts
Summary:
---------
Currently the CLI has a bunch of messy code to try to force the usage of chrome, then if that fails we use the default browser.  This removes that code and just always uses the users default browser.
Test Plan:
----------
Tested locally on my box.  (Windows machine - msedge default).  The code being run isn't new code, as its run when a user doesn't have chrome installed so it should work ok.
> Just use the users default browser

- packages/platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Summary:
---------
Working on a white label feature for an app, I ran into an issue where I needed to set the appId differently to the package name and an explicit main activity in a different package.
For example my build.gradle application ID could be `com.test` and the manifest package be `com.test` however my main activity, from a dependency, has been set explicitly set in the manifest as `com.dependency.AnActivity`.
When running:
`react-native run-android --appId com.test --main-activity com.dependency.AnActivity`
the result would be:
`Error: Activity class {com.test/com.packagename.com.dependency.AnActivity} does not exist.`
I have made a small change to allow an explicit main activity with package name set.
Test Plan:
----------
Run similar to `react-native run-android --appId …
> Fix package name for main activity when appId set

- packages/cli/src/tools/envinfo.ts
- yarn.lock
Summary:
---------
This PR will enable out of tree platforms to report their npm packages in `react-native info`
Test Plan:
----------
Verified that running the built JS on a react-native-windows app correctly reports the react-native-windows package too.
Verified that changing the mapping to not include win32 (so that platform never matches it) correctly does not report it.
> feat: augment `info` with out of tree platform packages info

- packages/cli-hermes/src/profileHermes/downloadProfile.ts
Summary:
---------
this PR remove await in `getLatestFile `  call function from `packages/src/cli-hermes/profileHermes/downloadProfile.ts` it has no effect this function.
> chore: remove await in getLatestFile function call from downloadProfile file.

- packages/cli/package.json
- yarn.lock
Summary:
---------
Refs: #1244
This PR bumps Joi types package to match used Joi version. New types are still available under org scoped `hapi__joi`, the `joi` types package stops at 14 release.
Test Plan:
----------
Successful `yarn install` run!
> chore: bump joi types to 17

- packages/cli/src/commands/init/printRunInstructions.ts
Summary:
---------
This PR adjust the run instructions printed at the end of `init` command run which now should show only valid targets for the user platform. I have also updated the links for the desktop forks from MS to lead exactly to platform specific guides.
* `iOS` and `macOS` instructions will be only visible on `darwin`
* `Windows` instructions will be only visible on `win32`
Test Plan:
----------
I was trying to test the `init` locally using [Contributing guide](https://github.com/react-native-community/cli/blob/master/CONTRIBUTING.md#testing-init-command), but I have experienced problems and issues after publishing `react-native` master locally. 
One of many problems which leads to `init` termination:
```
error Couldn't find package …
```
> chore: adjust run instruction based on the user platform

- packages/platform-ios/src/commands/runIOS/index.ts
this PR update iOS description for `iPhone SE`, We have to specify the generation for the `iPhone SE` simulator.
> chore: update description for ios simulator

- docs/plugins.md
Summary:
---------
As discussed in #1300 I've added a simple note about the usage of the word `--version` for `options.name` to warn future plugin writers about that specific case
This closes #1300
> chore: add docs note about option.name version

- CONTRIBUTING.md
Summary:
---------
No need for verdaccio, we can run init command locally, without proxying it through `react-native` binary.
Test Plan:
----------
None
> docs: remove legacy init testing section

- package.json
- packages/cli/src/commands/start/watchMode.ts
- yarn.lock
Summary:
---------
Refs: #1072
This small PR bumps the Node types package (`@types/node`) to the `10.0.0` version to match the current [minimal supported version](https://github.com/react-native-community/cli/blob/master/packages/cli/package.json#L21) of Node required for the CLI.
Test Plan:
----------
Successful `yarn install` run!
> chore: bump Node types to match supported Node version

- packages/cli/src/commands/init/errors/ReservedNameError.ts
- packages/cli/src/commands/init/validate.ts
Summary:
---------
to be a valid project name the name must not be a keyword, currently the error being thrown will claim the user tried using "React" as the project name even if they used another keyword.
Test Plan:
----------
There is already a test that check the error is created correctly, we can add a test with another keyword but I don't think that is needed.
There are two commits in this PR, the second one can be dropped if we don't consider the error class part of the public API since we only use the class in one place and in that place I added the new parameter.
> The keyword error gives a misleading message when the keyword is not "React"

- packages/cli-server-api/package.json
- packages/cli-server-api/src/index.ts
- packages/debugger-ui/package.json
- packages/debugger-ui/src/middleware/index.ts
- yarn.lock
Summary:
---------
It looks like the built assets get cached sometimes causing issues such as https://github.com/facebook/react-native/issues/28844
This might happen if the HTML file got cached, but there's a new version available with different links.
It's better to disable the caching altogether since the development server is run locally and caching files causes more problems than it helps.
Normally it's possible by developers to disable caching when devtools is open, but it's not reasonable to expect everyone to do it.
The commit changes 2 things:
- Set relevant headers to prevent caching of assets using the 'nocache' middleware
- When building files with parcel, make sure that the name of the built files don't change
Fixes #1081 
Test Plan:
----------
I have tested this in a fresh …
> fix: disable caching of assets for the development server

- .circleci/config.yml
- babel.config.js
- packages/cli/package.json
Summary:
---------
Updated node version of CI to use v12, as supported node version for React Native will be v12 from react-native v0.64
Test Plan:
----------
CI to pass on Node v12
> chore(breaking): use Node 12 as compile target

- packages/cli/src/commands/bundle/buildBundle.ts
- packages/cli/src/commands/bundle/bundleCommandLineArgs.ts
Summary:
---------
This adds a new command line option `--unstable-transform-profile` and simply passes the value to metro.
Test Plan:
----------
Tested in an app by adding `extraPackagerArgs: ["--unstable-transform-profile", "hermes-canary"],` in the build.gradle react config.
> Support experimental transform profile for bundle command

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Updating the default iOS simulator to `iPhone 12` and adding `iPhone 11` as a fallback simulator to support those not using Xcode 12. I'm tempted to remove `iPhone X` as a fallback since `iPhone 11` has been used as the default simulator.
Test Plan:
----------
yarn
yarn lint
yarn test
> Update default iOS simulator and fallback

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
This request is to cherry-pick the fix for #1208 from commit c736b21c8f3965028b5c59bd8cde07b0b32d08cc onto the 3.x branch for RN 0.61 compatibility with iOS 14 SDK. The commit applied cleanly with no modification.
See pull #1236 for original, summary included here:
Fix: #1208
This behavior
with this envs:
```
PRODUCT_BUNDLE_IDENTIFIER = paz.church;
PRODUCT_NAME = Paz.Church;
```
Test Plan:
----------
test plan from original PR:
```
react-native run-ios --simulator="iPhone 11 Pro Max"
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
- react-native-code-push (to unlink run: "react-native unlink react-native-code-push")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going …
```
> fix: 🐛 executableFolderPath to run app name in iOS 14.0 (#1236) for 3.x branch

- packages/cli/package.json
- packages/cli/src/tools/loadMetroConfig.ts
- yarn.lock
Summary:
---------
When testing RN CLI on a sample project we pass a `--watchFolders /path/to/cli` flag to Metro after performing `yarn link` to overcome no symlinks support. In one of the recent releases of Metro (0.63 or later) this workflow broke with `UnableToResolveError`. After small digging it turned out that `metro-runtime/src/modules/asyncRequire` is not resolved properly in such a workflow. 
We can overcome this in CLI by manually overwriting `asyncRequireModulePath` with an absolutely resolved path. Not sure if CLI users need that change, but without it we can't test Metro locally, so adding this just in case.
Test Plan:
----------
Run `react-native start` locally set up to run CLI from source and make sure it runs properly in cases like fast refreshing, reloading from …
> fix: overwrite asyncRequireModulePath to make Metro work locally

- __e2e__/init.test.ts
Summary:
---------
Increase test coverage.
Test Plan:
----------
Supplying `--npm` prefers `npm` for initialization, added a test case that ensures this behavior.
> tests: add test case for using --npm with init

- packages/cli/package.json
Summary:
---------
Fix https://github.com/react-native-community/cli/issues/1318
```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-native@undefined
npm WARN node_modules/react-native/node_modules/react-native
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-native@">=0.64.0-rc.0" from @react-native-community/cli@5.0.1-alpha.0
npm WARN node_modules/react-native/node_modules/@react-native-community/cli
npm WARN   @react-native-community/cli@"^5.0.1-alpha.0" from react-native@0.0.0-00e623ddb
npm WARN   node_modules/react-native
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native@>=0.64.0-rc.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't …
```
> Allow react-native nightly builds

- docs/dependencies.md
- packages/cli-types/src/android.ts
- packages/cli-types/src/ios.ts
- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/src/tools/config/__tests__/index-test.ts
- packages/cli/src/tools/config/schema.ts
- packages/platform-android/native_modules.gradle
- packages/platform-android/src/config/index.ts
- packages/platform-ios/native_modules.rb
- packages/platform-ios/src/config/index.ts
Summary:
---------
Currently, you can't use the auto-linking with modules that should be added only to a specific build type (for example, only to the debug builds). With those changes, people can easier install helper packages. I believe this is a really nice addition to the `react-native-cli`.
Why have I added two fields (under `ios` and `android`)?
I believe in that way we give users the most control over their packages. Moreover, users people can use everything that native platforms give them - build variants/flavors on Android, pod configuration on iOS.
Test Plan:
----------
- create a package with custom `react-native.config.js`
```
dependency: {
platforms: {
android: {
buildTypes: ['debug']
},
ios: {
buildTypes: ['debug']
}
}
}
}
```
- link this package into your …
> feat: allow adding modules only for the specific build type

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Fixes #1282 
We used to parse the build output for `appName` (or used scheme as a default value) only to check if it contains `tvOS` to detect whether we should spin up a `tvOS` simulator.
There's a better way to do it - we can return `buildOutput` and just look for `PLATFORM_NAME` variable which will be of `appletvsimulator`, `iphonesimulator` or `iphoneos` depending on how we built the project before.
It is unlikely that we don't find the value, but because of types, I have included an `if` statement to throw in such case, which I consider unexpected.
I have also updated regular expression to factor in potential quotation marks and `=` escaping.
As a result, we can simplify the code. Related prior work #1314 
Test Plan:
----------
Run `react-native run-ios` on …
> feat: better platform name detection

- __e2e__/init.test.ts
Summary:
---------
The init functionality fails if the specified directory already exists; added a test case for this scenario.
Test Plan:
----------
This PR aims at updating the test suite.
> chore: add e2e test for when init fails if the directory already exists

- docs/commands.md
Summary:
---------
Information regarding `--assetPlugins` was missing from the docs.
Test Plan:
----------
N/A
> docs: add info regarding --assetPlugins

- packages/cli/src/commands/index.ts
It turns out that, by a mistake, `doctor` command is registered twice, both as project and detached command. It has been converted to `detached` few months ago. 
It could be hidden `commander` feature that when multiple functions are registered under the same name, they run in order. Attaching some screenshots for reference:
Removing it from `projectCommands` fixes the problem.
We will address similar issue https://github.com/react-native-community/cli/issues/1261 soon where detached commands (such as `doctor` included) can receive and take advantage of `config` when present in the project.
> fix: doctor command prints output twice

- packages/cli/src/tools/__tests__/loadMetroConfig-test.ts
- packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
Motivation outlined in https://github.com/react-native-community/cli/issues/1348
Test Plan:
----------
I wasn't sure what to do for testing this because there isn't any precedent for testing `loadMetroConfig` or `getDefaultConfig` that I could find. I added a test for `getDefaultConfig` to ensure this option doesn't accidentally get disabled, although I understand that this is not the most useful test.
Note: the `Context` type is massive and difficult to construct, so I tried to narrow it to just what we use here by replacing `ctx: Context` with `ctx: ConfigLoadingContext` as defined here:
```ts
type ConfigLoadingContext = Pick<Config, 'root' | 'reactNativePath'> & {
platforms: {
[name: string]: {npmPackageName?: string};
};
};
```
I tried to add a test for …
> feat: default to enableOptionalDependencies: true in metro config

- docs/autolinking.md
Summary:
---------
Adds a note explaining a caveat with auto-linking in a monorepo.  Ran into this problem today trying to get a monorepo working.
> docs: update monorepo autolinking section with a disclaimer

- docs/commands.md
Summary:
---------
I found the doctor command at an issue in react-native repository (https://github.com/facebook/react-native/issues/28712). So I looking for here, at the cli documentation and I not found, I don't no the reason.
I believe this addition may help a lot of people
> Add doctor command at commands list

- packages/cli-server-api/tsconfig.json
Summary:
---------
I was having issues with the ts build after a fresh clone because it couldn't find the debugger-ui package. I noticed the cli-server-api package didn't have any project refs defined. Adding those and doing a clean build makes it work again.
Test Plan:
----------
Run clean + build
> Add missing project refs

- packages/cli/src/tools/config/schema.ts
Summary:
---------
Minor error in the health check schema prevents plugins from being able to specify that a health check is not required.
I found this while adding a bunch of health checks to `react-native-windows`: https://github.com/microsoft/react-native-windows/pull/7090.
Test Plan:
----------
Verified that with this change I can use the isRequired property from within `react-native-windows` and it'll show a failed check using the yellow circle instead of a red x.
> Minor fix for health check schema

- packages/cli/src/commands/init/__fixtures__/editTemplate/package.json
- packages/cli/src/commands/init/__tests__/__snapshots__/editTemplate.test.ts.snap
- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
Summary:
---------
Fixes: https://github.com/react-native-community/cli/issues/814
That PR introduces the fix and make the project name _lowercased_ in `package.json` within freshly initialised project. 
Introduced part is covered by test case.
Test Plan:
----------
Locally run `init` command and expect that name in package.json within new project is lowercased.
> Make project name lowercased in package.json

- packages/cli-hermes/package.json
- packages/cli-server-api/package.json
- packages/cli-types/package.json
- packages/cli/package.json
- packages/debugger-ui/package.json
- packages/global-cli/package.json
- packages/platform-android/package.json
- packages/platform-ios/package.json
- packages/tools/package.json
Summary:
---------
Fixes: https://github.com/react-native-community/cli/issues/1380
Test Plan:
----------
No testing needed, as only homepage and repository fields were added in package.json to make GitHub repo discoverable on npmjs website.
Docs:
* homepage https://docs.npmjs.com/cli/v7/configuring-npm/package-json#homepage
* repository https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
> chore: add homepage and repository fields to package.json

- README.md
Summary:
---------
Apart from updating 5.x, I also removed `next` - it looks like it's not up to date right now and definitely not tracking the upcoming 6.x.
> chore: update versions in readme

- packages/cli-server-api/src/index.html
Summary:
---------
Added `Go to Debugger-UI` link so it's easier to find.
Test Plan:
----------
1. Run your project.
2. Visit `localhost:8081` (or the port you've configured).
> feat: add 'go to debugger-ui' link for packager index

- packages/platform-ios/src/commands/runIOS/index.ts
Fixes #1404
Summary:
---------
Fix for 'No iOS devices connected.' error when using 'run-ios --device' on XCode 12.5 with backwards compatibility. Checks output using stderr and uses stdout when blank text is returned.
Test Plan:
----------
> Fix for 'No iOS devices connected.' 

- packages/cli-hermes/src/profileHermes/downloadProfile.ts
Summary:
---------
The command `profile-hermes` does not work on Windows, but replacing `egrep` with `grep -E` would at least 
allow it to work in git bash on Windows
Fixes #1431 
https://www.computerhope.com/unix/uegrep.htm
> Running egrep is equivalent to running grep with the -E option.
Test Plan:
----------
I've tested this by manually running the `profile-hermes` on git bash.
- Before the change I would get an error  - "'egrep' is not recognized as an internal or external command"
- After the change the script finishes successfully and produces a `-converted.json` file
> fix(cli-hermes): profile-hermes doesn't work on Win

- packages/platform-android/native_modules.gradle
Summary:
---------
An illegal argument exception is thrown when attempting to build RN Android apps using Gradle 7.0-rc-1 due to a type mismatch. This is down to a typo in `native_modules.gradle` which mistakenly makes `packages` an array of `ArrayList`.
Gradle 7 updated Groovy from 2 to 3 which is presumably why the behaviour doesn't occur when using Gradle 6.X.
I've tested the change locally and this changeset resolves the issue for me.
Test Plan:
----------
- Generate a fresh react-native app
- Update the gradle wrapper to 7.0-rc-1
- Build the app with `./gradlew assemble`, observe that an exception occurs
> Prevent type mismatch exception thrown in Gradle 7

- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/initCompat.ts
- packages/cli/src/commands/upgrade/upgrade.ts
- packages/cli/src/tools/installPods.ts
Summary:
---------
When initialising a new project, if you set a `--directory` and then got an error during `pod install`, it would show the wrong command to fix it.
```sh
$ react-native init TestProject --directory test-project
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./TestProject/ios && pod install".
```
after my change:
```sh
$ react-native init TestProject --directory test-project
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./test-project/ios && pod install"
```
Test Plan:
----------
- Break `pod install` somehow (I just unset ruby in my ruby version manager - you could probably add `pod() { exit …
> have pod install error message show correct directory

- packages/platform-ios/package.json
Summary:
---------
Previous version of `@react-native-community/cli-platform-ios` requires `xmldom@0.1.x` through `plist@3.0.1`, which has a CVE security alert: https://github.com/advisories/GHSA-h6q6-9hqw-rwfv
`plist` fixed its dependency in `3.0.2`, and upgrading `plist` version here can resolve the CVE security alert.
Fixes #1383.
Test Plan:
----------
Test whether a sample iOS app can build and run.
> fix: bump dependency plist to 3.0.2 in order to resolve a CVE security alert

- packages/cli-hermes/src/profileHermes/downloadProfile.ts
Summary:
---------
It appears that on most android devices, including emulators, `/sdcard` is not writeable, resulting in the issue described in #1379 
This change avoids copying, and instead just `cat`s the file to STDOUT which is then piped to a file. Since the profile text is text/json, this shouldn't be an issue.
Fixes #1379
Test Plan:
----------
1. Open a RN app that uses Hermes on Android
2. In the development menu, enable profiling
3. Disable profiling after some time
4. Run `react-native profile-hermes .`
Output should be:
```
➜ yarn react-native profile-hermes .       
info Downloading a Hermes Sampling Profiler from your Android device...
info No filename is provided, pulling latest file
info File to be pulled: sampling-profiler-trace8710561212640121744.cpuprofile
success …
```
> fix(cli-hermes): avoid copying profile to /sdcard

- packages/cli/src/commands/doctor/healthchecks/__tests__/jdk.test.ts
- packages/cli/src/commands/doctor/versionRanges.ts
Summary:
---------
`envinfo` uses `javac -version` to work out the JDK version number. The doctor command was looking for a semver range of `>= 8` but this won't work for JDK 8 as it uses the old style numbering scheme (e.g. `1.8.x` not `8.x.x`). JDKs 9+ use the new version numbering scheme.
Fixes #1255
Test Plan:
----------
On macOS, before applying this PR's changes:
* `brew install openjdk@8`
* `export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)`
* Confirm `javac -version` outputs something like `javac 1.8.0_282`
* `react-native doctor`
Observe doctor complains about the JDK version:
```
Android
✖ JDK
- Version found: 1.8.0_282
- Version supported: >= 8
```
Apply changes and run `react-native doctor` again, observe 8 is now correctly detected as supported:
```
Android
✓ JDK
```
Repeat …
> fix: JDK version check wouldn't detect JDK 8 correctly

- docs/commands.md
- packages/cli/src/commands/start/runServer.ts
- packages/cli/src/commands/start/start.ts
Summary:
---------
While investigating https://github.com/react-native-community/cli/issues/1391 I discovered that the start command had a `--verbose` option that didn't do anything. You _do_ get extra logging with `--verbose` but this comes from the parent react-native command, where it is already documented.
I had a look through the metro functions being called to see if `verbose` was meant to be passed to one of them and had been missed but couldn't find anywhere it would be relevant. The only one I could see that it would potentially apply to is the `loadMetroConfig` call. While `loadMetroConfig` doesn't document a verbose parameter of its own, it calls `loadConfig` in the `metro-config` package which *does* take a verbose parameter. However, all that does is kill the reporter if …
> fix: remove unused --verbose option from start command

- docs/commands.md
- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
The run-ios command already detects and uses xcpretty (https://github.com/xcpretty/xcpretty) if it's available.
This commit adds support for another xcodebuild output formatter, xcbeautify (https://github.com/thii/xcbeautify).
The logic for what is used is as follows:
1. If xcbeautify is available use it
2. If xcbeautify isn't available but xcpretty is use xcpretty
3. If neither are available fallback to raw xcodebuild output
Test Plan:
----------
Tested manually with the following scenarios;
* only xcbeautify installed (xcbeautify used)
* only xcpretty installed (xcpretty used)
* both installed (xcbeautify used)
* neither installed (xcodebuild used raw)
> feat: use xcbeautify for xcodebuild output if installed

- packages/platform-android/src/commands/runAndroid/adb.ts
- packages/platform-android/src/commands/runAndroid/index.ts
- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Building from source in debug takes a very long time because native builds need to run for all supported architectures. It is possible to check which architecture the devices for which we are about to launch the app on are and build only for those. For most cases we can reduce the number of architectures we build for to 1 instead of 4, resulting in a large speedup of the build.
This is inspired by iOS which has a "Build for active architecture only" option. Since android doesn't really support this natively we can implement it here and also in react-native by reading the build properties that we pass and alter the abi we build for.
With fabric / codegen coming up I suspect that we might want to default to building c++ soon. This should ease the transition as builds …
> feat: add option to build only active architectures on android

- docs/dependencies.md
- docs/platforms.md
- docs/projects.md
- packages/cli-types/src/android.ts
- packages/cli/src/tools/config/schema.ts
- packages/platform-android/native_modules.gradle
- packages/platform-android/src/config/index.ts
- packages/platform-ios/src/commands/runIOS/index.ts
This PR continues idea from this previous [PR](https://github.com/react-native-community/cli/pull/1177)
It allows user to define `customDependencyConfiguration` per project(`project.android`) and also per module itself inside `dependencies[packageName].android` key
```js
project: {
android: {
customDependencyConfiguration:
'embed project(path: ":$dependencyName", configuration: "default")',
},
},
dependencies: {
'react-native-brownfield': {
platforms: {
android: {
customDependencyConfiguration:
'embed project(path: ":react-native-brownfield-bridge", configuration: "default")',
},
},
},
},
};
```
Test Plan:
Init new project and checked whether applied config is correct.
> feat: Added custom scope method for android dependencies

- .circleci/config.yml
- azure-pipelines.yml
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidNDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/androidStudio.test.ts
- packages/cli/src/commands/doctor/healthchecks/__tests__/jdk.test.ts
- packages/cli/src/commands/start/watchMode.ts
- packages/cli/src/tools/config/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/src/tools/config/__tests__/index-test.ts
Summary:
---------
Whenever you are reviewing logs for any app, adding a few blank lines in the console is an often used practice that stopped working with react-native in the recent releases. This was requested at https://github.com/facebook/metro/issues/663 a few months back and I recently faced this as I moved to Windows from Mac and clearing the console isn't a supported action yet (https://github.com/microsoft/terminal/issues/1882).
Test Plan:
----------
- Verified that existing handled actions (r, d, ctrl+c and ctrl+d) still work.
- All other keypresses are logged as it is to the screen.
> Print unsupported keypresses directly to console.

- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
The run-ios command detects and uses xcpretty (https://github.com/xcpretty/xcpretty) if it's available. If it's not available it displays a loader/spinner animation until xcodebuild finishes.
If a build failure happens then the buildOutput and errorOutput are included in the raised CLIError and printed out to the terminal.
This makes sense when xcpretty isn't present as there has been no build output displayed up to now. However, if xcpretty is being used, this behaviour makes less sense:
Firstly, xcpretty has been doing coloured output, nicely highlighting warnings and errors as they happened. The raised CLIError will repeat the output but without colours which means you have to scroll back up past a potential mountain of monochrome xcodebuild output to find the …
> feat: less noisy run-ios build failures with xcpretty
