react-native-community/cli

- packages/cli/src/index.ts
Summary:
---------
Exports `loadConfig` so it can be used by other libraries. Specifically, I'm working on adding the ability to target specific platforms in Jest. Being able to detect which platforms are available (especially out-of-tree ones) would be most useful.
Test Plan:
----------
There are no code changes to test.
> fix: export `loadConfig` so it can be used for other purposes

- packages/cli/package.json
There is an issue with peer deps when using NPM and 0.66.
Using '*' should be fine since the CLI is installed as a dependency of react-native, so as long as react-native install the correct version they should be fine with each other
> Fix React Native peer dep

- docs/autolinking.md
- packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
this PR update iOS simulators according Xcode 13 release i think it's a good idea update for iPhone 13, 12, 11 simulators
> chore: update iOS simulators 

- packages/cli/src/commands/upgrade/__tests__/__snapshots__/upgrade-tv.test.ts.snap
- packages/cli/src/commands/upgrade/__tests__/upgrade-testing-methods.ts
- packages/cli/src/commands/upgrade/__tests__/upgrade-tv.test.ts
- packages/cli/src/commands/upgrade/upgrade.ts
Summary:
---------
The upgrade command does not currently work for Apple TV and Android TV projects, because they use `react-native-tvos`, a fork of the main repo. (Issue #1476) (https://github.com/react-native-tvos/react-native-tvos/issues/224)
Solution:
- Provide a version of https://github.com/react-native-community/rn-diff-purge that has the diffs for the TV repo
- Make `upgrade.ts` generic by detecting whether the project is using a forked repo, and having an easily extendable list of forks that are known to work.  This list includes the main repo as well.
```ts
type ForkNameType = 'react-native' | 'react-native-tvos';
const forks = {
'react-native': {
rawDiffUrl:
'https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs',
webDiffUrl: …
```
> feat: Allow the upgrade command to use TV repo

- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Use async `fs-extra` function for rename, which hooks into a `graceful-fs` implementation that can handle AV locked files on Windows. See https://github.com/isaacs/node-graceful-fs/blob/89dc1330dcd8fa218c5dff92a97d8792b7da6b12/polyfills.js#L96-L118 for details.
Test Plan:
----------
Existing test coverage.
> Better Handle EPERM on Windows

- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
The `reactNativeDebugArchitectures` property was renamed to `reactNativeArchitectures` in https://github.com/facebook/react-native/commit/43c38cdc8e31910e0109f85d258fba22ec9469a0. This passes both flags to be compatible with both versions.
Test Plan:
----------
Test the change locally in an app.
> Support renamed PreactNativeArchitectures

- package.json
- yarn.lock
Summary:
---------
Bump Lerna to 4.x, which dropped support for Node 6 and 8, then supports only 10+.
Test Plan:
----------
CI is same as before
> bump lerna to 4

- packages/platform-android/native_modules.gradle
Resolved NullPointer issue described in #1489
On lib version 6.2.0 with the environment described below, we had NullPointer during the project build.
**Environment:**
Android Studio: Artic Fox 2020| 3.1.0 Patch 3
ANDROID GRADLE PLUGIN: 7.0+
minSdk : 21
targetSdk : 30,
compileSdk : 30
You can test & verify changes on the simple project.
> Fixed NullPointer in native_modules.gradle

- packages/cli/src/commands/doctor/healthchecks/androidStudio.ts
Fixes #1513 
Summary:
---------
wmic is deprecated (removed) in newer version of Windows. Use powershell to find out the version of android studio
Test Plan:
----------
> fix: doctor breaks in newer versions of Windows

- packages/platform-android/src/config/__fixtures__/android.ts
- packages/platform-android/src/config/findPackageClassName.ts
Summary:
---------
This PR extends the `findPackageClassName` capability to address also TurboModules, which are implemented as subclasses of `TurboReactPackage` (see https://github.com/facebook/react-native/blob/2162bce44bbf40513bcf90b793810d05a67d2b7e/packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterApplication.java#L73-L111).
I didn't want to over-complicate the already existing Regex therefore I've created a separate one.
Test Plan:
----------
Tests are attached.
> Extend findPackageClassName to address TurboModules

- packages/cli/src/commands/doctor/healthchecks/androidStudio.ts
Reverts react-native-community/cli#1515
@asklar is out for the year, so we will not see an immediate fix. Reverting for now.
The hardcoded Powershell path causes failures on several current versions of Windows. This ends up also breaking the PR pipeline for `react-native-windows` regardless of whether we update, since we run `react-native doctor` on newly created user apps which hit the issue.
> Revert "fix: doctor breaks in newer versions of Windows"

- packages/cli-server-api/src/websocket/eventsSocketServer.ts
Summary:
---------
Fixes per work around: https://github.com/facebook/flipper/issues/3189#issuecomment-997191720. The same fix has been applied to FB infra, and the next release will temporarily set an `origin` header as work around for existing RN versions. 
Fixes:
* https://github.com/facebook/flipper/issues/2870
* https://github.com/facebook/flipper/issues/3189
The essence of the fix is that we shouldn't check the `origin` header if it is not present. That might sound unsafe, but it actually is just a check to protect from malicious websites, and browsers ensure the origin header is set for cross site requests. For websocket connections created outside a browser context, the creator has full control over the origin header anyway, so checking it would not add any safety.
Test Plan: …
> Fix metro crash when Flipper connects

- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
Summary:
---------
While working with RN 0.67, I've just noticed that we have two `_` prefixed files in a newly generate project from the template with the `yarn react-native init ...` command.
That's how a `ls -la` on a new template looks like:
```
-rw-r--r--    1 ncor  staff     114 Jan 20 12:20 .buckconfig
-rw-r--r--    1 ncor  staff      74 Jan 20 12:20 .eslintrc.js
-rw-r--r--    1 ncor  staff    1410 Jan 20 12:20 .flowconfig
-rw-r--r--    1 ncor  staff     821 Jan 20 12:20 .gitignore
-rw-r--r--    1 ncor  staff     144 Jan 20 12:20 .prettierrc.js
-rw-r--r--    1 ncor  staff       2 Jan 20 12:20 .watchmanconfig
-rw-r--r--    1 ncor  staff    2465 Jan 20 12:20 App.js
-rw-r--r--    1 ncor  staff     168 Jan 20 12:20 Gemfile
-rw-r--r--    1 ncor  staff    2413 Jan 20 12:20 Gemfile.lock …
```
> Add bundle and ruby-version to the underscored files

- packages/tools/package.json
- yarn.lock
Summary:
---------
Updating shell-quote to latest version for fixing security issue [CVE-2021-42740 ](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42740)
Test Plan:
----------
> Update shell-quote to fix security issue CVE-2021-42740

- packages/platform-android/native_modules.gradle
Summary:
---------
Android native_modules.gradle does not correctly get the app configuration. The cliResolveScript does not match the iOS version, and it only resolves to react-native/cli instead of @react-native-community/cli if avaiable
Test Plan:
----------
Green CI.
> Android native_modules.gradle cliResolveScript should resolve to @react-native-community/cli

- packages/platform-android/src/commands/runAndroid/adb.ts
Summary:
---------
Test Plan:
----------
1. Use Windows.
2. Use a "adb path" in folder with a space.
3. Check if the environment PATH, have the adb path correctly.
4. Execute the app, in my case I use `npx react-native run-android`
After fixed it, looks like
> fix: Windows unknown command on build android

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
This is a PR to simply bump the Metro dependencies to match the new version of Metro that has been released [0.67](https://github.com/facebook/metro/releases/tag/v0.67.0).
Most likely, this will mean that a new major of the package needs to be released too? I'm not sure how this bump will fit in the bigger picture work that is happening in the repo (see https://github.com/react-native-community/cli/issues/1527).
Test Plan:
----------
Locally, I did a quick `yarn test` and a few were failing - but wanted to double check against CI to verify if it's simply something going wrong locally.
> update: bump version of Metro packages to 67

- packages/cli-doctor/package.json
To be consistent with the bump in all other existing packages from
1ac43cce3df75bff069558ac13e8314a17d892e4, and not need consumers to pull
down two versions when installing the cli.
Chalk 5 is ESM only, so that will have to wait until we're ready to use
ESM packages.
> Bump chalk to 4.x in cli-doctor

- packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts
Summary:
---------
the jdk doctor fix command is using "[downloadAndUnzip](https://github.com/react-native-community/cli/blob/d2ac438528c282f69b71a7a39b1689f6bb276670/packages/cli-doctor/src/tools/healthchecks/jdk.ts#L35)", but the test
was mocking / spying on "unzip", this fixes the test to mock/spy on
the method actually used, patterned after the android studio test
This is the failure I see:
```
FAIL  packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts (34.812 s)
● jdk › downloads and unzips JDK on Windows when missing
thrown: "Exceeded timeout of 20000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
72 |   });
73 |
> 74 |   it('downloads and unzips JDK on Windows when missing', async () => {
|   ^
75 | …
```
> test(doctor, jdk): fix windows jdk doctor install test

- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
react-native apparently still works with v12, the only changelog
note I found was that v12 is the current minimum:
https://github.com/facebook/react-native/blob/main/CHANGELOG.md#breaking-1
I do not believe this is a breaking change here because react-native already required it
Test Plan:
----------
CI should be testing this?
Also when I make this change locally via manual patch (and then patch-package) in node_modules it works for me (I have v16 installed currently...)
> build(deps): bump minimum node to v12

- packages/cli-doctor/src/tools/checkInstallation.ts
- packages/cli-doctor/src/tools/healthchecks/__tests__/watchman.test.ts
- packages/cli-doctor/src/tools/healthchecks/watchman.ts
- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
fix(doctor, watchman): accept new date-based watchman versions
doctor was giving false-negatives with the new watchman versions
they use date-based versions now that violate semver with leading-zeros in numeric parts:
- https://github.com/npm/node-semver/issues/232
loose mode correctly pasrses them though, so add optional parameter to install check that
allows loose version range coercion
Should be compatible as watchman project is on record as being permanently backwards-compatible:
https://facebook.github.io/watchman/docs/compatibility.html
Test Plan:
----------
I wrote a test that covers watchman completely before modifying it, then modified it and added a chunk of test to check the modification - so, best reviewed one commit at a time
> fix(doctor, watchman): accept new date-based watchman versions

- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
Apple defines the minimum version of Xcode that is truly usable.
They will enforce iOS15 SDK (thus transitively requiring Xcode 13) in April 2022:
'Starting April 2022, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 13 and the iOS 15 SDK.'
Until then, Xcode 12 is still a viable compiler.
Test Plan:
----------
I have side-by-side installations of Xcode.app installed in one of my test environments.
I switched to Xcode-12.4, the oldest one I still have, and then did `npx react-native init TestApp124 --version=0.68.0-rc.1` and ran it, it seemed to run fine. So Xcode 12 still seems to compile fine.
Note the converse is not true in reverse, not sure how to enforce it, but if you use react-native 0.63 with Xcode 12.5+ it will not work, but you …
> build(deps): align Xcode with current App Store submission requirements

- packages/platform-ios/src/config/__tests__/getProjectConfig.test.ts
Summary:
---------
As per TODO in https://github.com/react-native-community/cli/pull/1537, adding missing tests.
Test Plan:
----------
CI is green.
> chore: add tests for `getProjectConfig` on iOS

- packages/platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
- packages/platform-android/src/commands/runAndroid/index.ts
- packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts
- yarn.lock
Summary:
---------
`root` was never used, `appFolder` was marked deprecated. It's a good timing to get rid of that.
This is a follow-up to https://github.com/react-native-community/cli/pull/1537
> breaking(run-android): remove deprecated run-android properties

- docs/init.md
- packages/cli/src/commands/init/init.ts
Summary:
---------
Related to #1492.
The idea is to remove the `ora` loader from the core of the cli to give this responsibility to the implementor. 
That way, template creator can be more creative like prompting questions to user for better experience. 
Before this, it was difficult because `ora` keeps refreshing the last line of terminal and so the prompted question.
Test Plan:
----------
I don't find any resources on how to test the init command locally. I tried to install globally the forked cli but it fails. 
Btw, I just remove the `ora` loader only for the post init script and do not add code to the base code so it's really simple and seems to work without extra testing.
But, if you tell me how to do that I'll be happy to test it !
> Postinit script loader

- docs/commands.md
> docs: add --active-arch-only to run-android

- packages/platform-android/src/link/isInstalled.ts
Summary:
---------
According to https://github.com/react-native-community/cli/discussions/1567#discussioncomment-2446121, older CLI versions do not handle build.gradle.kts as valid Gradle scripts, during autolinking.
This PR adds an additional check for default path to build.gradle.kts and throws an error, if there is no file at path.
Test Plan:
----------
- Create project with cli v7 and build.gradle rewritten from Groovy DSL to Kotlin DSL (you can use https://github.com/mateusz1913/RNKotlinPOC, but you have to set cli v7)
- Add library which requires autolinking on Android
- Run Android app
> fix: "no such file or directory" error when using Gradle Kotlin DSL

- package.json
- packages/cli-clean/package.json
- packages/cli-clean/src/__tests__/clean.test.ts
- packages/cli-clean/src/clean.ts
- packages/cli-clean/src/index.ts
- packages/cli-clean/tsconfig.json
- packages/cli-doctor/src/commands/doctor.ts
- packages/cli-doctor/src/tools/windows/androidWinHelpers.ts
- packages/cli/package.json
- packages/cli/src/commands/index.ts
- packages/cli/tsconfig.json
- packages/platform-ios/src/commands/runIOS/index.ts
- yarn.lock
Summary:
---------
This adds a `clean` command to the CLI for common cleaning operations.
Originally contributed by @dennismunene: https://github.com/microsoft/rnx-kit/pull/993
Test Plan:
----------
```
yarn link @react-native-community/cli @react-native-community/cli-clean
```
Test `--help`:
```
% npx react-native clean --help
react-native clean
Cleans your project by removing React Native related caches and modules.
Options:
--include <string>       Comma-separated flag of caches to clear e.g. `npm,yarn`. If omitted, an interactive prompt will appear.
--project-root <string>  Root path to your React Native project. When not specified, defaults to current working directory. (default: "/~/test-app")
--verify-cache           Whether to verify the cache. Currently only applies to npm cache. …
```
> feat: add "clean" command

- docs/commands.md
Summary:
---------
Added docs for the new `clean` command.
Test Plan:
----------
n/a
> docs: added docs for `clean`

- packages/cli-doctor/package.json
- packages/cli-doctor/src/tools/healthchecks/index.ts
- packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
- packages/cli-doctor/tsconfig.json
- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
- packages/platform-ios/src/config/findAllPodfilePaths.ts
- packages/platform-ios/src/config/findPodfilePath.ts
- packages/platform-ios/src/config/index.ts
- packages/platform-ios/src/index.ts
Summary:
---------
This PR adds the support for `.xcode.env` file in the `init` and `doctor` commands.
This PR depends on this other one: https://github.com/facebook/react-native/pull/33546
Test Plan:
----------
This PR is quite similar to 1530. I would rely on the same tests.
If anyone has suggestions about how to test this, I will be more than happy to implement them.
> [Feat] Add support for .xcode.env file in init and doctor commands

- .github/workflows/release.yml
Summary:
---------
Added release workflow to github actions. Releases marked as `pre-release` will add `--conventional-prerelease` flag with `alpha` as `preid`.
**In order to this workflow work properly** new `Automation` npm token named `NPM_TOKEN` must be added to project secrets.
As requested, lerna changelog generation is disabled for now.
> chore: Automated CLI releases

- .github/workflows/release.yml
Summary:
---------
Disabled persist credentials on checkout action that should eliminate lerna `protected branch hook declined` error.
Unfortunately the only way to confirm that is by merging changes to master first.
> chore(release): Disable persist credentials on checkout action

- packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
- packages/cli-plugin-metro/src/commands/bundle/bundleCommandLineArgs.ts
Summary:
---------
`@react-native/babel-plugin-codegen` is a Babel plugin that generates static view configs for Fabric components during bundling stage. Right now we have to add this plugin manually if we want to use Fabric: https://reactnative.dev/docs/next/new-architecture-app-renderer-ios#3-add-babel-plugins
In order to get rid of this manual step, we would like to ship this plugin as a part of Metro.
`--generate-static-view-configs` argument allows to turn it on or off. The idea is to have ON for Fabric projects and OFF for non-Fabric. Fabric users can also opt out, in case they don't need this feature for some reason.
Test Plan:
----------
Tested it locally by passing this argument to cli in _react-native/scripts/react-native-xcode.sh_
> Add generate-static-view-configs command line argument for bundle command

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
As raised [here](https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2673975), the metro version is out-of-sync with `react-native`. In this PR, I am bumping that to `^0.70.1`.
I have noticed that the resolved version is in the end `0.70.2` - `react-native` has versions as strict, should we have that, too? If so, I can update the PR. Otherwise, we should be good as it is.
Test Plan:
----------
CI passing should be enough of a validation here.
> update: bump version of Metro packages to 0.70.1

- packages/cli-plugin-metro/src/tools/metroPlatformResolver.ts
Summary:
---------
Metro changed how to hook into the resolver with this commit:
https://github.com/facebook/metro/commit/d81d8877c05637eac2b4ea946a9fa1e8ae869b06
The reactNativePlatformResolver is still using the old format, which causes bundle commands to fail if the project has any out of tree platforms (Ex: react-native-windows-macOS)
Test Plan:
----------
The following bundle command fails currently.  But works after making this change locally.
npx --yes react-native@0.0.0-20220415-2010-3c1a81446 init testcli --template react-native@0.0.0-20220415-2010-3c1a81446
cd testcli
npx --yes react-native-windows-init@latest --verbose --version 0.0.0-canary.495 --overwrite --language cs --projectType app --namespace MyCompany.MyApplication.MyComponent
npx react-native bundle --entry-file …
> Update reactNativePlatformResolver for new metro

- docs/autolinking.md
Summary:
---------
Show readers how to uninstall a package that supports autolinking since that's something they should know.
Closes #1606 
Test Plan:
----------
N/A
> (docs) mention the process of uninstalling a package

- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/schema.ts
align the joi schema for scriptPhases with the actually allowed values
Summary:
---------
react-native-firebase (and react-native-google-mobile-ads) use script phrases that are more than just strings, because we need to depend on the Info.plist file being generated from compilation to run the script
This worked in react-native <= 0.68 but is failing in 0.69.0-rc series
It appears that the validation has changed in the area from t.object to t.string, when it is t.object - our modules react-native-config.js files successfully validate and the modules are auto-linked, when it is t.string they are ignored.
However, if I alter it to t.object in schema.ts, then strings fail, so that's not right.
I attempted to do a joi alternatives with a full definition but I simply could **not** get the tests …
> fix(ios): allow detailed scriptPhases object in config

- packages/platform-android/src/config/findComponentDescriptors.ts
Summary:
---------
`findComponentDescriptors` may pick up directories, e.g. [decimal.js](https://www.npmjs.com/package/decimal.js),  and throw when trying to read it.
Test Plan:
----------
Add `decimal.js` as a dependency and run `react-native config`
> fix(platform-android): `findComponentDescriptors` picks up directories

- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/schema.ts
- packages/platform-android/src/config/index.ts
- packages/platform-ios/src/config/index.ts
Summary:
---------
Resolves #1612.
Test Plan:
----------
1. Clone and check out the branch with a repro:
```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
git checkout tido/enable-turbomodule
```
2. Apply below diff to make `@react-native-community/cli` think that `react-native-test-app` has native modules to link:
```diff
diff --git a/android/app/src/turbomodule/java/com/microsoft/reacttestapp/turbomodule/TurboModuleManagerDelegate.kt b/android/app/src/turbomodule/java/com/microsoft/reacttestapp/turbomodule/TurboModuleManagerDelegate.kt
index 2b02ad7..5ef4977 100644
--- a/android/app/src/turbomodule/java/com/microsoft/reacttestapp/turbomodule/TurboModuleManagerDelegate.kt
+++ b/android/app/src/turbomodule/java/com/microsoft/reacttestapp/turbomod …
```
> fix: allow `dependency.platforms.[platform]` to be `null` again

- packages/tools/package.json
- packages/tools/src/isValidUrl.ts
- packages/tools/src/launchDefaultBrowser.ts
- packages/tools/src/throwIfNonHttpProtocol.ts
I've been curious about how rn cli handle app in debug mode interactions with IDE, 
I know that when you get some error in your app (e.g crash) when you are coding, you get an error message saying what line broke.. And that got me thinking.. how can the app open my IDE? and I came across this endpoint from cli package `cli-server-api`:
```
POST /open-url
```
To put this in perspective, if you have the cli-server-api running and someone inside your network wants your pc to open any uri scheme, they can though this endpoint. Especial thanks to @R3tr074 for investigating it further (poc)
```bash
curl --request POST \
--url http://localhost:8081/open-url \
--header 'Content-Type: application/json' \
--data '{"url": "file:///etc/hosts"}'
```
Other uri schemes:
I've tested on linux and macOs, …
> refactor: url validation (http/https) before opening

- .github/workflows/test.yml
- packages/cli-doctor/src/tools/healthchecks/__tests__/androidSDK.test.ts
- packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
- packages/cli-doctor/src/tools/healthchecks/jdk.ts
- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
The template now inits a compileSdk/targetSdk 31 project,
JDK8 cannot compile reliably against SDK31, so bump JDK as well
~~I will mark this as draft, it should get a few more commits:~~
Test Plan:
----------
seems to work for me locally?
Each commit is separate and useful, they should be removed commit by commit to make it all crystal clear
:skull_and_crossbones: : :warning: the `!` in the commit message is a good idea or not, to drive a breaking change semver? :warning: :skull_and_crossbones: :
> build(deps)!: JDK11 and SDK 31+ are required

- .github/workflows/test.yml
- packages/cli-clean/src/clean.ts
Summary:
---------
I just saw that the CLI has a new clean command. That's fantastic!
Historically I steer people to https://github.com/pmadruga/react-native-clean-project but really it's basic functionality, glad to see it in the CLI.
I had a problem that I PRd to react-native-clean-project regarding cocoapods spec cache poisoning, and install / unpack failures, and they were solved by also cleaning `~/.cocoapods` and cleaning `ios/Pods` so I am PR'ing that here
I understand paths might be an issue but since we are inside an `os === darwin` conditional, the `~/` should be okay. I'm not sure about the `ios/` though and will happily take guidance
Test Plan:
----------
In practice for a long time, here: 
https://github.com/pmadruga/react-native-clean-project/blob/65c012ed0dcf4ea6786af867e8a7 …
> fix(clean, cocoapods): clean spec cache + installed Pods

- packages/tools/src/releaseChecker/printNewRelease.ts
Summary:
---------
When a new version available, the link to the Changelog is broken. But the reason is simple: the period at the end of the sentence is getting in the way.
Removing that dot ('.') works great!
fixes: #1632 
Test Plan:
----------
Being with react-native in an earlier version 0.69.0 the cli will display information that there is a new version. We will be able to click on the link to view the Changelog, without breaking! o/
Evidence:
----------
> fix: broken link to changelog

- packages/platform-android/src/config/__fixtures__/android.ts
- packages/platform-android/src/config/__fixtures__/files/build.gradle
- packages/platform-android/src/config/__tests__/findLibraryName.test.ts
- packages/platform-android/src/config/findLibraryName.ts
- packages/platform-android/src/config/index.ts
Summary:
---------
Here I'm extending the `findLibraryName` function to do the following:
1. Account for `codegenConfig.name` in the package.json in the root (if available)
2. Handle both single and double quotes in build.gradle files
3. Handle libraries using build.gradle.kts files.
This implements the remaining points listed here https://github.com/facebook/react-native/pull/33777#issuecomment-1165104204
Test Plan:
----------
I've wrote a small test suite for `findLibraryName` as it was empty.
> [android] Refine and test the findLibraryName function

- packages/platform-android/native_modules.gradle
Summary:
---------
Given a `react-native config` that has the following setup:
```
{
"dependencies": {
"react-native-awesome-module": {
"root": "/Users/ncor/git/react-native/template/node_modules/react-native-awesome-module",
"name": "react-native-awesome-module",
"platforms": {
"android": {
"sourceDir": "/Users/ncor/git/react-native/template/node_modules/react-native-awesome-module/android",
"packageImportPath": "import com.reactnativeawesomemodule.AwesomeModulePackage;",
"packageInstance": "new AwesomeModulePackage()",
"buildTypes": [],
"componentDescriptors": [],
"androidMkPath": "/Users/ncor/git/react-native/template/node_modules/react-native-awesome-module/android/build/generated/source/codegen/jni/Android.mk"
}
}
}
},
```
(note that `libraryName` is missing), you should not import …
> [android] Do not import a linked Android.mk file if the library is not specifying a libraryName

- packages/tools/package.json
- yarn.lock
Summary:
---------
Attempt to patch critical security issue in cli 7.x mentioned in #1641 due to the shell-quote 1.6.1 dependency
Test Plan:
----------
CI should pass
> chore(deps): bump shell-quote to 1.7.3

- jest/helpers.ts
- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/loadConfig.ts
- packages/cli-config/src/readConfigFromDisk.ts
- yarn.lock
Summary:
---------
When Joi validates the schema, it will abort early and thus prevent us from constructing the rest of the configuration, which might be correct. In such case the CLI would emit a warning that configuration for a certain package was invalid. However what this warning wouldn't tell is that the library failed to autolink completely. 
This PR changes the Joi validation to not abort early and make warnings what they really are, without preventing the schema object to be created. 
This caused issues like this one: https://github.com/reactwg/react-native-releases/discussions/23 
Test Plan:
----------
Adjusted the wording of the warning:
> fix: schema validation errors disguised as warnings

- packages/cli-tools/package.json
- packages/cli-tools/src/__tests__/resolveNodeModuleDir.test.ts
- packages/cli-tools/src/findPackageDependencyDir.ts
- packages/cli-tools/src/resolveNodeModuleDir.ts
- yarn.lock
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/1168
As described in the issue, it's currently not possible to use RN CLI with packages that have `exports` in their `package.json` and do not contain `package.json` itself in the `exports` object. For example, `d3` dependency [does just that](https://github.com/d3/d3/blob/main/package.json#L32-L35). While maintainers could make their package compatible with the RN CLI, such an effort would be huge and not all maintainers want [to do that](https://github.com/d3/d3/pull/3576) – understandably so, especially if their packages are not exclusively for RN.
To fix this, I've imported [this](https://github.com/microsoft/rnx-kit/blob/f37adca5161eba66fc27de25d48f72973fff9e8e/packages/tools-node/src/package.ts#L213-L234) …
> Fix resolving node modules directory with custom exports

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
Autolinking for New Architecture, on Android, with CMake, with more than 1 library is currently broken. The reason is that the library list is separated by `\` (as it was supposed to be for Android.mk) that are not a valid char for CMake (see https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists for reference).
Test Plan:
----------
I've tested this against https://github.com/react-native-community/RNNewArchitectureApp.
Before:
```cmake
cmake_minimum_required(VERSION 3.13)
set(CMAKE_VERBOSE_MAKEFILE on)
add_subdirectory(/Users/ncor/pg/RNNewArchitectureApp/AwesomeApp/node_modules/calculator/android/build/generated/source/codegen/jni/ calculator_autolinked_build)
add_subdirectory(/Users/ncor/pg/RNNewArchitectureApp/AwesomeApp/node_modules/ce …
```
> [android] Do not separate autolinked libraries with \ on CMake

- packages/cli-platform-android/src/config/__tests__/getAndroidProject.test.ts
- packages/cli-platform-android/src/config/getAndroidProject.ts
Summary:
---------
Currently `validatePackageName` fails for package names containing uppercase letters. A message like this is shown during pod install:
```
warn Invalid application's package name "com.lugg.ReactNativeConfig" in 'AndroidManifest.xml'. Read guidelines for setting the package name here: https://developer.android.com/studio/build/application-id
warn Invalid application's package name "com.BV.LinearGradient" in 'AndroidManifest.xml'. Read guidelines for setting the package name here: https://developer.android.com/studio/build/application-id
warn Invalid application's package name "com.lugg.ReactNativeConfig" in 'AndroidManifest.xml'. Read guidelines for setting the package name here: https://developer.android.com/studio/build/application-id
warn Invalid application's package …
```
> Ignore case in validatePackageName

- docs/autolinking.md
Summary:
---------
Fix links in docs redirecting to 404 in the `docs/autolinking.md`.
> Fix links redirecting to 404 in autolinking guide

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Upgrades Metro dependencies to v0.72.0. The main user-impacting features this release includes are out-of-the-box support for `.cjs` and `.mjs` files and the new React 17 JSX transform, as well as strict CLI validation when `metro` is run directly.
Per the release notes we shared (linked below), I am suggesting that this is a breaking change for RN CLI.
Metro release notes:  https://github.com/facebook/metro/releases/tag/v0.72.0
Changelog between 0.71.3 and 0.72.0: [https://github.com/facebook/metro/compare/v0.71.3..v0.72.0](https://github.com/facebook/metro/compare/v0.71.3%E2%80%A6v0.72.0)
Test Plan:
----------
- Updated dependencies with `yarn`.
- ✅ Ran `yarn test`.
> breaking: Upgrade metro dependencies to 0.72.0

- packages/cli-platform-android/src/config/findComponentDescriptors.ts
Summary:
---------
See https://github.com/reactwg/react-native-releases/discussions/26#discussioncomment-3329589 for more context. We should not traverse other `node_modules when calling `findComponentDescriptors` as we might pick up too many files.
Test Plan:
----------
I've tested this manually against the linked project.
> Do not glob `node_modules` in findComponentDescriptors

- CONTRIBUTING.md
Summary:
---------
Just a minor docs change. Noticed the actual main branch was named `main` now and not `master`.
Test Plan:
----------
I didn't test this at all. 🤷
> Update CONTRIBUTING.md to `main` branch name

- packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
Summary:
---------
Noticed that doctor does not create `.xcode.env` file when it should. 
It was happening because this command was failing silently:
```ts
const templateIosPath = path.dirname(
require.resolve('react-native/template/ios'),
);
```
Test Plan:
----------
Create fresh project and then delete `.xcode.env` file. Then run `doctor` command and try to autofix the error. 
```bash
❯ npx react-native doctor                         
Common
✓ Node.js
✓ yarn
✓ Watchman - Used for watching changes in the filesystem when in development mode
Android
✓ JDK
✓ Android Studio - Required for building and installing your app on Android
✓ Android SDK - Required for building and installing your app on Android
✓ ANDROID_HOME
iOS
✓ Xcode - Required for building and installing your app on iOS
✓ …
```
> fix: properly create .xcode.env file with doctors auto fix

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Upgrades Metro dependencies to 0.72.1. This is a minor release with no anticipated compatibility issues.
Metro release notes:  https://github.com/facebook/metro/releases/tag/v0.72.1
Changelog between 0.72.0 and 0.72.1: [https://github.com/facebook/metro/compare/v0.72.0..v0.72.1](https://github.com/facebook/metro/compare/v0.72.0%E2%80%A6v0.72.1)
Test Plan:
----------
- Updated dependencies with `yarn`.
- ✅ Ran `yarn test`.
> chore: Upgrade metro dependencies to 0.72.1

- packages/cli-platform-android/src/config/__fixtures__/files/package.json
- packages/cli/package.json
Summary:
---------
Peer dep on "react-native" makes npm 7+ automatically install the "latest" version, which is currently 0.69.x, and when someone is installing RN 0.70 RC, it's erroring out. This PR essentially removes the peer dep from one and only package that defines it. Making it an implicit peer dependency.
Test Plan:
----------
None
> fix: remove peerDependencies on react-native

- docs/autolinking.md
- docs/dependencies.md
- docs/platforms.md
- packages/cli-config/src/schema.ts
- packages/cli-platform-android/native_modules.gradle
- packages/cli-platform-android/src/config/index.ts
- packages/cli-types/src/android.ts
Summary:
---------
Power library authors might want to specify a custom CMake path. Currently we've been reusing the `androidMkPath` config key assuming that the CMake file would be in the same folder (which is a sound assumption). However we should be more precise here and allow users to specify a custom `cmakeListsPath` if they want.
Test Plan:
----------
@thymikee not sure how can we test this as the change is touching several files.
> Add support for explicit cmakeListsPath in react-native.config.js

- packages/cli-doctor/src/tools/healthchecks/watchman.ts
- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
Closes #1694 
Watchman is using CalVer for versioning and is appears that in some cases `semver` have difficulties to correctly check if it `satisfies` our minimum version required, even when `looseRange` is on. 
We could do a special CalVer check for watchman but then question arises what is oldest version CLI supports. Oldest release found on GitHub is [v2020.07.13.00](https://github.com/facebook/watchman/releases/tag/v2020.07.13.00) while latest semver release ([4.9.0](https://facebook.github.io/watchman/docs/release-notes.html#watchman-490-2017-08-24)) was done in 2017 so quite some time ago...
So actually it appears that we support **all versions**, it only needs to be installed.
Test Plan:
----------
Clone the repo, checkout to branch with the fix and run doctor …
> fix: no minimum version of Watchman

- docs/autolinking.md
- docs/commands.md
- docs/healthChecks.md
- docs/init.md
- packages/cli-platform-ios/src/commands/runIOS/__tests__/findMatchingSimulator.test.ts
- packages/cli-platform-ios/src/commands/runIOS/findMatchingSimulator.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/types.ts
Summary:
---------
- docs: fix missing code block langs & typos
- feat: add iPhone 14 as a fallback simulator
- feat: add last booted simulator pick, if no other matches the finder
```
** last booted simulator **
Sometimes, it's better to have the last booted simulator as a fallback, instead of the first available simulator.
```
Test Plan:
----------
After a new Xcode install, when the simulators are fresh, and CLI yet doesn't have the latest iPhone listed as a fallback simulator, CLI fails to pick an appropriate simulator. If the user however run already any preferred simulator, it gets picked instead of failing on picking the appropriate simulator.
> feat: added last booted simulator pick & iPhone 14 as fallback + doc typos

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Addresses concerns raised here: https://github.com/facebook/react-native/pull/34803. From now on, it's expected from CLI to have Metro packages pinned to specific versions. And React Native to have RN CLI pinned to a specific version. This means, assuming users don't use "resolutions", we'll need to send PRs to RN whenever we release a minor/patch version to have the end users benefit from it.
Test Plan:
----------
None
> fix: pin Metro to specific version (0.72.3)

- packages/cli-doctor/src/tools/installPods.ts
- packages/cli-doctor/src/tools/runBundleInstall.ts
Summary:
---------
- Using Bundler as a default way to handle dependencies on iOS
Test Plan:
----------
- `yarn test`
- Possible error output, when other ruby version is used:
- Successful run:
> feat(ios): use Bundler for pods installation

- packages/cli-plugin-metro/package.json
Summary:
---------
Updating the versions of Metro in the `cli-plugin-metro` to incorporate the new Metro Release v0.73.0. This release switches the default minifier to `terser`, raises the minimum Node version to ^14.17, and drops support for old Watchman versions. It also improves support for Apple Silicon and will enable the use of BigInt out of the box in React Native 0.71.
Per the release notes we shared (link below), I am suggesting that this is a breaking change for RN CLI.
**Metro Release Notes:** https://github.com/facebook/metro/releases/tag/v0.73.0
**Full Changelog between v0.72.3 and v0.73.0:** https://github.com/facebook/metro/compare/v0.72.3...v0.73.0
Reminder : When React Native updates the CLI to a version that depends on metro 0.73.0, it must also update metro-runtime etc …
> Upgrade Metro dependencies to v0.73.0 in `cli-plugin-metro`

- docs/commands.md
Updates commands doc with the new xcconfig option
> Update ios readme to pass xcconfig from command line

- packages/cli-platform-android/src/config/__tests__/getAndroidProject.test.ts
- packages/cli-platform-android/src/config/findBuildGradle.ts
- packages/cli-platform-android/src/config/getAndroidProject.ts
- packages/cli-platform-android/src/config/index.ts
Summary:
---------
This commit introduces the support for getting the Android package from the `namespace` field inside the build.gradle file.
Starting from the recent version of AGP, users should use namespace to setup the package rather than AndroidManifest.xml
Not doing this, is causing this warning on new apps on console:
```
package="com.androidtemplateproject" found in source AndroidManifest.xml: /tmp/AndroidTemplateProject/android/app/src/main/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using …
```
> Add support for namespace inside build.gradle file.

- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Upgrades Metro dependencies to 0.73.3. This includes the last 3 minor releases with no anticipated compatibility issues.
Metro release notes: https://github.com/facebook/metro/releases/tag/v0.73.3
Changelog between 0.73.0 (latest version in `cli-plugin-metro` https://github.com/react-native-community/cli/pull/1711) and 0.73.1: [https://github.com/facebook/metro/compare/v0.73.0..v0.73.3](https://github.com/facebook/metro/compare/v0.73.0%E2%80%A6v0.73.3)
**Reminder**: When React Native updates the CLI to a version that depends on metro 0.73.3, it must also update `metro-runtime` etc to 0.73.3 in the same commit.
Test Plan:
----------
- Updated dependencies with `yarn`.
- ✅ Ran `yarn test`.
> Upgrade metro dependencies to 0.73.3

- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
Fixes #1706 
Test Plan:
Clone the branch and run `react-native run-ios --buildFolder "build"` command.
It should run the app as usual but put build artifacts into `ios/build` folder.
> Feat: customise ios build folder location with `iosBuildFolder` flag

- docs/commands.md
- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Update commands documentation about `buildFolder` for `run-ios`, mention it corresponds to `-derivedDataPath`.
Test Plan:
----------
Docs
> docs: update commands documentation, mention derivedDataPath

- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
`npx react-native run-ios` starts iPhone 13 simulator by default. This PR tries to fix this by selecting iPhone 14 as default simulator.
Test Plan:
----------
`npx react-native run-ios` should run iPhone 14 as default simulator.
> fix: select iPhone 14 as a default simulator

- packages/cli/src/commands/init/errors/TemplateAndVersionError.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
When we pass both `--version` and `--template` options to `init` command we are using version of react-native taken from template not the one passed with init command. 
This PR will raise and error in such case and show appropriate message:  
```ts
❯ node ./cli/packages/cli/build/bin.js init MyApp --version 0.68.4 --template react-native-template-typescript
error Passing both "version" and "template" is not supported. Templates are in control of "react-native" version. Please choose only one of these, like so:
--template react-native-template-typescript@x.y.z
where x.y.z is the version containing the "react-native" you'd like. Check: https://www.npmjs.com/package/react-native-template-typescript for available versions.
```
Test Plan:
----------
Clone the repo and try to …
> Fix: Prohibit passing both version and template to init command

- packages/cli-config/package.json
Summary:
---------
Adds `chalk` as a dependency. The [source code](https://github.com/react-native-community/cli/blob/main/packages/cli-config/src/readConfigFromDisk.ts#L9) uses [chalk](https://www.npmjs.com/package/chalk) but does not include it as a dependency. 
Test Plan:
----------
N/A
> fix: add chalk to cli-config dependencies

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
This PR removes unwanted spaces in paths in `add_subdirectory` command in autogenerated `Android-rncli.cmake`:
Along with #1734, this should fix building new-arch RN apps for Android on Windows.
Test Plan:
----------
I couldn't find any snapshot tests that would contain `add_subdirectory` so not sure how to prove it works 🤷
> Remove unwanted spaces `add_subdirectory` paths in Android-rncli.cmake

- packages/cli-platform-android/src/config/index.ts
Summary:
---------
The paths in the CMake script generated for autolinking the modules contains backslashes which CMake don't like. This patch fixes the file paths to replace the backslashes with forward slases.
Test Plan:
----------
Tested autolinking modules locally on windows.
> fix: Make paths in the CmakeLists scripts Windows friendly

- __e2e__/init.test.ts
- jest/helpers.ts
- packages/cli/src/commands/init/errors/DirectoryAlreadyExistsError.ts
- packages/cli/src/commands/init/errors/HelloWorldError.ts
- packages/cli/src/commands/init/errors/InvalidNameError.ts
- packages/cli/src/commands/init/errors/ReservedNameError.ts
- packages/cli/src/commands/init/errors/TemplateAndVersionError.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
I experienced the following issue: https://github.com/react-native-community/cli/issues/1741 and decided to fix it too.
I've made four changes:
- I removed the try-catch around the body of the init command, to allow errors to bubble up and be handled by the `handleError` in `src/index.ts`.
- I made all the init related errors extend `CLIError` to avoid printing the stack, since "we know exactly what went wrong" and expects the user to have the means to fix it.
- Fixed a failing e2e test (due to a trailing `\n` in the stderr)
- Added a branch to `jest/helpers.ts`'s `handleTestFailure` to assert a non-zero exit code if expectedFailure is true. This could have caught this (or a similar issue) earlier.
Test Plan:
----------
I suggest following the instructions for …
> fix: avoid catching `init` errors and avoid printing their stack

- packages/cli-doctor/src/tools/installPods.ts
Summary:
---------
This change should fix the issue with falling `react-native init` for people with `rvm` installed.
I believe this logic was invalid since we have `Gemfile` in the template root responsible for installing cocoa pods it seems to have no sense to verify its version before.
Test Plan:
----------
- clone repo
- run `yarn build`
- `node ./packages/cli/build/bin.js init ReactNativeUnicorn`
Test scenarios:
> fix: move bundle install above pod version check

- packages/cli-config/src/loadConfig.ts
Summary:
---------
Relates to #1750 
When user is running `yarn install --production` command, the `devDependencies` are not installed. Because of that, they cannot be found in the `node_modules` when loading  CLI's configuration and it ends up with an error `Failed to load configuration of your project.` while running any command. This PR prevents CLI from failing when `devDependencies` are not installed.
Test Plan:
----------
1. Clone the repo and checkout this branch
2. Run `yarn install` in the root catalog
3. Create new React Native project
4. Add any dev dependency, e.g. `yarn add left-pad --dev`
5. Run `yarn install --production`
6. Run `yarn start` - at this stage the command should fail
7. Link packages using [this setup …
> fix: run cli when dev dependencies are not installed

- .github/workflows/stale.yml
Summary:
---------
Relates to #1751 
Implements github action that runs once a day (cron set to 3:00am) to mark issues and PRs with no activity for 90 days as stale, and close stale issues/PRs after 7 days
Test Plan:
----------
Tested if the syntax of .yml file is correct using  [YAMLlint](http://www.yamllint.com/)
I guess the rest has to be tested directly on the respository, the job should run at 3:00am after merging this PR and all the issues older than 90 days should be marked as `stale`.
> add github action to mark issues & PRs as stale

- packages/cli/src/commands/init/init.ts
Summary:
---------
Fixes #1740 
Test Plan:
----------
Fork the branch and try to `init` new project with `react-native-template-typescript`. 
It should print the warning and default to normal r-n template.
> feat: redirect TS template to r-n

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
Upgrades Metro dependencies to 0.73.5 (two minor bumb)
Metro release notes: 
https://github.com/facebook/metro/releases/tag/v0.73.5 
https://github.com/facebook/metro/releases/tag/v0.73.4
Changelog between 0.73.3 and 0.73.5: [https://github.com/facebook/metro/compare/v0.73.3...v0.73.5](https://github.com/facebook/metro/compare/v0.73.3...v0.73.5)
Test Plan:
Updated dependencies with yarn.
Commands I ran for future upgrade reference:
```
yarn upgrade metro-memory-fs@0.73.5
cd packages/cli-plugin-metro
metro_version=0.73.5; yarn upgrade metro@$metro_version metro-config@$metro_version  metro-core@$metro_version metro-react-native-babel-transformer@$metro_version metro-resolver@$metro_version metro-runtime@$metro_version
```
> chore: Upgrade metro dependencies to 0.73.5

- packages/cli/src/commands/init/editTemplate.ts
Fixes https://github.com/react-native-community/cli/issues/1762
Summary:
---------
When using `init` command with `--template` parameter and a custom template in which `placeholderName` as well as the attached files (such as .xcscheme) are written in lowercase, an error occurs. 
This happens because both `shouldRenameFile(filePath, placeholderName)` and `shouldRenameFile(filePath, placeholderName.toLowerCase())` return True and `renameFile()` tries to rename non-existinf file. This commit implements a workaround so that the lowercase function is only executed if the normal function returns False.
Test Plan:
----------
Given that the change is minimal, I think it is enough that I have tested it on several templates: 
yarn react-native init App --template rnbnr-template@0.0.5 --npm …
> fix: avoid renaming a file if it is already renamed

- docs/commands.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts
- packages/cli-platform-android/src/commands/index.ts
- packages/cli-platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
`build-android` command that will create android build without starting packager and launching emulator. 
Fixes #1128 
Fixes #1150 
Part of #179 (together with #1744 ) 
Closes #1055 
Test Plan:
----------
Clone the fork and run `build-android` command with desired options.
> feat: build-android command

- .github/workflows/release-drafter.yml
Summary:
---------
Checking if removing `pull_request` works on this repository - based on this answer: [Forked PRs don't work with release-drafter action (and create an error)](https://github.com/release-drafter/release-drafter/issues/785#issuecomment-927616495)
Test Plan:
----------
On forked repository creating a pull request ended up with success. Let's see what happens here
> chore: run release drafter on pull request open

- docs/commands.md
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-platform-android/src/commands/runAndroid/tryInstallAppOnDevice.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Add support for `--binary-path` option to `run-ios` and `run-android`. This allows a caller to specify their own (pre-built) binary that they want to install on devices, while still keeping all the great os/emulator/device support that react-native-community-cli brings.
Test Plan:
----------
> feat: add --binary-path to run-ios and run-android to enable installing pre-build binaries

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
----------
Updating Metro dependencies in the `cli-plugin-metro` to incorporate the new Metro Release v0.73.6. This Metro release fixes duplicate 'add' events and reduces dropped events on new subtrees in `NodeWatcher`
Per the release notes we shared (link below), I am suggesting that this is a minor bump for RN CLI.
**Metro release notes:** https://github.com/facebook/metro/releases/tag/v0.73.6
**Changelog between 0.73.5 and 0.73.6:** https://github.com/facebook/metro/compare/v0.73.5...v0.73.6
Test Plan:
----------
Updated dependencies with yarn.
Commands I ran for future upgrade reference:
```
yarn upgrade metro-memory-fs@0.73.6
cd packages/cli-plugin-metro
metro_version=0.73.6; yarn upgrade metro@$metro_version metro-config@$metro_version  metro-core@$metro_version …
```
> Upgrade metro dependencies to 0.73.6 in `cli-plugin-metro`

- packages/cli-doctor/src/index.ts
- packages/cli/src/bin.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/1768
Test Plan:
----------
2. Download old version of `node` e.g. `v12.22.12`
3. Run `node packages/cli/build/bin.js start` inside repo and, you should get an error `You need at least Node 14 to run CLI.`
> feat: add condition for min node version

- packages/cli-plugin-metro/package.json
- packages/cli-plugin-metro/src/commands/start/watchMode.ts
Summary:
---------
This PR introduces running an app from terminal using Metro watch mode. The `run-ios` and `run-android` commands are running when `i` or `a` keys are pressed in the Terminal.
iOS:
https://user-images.githubusercontent.com/13985840/207847756-75ce1e13-00b9-425e-a015-1feee21bc4fe.mov
Android:
https://user-images.githubusercontent.com/13985840/207847801-9c13f152-bc4f-4efd-bf92-70fd840a6a5e.mov
Test Plan:
----------
2. Run `yarn start --watchFolders path/to/cloned/cli`
3. Press `a` to run the app on Android
4. Press `i` to run the app on iOS
> feat: run app on iOS and Android with a hotkey

- packages/cli-platform-android/src/commands/runAndroid/index.ts
fixes #1784 
Summary:
---------
When used with option --port and --deviceId, not working port option on run-android.
The reason is as follows.
This command is run with runOnAllDevices function.
runOnAllDevices function is include port argument push on gradle argument logic like below.
```typescript
if (args.port != null) {
gradleArgs.push('-PreactNativeDevServerPort=' + args.port);
}
```
This command is run with runOnSpecificDevice function.
but runOnSpecificDevice function is not include port argument logic.
I added port argument logic on runOnSpecificDevice function like below.
```typescript
// using '-x lint' in order to ignore linting errors while building the apk
let gradleArgs = ['build', '-x', 'lint'];
if (args.extraParams) {
gradleArgs = [...gradleArgs, ...args.extraParams];
}
if …
```
> fix: when used with option --port and --deviceId not working on run-android

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Updating Metro dependencies in the `cli-plugin-metro` to the Metro 0.73.7 hotfix release. This release fixes an issue where Windows Git Bash users would experience file-not-found redboxes due to Metro having an empty file map - https://github.com/facebook/metro/issues/914.
There's an ongoing discussion (@kelset, @cipolleschi, @cortinico) about whether this should be pulled in urgently to React Native 0.71.0, but if not we should aim to get it into 0.71.1
**Metro release notes:** https://github.com/facebook/metro/releases/tag/v0.73.7
**Changelog between 0.73.5 and 0.73.6:** [facebook/metro@v0.73.6...v0.73.7](https://github.com/facebook/metro/compare/v0.73.6...v0.73.7)
Thanks folks!
Updated dependencies with yarn.
*(Reminder : When React Native updates the CLI to a version that depends on …
> Update Metro dependencies to 0.73.7

- packages/cli-platform-android/src/commands/runAndroid/index.ts
Summary:
---------
While investigating issue #1792, I found that the `--active-arch-only`, is ignored, and not added to the gradle arguments.
Test Plan:
----------
2. Start an Android emulator and get it's name with `adb devices`.
3. Run `yarn react-native run-android --deviceId emulator-5554 --active-arch-only`, and the gradle command should use `-PreactNativeDebugArchitectures` and `-PreactNativeArchitectures`.
> fix: add missing activeArchOnly when using runOnSpecificDevice

- docs/commands.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
- packages/cli-platform-android/src/commands/runAndroid/listAndroidDevices.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-platform-android/src/commands/runAndroid/toPascalCase.ts
Summary:
---------
Fixes: https://github.com/facebook/react-native/issues/35838
If `variant` is passed to `run-android` command we still should respect it. 
Test Plan:
----------
- `yarn react-native run-android --mode FullDebug --verbose` should output `./gradlew app:installFullDebug` 
- `yarn react-native run-android --variant FullDebug --verbose` should output `./gradlew app:installFullDebug` 
- `yarn react-native build-android --mode FullDebug --verbose` should output `./gradlew app:assembleFullDebug` 
- `yarn react-native build-android --variant FullDebug --verbose` should output `./gradlew app:assembleFullDebug`
> fix: use variant arg in build-android command

- packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Summary:
---------
Correctly exec launch emulator command when no `port` param is passed. 
fixes: #1801
> fix: correctly exec launchEmulator when no port param is passed

- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Fixes: https://github.com/facebook/react-native/issues/35907
Test Plan:
----------
`yarn react-native run-ios --simulator "iPhone 14"` -> should run app on iPhone 14
`yarn react-native run-ios --device "iPhone Name"` -> should run app on iPhone Name
`yarn react-native run-ios --udid "xyz"` -> should run app on device with id xyz
`yarn react-native run-ios` -> should run on all booted devices
> fix: passing simulator via name

- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/tools/__tests__/checkIfConfigurationExists.test.ts
- packages/cli-platform-ios/src/tools/checkIfConfigurationExists.ts
- packages/cli-platform-ios/src/tools/getProjectInfo.ts
- packages/cli-platform-ios/src/types.ts
Summary:
---------
When running `run-ios` or `build-ios` command with `--mode` option, throw error if the configuration does not exist in the project.
Test Plan:
----------
1. Use `run-ios --mode Release` - should run correctly
2. Use `run-ios --mode Test` - should throw an error
3. Use `build-ios --mode Release` - should run correctly
4. Use `build-ios --mode Test` - should throw an error
> feat: check if configuration for iOS project exists

- packages/cli-platform-ios/package.json
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
- packages/cli-platform-ios/src/tools/getConfigurationScheme.ts
- yarn.lock
Summary:
---------
Closes #1454 
This PR implements using build configuration value associated to scheme provided with a `--scheme` flag.
Test Plan:
----------
Create new scheme in XCode with build configuration set to Release
In the app:
When running commands, watch for `info Building...` message and check if configuration and scheme values are properly set in `xcodebuild` command
> feat: read build configuration from scheme file

- docs/commands.md
- packages/cli/src/commands/init/__fixtures__/editTemplate/android/com/placeholdername/MainActivity.java
- packages/cli/src/commands/init/__fixtures__/editTemplate/ios/PlaceholderName/project.pbxproj
- packages/cli/src/commands/init/__tests__/__snapshots__/editTemplate.test.ts.snap
- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Closes #1269 
Relates to #1111 
Added `--package-name` option to `init` command, which allows initialising project with custom package name for Android and iOS.
Test Plan:
----------
Use `init` command with `--package-name` option:
1. If package name is incorrect e.g. it contains any special chars except dots or have only one segment it should end up with error. Examples: `example`, `com.example@2.app`
2. Initialise project with `--package-name example.app` - project should be initialised with `com.example.app` Android package name and iOS bundleID
3. Initialise project with `--package-name com.example.app` - project should be initialised with `com.example.app` Android package name and iOS bundleID
For 2. and 3., app should be installed on the device/emulator named by …
> feat: allow initialising project with custom package name with `init --package-name`

- .github/workflows/test.yml
- __e2e__/__snapshots__/config.test.ts.snap
- __e2e__/config.test.ts
Summary:
---------
Workflow to run E2E tests on macOS
Test Plan:
----------
E2E tests pass
> GitHub Actions E2E tests on macOS

- docs/commands.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
Summary:
---------
Closes #1821 
Test Plan:
----------
2. Run `yarn react-native run-ios --extra-params "-derivedDataPath somePath"` or `yarn react-native build-ios --extra-params "-derivedDataPath somePath"`, and param `-derivedDataPath somePath` should be added to the `xcodebuild` command.
> feat: add --extra-params to run-ios & build-ios command

- packages/cli-doctor/src/tools/healthchecks/androidHomeEnvVariable.ts
- packages/cli-doctor/src/tools/healthchecks/jdk.ts
- packages/cli-doctor/src/tools/healthchecks/nodeJS.ts
- packages/cli-doctor/src/tools/healthchecks/packageManagers.ts
Summary:
---------
I've noticed that some of our `doctor` inspections are missing labels. I've added the missing ones:
```
Common
✓ Node.js
✓ yarn
✓ Watchman - Used for watching changes in the filesystem when in development mode
Android
✓ JDK
✓ Android Studio - Required for building and installing your app on Android
✓ Android SDK - Required for building and installing your app on Android
✓ ANDROID_HOME
iOS
✓ Xcode - Required for building and installing your app on iOS
✓ CocoaPods - Required for installing iOS dependencies
✓ ios-deploy - Required for installing your app on a physical device with the CLI
✓ .xcode.env - File to customize Xcode environment
```
Test Plan:
----------
Not sure how to test this as that's mostly string changes
> Add missing doctor descriptions

- packages/cli-platform-ios/src/config/findPodfilePath.ts
Summary:
---------
This PR should fix a problem connected with bundle for which, when we run `bundle exec pod install` in a React Native app, the CLI founds two Podfiles.
This is the output before the change:
And this is the output after the change:
Test Plan:
----------
Tested manually in a new RN project, by changing the code in `@react-native-community/cli-platform-ios/build/config/findPodfilePath`.
> fix: avoid considering the Podfile in vendor/bundle/ruby folder as a possibly valid Podfile

- docs/healthChecks.md
- packages/cli-doctor/src/tools/healthchecks/ruby.ts
- packages/cli-doctor/src/types.ts
Summary:
---------
Follow up to: https://github.com/react-native-community/cli/pull/1835#issuecomment-1434420221, I'm making `description` field in `HealthCheckInterface` mandatory.
Test Plan:
----------
> docs: make `description` field mandatory

- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
React Native is increasing the minimum Node JS requirement from 14 to 16 in https://github.com/facebook/react-native/pull/36217, https://github.com/facebook/react-native-website/pull/3580 for 0.72 onwards. This makes the corresponding change in `doctor`.
Test Plan:
----------
CI
> feat: Bump minimum Node JS requirement to 16 for RN 0.72 in `doctor`

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
[Metro 0.73.8](https://github.com/facebook/metro/releases/tag/v0.73.8) addresses two bugs with Metro release bundle source map generation when using the default Terser minifier. This amounts to a regression for users who used the previous `uglify-es` default.
I've [proposed](https://github.com/reactwg/react-native-releases/discussions/58#discussioncomment-5054224) including this in a potential RN 0.71.4 release, a prerequisite of that is that we have a 10.x version of RN CLI that includes it. ~~(It'd be fine to hold off on merging this / a CLI release until RN 0.71.4 is definitely happening)~~
Test Plan:
----------
Versions bumped with Yarn so local changes are all generated. See https://github.com/facebook/metro/pull/928 and https://github.com/facebook/metro/pull/929 …
> [10.x] chore(deps): Metro to 0.73.8 (Terser source map fixes)

- packages/cli-platform-android/src/config/__tests__/getAndroidProject.test.ts
- packages/cli-platform-android/src/config/getAndroidProject.ts
Summary:
---------
When [adding react-native to existing APPs](https://reactnative.dev/docs/integration-with-existing-apps), namespaces with single quotes are quite common, e.g. `namespace 'com.example.myandroid'`
And `./gradlew --info` fails with
```
FAILURE: Build failed with an exception.
* Where:
Script '/home/user/w/Sunbreak/react-native-fabric-module.trial/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 450
* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /home/user/w/Sunbreak/react-native-fabric-module.trial/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, …
```
> fix: parsing namespace with single quotes

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Updating the versions of Metro in the `cli-plugin-metro` to incorporate the new Metro Release v0.75.1. 
https://github.com/facebook/metro/releases/tag/v0.75.1
Per the release notes shared below, this is not a breaking change for RN CLI and only patch release.
**Metro release notes:** 
* **[Feature]**: `metro-inspector-proxy`: Add a human-readable reference to each inspector entries/pages.(https://github.com/facebook/metro/pull/921 by @byCedric)
* **[Feature]**: `metro-inspector-proxy`: Report errors in the console. (https://github.com/facebook/metro/commit/da8b41b279e2618786901daa3d6f25f20e9202db)
* **[Fix]**: Race condition where a very recently modified file might have missing metadata.(https://github.com/facebook/metro/commit/baf28ab0ee3e2fd965691e57691c5d87b01897b2) …
> chore: Upgrading metro dependencies to v0.75.1

- packages/cli-doctor/src/commands/doctor.ts
- packages/cli-doctor/src/tools/envinfo.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
- packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
- packages/cli-doctor/src/tools/runAutomaticFix.ts
- packages/cli-doctor/src/types.ts
- packages/cli-types/src/index.ts
- packages/cli/src/index.ts
Summary:
---------
Resolves #1588
Test Plan:
----------
The doctor command should work as before:
```
```
> fix(doctor): pass config to health checks

- packages/cli-doctor/src/tools/healthchecks/__tests__/androidNDK.test.ts
- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
React Native is increasing the minimum Android_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.72 onwards.
https://reactnative.dev/docs/next/environment-setup#installing-dependencies
`ANDROID_SDK` from [versionRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts) file is not used anymore. For the `ANDROID_SDK` health check we're getting required SDK version from `android/build.gradle` file via `getBuildToolsVersion` helper function. So it depends what is shipped with core but updating the [versionRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts) for posterity. Similarly for the `ANDROID_NDK` …
> doctor : Modifying the version ranges to keep up to date with RN 0.72

- docs/projects.md
- packages/cli-config/src/schema.ts
- packages/cli-platform-android/native_modules.gradle
- packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
- packages/cli-platform-android/src/config/index.ts
- packages/cli-types/src/android.ts
Summary:
---------
This adds the `unstable_reactLegacyComponent` config key inside the `android.project.` object, so that users can use the `react-native.config.js` file to register a list of component they want to use on the New Architecture that are not yet migrated to support Fabric.
I've added the `unstable_` prefix as this is most likely going to change, but we'd like to have it out so soon-ish we can ask users to try it and report back if there are blockers.
I've added docs for this field:
> An array with a list of Legacy Component Name that you want to be registered with the Fabric Interop Layer. This will allow you to use on the New Architecture, libreries that are legacy and haven't been migrated yet.
> The list should contain the name of the components, as they're registered in …
> Add `unstable_reactLegacyComponent` to `cli-platform-android`

- docs/projects.md
- packages/cli-config/src/schema.ts
Summary:
---------
This PR is the equivalent of [this other](https://github.com/react-native-community/cli/pull/1849) but for iOS.
For iOS, the CLI doesn't have to generate anything: we just need to have the same field that we have for Android.
Test Plan:
----------
CI must be green as this is just a configuration addition with no attached behavior, we are happy if validation passes.
> Add the `unstable_reactLegacyComponentNames` to iOS project config

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Summary:
---------
Provide a default value for the [`resolver.unstable_conditionNames`](https://facebook.github.io/metro/docs/configuration#unstable_conditionnames-experimental) option when running Metro via React Native CLI (applicable to Metro >0.75.1, merged in https://github.com/react-native-community/cli/pull/1846), **enabling the `"react-native"` conditional export** (see [RFC](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0534-metro-package-exports-support.md#conditional-exports-user-conditions-and-configuration)).
Note: This does not set `unstable_enablePackageExports` by default, as we want this to be an opt-in by the user (which will be documented in an upcoming React Native blog post). However when users have enabled Package Exports, we …
> feat: Set "react-native" condition when using Package Exports

- packages/cli-doctor/src/tools/runBundleInstall.ts
Summary:
---------
As a follow-up to https://github.com/react-native-community/cli/pull/1873, the stack trace is irrelevant and not useful/actionable since we already know what went wrong with the `npx react-native@latest init AwesomeProject` step. Hence removing it in order to make the error more clear, concise and accurate.
Hence utilizing [CLIError](https://github.com/react-native-community/cli/blob/main/packages/cli-tools/src/errors.ts)  of it's ability to strip out the stack trace in this case.
Resolves https://github.com/react-native-community/cli/issues/1766
Test Plan:
----------
2. Init a new RN app using local built CLI : `node /Users/arushikesarwani/cli/packages/cli/build/bin.js init tests`
**BEFORE …
> fix: Getting rid of stack trace for `Installing Bundler` errors

- __e2e__/__snapshots__/config.test.ts.snap
- babel.config.js
- package.json
- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/loadConfig.ts
- packages/cli-doctor/src/commands/info.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
- packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
- packages/cli-doctor/src/tools/healthchecks/jdk.ts
- packages/cli-doctor/src/tools/healthchecks/ruby.ts
- packages/cli-doctor/src/tools/installPods.ts
- packages/cli-doctor/src/tools/runBundleInstall.ts
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-plugin-metro/src/commands/start/runServer.ts
- packages/cli-tools/src/__tests__/doclink.test.ts
- packages/cli-tools/src/doclink.ts
- packages/cli-tools/src/errors.ts
- packages/cli-tools/src/index.ts
- packages/cli-tools/src/releaseChecker/getLatestRelease.ts
- packages/cli-tools/src/releaseChecker/index.ts
- packages/cli-tools/src/releaseChecker/printNewRelease.ts
- packages/cli-types/src/index.ts
- yarn.lock
Summary:
---------
Everything is in, so this should be good to tests against.
~~These changes will only start to work once our documentation is updated to support this feature:~~
The outcome is that we now write links like this:
```typescript
import {findProjectRoot, logger, link} from '@react-native-community/cli-tools';
link.docs('environment-setup', 'ruby');
```
And get links this:
> https://reactnative.dev/docs/environment-setup#ruby?platform=ios&os=macos
For more complicated examples you'd write this:
```typescript
link.setVersion('0.69');
link.docs('environment-setup', {hash:'ruby', platform: 'ios', guide: 'native', very: 'extensible'})
```
> https://reactnative.dev/docs/0.69/environment-setup#ruby?platform=ios&os=macos&guide=native&very=extensible
Depending on how the user has run …
> feat: add deeplinks to our documentation

- packages/cli-doctor/src/tools/installPods.ts
Summary:
---------
As highlighted in https://github.com/react-native-community/cli/issues/1766, there are useless stack traces in errors that are meant to be human-readable. Hence utilizing [CLIError](https://github.com/react-native-community/cli/blob/main/packages/cli-tools/src/errors.ts) of it's ability to strip out the stack trace in such cases.
Test Plan:
----------
2. Init a new RN app using local built CLI : `node /Users/arushikesarwani/cli/packages/cli/build/bin.js init tests`
> fix : Getting rid of stack traces during `installPods` by using `CLIError`

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
[Metro 0.73.9](https://github.com/facebook/metro/releases/tag/v0.73.9) addresses a [regression](https://github.com/facebook/react-native/issues/36387) whereby directories created while Metro was running were not watched for changes, on Windows and Linux, if *not* using Watchman. This affects React Native 0.71.1-0.71.4 via the CLI.
This fix is earmarked for [inclusion in RN 0.71.5](https://github.com/reactwg/react-native-releases/discussions/59#discussioncomment-5379402), so a new point release of 10.x would be appreciated! Thanks again.
Test Plan:
----------
- New regression tests in Metro for this bug
- Manually tested in an RN app on Windows
- No issues reported by users who forced their `metro-file-map` to 0.76.0, as we [recommended as a …
> [10.x] chore(deps): Metro to 0.73.9 (Windows/Linux watcher fixes)

- packages/cli-tools/src/printRunDoctorTip.ts
Summary:
---------
Recently I updated docs, and this PR fixes link which is pointing to header which doesn't exist.
Test Plan:
----------
> fix: link inside `printRunDoctorTip.ts`

- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-platform-android/src/config/index.ts
Summary:
---------
As highlighted in https://github.com/react-native-community/cli/issues/1766, there are useless stack traces in errors that are meant to be human-readable. Hence utilizing [CLIError](https://github.com/react-native-community/cli/blob/main/packages/cli-tools/src/errors.ts) of it's ability to strip out the stack trace in such cases.
This workflow is part of the onboarding experience of RN, there by this would improve DevX
Test Plan:
----------
BEFORE :
```
arushikesarwani@arushikesarwani-mbp AwesomeProject % react-native run-android                                  
info JS server already running.
info Launching emulator...
error Failed to launch emulator. Reason: The emulator (Pixel_5_API_33) quit before it finished opening. You can try starting the emulator manually from …
```
> fix : Getting rid of stack traces during `run-android` by using `CLIError`

- __e2e__/__snapshots__/default.test.ts.snap
- __e2e__/unknown.test.ts
- package.json
- packages/cli-clean/package.json
- packages/cli-doctor/package.json
- packages/cli-platform-android/package.json
- packages/cli-platform-ios/package.json
- packages/cli-plugin-metro/package.json
- packages/cli/package.json
- yarn.lock
Summary:
---------
https://github.com/sindresorhus/execa/releases
5.x is the last version before the package is being rewritten to ESM.
execa now ships with typescript types embedded.
I see a previous attempt here was aborted:
https://github.com/react-native-community/cli/pull/1514/
error.code is deprecated in favor of error.exitCode
https://github.com/sindresorhus/execa/pull/250
Some changes to stripping the final newline:
https://github.com/sindresorhus/execa/commit/f8397ba9504b5fbba6cb6275b617fc5da6ced199
Test Plan:
----------
There should be no expected changes. From reading the Changelog I could not find any usage of deprecated APIs.
> Bump execa from 1.x to 5.x

- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
As highlighted in https://github.com/react-native-community/cli/issues/1766, there are useless stack traces in errors during `run-ios` that are meant to be human-readable. Hence utilizing [CLIError](https://github.com/react-native-community/cli/blob/main/packages/cli-tools/src/errors.ts) of it's ability to strip out the stack trace in such cases.
In case we are not able to find the simulators in Xcode, the error is direct and message is sufficient, hence removing the stack trace in such case to improve error reporting. This workflow is part of the onboarding experience of RN, there by this would improve DevX
Test Plan:
----------
1. Build cli codebase using : `node ./scripts/build.js && yarn build:debugger`.
2. `cd packages/cli-platform-ios`
3. Link packages using : …
> fix : Getting rid of stack traces during `run-ios` by using `CLIError`

- __e2e__/__snapshots__/config.test.ts.snap
- packages/cli-platform-ios/README.md
- packages/cli-platform-ios/src/commands/logIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/tools/getSimulators.ts
Summary:
---------
Closes  #1675
This PR connects output of two commands`xcrun simctl list --json devices` and `xcrun xcdevice list`. One command outputs `state`, but doesn't return `available`. But second command `xcrun xcdevice list` outputs `available` but doesn't output `state`. So I connected outputs from both commands.
Test Plan:
----------
```
node /path/to/react-native-cli/packages/cli/build/bin.js log-ios
```
> fix: `log-ios` command

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Summary:
---------
Relates to:
- https://github.com/react-native-community/cli/pull/1875
- https://github.com/facebook/react-native/pull/36502
- https://github.com/facebook/react-native/pull/36623
While preparing https://github.com/facebook/react-native/pull/36623, we discovered that (post monorepo) a few scripts in the React Native repo were starting RN CLI in directories outside of the project dir and weren't reading `metro.config.js` as expected — printing obscure errors due to missing config items.
This PR updates the CLI to throw a runtime error when `resolveConfig` fails for the target working directory (`ctx.root`). This is an important DevX enhancement, since a complete `metro.config.js` file will be required from React Native 0.72.
Test Plan:
----------
Pre-steps:
- Run `yarn …
> fix: Add runtime error when Metro config cannot be resolved

- packages/cli-doctor/src/tools/runBundleInstall.ts
Summary:
---------
“Installing Bundler” may be confusing in the context of React Native. It refers to a Ruby tool called “Bundler”, but the word “Bundler” is also sometimes used to describe Metro. Hence renaming it to "Installing Ruby Gems" instead.
Test Plan:
----------
BEFORE :
```
arushikesarwani@arushikesarwani-mbp ~ % npx react-native@latest init test
Welcome to React Native!                
Learn once, write anywhere               
✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing Bundler
✔ Installing CocoaPods dependencies (this may take a few minutes)
Run instructions for Android:
• Have an Android emulator running (quickest way to get started), or a device connected.
• cd "/Users/arushikesarwani/test" && npx react-native run-android
Run instructions for …
```
> Renaming `Installing Bundler` step of `init`

- packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts
- packages/cli-plugin-metro/launchPackager.command
Summary:
---------
This PR replaces `launchPackager.sh` with `launchPackager.command`, we though that we can use `launchPackager.sh`, but actually it doesn't work. Because in same cases when we ran `open -a Terminal.app /path/to/launchPackager.sh` it doesn't opens the Terminal.app with the script but the Code Editor with this file.
Test Plan:
----------
```
```
Metro bundler should be opened in right place in new terminal window.
> fix: replace `launchPackager.sh` with `launchPackager.command`

- packages/cli-plugin-metro/package.json
- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
- packages/cli-plugin-metro/types/@react-native/metro-config/index.d.ts
- yarn.lock
Follow ups to https://github.com/react-native-community/cli/pull/1875.
**Fixes**
- Fix a subtle bug where `loadConfig({cwd: ctx.root, ...options}, overrideConfig);` ([see original file diff](https://github.com/react-native-community/cli/pull/1875/files#diff-3eb3e1e81b924a57b22a630c633912f2f8777b5a201992591c8a3517fb63f525L128)) did not correctly merge `overrideConfig` (the extra config applied by RN CLI) over the newly migrated defaults (which were promoted into the project-level config file).
- After changes, `overrideConfig` will now be merged after all config, _including any user-set config_. This makes sense (as before), given the CLI applies very sparse override options based on required CLI inputs.
- **See test plan for E2E bugs fixed.**
**Upgrade improvements**
Provide a soft …
> fix: Fix merge of CLI Metro config overrides, add soft fallback to RN defaults

- packages/cli-doctor/package.json
- packages/cli-doctor/src/commands/info.ts
- yarn.lock
Summary:
---------
Closes #1809
Test Plan:
----------
```
node /path/to/react-native-cli/packages/cli/build/bin.js info
```
In the output you should see `Android` & `iOS` fields:
```
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false
```
> feat: add `newArchEnabled` and `hermesEnabled` to `info` command

- package.json
Summary:
---------
By default Lerna will only upgrade and publish the packages that were affected by recent changes. However this proves to be tricky, with different CLI sub-packages following different release schedule. To make it less confusing for anyone consuming the packages, this PR adds `--force-publish` flag to the `lerna publish` command, so that all packages are synced even when only one was upgraded.
This goes in line with the recently added `exact` setting to the `lerna.json`, which plays better with the way this CLI is consumed by React Native—through exact versions.
Test Plan:
----------
Doing it locally and now want to upstream it to the command.
> chore: add --force-publish to lerna to sync releases

- packages/cli-plugin-metro/package.json
- packages/cli-plugin-metro/src/tools/getDefaultMetroConfig.ts
- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
- yarn.lock
This is a follow up to https://github.com/react-native-community/cli/pull/1896.
Unfortunately the most recent CLI release was auto-consumed in React Native's CI, exposing a blocker where we could not consume the (repo-)circular dependency `react-native` → `@react-native-community/cli-plugin-metro` → `@react-native/metro-config` — I 100% jumped the gun on this setup(!).
While this is now mitigated by the new CLI release process, and possible in practice, **we're opting to remove this circular setup** as it would introduce maintenance headaches while we are working across two repos.
Changelog: Internal
---
This is an architectural simplification targeting React Native `main` (0.73). However it is also worth cherry picking this commit to RN CLI `10.x` (targeting RN 0.72), so that we can once …
> fix: Drop @react-native/metro-config dep for RN 0.72 config fallback

- scripts/build.js
Summary:
---------
By default the permission is `0o777`, but the `launchPackager.command` needs to have `0o755` to launch correctly.
Test Plan:
----------
Run `yarn build` and check the permission for the file `packages/cli-plugin-metro/build/launchPackager.command`. This file needs to have `-rwxr-xr-x` to launch correctly.
> fix: change permission in `launchPackager.command` when building packages

- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Upon getting gradle errors about JDK like this : 
https://gist.github.com/lunaleaps/21f9b72f4a1e617a8fb04a27c00e527b#file-gistfile1-txt-L16
It was unclear how to install the right JDK. There is no link to RN docs for our recommendation to install the right jdk?
Hence, in case we are sure about the error to be pertaining to JDK install, we can handle this common failure and make the errors more helpful. Also seen in : https://github.com/facebook/react-native/issues/33416
NOTE : The print Doctor Tip is part of both errors reported which is also helpful to fix your current state.
Test Plan:
----------
2. `cd packages/cli-platform-android`
3. Link packages using : `yarn link`
4. In RN app …
> Adding RN docs link for JDK install error

- package.json
- packages/cli-plugin-metro/package.json
- packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
- packages/cli-plugin-metro/src/commands/start/runServer.ts
- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
- yarn.lock
- Upgrades Metro dependencies to 0.76.2. This includes the last 2 minor releases with no anticipated compatibility issues.
- In particular, this contains fixes to experimental Package Exports support, and the removal of some dependencies.
- Removes `@types/metro*` dependencies, since [Metro packages now ship with TypeScript definitions](https://twitter.com/MetroBundler/status/1641490544907153408). Adjusts some `// @ts-ignore`s.
Metro release notes: https://github.com/facebook/metro/releases/tag/v0.76.2
Changelog between 0.76.0 (previous version in `cli-plugin-metro`) and 0.76.2: [https://github.com/facebook/metro/compare/v0.76.0..v0.76.2](https://github.com/facebook/metro/compare/v0.76.0%E2%80%A6v0.76.2)
---
**Reminder**: When React Native updates the CLI to a version that depends on …
> chore: Upgrade metro dependencies to 0.76.2

- package.json
- packages/cli-plugin-metro/package.json
- packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
- packages/cli-plugin-metro/src/commands/start/runServer.ts
- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
- yarn.lock
https://github.com/react-native-community/cli/pull/1910 targeting RN CLI `11.x`.
---
**📦 Please publish!**: We'd like to get the latest Metro fixes to users on the 0.72 RC.
---
- ✅ `yarn build`.
- ✅ `yarn test`.
> chore: Upgrade metro dependencies to 0.76.2 (11.x)

- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
Summary:
---------
Changed default `taskPrefix` in `build-android` command from `assemble` to `bundle`.
Test Plan:
----------
```
node /path/to/react-native-cli/packages/cli/build/bin.js build-android
```
Command should generate `android/app/build/outputs/bundle/debug/app-debug.aab`.
> feat: change default `taskPrefix` in `build-android` command

- packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Summary:
---------
Closes #1907
https://user-images.githubusercontent.com/63900941/232549980-ff709892-ec65-4a2b-8d48-d81588a21587.mp4
Test Plan:
----------
```other
```
should launch `adb shell` with `-a android.intent.action.MAIN -c android.intent.category.LAUNCHER`
> fix: add missing arguments to `adb shell` in `run-android` command

- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
Summary:
---------
This PR removes the addition of `com.` to the package name during project initialization.
Closes #1903
Test Plan:
----------
```other
node /path/to/react-native-cli/packages/cli/build/bin.js init ProjectName --package-name net.company.projectname
```
3. Check two things: 
- `net.company.projectname` should be used as package name, without `com.` prefix
-  path `android/app/src/debug/java/net/company/projectname` should exsist.
> fix: delete `com.` prefix in package name

- packages/cli-platform-ios/src/tools/getProjectInfo.ts
- packages/cli-tools/src/errors.ts
Summary:
---------
`xcodebuild` can throw but when it does inside `JSON.parse` we won't get any error in `catch` block which in turn will cause another error `Error: str.replace is not a function` in CLIError's constructor. 
Partially related to #1883 and #1908  -not a real fix for those issues but at least it will make debugging bit better :)
> fix: str.replace not a function issue

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Updating the versions of Metro in the `cli-plugin-metro` to incorporate the new Metro Release v0.76.3. 
https://github.com/facebook/metro/releases/tag/v0.76.3
Per the release notes shared below, this is not a breaking change for RN CLI and only patch release.
**Metro release notes:** 
* **[Feature]**: Support custom `__loadBundleAsync` implementations in the default `asyncRequire` function. See the [lazy bundling RFC](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0605-lazy-bundling.md) for more details. (https://github.com/facebook/metro/commit/ac3adced45a6ca32286dda9e9470eab6eb4218bf, https://github.com/facebook/metro/commit/f07ce5c455a76b63d47c5ccec9611fc8cd66cd0e by @motiz88)
* **[Feature]**: Support `lazy` parameter in …
> chore : Upgrading metro dependencies to 0.76.3

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Bumps Metro to 0.76.4. This is a regularly scheduled release, but it does contain https://github.com/facebook/metro/commit/5d7305e2f3a9f5f4aebc889a452afb03b1db12a7, a last-minute fix that **may be important enough to pick into the v11 branch and RN 0.72** before RN 0.72 RC3 is cut.
I'm aware we *just* updated Metro in the CLI+RN an hour ago, sorry @thymikee @kelset! We're not currently planning anything else that would force another bump.
Full Metro release notes: https://github.com/facebook/metro/releases/tag/v0.76.4
**Reminder:** When React Native updates the CLI to a version that depends on `metro` 0.76.4, it must also update `metro-runtime` etc to 0.76.4 in the same commit.
Test Plan:
----------
Careful visual inspection
> Upgrade Metro to 0.76.4

- packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
Summary:
---------
Fixes: [#36561](https://github.com/facebook/react-native/issues/36561)
Test Plan:
----------
```other
```
Android build variants should be found correctly, and this command should run correctly app.
> fix: trim whitespace in `parseTasksFromGradleFile` on Windows

- packages/cli-platform-ios/README.md
- packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- destination is used for to specify the arch for iOS build
- this is needed for modules which require arch x84_64
Summary:
---------
With the destination build parameter it can be specified what destination (arch x86_64) gonna be used to build iOS
In case you are using an apple silicon Mac to build your app and you  are using Pod dependencies which were not made for apple silicon it were not possible to change the arch for these dependencies from cli.
Error:
`could not find module 'Adyen' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at:`
xcode would prompt to Build for Rosetta and add en config file
And create a settings file (which has no effect for cli build):
Test Plan:
----------
1. Install this fork
2. Run following command `npx react-native run-ios …
> fix: add missing argument to xcodebuild shell (destination)

- packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts
- packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
Updated Java version check in [versionRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts) to be strictly [11 - 18] (i.e. 19 is not supported).
Part of #1936
Test Plan:
----------
Updated tests and run `yarn test`
> chore (doctor): update Java version range to be strictly 11-18

- packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
- packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
Summary:
---------
This pull request should close issue https://github.com/react-native-community/cli/issues/1927. It was caused by being too rigid when it comes to filtering out versions while searching for a valid simulator. This PR reintroduces `tvOS` as a valid version on this code path. @adamTrz is there a reason why it has been removed in the first place?
Test Plan:
----------
1. Go to https://github.com/react-native-community/cli/issues/1927 and follow the repro steps. Run the `yarn ios` command with `--simulator` set as `Apple TV`.
2. Create a new React Native project and try to run non-tvOS simulator - `yarn ios --simulator "iPhone 14 Pro"` or not specific simulator at all `yarn ios`. It should still run.
> Reintroduce tvOS as valid simulator version when matching for simulators 

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
https://github.com/react-native-community/cli/pull/1943 targeting RN CLI `11.x`.
---
**📦 Please publish!**: We'd like to get the latest Metro fixes to users for React Native 0.72.
---
- ✅ `yarn build`.
- ✅ `yarn test`.
> Upgrade metro dependencies to 0.76.5 (11.x)

- docs/platforms.md
- docs/projects.md
- packages/cli-config/src/schema.ts
- packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
- packages/cli-platform-android/src/config/index.ts
- packages/cli-platform-ios/src/config/__tests__/getProjectConfig.test.ts
- packages/cli-platform-ios/src/config/index.ts
- packages/cli-plugin-metro/src/commands/start/runServer.ts
- packages/cli-plugin-metro/src/commands/start/watchMode.ts
- packages/cli-types/src/android.ts
- packages/cli-types/src/ios.ts
Summary:
---------
Closes #1872
Add `watchModeCommandParams` to configure `run-ios` or `run-android` commands when pressing `i` or `a` inside terminal in watch mode.
Test Plan:
----------
2. Edit `react-native.config.js` inside project to look something like this:
```js
project: {
ios: {
watchModeCommandParams: ['--mode', 'Release'],
},
android: {
watchModeCommandParams: ['--mode', 'Release'],
},
},
};
```
4. Run this command:
```other
node /path/to/react-native-cli/packages/cli/build/bin.js start
```
5. Press `i` inside terminal and the comand `npx react-native run-ios --mode Release` should be run.
6. Press `a` …
> feat: add `watchModeCommandParams` to `react-native.config.js`

- packages/cli/src/index.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/1391
Closes https://github.com/react-native-community/cli/issues/1391
Added `.enablePositionalOptions();` to `CommanderCommand`.
Read [here](https://github.com/tj/commander.js#parsing-configuration) more about this option.
Test Plan:
----------
```other
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --verbose
```
Should correctly pass the --verbose flag to the `run-ios` command.
> fix: `--verbose` option not working for `run-ios`

- __e2e__/__snapshots__/default.test.ts.snap
- packages/cli/src/index.ts
Summary:
---------
Recently we [added](https://github.com/react-native-community/cli/pull/1946) `.enablePositionalOptions()` to the commander, and this caused one problem, because we specified `--verbose` directly to the `react-native` so we were able to do `react-native --verbose`, but if we did `react-native run-android --verbose` it didn't work - so the solution for this is to add `--verbose` to every command.
Test Plan:
----------
`npx react-native -v` <- should give version of CLI
`npx react-native --verbose` <- shouldn't work
`npx react-native run-android --verbose` <- should pass verbose to `run-android`
> fix: always add `--verbose` to the command

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Bump Metro from `^0.70.1` to `^0.70.4`.
Since this version of the CLI used caret semver ranges for Metro dependencies, users may be on any of 0.70.1-0.70.4 already. This ensures everyone will move to 0.70.4 with the next release of React Native 0.69.
The only change in 0.70.4 is support for query-string free / "JSC safe" bundle request URLs (`//&` in place of `?`). This bump is part of the effort to backport our fix for https://github.com/facebook/react-native/issues/36794 to React Native 0.69.x
Metro release notes: https://github.com/facebook/metro/releases/tag/v0.70.4
> [8.x] Bump Metro to 0.70.4

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Bump Metro from `0.73.9` to `0.73.10`.
The only change in this release is support for query-string free / "JSC safe" bundle request URLs (`//&` in place of `?`). This bump is part of the effort to backport our fix for https://github.com/facebook/react-native/issues/36794 to React Native 0.71.x
Metro release notes: https://github.com/facebook/metro/releases/tag/v0.73.10
> [10.x] Bump Metro to 0.73.10

- packages/cli-platform-ios/src/tools/getConfigurationScheme.ts
Summary:
---------
`getBuildConfigurationFromXcScheme` currently assumes where the `.xcodeproj` lives (it could be anywhere). The proper fix is to get the path from `.xcworkspace`, but that's a much more intrusive change. The least we can do for now is to fall back to `Debug`.
Test Plan:
----------
```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.72
yarn
cd example
pod install --project-directory=ios
yarn ios
```
Take note of whether `-configuration` is correctly set when `xcodebuild` is run. This is what it looks like without this fix:
```
info Building (using "xcodebuild -workspace Example.xcworkspace -configuration  -scheme Example -destination id=0")
```
> fix(ios): fix Xcode defaulting to 'Release'

- packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
- packages/cli-plugin-metro/src/commands/bundle/bundleCommandLineArgs.ts
Cleans up unused arg added in https://github.com/react-native-community/cli/pull/1595. This property is not present in Metro's source code.
@dmytrorykun has confirmed that this flag is unused.
Changelog: None
—
> chore: Remove generateStaticViewConfigs option from bundle command

- packages/cli-plugin-metro/src/commands/bundle/assetCatalogIOS.ts
Refactor to reference `fs` instead of `fs-extra` within `cli-plugin-metro`, removing this (implicit) npm dependency.
Changelog: None
[Incoming]
> chore: Remove fs-extra reference from cli-plugin-metro

- packages/cli-plugin-metro/src/commands/bundle/assetCatalogIOS.ts
Summary:
---------
https://github.com/react-native-community/cli/pull/1971 sought to replace `fs-extra` with native `fs` APIs but missed the behaviour difference of the subtly-differently-named API. [`fsExtra.mkdirsSync`](https://github.com/jprichardson/node-fs-extra/blob/v2.1.2/docs/ensureDir-sync.md) operates like `mkdir -p` - recursively creating non-existent directories, and not complaining when a directory already exists. 
This is the behaviour of [`fs.mkdirSync`](https://nodejs.org/api/fs.html#fsmkdirpath-options-callback) if and only if `recursive` is set.
> If `recursive` is `false` and the directory exists, an `EEXIST` error occurs.
CC @huntie 
Test Plan:
----------
Restores previous behaviour
> fix: Potential EEXIST error when iOS asset catalog dir already exists

- packages/cli-platform-ios/src/commands/buildIOS/buildProject.ts
Summary:
---------
This PR cleans up the error message when running `react-native run-ios`. It is now shorter, variables are escaped, and most importantly it removes the "We" which has no meaning in the context of running a command on my computer.
Test Plan:
----------
Check the output of `react-native run-ios` when it throws an error.
> Update `react-native run-ios` command error output.

- packages/cli-plugin-metro/src/commands/bundle/buildBundle.ts
- packages/cli-plugin-metro/src/commands/bundle/bundleCommandLineArgs.ts
- packages/cli-plugin-metro/src/commands/start/runServer.ts
Summary:
---------
Removes `@ts-ignore` from `cli-plugin-metro` package, and now types matches in types in Metro.
Test Plan:
----------
CI Green ✅
> fix: remove `@ts-ignore` in `cli-plugin-metro`

- packages/cli-hermes/src/profileHermes/downloadProfile.ts
- packages/cli-hermes/src/profileHermes/metroBundleOptions.ts
- packages/cli-hermes/src/profileHermes/sourcemapUtils.ts
This fixes #1831
Summary:
---------
As described over in #1831, until now the `profile-hermes` command would always load the `dev` mode soureMaps, even if a production build was being profiled - this lead to wrong line numbers (at best).
This PR detects if the profile has been recorded with a `dev` or `prod` build, which platform was used and if `minify` was enabled.
Unfortunately, at this point, something further down the line seems to fail with a profile that was produced for a minifed build, so I could not really test that - that seems to be some problem with the general process and not with my changes, though.
With `minify: false`, I verified this to work correctly for both `dev=true` and `dev=false`.
If no URL information is present in the profiler, the PR just defaults to the values …
> download correct sourceMap for dev/prod profiles, add warning for Expo Dev menu profiles

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Summary:
---------
I just upgraded to react-native 0.72.0 in our project and found out that `resolver.resolveRequest` from the project config is always getting overridden by the `getOverrideConfig` function. The PR helps fix the issue so that we are able to define our custom `resolveRequest` functions.
For example here's the `metro.config.js` file of our project where we are using `resolveRequest`. This was working in RN 0.71.11 but stopped working after upgrading to 0.72.0. 
```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
/**
* Metro configuration for React Native
* https://github.com/facebook/react-native
*
* @format
*/
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');
const config = {
...
};
const …
```
> fix: resolver.resolveRequest is always undefined

- packages/cli-clean/package.json
- packages/cli-config/package.json
- packages/cli-debugger-ui/package.json
- packages/cli-doctor/package.json
- packages/cli-hermes/package.json
- packages/cli-platform-android/package.json
- packages/cli-platform-ios/native_modules.rb
- packages/cli-platform-ios/package.json
- packages/cli-platform-ios/src/config/__tests__/__snapshots__/findPodfilePath.test.ts.snap
- packages/cli-platform-ios/src/config/findPodfilePath.ts
- packages/cli-plugin-metro/README.md
- packages/cli-plugin-metro/package.json
- packages/cli-server-api/package.json
- packages/cli-tools/package.json
- packages/cli-types/package.json
- packages/cli/package.json
- packages/cli/src/commands/init/template.ts
Summary:
---------
Changed from `master` to `main` in links, and also some links in `homepage` field in `package.json` didn't have `cli` prefix 🙈
Test Plan:
----------
All links should work now. ✅
> docs: replace `master` with `main`

- packages/cli-tools/src/releaseChecker/getLatestRelease.ts
Summary:
---------
This PR removes useless check which actually caused error when the version was released less than week ago, and if yes it returns nothing - what caused strange situation. For example if I were on `0.71.11` (latest release) and I ran `upgrade` command I had an error "Cannot figure out your...", from this line:
https://github.com/react-native-community/cli/blob/4650a8d41c5f9851e0f6bf5939a1bd8f4326c990/packages/cli/src/commands/upgrade/upgrade.ts#L13-L19
Test Plan:
----------
2. Create app with `npx react-native@latest init --version 0.71.10`
```sh
node …
```
> fix: remove useless check in `upgrade` command

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Resolves https://github.com/react-native-community/cli/issues/1987.
Adds improved check to detect if `@react-native/metro-config` (containing the base Metro config for all non-Expo React Native apps — and including `rnx-kit`) has been loaded for a given project. Paired with change:
- https://github.com/facebook/react-native/pull/38126
Since we cannot expect all users to bump `@react-native/metro-config` in their project between `0.72.0` → `0.72.1`, the previous check remains alongside this. If one of these detection methods works, no warning/fallback loading is performed.
**Targets the `11.x` branch (React Native 0.72).**
---
**📦 Please publish!**: We'd like to get this convenience fix to users for React Native 0.72.1.
---
**Remove `@react-native/metro-config` import from config file …
> feat: Add alternative base config check to loadMetroConfig (11.x)

- packages/cli-platform-ios/src/config/findAllPodfilePaths.ts
Summary:
---------
`cli-plugin-ios` performs a glob search for `Podfile` as a heuristic for the ios project root. In a default installation, where Bundler installs Cocoapods as a gem into `vendor`, the vendored cocoapods directory itself contains a Podfile, and this leads to a harmless but noisy warning:
> warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
This amends the existing exclusion list for the `Podfile` search (which already hardcodes and exclusion for eg …
> fix: "Multiple Podfiles were found" due to vendor inclusion

- packages/cli-doctor/src/tools/healthchecks/adb.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
- packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
- packages/cli-doctor/src/tools/healthchecks/jdk.ts
- packages/cli-doctor/src/tools/healthchecks/ruby.ts
- packages/cli-doctor/src/tools/installPods.ts
- packages/cli-doctor/src/tools/runBundleInstall.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-tools/src/__tests__/doclink.test.ts
- packages/cli-tools/src/doclink.ts
- packages/cli-tools/src/releaseChecker/printNewRelease.ts
Previously this would default to Android, which isn't intuitive. Also fixed some links to be more specific.
Summary:
---------
Test Plan:
----------
Built and ran the cli to `init` a new project.
> fix: doclinks should not select a default platform

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Updates Metro to 0.76.7 in 11.x (for RN 0.72).
This release includes a feature from @byCedric to improve debugging stability, and a fix for `EPERM` watcher errors while building a native app on Windows. 
- [0.76.7 Release Notes](https://github.com/facebook/metro/releases/tag/v0.76.7)
- [0.76.6 Release Notes](https://github.com/facebook/metro/releases/tag/v0.76.6)
- [Full changelog since 0.76.5](https://github.com/facebook/metro/compare/v0.76.5...v0.76.7)
Test Plan:
----------
- ✅ `yarn build`.
- ✅ `yarn test`.
> [11.x] chore: Update Metro to 0.76.7

- docs/commands.md
Summary:
---------
Related: https://github.com/react-native-community/cli/pull/1879
Test Plan:
----------
n/a
> docs: sync status with current state of `upgrade` command

- CONTRIBUTING.md
Summary:
---------
The instructions to test local changes with yarn v1 were missing the lib @react-native-community/cli-doctor in the yarn link command. This PR adds it.
Test Plan:
----------
Apply changes to cli-doctor and follow the contributing guide instructions to test local changes with yarn v1.
Checklist
----------
> Update contributing guide with missing step to test local changes

- package.json
- packages/cli-server-api/src/securityHeadersMiddleware.ts
- packages/cli-tools/src/throwIfNonAllowedProtocol.ts
Summary:
---------
Using this guide to connect Chrome DevTools, I was unable to get source maps because CLI was blocking it: https://reactnative.dev/docs/next/hermes
Bonus: Also fixed this warning:
```
⚠ Detected incorrect braces with only single value: `./packages/**/*.{ts}`. Reformatted as: `./packages/**/*.ts`
```
Test Plan:
----------
Follow the guide above, and make sure Ctrl-/⌘P lets you select source files (not just the bundle itself).
Checklist
----------
> fix: allow DevTools to connect

- packages/cli-doctor/src/tools/healthchecks/iosDeploy.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Fixes #2011
Changed the package manager for installing `ios-deploy`. We were installing package via `npm` or `yarn`, but to follow `ios-deploy`'s offical docs we should install the package [with Homebrew](https://github.com/ios-control/ios-deploy#installation). 
Test Plan:
----------
2. Make sure you have not installed `ios-deploy` package. 
```sh
```
Click `f`  to try to fix issue, and `ios-deploy` package should be installed with Homebrew ✅
----------
> chore: use Homebrew for installing `ios-deploy`

- .github/workflows/test.yml
- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Updating the versions of Metro in the cli-plugin-metro to incorporate the new Metro Release v0.77.0.
https://github.com/facebook/metro/releases/tag/v0.77.0
Per the release notes shared below, this is a breaking change for RN CLI including bumping minimum Node version to 18, using Terser's default for comments and removing `metro-minify-uglify` from `metro` dependencies
Metro release notes:
* **[Breaking]**: Increase minimum Node version from 16 to 18. (https://github.com/facebook/metro/commit/ebaf27ab49eb8b9394107bd7a796b24bc342c483 by @arushikesarwani94)
* **[Breaking]**: Use Terser's default for comments. (https://github.com/facebook/metro/pull/972 by @tido64)
* **[Breaking]**: Remove `metro-minify-uglify` from `metro` dependencies. …
> chore: Upgrading Metro dependencies to 0.77.0

- packages/cli-platform-android/src/config/findManifest.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2012
It looks that the `glob` package was looking in wrong directories in my case (I tested this in RNTester on `main`). One thing that is interesting, before RN moved to monorepo the `glob` was finding `AndroidManifest.xml` immediately, but after RN moved fully to the monorepo, glob is looking into packages, which takes some time. But I think this change will make it enough fast. 
Before this change:
| 0.71 | 0.72 |
| ------------- | ------------- |
|  <img width="558" alt="CleanShot 2023-07-11 at 17 27 18@2x" src="https://github.com/react-native-community/cli/assets/63900941/0557b62a-6711-4649-bdb0-663b88c57f28">  | <img width="865" alt="CleanShot 2023-07-11 at 17 28 51@2x" …
> fix(perf): ignore Pods and Hermes files when looking for AndroidManifest

- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Getting rid of duplicate error logging for Gradle. Leaving error messages for specific cases like :
1. No connected devices
2. License
3. Incompatible Java version
in place where we already know what's wrong and provide more helpful error message instead of dumping gradle error. However in all other generic cases, getting rid of duplicate error messages for Gradle.
Test Plan:
----------
4. `cd packages/cli-platform-android`
5. Link packages using : `yarn link`
6. In RN app AwesomeProject, run `yarn link "@react-native-community/cli-platform-android"` to see successful linking :
```
arushikesarwani@arushikesarwani-mbp AwesomeProject % yarn link "@react-native-community/cli-platform-android" …
```
> fix : Getting rid of duplicate gradle error messages

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
- yarn.lock
Summary:
---------
When resolving npmPackageName currently, we are resolving it from the cli-plugin-metro package. But cli-plugin-metro does not have a direct dependency on any of the out of tree platform packages (say react-native-windows or react-native-macos).  Instead we should be resolving npmPackageName from the project root, which will have the out of tree package as a dependency.
This generally works today because so many package managers hoist everything and so packages can resolve other packages that are used in the repo even if they are not declared as dependencies.  But some package managers are moving to be more strict about this.
Test Plan:
----------
Checklist
----------
> npmPackageName should be resolved from project root, not from cli-plugin-metro

- packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/1989
Right now when looking for `.xcode.env` file, we look in directories defined in `react-native.config.js`. It fixes the problem for the brownfield setups, where very often there `ios/` folder is not in the default location. 
Test Plan:
----------
```sh
```
Should find the `.xcode.env`, and if it doesn't exist - after fixing issues by pressing `f` inside terminal, it should create the file in correct location.
Checklist
----------
> fix: adjust `doctor` command to work with custom `ios/` folder location

- packages/cli-tools/src/releaseChecker/printNewRelease.ts
Summary:
---------
In #1882 there was introduced `inherit` platform, when using `link.docs` function, and when using this platform there is following check:
https://github.com/react-native-community/cli/blob/f1de95b60f8d0701327a77a468f51f72a973aafe/packages/cli-tools/src/doclink.ts#L68-L73
it fails, when there's no platform selected. When printing information about new release (we're doing this in `info` and `start` command), we can't really say what platform it is, so the solution for this is to use `none` as platform.
| Before | After |
| ------------- | ------------- |
|   <img width="1397" alt="CleanShot 2023-07-13 at 12 52 33@2x" src="https://github.com/react-native-community/cli/assets/63900941/3c4a3f20-7b19-4898-b2ab-dd9d68c8c7bc"> |  <img width="656" alt="CleanShot 2023-07-13 at …
> fix: use `none` as platform for printing upgrading link

- babel.config.js
- package.json
- packages/cli-doctor/src/tools/versionRanges.ts
- packages/cli-tools/package.json
- packages/cli/package.json
- yarn.lock
Summary:
---------
Set minimum Node version to 18.
Part of https://github.com/react-native-community/cli/issues/1936
Reference: https://github.com/facebook/react-native/pull/37709
> breaking: update Node minimum version to 18

- packages/cli/src/index.ts
I noticed a non-obvious bug when attempting to use `react-native.config.js` to override `commands` (i.e. the plugin system) over the CLI's built-in defaults.
While the below printout shows the project-configured commands being successfully read after the internal commands, **these are never applied** — due to a bug in all versions of the [commander](https://www.npmjs.com/package/commander) library where `commands` are stored as an array structure where the **first registered command with a given `name` is used** (and silently failing upon re-registering a command later 😐).
Changelog:
[Breaking] Custom `commands` in `react-native.config.js` files in libraries or projects will now override built-in CLI commands if defined with the same command `name`
- Set up more `console.log`s
- Build
- …
> breaking: Fix ability to override commands via config

- docs/commands.md
Summary:
---------
Fix profile-hermes link
As is: Link to cli-android
To be: Link to cli-hermes
Test Plan:
----------
Checklist
----------
> docs: fix link to `profile-hermes` command

- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Resolves #2042. Config validation within `loadMetroConfig` was not passing `options.config` to Metro's `resolveConfig` function — where this is done later for `loadConfig`.
**No `--config` arg (Unchanged)**
✅ Implicitly loads `./metro.config.js`
**With `--config` specified**
✅ Loads `metro.config.js` file from alternative file path
**With `--config` specified, file does not exist**
✅ Throws underlying error from Metro
(Note: This error message could be improved in Metro's source — to keep CLI lean I'm not wrapping this with anything now as the error is just about clear enough, cc @robhogan)
> fix: Fix loading Metro config from alternative config path

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Upgrades Metro to latest hotfix release for 0.76.x. This includes:
- https://github.com/facebook/metro/commit/82016b4dae2abd9018e57bce6b9efc5c480ff7b7 / https://github.com/facebook/metro/pull/1027
cc @lunaleaps 
---
**📦 Please publish!**: We'd like to get this hotfix to users in the next React Native 0.72 patch release.
---
> Upgrade Metro dependencies to 0.76.8 (hotfix) (11.x)

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Upgrades Metro to 0.78.0, removes the unreferenced dependencies on `metro-react-native-babel-transformer` and `metro-runtime`, and demotes `metro-resolver` to a `devDependency` (as it is used only for types).
Metro 0.78.0 contains the following breaking changes that we **do not believe are breaking** for CLI users:
* **[Breaking]** Update default server port to 8081. (https://github.com/facebook/metro/commit/891fe9674cb6bc63aea4cea365f78fa2584ab138 by @huntie)
* **[Breaking]** Remove `metro-react-native-babel-transformer` and `metro-react-native-babel-preset`, which will be published as `@react-native/metro-babel-transformer` and `@react-native/babel-preset` going forward. (https://github.com/facebook/metro/commit/799aa0a546e39546e2d0463f3fb1a963dc102bdf by @dmytrorykun)
* **[Breaking]** …
> chore: Upgrade Metro to 0.78.0

- lerna.json
- package.json
- yarn.lock
Summary:
---------
Bumped Lerna to the current latest version - `7.1.3`.
Test Plan:
----------
CI Green ✅
Build package with Node 20 installed.
Checklist
----------
> chore: bump `lerna` to `7.1.3`

- .github/workflows/release.yml
- .github/workflows/test.yml
Summary:
---------
Recently I saw that actions that we're using are outdated, see here:
This PR updates `actions/checkout` and `actions/setup-node`.
Test Plan:
----------
CI Green ✅
No warnings ✅
Checklist
----------
> chore: upgrade GitHub actions

- packages/cli-plugin-metro/src/commands/start/runServer.ts
- packages/cli-plugin-metro/src/tools/loadMetroConfig.ts
Summary:
---------
closes #2020
User-defined reporter on the current implementation will definitely be overridden.
Reimplemented `eventsSocketEndpoint.reportEvent`. If the customLogReporterPath does not exist, the reporter is not overwritten and only the `update` method of the `reporter` is modified.
Also modified some type definitions.
Test Plan:
----------
```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
/**
* Metro configuration
* https://facebook.github.io/metro/docs/configuration
*
* @type {import('metro-config').MetroConfig}
*/
const config = {
reporter: {
update: (event) => {
console.log(1, event);
},
},
};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```
Checklist
----------
> fix: does not override user-defined reporter

- packages/cli-platform-android/README.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Some time ago, we deprecated `--variant` option from `run/build-android`, now I deleted this option. Now everyone should use `--mode` option. 
Checklist
----------
> breaking: remove `--variant` option from `run/build-android` command

- packages/cli-plugin-metro/src/commands/start/watchMode.ts
- packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
- packages/cli-tools/src/index.ts
- packages/cli-tools/src/prompt.ts
Summary:
---------
In this PR I created `KeyPressHandler` that allows us to pause handling keystrokes because in nearest future we will add interactive prompts to `start` command, so they will run in watch mode. If we do not pause the handling keystrokes, the "focus" will be on the prompt. I created a function that wraps `prompts` and pauses and resumes interactivity in watchMode. 
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js start
```
3. Press key that we're handling (`a`,` i`, `d`, `r`) and check if keystrokes are properly handled. 
Checklist
----------
> feat: enable pausing handling keystrokes in watch mode

- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
- packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
- packages/cli-platform-ios/src/types.ts
Summary:
---------
Fixes: #2032 
The `if` statement was checking `booted` value, but in some code path, the `booted` value didn't exist. I unified this, to use `state` field. 
Test Plan:
----------
2. Boot iOS simulator
```sh
```
You should see booted simulator, and this simulator shouldn't boot another time.
Checklist
----------
> fix: prevent booting already booted simulators

- packages/cli-server-api/src/__tests__/statusPageMiddleware.test.ts
- packages/cli-server-api/src/statusPageMiddleware.ts
- packages/cli-tools/src/isPackagerRunning.ts
Summary:
---------
Recently in https://github.com/react-native-community/cli/pull/2021 I changed the response in `/status` endpoint. It worked out that it was breaking change, and React Native depends internally on this response. In this PR I moved passing this information to header, and that's perfect for us because we don't create breaking change and we can make the same logic as before. 
Test Plan:
----------
Everything described in #2021 should work the same after changes in this PR.
Checklist
----------
> fix: change request response in `/status` endpoint

- __e2e__/__snapshots__/config.test.ts.snap
- docs/platforms.md
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-platform-android/package.json
- packages/cli-platform-android/src/commands/runAndroid/__tests__/runOnAllDevices.test.ts
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
- packages/cli-platform-android/src/config/__fixtures__/android.ts
- packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest-className.xml
- packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest-few-activities.xml
- packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest.xml
- packages/cli-platform-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
- packages/cli-platform-android/src/config/__tests__/getMainActivity.test.ts
- packages/cli-platform-android/src/config/getMainActivity.ts
- packages/cli-platform-android/src/config/index.ts
- packages/cli-types/src/android.ts
- yarn.lock
Summary:
---------
Fixes: https://github.com/react-native-community/cli/issues/896
In this PR I created `getMainActivity` function that reads `AndroidManifest.xml` file and gets the main activity name. 
Before this PR when user changed the main activity they have to manually provide main activity by option `--main-activity`.
Test Plan:
----------
2. Change main activity name.
```sh
```
Main activity should be correctly read from `AndroidManifest.xml` and correctly launched on emulator.
> feat: read main activity from `AndroidManifest.xml` automatically

- packages/cli-server-api/src/__tests__/statusPageMiddleware.test.ts
- packages/cli-server-api/src/statusPageMiddleware.ts
- packages/cli-tools/src/isPackagerRunning.ts
Small rename to formalise the custom header added in https://github.com/react-native-community/cli/pull/2056.
Updated test case.
> Rename /status project root header

- packages/cli-platform-ios/src/tools/__tests__/checkIfConfigurationExists.test.ts
- packages/cli-platform-ios/src/tools/checkIfConfigurationExists.ts
Summary:
---------
Assumptions about where the `.xcodeproj` lives causes `checkIfConfigurationExists` to crash because `undefined` was passed as project.
Test Plan:
----------
```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.72
yarn
cd example
pod install --project-directory=ios
yarn ios --mode 'Debug'
```
The last command should not crash.
> fix(ios): fix crash when `--mode` is specified

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- README.md
- docs/commands.md
- docs/healthChecks.md
- docs/init.md
- docs/plugins.md
- docs/projects.md
- packages/cli-clean/README.md
- packages/cli-config/README.md
- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/readConfigFromDisk.ts
- packages/cli-doctor/README.md
- packages/cli-doctor/src/tools/healthchecks/packager.ts
- packages/cli-hermes/README.md
- packages/cli-platform-android/README.md
- packages/cli-platform-ios/README.md
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-plugin-metro/README.md
- packages/cli-tools/src/printRunDoctorTip.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2031
There are people who just copy and pastes commands from docs, and it is not allowed to have globally installed `react-native` package, so I synced every command  in docs, warning and errors - to have `npx` prefix before `react-native` for those who just copy and pastes commands into terminal :)
Test Plan:
----------
Just read it :)
Checklist
----------
> docs: add `npx` prefix before `react-native` command

- jest/helpers.ts
Summary:
---------
Execa returns code as undefined when there are no issues. Let's not print errors in such case to avoid obscuring the output
Test Plan:
----------
CI
Checklist
----------
> chore(e2e): check for undefined code before printing fail

- packages/cli-tools/src/handlePortUnavailable.ts
- packages/cli-tools/src/port.ts
Simplifies "port taken" messages to replace `[packager|Metro|Metro Bundler]` with "dev server", matching recent changes in `@react-native/community-cli-plugin`.
> fix: Adjust wording for dev server port taken messages

- packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
Summary:
---------
Related https://github.com/react-native-community/cli/issues/2012. Few months ago we introduced fetching gradle tasks to validate them and for `--interactive` flag - and it turned out that it takes a lot of time (especially in large projects). So right now we're downloading tasks only for right type (so either `build` or `install`). 
Test Plan:
----------
CI Green
Checklist
----------
> fix: get only tasks for passed type

- packages/cli-platform-android/src/config/findManifest.ts
Summary:
---------
The CLI should not attempt to look into test folders to grab manifests from there.
Specifically this is broken in the `react-native` repo as we do have those two Manifests:
```
packages/rn-tester/android/app/src/debug/AndroidManifest.xml
packages/rn-tester/android/app/src/main/AndroidManifest.xml
```
With this change we prevent the CLI from searching inside `src/test/` and `src/androidTest`.
Test Plan:
----------
I've tested this on `main` of `react-native` and `yarn android` now works well.
Checklist
----------
> Do not attempt to search for manifest in test folders

- docs/commands.md
- packages/cli-clean/src/clean.ts
- packages/cli-doctor/src/tools/checkInstallation.ts
- packages/cli-doctor/src/tools/versionRanges.ts
- packages/cli-doctor/src/types.ts
- packages/cli/src/commands/init/__tests__/template.test.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/template.ts
- packages/cli/src/tools/__tests__/packageManager-test.ts
- packages/cli/src/tools/bun.ts
- packages/cli/src/tools/npm.ts
- packages/cli/src/tools/packageManager.ts
- yarn.lock
Summary:
---------
Adding support for Bun package manager with `init` command.
With template and dependencies installed via bun package manager, the JS code execution time went from ~41s to ~2,5s.
In order to make package managers easier to use, this PR deprecates `--npm` flag and introduces `--pm` flag where it's possible to use one of the packagers: `yarn`, `npm` or `bun`.
Test Plan:
----------
Follow the contributing guide
1. Run `init` command as usual. It should install template and dependencies using yarn and you should have `yarn.lock` file in created project.
2. Run `init` command with `--pm yarn` flag.  Once it's done, you should have `yarn.lock` file in created project.
3. Run `init` command with `--pm npm` flag. Once it's done, you should have `package-lock.json` file in …
> feat: add Bun to `init` command

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
With this change, we are preparing the CLI to support double publishing of React Native.
This change should be transparent to our users until we set up a version of React Native that is different from 0.X.Y
Test Plan:
----------
Tested the code with RNTester.
Checklist
----------
> [Android] Prepare auto-linking for double publishing

- __e2e__/__snapshots__/default.test.ts.snap
- __e2e__/init.test.ts
- packages/cli-clean/src/__tests__/clean.test.ts
- packages/cli-platform-android/src/commands/runAndroid/__tests__/listAndroidTasks.test.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2063
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init 
```
Should prompt user for the project name. 
Checklist
----------
> fix: improve providing project name in `init` command

- packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
Summary:
---------
https://github.com/react-native-community/cli/issues/2068
Test Plan:
----------
```sh
```
3. Check if Android Studio is installing correctly on Windows when using automatic fix.
Checklist
----------
> feat: upgrade Android Studio version when installing on Windows

- packages/cli-debugger-ui/src/ui/index.css
- packages/cli-debugger-ui/src/ui/index.html
In React Native 0.73 we are deprecating Remote JSC Debugging (the `/debugger-ui` endpoint). This PR adds an informational warning header to this page as a signal to users of this change.
This will be supported by (upcoming) improvements to React Native's debugging docs.
| Light | Dark |
|--------|--------|
| ![image](https://github.com/react-native-community/cli/assets/2547783/51337b23-0497-4675-b925-2614ee646456) | ![image](https://github.com/react-native-community/cli/assets/2547783/e77d7b3f-ae58-42df-b97b-e71b3926fb78) |
> Add remote debugging deprecation header

- packages/cli-doctor/package.json
- packages/cli-doctor/src/tools/healthchecks/index.ts
- yarn.lock
Summary:
---------
Update `doctor` command to detect if command was ran in React Native app, if yes we can show the project specific checks. 
Test plan
----------
2. Run this command outside of React Native project, and you should see only checks related to setup.
```sh
```
```
Common
✓ Node.js - Required to execute JavaScript code
✓ yarn - Required to install NPM dependencies
✓ Watchman - Used for watching changes in the filesystem when in development mode
Android
✓ Adb - Required to verify if the android device is attached correctly
✓ JDK - Required to compile Java code …
```
> feat(doctor): adjust healthchecks based on where command was ran

- packages/cli-platform-ios/src/commands/buildIOS/buildOptions.ts
Summary:
---------
Noticed that during resolving merge conflicts the `--force-pods` flag got lost because of moving the build options to `buildOptions.ts` file. 
Test Plan:
----------
Run `run-ios --force-pods` to run pods installation
Checklist
----------
> fix: add missing `--force-pods` flag for `run-ios` and `build-ios`

- packages/cli-debugger-ui/src/ui/index.html
- packages/cli-server-api/src/devToolsMiddleware.ts
- packages/cli-server-api/src/index.ts
- packages/cli-tools/src/index.ts
- packages/cli-tools/src/launchDebugger.ts
- Revert #2065 — since this is referenced as part of necessary auto-launch logic for remote debugging in 0.73!:
- https://github.com/facebook/react-native/blob/780567c7272802fcfba7b3eef186f1b83557f2d1/packages/react-native/React/CoreModules/RCTWebSocketExecutor.mm#L71
- https://github.com/facebook/react-native/blob/780567c7272802fcfba7b3eef186f1b83557f2d1/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L351
- Update remote debugging page title from "React Native Debugger" to "React Native Remote Debugging (Deprecated)".
- iOS JSC build
- Enable remote debugging via `NativeDevSettings.setIsDebuggingRemotely(true)`
✅ Auto-launches `/debugger-ui`, connects external JS runtime
> Restore /launch-js-devtools endpoint (revert #2065)

- packages/cli-platform-ios/src/commands/runIOS/index.ts
Addressing regression from #2078
> fix(iOS): restore simulator, device, and UDID args on `run-ios` command

- packages/cli-tools/src/cacheManager.ts
Summary:
---------
If `package.json` had scoped package name, e.g. `@react-native/tester`, it was unable to create CLI cache since `fs.writeFileSync` could not create it in a path that does not exist. With this PR it will recursively create necessary folder for scoped packages before trying to save the cache file.
Test Plan:
----------
1. Follow the contributing guide
2. run `node ./path/to/cli init AppName`
3. Run `yarn ios` and make sure app runs correctly
4. Change `name` in `package.json` to `@react-native/tester`
5. Run `yarn ios` and make sure app runs correctly
6. Open `~/Library/Caches/react-native-cli/@react-native` folder and make sure `tester` file exists
Checklist
----------
> fix: Creating cache for scoped packages

- packages/cli/src/tools/copyFiles.ts
Summary:
---------
Recently the Babel react-native e2e test is breaking:
https://github.com/babel/babel/actions/runs/6345671251/job/17316512072#step:10:82
```
Error: ENOENT: no such file or directory, chmod '/tmp/rnbabel/ios/HelloWorld/Images.xcassets/Contents.json'
at Object.chmodSync (node:fs:1991:3)
at Object.chmodSync (/home/runner/.npm/_npx/[79](https://github.com/babel/babel/actions/runs/6345671251/job/17316512072#step:10:80)30a8670f922cdb/node_modules/graceful-fs/polyfills.js:263:21)
at ReadStream.<anonymous> (/home/runner/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
at ReadStream.emit (node:events:517:28)
at emitCloseNT (node:internal/streams/destroy:132:10)
at process.processTicksAndRejections …
```
> fix: avoid chmod on read stream close

- packages/cli-tools/src/launchPackager.command
Summary:
---------
Fixes #2095 
Test Plan:
----------
2. Run this command in Bash:
```sh
```
Checklist
----------
> fix: add missing shebang to `launchPackager.command`

- packages/cli-platform-ios/src/tools/pods.ts
Summary:
---------
Skip pods installation in `run-ios` and `build-ios` if they were installed manually before
Test Plan:
----------
1. Init new project
2. Go to `ios` and run `pod install`
3. Use `run-ios` and verify pods are not installed
4. Add new package containing native code, e.g. `react-native-gesture-handler`
5. Use `run-ios` again and verify pods are installed
6. Init new project
7. Use `run-ios` and verify pods are installed
Checklist
----------
> fix: skip pods installation when it's already installed

- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Currently we're not displaying errors if they other than we expect, so even we're not showing errors that we return inside CLI - which leads to situations like this one https://github.com/react-native-community/cli/issues/2105, when user don't know what to do because the error is only "**error** Failed to install the app". 
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-android --mode=randomMode
```
Checklist
----------
> fix(android): properly handle errors

- packages/cli-platform-ios/src/tools/installPods.ts
- packages/cli-platform-ios/src/tools/pods.ts
Summary:
---------
We get path to iOS folder by looking for `Podfile`, even if we rename folder containing iOS files it should work, but by hardcoding it will break.
Test Plan:
----------
2. Rename `ios` folder -> `mv ios fios`,
```sh
```
4. Install library (to get new hash)
```sh
yarn install react-native-slider
```
6. Should detect change in `package.json` and install install pods in new folder.
```sh
```
Checklist
----------
> fix: remove hardcoded path to iOS folder

- packages/cli-doctor/src/commands/info.ts
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/index.ts
- packages/cli-platform-ios/src/tools/getArchitecture.ts
- packages/cli-platform-ios/src/tools/installPods.ts
- packages/cli-platform-ios/src/tools/pods.ts
Summary:
---------
Coming from #2091. Currently, when installed pods with New Architecture manually, added new package and used `run-ios`, it installed pods with old Architecture again. This change checks if the New Architecture is enabled and installs it with/without a flag.
Test Plan:
----------
1. Init new project and install pods during the init
2. Add a library containing native code e.g. `react-native-gesture-handler`
3. Run `run-ios` and verify it installed pods and ran the app
4. Go to `ios` folder and install pods with New Arch manually, `RCT_NEW_ARCH_ENABLED=1 pod install`
5. Add another library, e.g. `react-native-reanimated`
6. Run `run-ios` and verify pods are being installed with a `with New Architecture` message
7. When app is running, verify `fabric: true` is visible in …
> fix: install pods on ios-commands with New Arch

- __e2e__/init.test.ts
Summary:
---------
Mocking `prompts` doesn't change anything if we're running command in real world scenario with `runCLI` function. 
Test Plan:
----------
CI Green.
Checklist
----------
> fix: delete useless mocking in e2e tests

- packages/cli-debugger-ui/src/ui/index.html
Follows https://github.com/react-native-community/cli/pull/2081.
Tweak details related to 0.73 debugger launch:
- Maintains "Open Debugger workflow" guidance: referring to Flipper or the experimental new debugger.
- Qualifies "pressing `j` in the CLI" with the `--experimental-debugger` flag.
- Adds JSC direct debugging link.
| Before | After |
|--------|--------|
| <img width="821" alt="image" src="https://github.com/react-native-community/cli/assets/2547783/6c06667d-14ca-4dd8-b484-810616e4bdc8"> | <img width="820" alt="image" src="https://github.com/react-native-community/cli/assets/2547783/5232c888-e49c-42bf-9372-3e95ea99122e"> |
> Update remote debugging deprecation notice

- packages/cli-platform-ios/src/commands/buildIOS/getConfiguration.ts
- packages/cli-platform-ios/src/tools/__tests__/checkIfConfigurationExists.test.ts
- packages/cli-platform-ios/src/tools/checkIfConfigurationExists.ts
- packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
- packages/cli-platform-ios/src/tools/getInfo.ts
- packages/cli-platform-ios/src/tools/getProjectInfo.ts
- packages/cli-platform-ios/src/tools/prompts.ts
- packages/cli-platform-ios/src/tools/selectFromInteractiveMode.ts
- packages/cli-platform-ios/src/types.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2115
Regression introduced in https://github.com/react-native-community/cli/pull/2078
Reverts this code that was used in 0.72:
https://github.com/react-native-community/cli/blob/9d486c833d5af7f2e6fbf7bec046e54283ba140f/packages/cli-platform-ios/src/commands/runIOS/index.ts#L87-L92
Test Plan:
----------
```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.73 -- --core-only
yarn
cd example
pod install --project-directory=ios
yarn ios
```
Checklist
----------
> fix: get scheme from `xcodeProject` name

- packages/cli/src/tools/packageManager.ts
Summary:
---------
When bun is not available, check if yarn is available in fist place. 
Checklist
----------
> fix: fallback first to `yarn` when `bun` not available

- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-tools/src/findDevServerPort.ts
- packages/cli-tools/src/handlePortUnavailable.ts
- packages/cli-tools/src/index.ts
Summary:
---------
Hides prompt when port is busy when provided `--no-packager` flag.
Test Plan:
----------
2. Start packager in other app on 8081 port
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --no-packager
```
Shouldn't prompt for port change.
Checklist
----------
> fix: do not ask for port change when `--no-packager` provided 

- packages/cli-clean/package.json
- packages/cli-clean/src/clean.ts
- packages/cli-doctor/package.json
- packages/cli-platform-android/src/commands/runAndroid/__tests__/listAndroidTasks.test.ts
- packages/cli-platform-android/src/commands/runAndroid/listAndroidDevices.ts
- packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
- packages/cli-platform-android/src/commands/runAndroid/listAndroidUsers.ts
- packages/cli-platform-ios/src/commands/logIOS/index.ts
- packages/cli-platform-ios/src/tools/prompts.ts
- packages/cli-tools/src/prompt.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
In this PR I moved all prompts to use internal wrapper that we have in `cli-tools` that overwrites `onCancel` method with relevant error. 
| Before | After |
|--------|--------|
| ![CleanShot 2023-10-27 at 16 45 59@2x](https://github.com/react-native-community/cli/assets/63900941/dce67187-273c-4b67-9ba1-f5e01d197a97)| ![CleanShot 2023-10-27 at 16 45 39@2x](https://github.com/react-native-community/cli/assets/63900941/3534da5c-bd5e-43a5-9b94-a1081752cb43)|
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init
```
3. Press `ctrl + c` and you should see "Prompt …
> feat: handle better canceling prompts

- packages/cli-platform-android/README.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts
- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Related: #2012 
When running `run-android` command, it takes a lot of time to build the app for more complex projects with lots of dependencies and different flavors. It is caused by the code checking if the task for provided mode exists. Under the hood, it's running `./gradlew tasks` which takes a lot of time. A good example of such complex project is [Expensify App](https://github.com/Expensify/App), where delay in building the app takes ~4mins. 
Here is a screenshot from profiling report of `./gradlew tasks --group install` from Expensify :
This PR removes this check - Gradlew itself throws an error if the task for provided mode does not exist so we can rely on that:
```
FAILURE: Build failed with an exception.
* What went wrong:
Cannot locate tasks that match …
```
> perf: remove Gradle task check on run-android

- packages/cli-platform-ios/src/commands/logIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
In this PR I added condition which check if there are any simulators / physical devices available. 
Test Plan:
----------
2. Uninstall simulators and unpair physical devices
3. Command `xcrun xcdevice list` should list only your computer
4. Run this command:
```sh
```
It should give an error.
Checklist
----------
> fix(ios): check if there are any available simulators or physical devices

- packages/cli/src/commands/init/template.ts
- packages/cli/src/tools/packageManager.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/1637
We need to be sure that `node_modules` directory exists, because then we're getting template from it. I tested and that command works in v1, v2, v3. 
Checklist
----------
> fix: force users to use `nodeLinker: node-modules` when installing template packages

- __e2e__/config.test.ts
- __e2e__/root.test.ts
- jest/helpers.ts
- packages/cli-platform-ios/src/tools/installPods.ts
Summary:
---------
In this PR I changed to link all packages before running testes. Recently there was introduced change to `init` which creates `react-native.config.js` with some flag. But in tests we were only linking `cli-platform-android` and `cli-platform-ios` so creating project was failing since it installs Pods, and during installing Pods we call `use_native_modules` which executes `config` command that was outdated. And it was giving error: 
Test Plan:
----------
CI Green 
Checklist
----------
> fix(e2e): correctly link packages

- .github/workflows/test.yml
Summary:
---------
Bumps Java to 17, since 0.73 will require it to build app. More details here: https://github.com/react-native-community/cli/issues/2044.
Test Plan:
----------
CI
Checklist
----------
> ci: bump java to 17

- .github/workflows/test.yml
Summary:
---------
Updating the node version missed in https://github.com/react-native-community/cli/pull/2007/ as 18 is the Current version, will be LTS in October.
Test Plan:
----------
Tests pass
> chore: Changing node version missed during metro dependencies upgrade

- packages/cli-platform-ios/src/tools/__tests__/findMatchingSimulator.test.ts
- packages/cli-platform-ios/src/tools/findMatchingSimulator.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2143
In this PR I added sorting simulators to first run iOS ones, to avoid situation like this [one](https://github.com/software-mansion/react-native-reanimated/actions/runs/6692444414/job/18181645440).
Test Plan:
----------
```sh
```
Checklist
----------
> feat(ios): sort simulators to get iOS first

- packages/cli-clean/src/clean.ts
Summary:
---------
According to Node docs, `fs.rmdir(path, { recursive: true })` [will be deprecated](https://nodejs.org/api/deprecations.html#dep0147-fsrmdirpath--recursive-true-) and right now `fs.rm` is a right choice.
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js clean
```
Works in the same way as before.
Checklist
----------
> chore: replace `fs.rmdir` with `fs.rm`

- packages/cli-clean/src/clean.ts
Summary:
---------
By using `ctx.project.android?.sourceDir` `clean` command will work when Android project is under different path.
Test Plan:
----------
2. Change `android` folder name and specify in `react-native.config.js` new path.
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js clean
```
Choose `android` cache to clean, and command should be executed in correct place.
Checklist
----------
> fix: remove hardcoded android path

- .github/workflows/test.yml
- packages/cli/src/commands/init/createGitRepository.ts
Summary:
---------
Sometimes initialising git repository fails, because machine doesn't have git installed or configured correctly so when running E2E tests we need to take this into account and dynamically assign files that we're expecting.  
Test Plan:
----------
CI
Checklist
----------
> fix(ci): setup global git user

- __e2e__/init.test.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/index.ts
Summary:
---------
This PR adds `platform-name` option to allow for out of tree platforms to leverage `init` command without (almost) any changes in their repo. 
When initializing project (for OOT platform) with command similar to this: `@callstack/react-native-visionos init MyApp` current approach would be to pass `--template` option to specify custom template for this platform. However this requires to maintain separate template (as RN-TvOS is doing: https://www.npmjs.com/package/react-native-template-typescript-tv).
Also CLI has a hardcoded path to retrieve template URI (in `createTemplateUri`). 
Allow OOT platforms to pass it's name to `cli.run()` function call which doesn't require to pass any extra flags by user. 
Inside of `[OutOfTreePlatform]/packages/react-native/cli.js` we pass …
> feat: add platform-name option to init for out of tree platforms init

- __e2e__/default.test.ts
- packages/cli/src/index.ts
Summary:
---------
This PR fixes a regression caused by #2170. Now we pass the `platform-name` **only** to init command. Which was the source of error: `Unkown command `--platform-name` as other commands didn't expect this option passed.
I've added a test case to check for this special case
Test Plan:
----------
Green CI
Checklist
----------
> fix: platform-name option causing regressions for other commands

- packages/cli/src/index.ts
Summary:
---------
With current solution we're sure that command `init` was passed, with previous approach folder name could have "init" inside name and condition would be true
Test Plan:
----------
CI Green
Checklist
----------
> fix: make sure command is passed

- docs/init.md
Summary:
---------
Sync with current state of things.
> feat(docs): sync `init` docs with current state

- docs/commands.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Adds flag to opt out `git init` inside `init` command.
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init asdf --skip-git-init
```
3. Should not create git repository.
Checklist
----------
> feat: add `--skip-git-init` to opt out git init

- packages/cli-platform-android/src/config/__fixtures__/android.ts
- packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest-custom-flavor.xml
- packages/cli-platform-android/src/config/__tests__/getMainActivity.test.ts
- packages/cli-platform-android/src/config/findManifest.ts
Summary:
---------
This PR fixes a newly introduced (https://github.com/react-native-community/cli/pull/1967) problem that having multiple build flavors in app causes the `findManifest` script to take the first found one. We think it seems more reasonable to take the one from `main` folder, if present. It fixes the error in `Expensify` app, where `e2e` manifest is the first found one, and the `MainActivity` is present in the `main` folder's `AndroidManifest.xml`. It throws such error then: 
```
error Main activity not found in /Users/.../android/app/src/e2e/AndroidManifest.xml.
```
Test Plan:
----------
Make a simple app with `activity` tag inside `main` `AndroidManifest.xml` and add a directory e.g. `e2e` with other `AndroidManifest.xml`, which should have the `activity` merged from the …
> fix: check for main manifest if multiple are present

- packages/cli-platform-ios/native_modules.rb
Summary:
---------
Removes deprecated option in `native_modules.rb` 
Test Plan:
----------
2. Run this command
```
pod install
``` 
inside `ios/` directory.
Checklist
----------
> chore(ios): remove deprecated param in `use_native_modules`

- packages/cli-types/src/ios.ts
Summary:
---------
This is useful to quiet the `pod install` warning:
"Run script build phase '<script phase name>' will be run during every build because..."
It already exists and works (parses correctly, is carried correctly through native_modules.rb, pod install consumes it and behaves correctly) as an attribute in the type - this just exposes it
ref https://www.rubydoc.info/gems/cocoapods-core/Pod/Podfile/DSL#script_phase-instance_method
I took the opportunity to move the dependency_file attr below execution_phase, so now the order of attributes matches upstream reference documentation order
Test Plan:
----------
react-native-firebase has two script phases that depend on inputs but can't specify output because it would duplicate the output. The scripts themselves are idempotent so it …
> fix(types): IOSScriptPhase accepts "always_out_of_date"

- __e2e__/init.test.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-tools/src/__tests__/cacheManager.test.ts
- packages/cli-tools/src/cacheManager.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Fixing numerous small issues that could lead for potential breaking `run-ios` command:
- if `run-ios` was called for the first time, and Pods were not installed during `init`, after installation it was trying to run `xcodebuild` command with `.xcodeproj` instead of `.xcworkspace`
- if project with a name existed in cache, it was skipping `bundle install` step in `run-ios`
-  if `--version` flag was used with < 0.73, pods had trouble installing because unknown flag was used in the config (this scenario will fail unless 0.73 is `latest`, if you are experiencing it, it's because `latest` is used when `--version` flag is not used)
Test Plan:
----------
1. Follow the [Contributing guide](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md)
2. Create new …
> fix(ios): `run-ios` command

- packages/cli-platform-ios/native_modules.rb
Summary:
---------
This partially reverts commit 2486e49ab6b8d25172953f7dc0075e97134ad70e. It broke tests that run when `ruby` and `pod` are installed (which apparently is not the case on our CI, we should fix that). These tests inject different `config`s to `use_native_modules!`, so the `config` argument is still needed, just for the testing purposes.
Test Plan:
----------
Verify locally that all test suites are executed, and none skipped
Checklist
----------
> Fix native_modules.rb tests

- packages/cli-platform-android/src/config/index.ts
Summary:
---------
Sometimes there are _really_ complicated setups, like this [one](https://github.com/react-native-community/cli/issues/2183) - that are based on `native_modules.gradle`, so are based on `config` command. We should not block users in these cases. 
Test Plan:
----------
CI
Checklist
----------
> fix: remove error when main activity not found in `AndroidManifest.xml`

- README.md
Summary:
---------
before: 
after:  ![CleanShot 2023-11-30 at 20 38 02@2x](https://github.com/react-native-community/cli/assets/63900941/e124ac68-073a-438f-848f-730c9f879ceb)
> fix: warning in `README.md`

- .github/workflows/test.yml
- __e2e__/root.test.ts
Summary:
---------
Every time we're running `root.test.ts` it downloads Gradle. In template there's specified Gradle's `-all` distribution, but with `gradle/gradle-build-action` we can't specify it :( So we need to overwrite to `-bin`.
Test Plan:
----------
CI should cache Gradle version.
Checklist
----------
> ci: properly cache gradle

- packages/cli-tools/src/findDevServerPort.ts
Summary:
---------
When the packager is not running `findDevServerPort` returns `startPackager = false` which is not what we want. Changing the initial value of `startPackager` fixes it (we could also add a branch to check for not_running state but it seemed redundant).
Test Plan:
----------
Tested this patch in an app on RN 0.73 and made sure packager starts when running cli on iOS and Android.
Checklist
----------
> fix: packager starting when using run-ios and run-android

- packages/cli-tools/src/launchEditor.ts
Summary:
---------
Fixes: #2180
https://www.jetbrains.com/help/idea/opening-files-from-command-line.html
Test Plan:
----------
Checklist
----------
> fix: launchEditor not working for JetBrains IDEs

- packages/cli-doctor/src/tools/healthchecks/gradle.ts
- packages/cli-doctor/src/tools/healthchecks/index.ts
Summary:
---------
Feature request #2127 
Test Plan:
----------
For now, 
- `yarn build`
- `cd AwesomeProject && chmod -u ./android/gradlew`
- `node ~/path/to/cli/packages/cli/build/bin.js doctor`
Checklist
----------
> feat: add gradlew doctor check permissions

- __e2e__/init.test.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/printRunInstructions.ts
Summary:
---------
This PR aims to: 
1. Add manual cocapods info when installation fails or user chooses "No" when prompted to install
2. Fix CLI exiting the process when cocoapods installation goes wrong
Test Plan:
----------
CI Green
Checklist
----------
> feat: add manual Cocoapods installation info

- packages/cli-platform-ios/src/tools/prompts.ts
Summary:
---------
Sometimes when user has installed few iOS version, it might be helpful to show simulator version to allow them to pick right one to run.
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --list-devices 
```
3. Should list simulators with iOS versions
Checklist
----------
> feat(ios): show simulator version in prompt

- packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts
Summary:
---------
just an enhancement. Add more guard conditions when retrieving buildConfig from XcScheme.
Test Plan:
----------
add a new project to `/ios/` folder looks like this:
```
|-- ios
|-- foo.xcodeproj
|-- bar.xcodeproj
```
when running `npx react-native run-ios` it would throw an accurate error message.
Checklist
----------
Note:
----------
I'm not good at English, please feel free to correct the error message. Thanks.
> fix: add more guard conditions for retrieving buildConfig from XcScheme

- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/tools/prompts.ts
- packages/cli-tools/src/cacheManager.ts
Summary:
---------
Developers often have a lot of simulators installed on their machines, and if they are running `--list-devices` or `--interactive` they need to go through all of them, but by adding simple caching we'll move last used device to the top of the list. 
Uploading CleanShot 2023-11-07 at 17.06.00.mp4…
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --list-devices
```
3. Choose one devices
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --list-devices
```
5. Chosen device from third step should be on the top of the list.
Checklist …
> feat(ios): cache last used device 

- packages/cli/src/commands/init/init.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2213, when using `npx` ->  `npm_config_user_agent` is `npm`.
Test Plan:
----------
Not really tested, reverts old behaviour when user has strange setup.
Checklist
----------
> fix(init): use `yarn` as package manager when calling `init` with `npx`

- packages/cli/src/commands/init/createGitRepository.ts
Summary:
---------
It may be confusing when we throw an error while initialising Git repo, let's just don't give any information since isn't not-blocking thing. Reference: https://github.com/react-native-community/cli/issues/2212
Test Plan:
----------
2. Put `throw new Error('Git commit failed');` on 57th line in `createGitRepository.ts` file.
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init
```
Git repo init loader shouldn't be presented. 
Checklist
----------
> chore(init): remove error when Git initialisation failed

- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/buildCommand/getXcodeProjectAndDir.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
This PR extracts duplicated code to re-check Xcode project between run and build commands, part of #2217 
Test Plan:
----------
CI Green
Checklist
----------
> refactor: extract duplicated code to `getXcodeProjectAndDir`

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
Regression implemented https://github.com/react-native-community/cli/pull/2208
Test Plan:
----------
```sh
```
3. Should only run on devices once it booted and available. 
Checklist
----------
> fix: only run app on booted and available devices

- packages/cli-platform-apple/src/commands/logCommand/createLog.ts
- packages/cli-platform-apple/src/tools/prompts.ts
Summary:
---------
Related https://github.com/react-native-community/cli/issues/2217
Test Plan:
----------
2. Start few simulators
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js log-ios --interactive
```
Works as before.
> chore: move devices prompt to `prompts.ts`

- packages/cli-platform-apple/README.md
- packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
- packages/cli-platform-apple/src/commands/logCommand/logOptions.ts
- packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
- packages/cli-platform-apple/src/config/index.ts
- packages/cli-platform-apple/src/index.ts
- packages/cli-platform-ios/src/commands/buildIOS/index.ts
- packages/cli-platform-ios/src/commands/logIOS/index.ts
- packages/cli-platform-ios/src/commands/runIOS/index.ts
- packages/cli-platform-ios/src/config/index.ts
Summary:
---------
This PR converts buildOptions and runOptions to follow the same builder pattern. That way we can remove irrelevant platform options and stick to a consistent pattern. 
Dependency config is now also a builder for consistent usage. Example of `run-visionos --help`: 
Test Plan:
----------
Test --help command 
Checklist
----------
> feat: convert command options and dependencyConfig into getters

- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/buildCommand/getXcodeProjectAndDir.ts
- packages/cli-platform-apple/src/commands/logCommand/createLog.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-platform-apple/src/config/findPodfilePath.ts
Summary:
---------
This PR warns about multiple podfiles only if user is using an unsupported platform directory (for example: `native-ios-folder` for ios root). 
It also provides a useful error message when user overrides the sourceDir for given platform. For example:
For this `react-native.config.js`: 
```
project: {
visionos: {
sourceDir: './not-exist',
},
},
};
```
We show this error: 
Test Plan:
----------
Init multi-platform project and check if the warning is there
Checklist
----------
> feat: warn about multiple podfiles only if provided platform is unsupported

- packages/cli/src/tools/__tests__/copyFiles.test.ts
Summary:
---------
Disables flaky tests.
Test Plan:
----------
CI Green
> chore: disable flaky tests

- packages/cli-tools/src/releaseChecker/getLatestRelease.ts
Summary:
---------
As per https://github.com/react-native-community/cli/commit/5774e6adbf532e940c35a11aa78be2108509f74b#r135571193 I think a copy-paste error happened while refactoring this code. This is the current output printed by the `printNewRelease` function:
```
info React Native v0.73.1 is now available (your project is running on v0.73.0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```
Note how the `from` query param of the diff URL uses the stable version instead of the current.
This is the code prior to the commit that introduced the issue: …
> Update `getLatestRelease.ts` to use `currentVersion` in `diffUrl`

- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
Summary:
---------
Looks like there's one more flaky test... Example [failure](https://github.com/react-native-community/cli/actions/runs/7301255982/job/19897539383?pr=2234).
Test Plan:
----------
CI
Checklist
----------
> chore: disable `editTemplate` test on Node v20

- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/buildCommand/getConfiguration.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
When building app for macOS a scheme looks like this `AppName-macOS`. Inside `run-macos` implemention in `react-native-macos` repo [it's hardcoded assumption](https://github.com/microsoft/react-native-macos/blob/164469a0c424b8a6710b9f9b0d6f761ba289cec4/packages/react-native/local-cli/runMacOS/runMacOS.js#L61). I think we can also support this, so if the default one is not accessible, let's give a warning and fallback to one with the suffix. 
Test Plan:
----------
2. Follow steps described [here](https://github.com/react-native-community/cli/blob/main/packages/cli-platform-apple/README.md) to add OOT platform e.g. …
> feat: fallback to OOT scheme

- packages/cli-platform-android/src/commands/runAndroid/index.ts
- packages/cli-tools/src/getDefaultUserTerminal.ts
- packages/cli-tools/src/startServerInNewWindow.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2219
Fixes `run-android` command on windows.
The issue is reported here - #2219 
Bug was introduced on #2021
Issue is - there is no default terminal defined for windows. In the above mentioned PR - terminal param became mandatory. So it was failing.
It also fixes where it tries to run `startServerInNewWindow` with async call, which causes CLI to hang indefinitely. And the native build never starts.
Test Plan:
----------
https://github.com/react-native-community/cli/assets/1908862/e11c1db4-6bac-422d-b9d8-f4d518f07060
Checklist
----------
> Fix for `run-android` on windows.

- packages/cli-platform-apple/src/commands/runCommand/getBuildPath.ts
- packages/cli-platform-apple/src/commands/runCommand/getBuildSettings.ts
- packages/cli-platform-apple/src/commands/runCommand/installApp.ts
- packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts
- packages/cli-platform-apple/src/commands/runCommand/runOnSimulator.ts
Summary:
---------
Moves installing and launching app logic to separate function, so that adding additional logic for another platforms will be fairly easy.
Test Plan:
----------
```sh
```
Works same as before.
Checklist
----------
> refactor(cli-platform-apple): move installing and launching app logic to separate function

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
This PR fixes a regression where builds were executed multiple times because of missing return statement (Introduced during refactor #2208). 
This code before `cli-platform-apple` refactor: https://github.com/react-native-community/cli/blob/3906b900b6a97a234f1f377bb768072d2162292c/packages/cli-platform-ios/src/commands/runIOS/index.ts#L189
Issue screenshot: 
Test Plan:
----------
1. Run `yarn ios` and check if build happens only once
Checklist
----------
> fix: regression where run was executing multiple times

- packages/cli-platform-apple/src/commands/logCommand/createLog.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-platform-apple/src/tools/listDevices.ts
Summary:
---------
This PR removes `getSimulators()` from createRun and adopts them for createLog. I've also added a handful info message from where we are tailing logs from: 
Test Plan:
----------
Check if returned devices are the same.
Checklist
----------
> refactor: adapt `getSimulators()` for OOT platforms

- __e2e__/init.test.ts
- jest/helpers.ts
- packages/cli/src/commands/init/git.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/template.ts
- packages/cli/src/tools/executeCommand.ts
- packages/cli/src/tools/packageManager.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/pull/1931 
When creating new project we'll try to bump Yarn version to v3. We'll only do this if:
- the project is initialised in fresh environment (not in existing Git repo),
- and the Yarn version in the location is Yarn Classic
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init
```
3. Should use Yarn v3 🎉
Checklist
----------
> feat: use Yarn v3 with `nodeLinker: node-modules` for new projects

- packages/cli-tools/src/launchPackager.command
- packages/cli-tools/src/startServerInNewWindow.ts
This pull request addresses compatibility issues with the 'make run-android' command in various shell environments. The changes ensure consistent behavior across different shells by improving path handling and quoting. Specifically, the modifications in 'launchPackager.command' and 'startServerInNewWindow.ts' include enclosing paths with spaces in double quotes and refining the quoting of variables.
> Improve Quotation and Path Handling in CLI Tools

- packages/cli-platform-apple/src/commands/buildCommand/buildProject.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2228
When passing `--port` to `run-ios` command it is of type `number`:
https://github.com/react-native-community/cli/blob/0e8cf75bde113f6c0040f61a679882372b53b8b7/packages/cli-platform-apple/src/commands/runCommand/createRun.ts#L44
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios --port 8888
```
3. Simulator should connect to a dev server on `8888` port.
https://github.com/react-native-community/cli/assets/63900941/026358cb-c568-4cd6-ac5b-91acbee81947
Checklist
----------
> fix(ios): properly pass port to `env` in `xcodebuild`

- packages/cli-tools/src/startServerInNewWindow.ts
Summary:
---------
We don't need to end the whole building app process when running packager failed. We can just give an error, and go ahead.
Checklist
----------
> fix: do not block `run-ios/android` when failed to start packager

- docs/projects.md
Summary:
---------
While upgrading from 0.67 to 0.7x finding `react-native.config` type information was not obvious. Adding annotations so autocomplete works on most editors.
Test Plan:
----------
Just docs
Checklist
----------
> docs: projects.md to include type information

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
Directly calling Runtime.exec breaks Gradle configuration caching. An easy workaround is to use `providers.exec` instead, which supports configuration caching.
Test Plan:
----------
This change should be functionally equivalent to existing behavior. I've tested locally that my project's gradle build still works with this change, both with and without the --configuration-cache argument
Checklist
----------
> build: support Gradle configuration cache

- __e2e__/init.test.ts
- docs/commands.md
- packages/cli/src/commands/init/errors/DirectoryAlreadyExistsError.ts
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
In this PR I added option to replace existing files in the selected directory.
Related https://github.com/react-native-community/cli/pull/1591
Test Plan:
----------
2. Create a directory `hello` with few files
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init hello
```
4. Should ask do user want to replace existing files.
5. If yes, it deletes directory.
6. If not, it prints an error.
Checklist
----------
> feat: log files in selected directory and add option to replace them

- docs/plugins.md
- packages/cli-config/src/__tests__/__snapshots__/index-test.ts.snap
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/loadConfig.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2227, from now commands added inside `react-native.config.js` will override existing ones.
Test Plan:
----------
2. Create`react-native.config.js` file with following content:
```js
commands: [
{
name: 'start',
func: () => {
console.log('hello!');
},
},
],
};
```
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js start
```
4. Command should be replaced ✅
Checklist
----------
> feat: allow overriding commands from `react-native.config.js`

- packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2262.
In https://github.com/react-native-community/cli/pull/2078 `--device` was accidentally removed, and in https://github.com/react-native-community/cli/pull/2086 the flag was restored, but with a small change where now `--device` flag accept value wrapped `<>` instead of `[]`:
- Current implementation: 
https://github.com/react-native-community/cli/blob/f50cc16bce038808680f55c10d659b94215f1a71/packages/cli-platform-apple/src/commands/runCommand/runOptions.ts#L46
- Old one:
https://github.com/react-native-community/cli/blob/a2eb8c0d605bdc5ad03b20a78d515b2ac7994699/packages/cli-platform-ios/src/commands/buildIOS/index.ts#L227
that caused a regression, because with `<>` value is required, but with `[]` is …
> fix: allow users to specify `--device` without value

- docs/projects.md
- packages/cli-config/src/schema.ts
- packages/cli-platform-android/native_modules.gradle
- packages/cli-platform-android/src/config/index.ts
- packages/cli-platform-apple/src/config/index.ts
- packages/cli-types/src/android.ts
Summary:
---------
Related to:
- https://github.com/facebook/react-native/pull/42294
With RN 0.74 specifying the legacy components name wont' be necessary anymore as the framework will detect it automatically.
Test Plan:
----------
Not sure how to test this. I'm basically ignoring the `unstable_reactLegacyComponentNames`. We can remove this in 0.75
Checklist
----------
> feat: Deprecate `unstable_reactLegacyComponentNames`

- packages/cli-clean/package.json
- packages/cli-clean/src/__tests__/clean.test.ts
- packages/cli-clean/src/clean.ts
Summary:
---------
`fs.rm` function does not expand, so when using `clean` command, Metro files are not removed.
This is a follow-up PR to #2161 which solves this problem for Windows, but since `fs.rm` does not expand at all, it still doesn't work properly for macOS. Removing OS check in this solution does not solve the issue, probably because `convertPathToPattern` from `fast-glob` modifies the pattern from `metro-*` to `metro-\*`. This PR should work correctly on both operating systems.
Closes #2161
Test Plan:
----------
1. Find your OS temp directory (`os.tmpdir()`)
2. Use `start` command in any CLI app
3. `ls` in the temp directory to verify any `metro-*` are listed
4. Use `clean` command, select `metro` option and confirm
5. `ls` in the temp directory again and verify all `metro-*` …
> Fix: cleaning metro cache

- packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
- packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Summary:
---------
Take into account that activity may be defined as fully qualified name.
Fixes https://github.com/react-native-community/cli/issues/2268
Test Plan:
----------
Added a unit test
Checklist
----------
> fix: launching activity defined with fully qualified name

- docs/commands.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/template.ts
Summary:
---------
In React Native CI when initialising project all packages are downloaded from local server, recently we introduced Yarn v3, to make Yarn v3 working with local packages we need to pass the server destination inside Yarn config file `.yarnrc.yml`. In this PR I created an option that accepts `key=value` format value, which is then passed via `yarn config set` when installing template packages in `/tmp/` directory. 
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init --yarn-config-options npmRegistryServer="http://localhost:4873" --verbose
```
3. You should see …
> feat(init): add `--yarn-config-options` option

- packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
- packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Summary:
---------
Take into account that activity may be defined as fully qualified name.
Cherry-picks https://github.com/react-native-community/cli/pull/2269
Test Plan:
----------
n/a
Checklist
----------
> fix: launching activity defined with fully qualified name (#2269)

- package.json
- packages/cli-plugin-metro/package.json
- yarn.lock
Summary:
---------
Update Metro to 0.76.9, using `^` to allow future updates (safe since https://github.com/facebook/metro/commit/6d46078e74ae9a43aa90bed46dbd6610e2696cd0) 
Full Metro release notes: https://github.com/facebook/metro/releases/tag/v0.76.9
Test Plan:
----------
- All changes in Metro 0.76.9 are also live in 0.80.5 (RN 0.73)
- Used `resolutions` to smoke test RN 0.72.10 with Metro 0.76.9 
Checklist
----------
> [11.x] Update Metro to ^0.76.9

- docs/autolinking.md
Summary:
---------
The `react-native` project updated how the auto-linking script is imported into the `Podfile` (https://github.com/facebook/react-native/pull/36485), so we need to update the docs to reflect these changes.
Checklist
----------
> docs: update iOS auto-linking docs after adding support for PNPM and workspace setups

- packages/cli-tools/package.json
Summary:
---------
`execa` is not declared as a dependency inside of `cli-tools`. This causes CLI to fail in setups with `pnpm`
Test Plan:
----------
not needed
Checklist
----------
> fix: `execa` phantom dependency in cli-tools

- packages/cli-platform-android/README.md
Summary:
---------
In https://github.com/react-native-community/cli/pull/2026 we've removed `--variant` flag. In this PR I removed last reference to this flag from docs.
> docs: update `--tasks` option description

- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
I improved type safety of `platformConfig` in `createRun` function. and removed unnecessary optional chaining of the `platformConfig`.
(code is located in cli-platform-apple/src/commands/runCommand/createRun.ts)
before I modified type of `platformConfig`, we couldn't infer that platformConfig could be `undefined`.
so, I added `undefined` type to `platformConfig` as optional.
Additionally, there was unnecessary optional chaining, so I removed it.
``` typescript
// * already checked if platformConfig is 'undefined'.
if (
platformConfig === undefined ||
supportedPlatforms[platformName] === undefined
) {
throw new CLIError(
`Unable to find ${platformReadableName} platform config`,
);
}
//  * as far as I see, we don't need optional chaining in here
if …
```
> refactor: improved type safety of platformConfig in createRun function

- packages/cli-doctor/package.json
- packages/cli-hermes/package.json
- packages/cli-hermes/src/profileHermes/downloadProfile.ts
- packages/cli-hermes/src/profileHermes/index.ts
- packages/cli-hermes/src/profileHermes/metroBundleOptions.ts
- packages/cli-hermes/src/profileHermes/sourcemapUtils.ts
Summary:
---------
Backports https://github.com/react-native-community/cli/pull/2299, and https://github.com/react-native-community/cli/pull/1833 which is crucial for `profile-hermes` command.
> fix(10.x): replace `ip` package with default value and `--host` flag

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
When working on TM CXX Autolinking I forgot to return the value here, and this results in `AUTOLINKED_LIBRARIES` CMake variable being empty. Effectively we're not linking against anything then, which is causing build failures in OSS.
See:
- https://github.com/facebook/react-native/issues/43145
Test Plan:
----------
Tested against RNTA reporducer by @tido64 
Checklist
----------
> fix: Do not have empty `AUTOLINKED_LIBRARIES`

- packages/cli-platform-apple/src/commands/runCommand/getBuildPath.ts
Summary:
---------
Hi there! I have a demo script I use to test ios + android builds in both debug+release on rc candidates to make sure react-native-firebase will work with upcoming releases
I'm testing the 0.74-rc series now
It also tests macCatalyst builds, and since that's a pretty niche build setup I frequently find little issues.
I believe I found a little issue here, where after the build (which did work...) there was no ability to launch the macCatalyst app because the path construction for the macCatalyst build was very subtly incorrect
----
Related but not completely related:
I actually have a separate issue with macCatalyst builds in that it is impossible without a hacky-patch to target macCatalyst from the command line but I'm not sure what to do with that. [Explanation here …
> fix(macCatalyst): construct correct path for macCatalyst build

- packages/cli/package.json
Summary:
---------
When linking project inside app that is using Yarn > 3 there's an error:
```
➤ YN0000: ┌ Link step
➤ YN0071: │ Cannot link @react-native-community/cli-tools into @react-native-community/cli@portal:/path/cli/packages/cli::locator=RN0740RC1%40workspace%3A. dependency find-up@npm:5.0.0 conflicts with parent dependency find-up@npm:4.1.0
```
So by aligning `find-up` versions across monorepo 
Test Plan:
----------
CI
Checklist
----------
> fix: align `find-up` package version across packages

- packages/cli-config/src/loadConfig.ts
Summary:
---------
Closes #2321 
User-defined health checks were not passed to the config, making it not possible to define custom checks.
Test Plan:
----------
1. In a RN project, create a `react-native.config.js` file with the following content:
```
healthChecks: [
{
label: 'Custom category',
healthchecks: [
{
label: 'Custom Health Check',
description: 'This is a custom health check',
visible: true,
isRequired: true,
getDiagnostics: async () => ({
needsToBeFixed: true,
}),
runAutomaticFix: async () => {
return new Promise.resolve({});
},
},
],
},
],
};
```
2. Run `node ./path-to-cli/cli/build/bin.js doctor`
3. Verify the custom health check appears in the command output
Checklist
----------
> fix: pass user-defined health checks to config

- scripts/build.js
Summary:
---------
When debugging I noticed the source-maps weren't working, turns out these didn't match:
Test Plan:
----------
Verified in my development environment, with `node --inspect-brk ./packages/cli/build/bin.js --help`.
Checklist
----------
> fix: sourceMappingURL were incorrect .ts → .js

- __e2e__/init.test.ts
- jest/helpers.ts
- packages/cli-platform-android/src/config/findManifest.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Checks that we're using yarn > 1.x when calling `yarn set` which isn't supported [1] but is for later versions [2].  This also updated the E2E test to vary depending on whether yarn 1 or 3 is running.
[1] https://classic.yarnpkg.com/en/docs/cli/set
[2] https://yarnpkg.com/cli/set/version
Test Plan:
----------
Ran against earlier version of yarn where I hit this.
Checklist
----------
> fix: init uses yarn assuming version > 1.x

- .github/ISSUE_TEMPLATE/bug_report.md
Summary:
---------
the "info" command is not known to the react-native wrapper on npmjs.com so "info" only works if you run it from inside a directory where react-native is installed as a local package
This is what happens if you just run `npx react-native info` outside a project:
```
mike@isabela:~ % npx react-native info
npm WARN cli npm v10.2.4 does not support Node.js v18.15.0. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
Need to install the following packages:
react-native@0.73.5
Ok to proceed? (y) y
error: unknown command 'info'
(Did you mean init?)
```
Test Plan:
----------
Run it inside a working project with react-native installed, and it works
Checklist
----------
> chore: specify where to run `npx react-native info` for bug reports

- packages/cli-tools/src/startServerInNewWindow.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2307
From now we're saving `.packager.env` and `launchPackager.command` under `${ctx.root}/node_modules/.generated`, so that setups like Yarn v4 with `node-linker: pnpm` will also work.
Test Plan:
----------
2. Run `yarn start` in other project on port 8081.
```sh
```
4. and you should see this output:
```
> yarn ios
info Another process is running on port 8081.
✔ Use port 8082 instead? › Yes
info Found Xcode project "CliStartServerYarnPnpm.xcodeproj"
```
Checklist …
> fix: save `.env` files under `node_modules/.generated`

- packages/cli-platform-android/src/config/index.ts
Summary:
---------
Currently `cxxModuleCMakeListsPath` works only with absolute paths. This is quite bad as it prevents C++ autolinking adoption in 0.74.
Test Plan:
----------
Tested against the TM C++ Autolinking here:
https://github.com/cortinico/reproducer-cxx-tm-autolinking
Specifically here https://github.com/cortinico/reproducer-cxx-tm-autolinking/commit/d9866946e0b554c3f946e425dae2a72d9a4b26c1#r140284699
With this change we can change this file as follows
```diff
dependency: {
platforms: {
android: {
cxxModuleCMakeListsModuleName: "react-native-reproducer-cxx-tm-autolinking",
-       cxxModuleCMakeListsPath: "/Users/ncor/pg/RN074/node_modules/react-native-reproducer-cxx-tm-autolinking/android/CMakeLists.txt",
+       cxxModuleCMakeListsPath: "./CMakeLists.txt", …
```
> fix: Make sure cxxModuleCMakeListsPath is treated as relative path

- packages/cli-tools/src/releaseChecker/getLatestRelease.ts
- packages/cli-tools/src/releaseChecker/index.ts
- packages/cli-tools/src/releaseChecker/printNewRelease.ts
Summary:
---------
Nightly builds no longer contain `1000.0.0`. Changed to check for either `-nightly` or `-canary` (Windows).
Test Plan:
----------
n/a
> fix(cli-tools): fix nightly builds not being correctly detected

- __e2e__/config.test.ts
- packages/cli-config/package.json
- packages/cli-config/src/readConfigFromDisk.ts
- yarn.lock
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2253
Test Plan:
----------
2. Create `react-native.config.ts` with some config.
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js config
```
4. Changes applied inside `react-native.config.ts` should be visible inside command's output.
Checklist
----------
> feat: add support for `react-native.config.ts`

- docs/commands.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
Support RFC-0759 decoupling of template from react-native. This makes use of the new @react-native-community/template project. We're careful to validate against what npm and github show for the state of the react-native project.
Test Plan:
----------
Checklist
----------
> feat: RFC-0759: check npm and github for template

- packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/pull/2351
Fixes https://github.com/react-native-community/cli/issues/2350
```
» npm run android 
> connectedCoffee@0.0.1 android
> react-native run-android
info Launching emulator...
error Failed to launch emulator. Reason: The emulator (INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 30977) quit before it finished opening. You can try starting the emulator manually from the terminal with: /Users/sung.lee/Library/Android/sdk/emulator/emulator @INFO    | Storing crashdata in: /tmp/android-sung.lee/emu-crash-34.1.20.db, detection is enabled for process: 30977.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
``` …
> Fixed cannot start Android emulator version 34.1.20.0

- packages/cli/src/commands/init/init.ts
Summary:
---------
In https://github.com/react-native-community/cli/pull/2329 we've fixed support for older Yarn version, but also added a regression where actually *all* version of Yarn 1.x won't bump Yarn to `3.6.4` which is not what we want. 
In this Pull Request I've extended a condition to check the minor version, if it's higher or equal to `22` we can use safely use `yarn set version 3.6.4`, if not we use `yarn set policies set-version` with `3.6.4` not with the latest Yarn Classic versions.
Test Plan:
----------
2. Make sure your global Yarn version is `1.22.9`
```sh
node …
```
> fix(init): bump Yarn version on older Yarn versions

- .github/workflows/test.yml
- __e2e__/__snapshots__/config.test.ts.snap
- __e2e__/config.test.ts
- __e2e__/init.test.ts
- __e2e__/root.test.ts
- scripts/buildTs.js
Summary:
---------
React Native was released two weeks ago, in this Pull Request I've synced our e2e infra to unblock CI.
Test Plan:
----------
CI Green.
Checklist
----------
> fix(e2e): sync with React Native 0.74

- packages/cli/package.json
Summary:
---------
In this Pull Request I changed `react-native` executable to `rnc` key, `react-native` as key caused an issue where `@react-native-community/cli` executable overwrites `react-native`'s one (it sorts executables alphabetically). With current change running `npx react-native init` will execute [`cli.js`](https://github.com/facebook/react-native/blob/362abb9ffea5af7e6e5616849fbce28166c758a0/packages/react-native/package.json#L27) which is inside `react-native`, and then it'll resolve to `@react-native-community/cli`, so this change doesn't affects any of current behaviour for now.
If you want to check how `npx` resolves executables under same key, and why it's causing an issue - read more [here](https://github.com/byCedric/npm-npx-bin-collision#readme).
Test Plan: …
> chore: change `react-native` executable path key to `rnccli`

- yarn.lock
Summary:
---------
Fixes CI issues, in `0.1.29` they've added support for Windows on newer Node versions.
Test Plan:
----------
CI
Checklist
----------
> chore: upgrade deasync to unblock CI

- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/commands/config.ts
- packages/cli-config/src/loadConfig.ts
- packages/cli-doctor/src/commands/__tests__/info.test.ts
- packages/cli-doctor/src/tools/healthchecks/index.ts
- packages/cli-platform-android/native_modules.gradle
- packages/cli-platform-ios/native_modules.rb
- packages/cli/src/index.ts
Summary:
---------
This Pull Request implements fetching only platform's specific properties. It means when passing `--platform` option to `config` command, config logic will only get platform's properties, because it doesn't make sense to get informations about Android platform when running `native_modules.rb`, and same deal with `native_modules.gradle`.
I did some benchmarks in project with 50 linked dependencies, and results are:
| Command | Result |
|--------|--------|
| Standalone `config` | 7.62s |
| `config --platform ios` | 0.66s |
| `config --platform android` | 7.43s | 
So it means that linking dependencies during `pod install` got ~7 seconds faster _in this specific scenario_. If there are more dependencies to be linked, the results are higher.
Test Plan:
----------
1. Clone …
> perf(autolinking): get platform's specific properties

- .gitignore
- packages/cli-debugger-ui/.babelrc
- packages/cli-debugger-ui/.parcelrc
- packages/cli-debugger-ui/package.json
- packages/cli-debugger-ui/src/ui/index.html
- packages/cli-debugger-ui/src/ui/index.js
- yarn.lock
Summary:
---------
builds correctly but no idea if the config is right, needs to be tested
Test Plan:
----------
Checklist
----------
> chore: upgrade parcel to v2

- packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
- packages/cli-platform-android/src/commands/runAndroid/tryLaunchAppOnDevice.ts
Summary:
---------
If you have a main activity that is not in package, and is fully specified, it used to work, but it regressed after adding auto-activity detection
If your launcher / `MAIN` activity either specified by --main-activity or in AndroidManifest.xml is fully specified for example like "com.zoontek.rnbootsplash.RNBootSplashActivity" then it needs to launch for example "com.kullki.kscore.dev/com.zoontek.rnbootsplash.RNBootSplashActivity" not "com.kullki.kscore.dev/com.kullki.kscore.dev.com.zoontek.rnbootsplash.RNBootSplashActivity"
So basically I added an "or" in the first conditional chunk that just uses the `mainActivity` as-is, that will allow that if `    (!mainActivity.startsWith('.') && mainActivity.includes('.'))` which I think captures the spirit of the previous code in …
> fix: correct derivation of fully specified android launch activities

- packages/cli-platform-android/README.md
- packages/cli-platform-android/src/commands/runAndroid/index.ts
Summary:
---------
To avoid confusion between `run-android` and `run-ios`, I deprecated `--device-id` in favour of `--device. When someone will use `--device-id` a warning will be presented, so that users can migrate their scripts.
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-android --deviceId "asdf"
```
Should give the warning and pass id the same way as before.
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-android --device "asdf"
```
Should launch an app on passed id.
Checklist
----------
> chore(run-android): deprecate `--deviceId` in favour of `--device`

- packages/cli-tools/src/releaseChecker/getLatestRelease.ts
Summary:
---------
When the newer ReactNative version comes out, we can see some info at console like this:
```
info React Native v0.74.1 is now available (your project is running on v0.73.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.1
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
info Dev server ready
```
but the Diff link can accept both old version and new version like this: 
```
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.6&to=0.74.1
```
This is what this pr solved
Test Plan:
----------
Checklist
----------
> fix: update the diff link at update check to show both the old and new versions

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
Summary:
---------
In `run-ios` command we prioritize simulators over devices:
https://github.com/react-native-community/cli/blob/992d01dc2d985c9950acac5a5d4855f91d54fd74/packages/cli-platform-apple/src/commands/runCommand/createRun.ts#L225
but we're launching app first on a device then on a simulator, in this PR I switched the order of launching app to align with logging and previous assumptions.
Test Plan:
----------
Checklist
----------
> fix(ios): prioritize simulators over devices

- packages/cli-platform-android/src/config/__fixtures__/android.ts
- packages/cli-platform-android/src/config/__fixtures__/files/React.java
- packages/cli-platform-android/src/config/__fixtures__/files/React.kt
- packages/cli-platform-android/src/config/__tests__/findPackageClassName.test.ts
- packages/cli-platform-android/src/config/findPackageClassName.ts
- packages/cli-platform-android/src/config/isProjectUsingKotlin.ts
Summary:
---------
This Pull Request changes schema that looks for files to check to find class name, after my tests in various application the match results were included almost in every library in files with `Package` at the end. But our previous logic was going through every file in library with `.kt` and `.java` extension until it found file with `implements ReactPackage`, some libraries can have 100+ files and we were reading them until we matched relevant Regex schema 😅
I also added a fallback which checks files with `*.kt` and `*.java` extensions if it couldn't find `implements ReactPackage` in file with `*Package` at the end, which ensures us that we don't introduce any breaking change. **The output of `config` command stays the same.**
Performance improvement
---------
I did a …
> perf(autolinking)!: prioritise files with `*Package.java|*Package.kt` in `getPackageClassName`

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-platform-apple/src/commands/runCommand/matchingDevice.ts
- packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
- packages/cli-platform-apple/src/types.ts
Summary:
---------
We have bunch of options to provide a target to run app on:
→ `--device`,
→ `--simulator`, 
→ `--udid`.
It creates some misconception for users, where one flag works as expected in theory but user think that it's not working since they may don't know about other options.
In this Pull Request I've improved experience of using `--device` flag in `run-ios` function (I'll add `run-android` implementation in separate Pull Request). From now `--device` accepts device name and unique device identifier and also checks if target device is maybe a simulator to give an appropriate error message to guide user what they should use. 
Test Plan:
----------
1. Clone the repository and do all the required steps from the [Contributing …
> feat(run-ios): allow passing UDID inside `--device` option

- docs/commands.md
Ram bundle was removed in https://github.com/facebook/react-native/pull/43292 Readme points to non existing command since.
Summary:
---------
Remove dead-end from readme.
Test Plan:
----------
None.
Checklist
----------
> docs: Remove ram-bundle from README

- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
React Native 0.67 is not longer supported.
Test Plan:
----------
N/A
Checklist
----------
> chore: remove specifying `-PreactNativeDebugArchitectures` in Android builds

- __e2e__/init.test.ts
- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/tools/npm.ts
The new template handling in @react-native-community/template means that these are shipped with version 1000.0.0 for React Native. The CLI now owns having to update to the correct version.
**NOTE:** This will only apply if the template has a `react-native@1000.0.0`, i.e. is from `@react-native-community/template`.
Summary:
---------
1. Allow using `--template` and `--version` when `--version` is >= 0.75.  Added a warning about doing this, but it's valid if the user gets into trouble or more advanced users want to do fun stuff.
2. `@react-native/` scoped dependencies **must** match the version of `react-native`.  `init` now enforces this.
3. Done some work to normalise tags into concrete versions.  Going forward `@react-native-community/template` will release matching version for each …
> fix: update react-native version in the template for versions >= 0.75.

- packages/cli/src/commands/init/init.ts
- **fix: only show warning about --template & --version when necessary**
Summary:
---------
When running `npx @react-native-community/cli init`, you now get a warning:
```
$ npx @react-native-community/cli@next init TestInit --version next
warn Use --template and --version only if you know what you're doing. Here be dragons 🐉.
```
It's clearly wrong and should only happen when `--version` and `--template` are used together.
Test Plan:
----------
```
node scripts/build
...
$ node ./packages/cli/build/bin.js init --version next --skip-install --verbose TestInit2
debug Initializing new project
$ node ./packages/cli/build/bin.js init --version next  --template @react-native-community/template@next TestInit --skip-install --verbose
warn Use --template and --version only if you know what you're …
```
> fix: only show warning about --template & --version when necessary

- packages/cli/src/commands/init/__tests__/editTemplate.test.ts
- packages/cli/src/commands/init/editTemplate.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/tools/npm.ts
Summary:
---------
This will take advantage of changes coming in the way we publish the template: react-native-community/template/pull/30
refactor: init now expects templates to have react-native version set
For 0.75's previous RCs, we didn't have the infrastructure in place to
tag @react-native-community/templates 0.75-stable branch correctly, as
well as publishing the corresponding version to npm.
For example:
If @react-native-community/template@0.75.1 is the latest version
published, and I specified --version next: I'd expect 0.75.1 of the
template to be used with 0.75.1 of react-native.
The downside of this approach is, if you init an older version then
things might not work.  You'd have to specify the matching template
using --template @react-native-community/template@<some version>. …
> refactor: init now expects templates to have react-native version set

- packages/cli-platform-android/native_modules.gradle
Summary:
---------
While working on a react-native project I've encountered an error comming from ```native_modules.gradle``` upon running gradle sync which was caused by the ```exec``` method not re-running threads asynchronously, using ```ProcessBuilder``` provides a better way of approaching this issue.
Test Plan:
----------
- Compile your android project straight from CLI utilising the new ```getCommandOutput``` method
Checklist
----------
> FIX: ```getCommandOutput``` exec thread

- packages/cli/src/commands/init/init.ts
Summary:
---------
We were checking for Yarn major to be higher than 1, which is okay ✅ but we also checked in every scenario for minor to be higher than 22, which e.g for Yarn version 3.6.4 is not the case and CLI was running `yarn policies set-version x.y.z` for Yarn v3 which was throwing an error, and PnP was used.
Test Plan:
----------
1. Use Yarn v3/v4 globally 
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js init
```
3. Packages should be installed with yarn and `nodeLinker: node-modules` should be used.
Checklist
----------
> fix: correctly check Yarn version

- packages/cli/src/commands/init/init.ts
- packages/cli/src/tools/npm.ts
Summary:
---------
1. Removing ~ npm version range from the template looking for installs > 0.75.0. This effectively forces version pinning against the react native release version.  For example:
```
npx @react-native-community/cli init Foo --version 0.75.0-rc.2
```
Would install @react-native-community/template@0.75.0-rc.2 template only. We have a plan to do something more comprehensive, but this is affecting the release and had to be paused. There are 2 exceptions:
- nightly - always points to the nightly tag
- 0.75.0-rc.1 - points to 0.75.0-rc.1.1 to unblock the RC1 release
2. Fixed a bug which disabled using --template and --version for installs > 0.75.0, as the release candidates were < 0.75.0.
Test Plan:
----------
1.  ✅ `node ./packages/cli/build/bin.js init RN075 --version …
> fix: react-native RC2 fixes

- packages/cli-platform-android/README.md
- packages/cli-platform-android/src/commands/buildAndroid/index.ts
- packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
- packages/cli-platform-apple/src/commands/logCommand/logOptions.ts
- packages/cli-platform-ios/README.md
Summary:
---------
`-i` is easier and faster to type. 
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js run-ios -i
```
3. Should work the same as with `--interactive`
Checklist
----------
> feat: add `-i` alias for `--interactive` option

- packages/cli-server-api/package.json
- yarn.lock
Summary:
---------
Related to https://github.com/facebook/react-native/pull/45147
[INTERNAL] [SECURITY] - Fixes [CVE-2024-37890](https://github.com/advisories/GHSA-3h5v-q93c-6h6q)
Test Plan:
----------
NA
Checklist
----------
> chore: bumps `ws` package which patches a security vulnerability

- packages/cli/src/commands/init/init.ts
Summary:
---------
When users call the cli through react-native (a deprecated path), it hard-codes the platform name to 'react-native'. This is an error, and doing this bypasses all template selection logic.
This excludes setting the platform name to 'react-native', which is assumed.
Test Plan:
----------
Replicates these changes to the npx cache `~/.npx/_cache/.../index.js` to confirm this fixes the issue holding up the release.  Added some logging to show:
1. The `run()` method is called with `react-native`, which we should ignore.
2. The raw `process.argv` used to call
3. The expected outcome with out change.
Checklist
----------
> fix: issue calling init from 0.75.0-rc.1 release

- packages/cli-platform-android/src/config/__fixtures__/files/AndroidManifest-className.xml
- packages/cli-platform-android/src/config/getMainActivity.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2392
If `intent-filter` with `android.intent.action.MAIN` and `android.intent.category.LAUNCHER` was preceded by an `intent-filter` without `action`/`category` `getMainActivity` function would fail.
Test Plan:
----------
2. Put this snippet inside `AndroidManifest.xml`
```
<intent-filter>
<action android:name="android.intent.action.VIEW" />
</intent-filter>
```
```sh
```
4. App should launch correctly ✅
Checklist
----------
> fix: skip if there's no `action` or `category`

- docs/autolinking.md
- docs/projects.md
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/1137
Users when linking libraries should leverage `__dirname` instead of `processs.cwd()`.
Checklist
----------
> docs: note that `root` property should use `__dirname`

- packages/cli-doctor/package.json
- yarn.lock
Summary:
---------
New version of `envinfo` contains a fix for detecting Android Studio: https://github.com/tabrindle/envinfo/releases/tag/v7.13.0
Related: https://github.com/react-native-community/cli/issues/2354
Test Plan:
----------
n/a
Checklist
----------
> chore: bump `envinfo` package

- packages/cli-clean/src/clean.ts
Summary:
---------
In this Pull Request I've moved `npm` to the end of list → removing `node_modules` at the end of `clean` command makes sure that we don't remove CLI itself before finish command 😅
Fixes https://github.com/react-native-community/cli/issues/2353
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js clean
```
3. `npm` should be always as last item ✅
Checklist
----------
> fix(clean): make sure to delete `node_modules` as last item

- README.md
Summary:
---------
I've done a pass to bring the README up to date with the current status of the CLI.
> Update README to reflect current status of the CLI

- packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
Summary:
---------
Android Studio executable can sometimes contain architecture in the file name. Inside CLI we already honor architecture in the AS file name:
https://github.com/react-native-community/cli/blob/b17d969a17b6bfc04306cd151be917dfccd96d00/packages/cli-doctor/src/tools/healthchecks/androidStudio.ts#L67
Test Plan:
----------
```sh
```
3. Android Studio should be properly detected on Windows ✅ 
Checklist
----------
> fix(doctor): update Android Studio detection path on Windows

- packages/cli-link-assets/src/linkAssets.ts
- packages/cli-platform-apple/src/commands/buildCommand/getXcodeProjectAndDir.ts
Summary:
---------
Guides user to maybe install Cocoapods when Xcode project is not available (there are some project when running `pod install` generates projects).
Test Plan:
----------
2. Create a project with `npx --package react-native-test-app@latest init`
3. Run `yarn react-native run-ios`.
Checklist
----------
> feat: improve error message when cannot find Xcode project

- packages/cli/src/commands/init/init.ts
Summary:
---------
Sometimes when running `yarn set version` - Yarn produces different warnings that as of my testing are not relevant and for sure not fixable during `init` command.
Test Plan:
----------
`init`'s command output shouldn't produce warnings/success messages from Yarn.
Checklist
----------
> fix: show only warnings from Yarn when verbose mode is enabled

- .github/workflows/nigthly-release.yml
Summary:
---------
Latest nightly failed because it pulled latest `lerna` version which fails with current arguments, in this Pull Request I added a step to install (and build) packages before publishing. 
Test Plan:
----------
After margining this Pull Request let's wait for 00:00 UTC for actions to trigger.
Checklist
----------
> ci: install dependencies before releasing nightly version

- docs/autolinking.md
Summary:
---------
Fix broken link in autolinking.md due to moving template code to the community repository.
Test Plan:
----------
[rendered diff](https://github.com/react-native-community/cli/pull/2448/files?short_path=30560cb#diff-30560cbb6b72f5d4b12a887cfdecd79911c3cff868ec8ef828585bcc2dd4ee79) is displayed correctly, and the link works.
Checklist
----------
> docs: fix broken link to Podfile in React Native template

- .github/workflows/nigthly-release.yml
Summary:
---------
`version` command doesn't accept `from-package` option:
```
❯ npx lerna version from-package
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', or 'prerelease'.
```
Test Plan:
----------
After margining this Pull Request let's wait for 00:00 UTC for actions to trigger.
Checklist
----------
> ci: remove wrong option passed to command

- packages/cli/src/tools/npm.ts
Summary:
---------
Commands are failing on npm 10.7.0 (and Node 20.15.1) when inside a monorepo. Example when building Android:
```
Error executing command '[node, npm error code ENOWORKSPACES
npm error This command does not support workspaces.
npm error A complete log of this run can be found in: ~/.npm/_logs/2024-07-15T08_41_45_432Z-debug-0.log
/~/node_modules/@react-native-community/cli/build/bin.js, config, --platform, android]': Command '[node, npm error code ENOWORKSPACES
npm error This command does not support workspaces.
npm error A complete log of this run can be found in: ~/.npm/_logs/2024-07-15T08_41_45_432Z-debug-0.log
/~/node_modules/@react-native-community/cli/build/bin.js, config, --platform, android]' failed with exit code 1.
```
The culprit seems to be this command, which …
> fix(cli): fix `ENOWORKSPACES` when running any command on latest npm

- .github/workflows/nigthly-release.yml
Summary:
---------
When Prerelease step fails logs are not printed, in this PR I've changed to log it always regardless of the previous step output.
> ci: always print debug log from lerna

- packages/cli/src/index.ts
Summary:
---------
Add `--version` option, we already have abbreviation one `-v`.
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js --version
```
3. Should output current CLI version.
Checklist
----------
> feat: add `--version` option

- packages/cli-config/src/loadConfig.ts
Summary:
---------
If dependency does not have native code, it does not have `platforms` property in dependency config. Passing `--platform [platformName]` was breaking when it was trying to read `platforms` from such dependencies.
Closes #2463 
Test Plan:
----------
1. Run `node ./path-to-cli/cli/build/bin.js config --platform ios`
2. Verify the output was returned properly
3. Run `node ./path-to-cli/cli/build/bin.js config --platform android`
4. Verify the output was returned properly
Checklist
----------
> fix: config fails to load with --platform flag

- packages/cli-platform-apple/src/config/findAllPodfilePaths.ts
Summary:
---------
This PR addresses https://github.com/react-native-community/cli/issues/2479. Basically the unbounded search for `**/Podfile` never finishes on my machine. Normally the required depth should be `2`, since `ios/Podfile` is the default location. So this still provides significantly more depth than most users should need.
Test Plan:
----------
To be honest I'm not sure what causes this issue on my system, I only investigated what fixes it so far. It's clearly an issue with a deeply-nested submodule that we have, but I can't see what about it is causing the issue. If I run `find .` in my project root, all files (including the deeply-nested ones) can be printed within a few seconds, whereas `fast-glob` appears to never finish its search without this `deep: 10` limitation. …
> Put an upper bound on "**/Podfile" search depth

- __e2e__/__snapshots__/config.test.ts.snap
- __e2e__/__snapshots__/default.test.ts.snap
- __e2e__/root.test.ts
Summary:
---------
Updated snapshots with `yarn test:ci:e2e -u`. Snapshots needed to be updated because of new React Native major and `--version` introduced in https://github.com/react-native-community/cli/pull/2460. 
Test Plan:
----------
CI green
Checklist
----------
> test(e2e): update snapshots

- packages/cli-config/src/readConfigFromDisk.ts
Summary:
---------
I was trying out 0.75 and not sure why is worked before, but now the `config` command returned [this value](https://github.com/vonovak/react-native-theme-control/blob/a0a68284f8dbaa011333331632b0ce2bf03d7a15/package.json#L8) - literally "src/index", instead of the value influenced by the config file.
Test Plan:
----------
`npx react-native config` returned a valid result in the [repo](https://github.com/vonovak/react-native-theme-control)
Checklist
----------
> fix: readConfigFromDisk should ignore package.json entries

- packages/cli-link-assets/package.json
- packages/cli-platform-android/package.json
- packages/cli-platform-apple/package.json
- yarn.lock
Fix vulnerability issue from [fast-xml-parser](https://github.com/advisories/GHSA-mpg4-rc92-vx8v)
Closes [2465](https://github.com/react-native-community/cli/issues/2465)
> chore: bump `fast-xml-parser` from 4.2.4 and 4.3.2 to 4.4.1

- packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
- packages/cli-platform-apple/src/commands/runCommand/runOptions.ts
- packages/cli-platform-ios/README.md
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2473
Test Plan:
----------
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js build-ios --device
```
Checklist
----------
> fix: add missing `--device` option to `build-ios` command

- packages/cli-platform-android/src/config/findPackageClassName.ts
Summary:
---------
Recently [blog post](https://github.com/react-native-community/discussions-and-proposals/discussions/814) regarding performance improvements inside autolinking was published, as it turns between implementations there's a big difference.
After my investigation it is due getting package class name from classes which are implementing `ReactPackage` or `TurboReactPackage`. In past we landed improvements to this logic (read more [here](https://github.com/react-native-community/cli/pull/2384)).
But as mentioned in the blog post the difference is still big and the root cause of this issue is because of reading hundreds of files from expo modules and trying to find classes that implements `ReactPackage` or `TurboReactPackage`, but expo modules don't implement `ReactPackage` or …
> perf: skip getting package class name inside expo module

- packages/cli/src/commands/init/__tests__/version.test.ts
- packages/cli/src/commands/init/constants.ts
- packages/cli/src/commands/init/init.ts
- packages/cli/src/commands/init/types.ts
- packages/cli/src/commands/init/version.ts
- packages/cli/src/tools/__tests__/npm-test.ts
- packages/cli/src/tools/npm.ts
Summary:
---------
When we trigger a release of the template, we capture the version of react-native it's built with in the `scripts.version` field. This is accessible for all version of the template:
`$ curl --silent https://registry.npmjs.org/@react-native-community%2ftemplate | jq '.versions[] | {scripts: .scripts,version: .version}'`
```json
{
"scripts": {
"version": "0.75.0-nightly-20240618-5df5ed1a8"
},
"version": "0.76.0-nightly-20240621-e2b44a9"
}
...
{
"scripts": {
"version": "0.75.0-rc.6"
},
"version": "0.75.0-rc.6"
}
...
```
and
`$ curl --silent https://registry.npmjs.org/@react-native-community%2ftemplate | jq '.time'`
```json
{
"created": "2024-06-17T11:02:34.827Z",
"modified": "2024-08-15T12:33:44.181Z",
"0.75.0": "2024-06-14T17:10:22.041Z",
"0.76.0-nightly-202487-8f93044": …
```
> feat: determine react-native → template from npm registry data

- packages/cli/src/commands/init/init.ts
Summary:
---------
The problem I noticed was that when I specified the wrong template, the error wording was funny.
```
$ react-native init TestProduct --template typescript
Welcome to React Native!                
Learn once, write anywhere               
✔ Downloading template
⠋ Copying templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.
```
However, looking at the source code, this issue as well as many other errors are not displayed correctly.
The error handling part of cocoapods seems to be wrong.
Moved pods error handling out of the way of the others, and added additional unknown error handling. …
> fix: Correctly display errors in react-native init

- __e2e__/init.test.ts
Summary:
---------
`react-native-macos` stopped shipping `template.config.js` in the latest release and it caused our current test suite to fail, in the nearest future we should revisit logic for mapping template location for supported OOT platforms.
Test Plan:
----------
CI green
Checklist
----------
> ci: disable `react-native-macos` test

- __e2e__/init.test.ts
- docs/commands.md
- docs/init.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
The `--npm` flag in `init` command has been deprecated for more than a year now in favor of using `--pm` flag. Since `npm` will become a default package manager when initializing new project (#2503), I think it's a good time to remove this flag.
Test Plan:
----------
1. Run `init` command locally and use `--npm` flag
2. Verify error is displayed:
```
error: unknown option '--npm'
(Did you mean --pm?)
```
Checklist
----------
> chore: remove deprecated --npm flag

- __e2e__/init.test.ts
- docs/init.md
- packages/cli/src/commands/init/index.ts
- packages/cli/src/commands/init/init.ts
Summary:
---------
After discussing it internally, we decided to make npm a default package manager for projects created with `init`. `yarn` in version >= 3 generates a lot of issues and makes the first experience with React Native worse.
Test Plan:
----------
1. Run `init` command locally
2. Once the process is complete, verify `package-lock.json` is in the folder, and there is no `yarn.lock` file
Checklist
----------
> chore: set npm as default package manager to init

- packages/cli-config/src/__tests__/findDependencies-test.ts
- packages/cli-config/src/findDependencies.ts
Summary:
---------
`config` currently ignores `peerDependencies` and instead reads `devDependencies`, leading to missing dependencies.
Resolves #2419.
Test Plan:
----------
In any project, run the following:
```
yarn add @react-native-webapis/web-storage@0.2.6
cd node_modules/@react-native-webapis/web-storage
yarn react-native config
```
Checklist
----------
> fix(cli-config): include peer dependencies when finding dependencies

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-platform-apple/src/tools/prompts.ts
Summary:
---------
In https://github.com/react-native-community/cli/pull/2162 I added preferred device feature - it saves device id to cache, and then when running `run-ios` command it'll push preferred device to the beginning. 
For some strange reason, we only enabled this for `--interactive` or `--list-devices` mode. In this Pull Request preferred device is also in default mode. 
Test Plan:
----------
2. Run `run-ios --interactive` pick a simulator
3. Open bunch other simulators
4. Run this command:
```sh
```
5. It should pick one that was selected in the interactive …
> fix: use preferred device in default mode

- package.json
- packages/cli-link-assets/package.json
- packages/cli-link-assets/src/tools/helpers/font/androidFontAssetHelpers.ts
- scripts/build.js
- scripts/linkPackages.js
Summary:
---------
`link-assets` package was using `glob` dependency that was not declared. Replaced it with `fast-glob`. Done the same for local scripts too and removed the `glob` entirely.
Test Plan:
----------
Green CI, please test locally
Checklist
----------
> chore: use fast-glob for link-assets and scripts

- packages/cli-tools/package.json
Summary:
---------
`prompts` is used in `cli-tools`, but never declared as a dependency, causing commands to fail in pnpm setups:
```
Error: Cannot find module 'prompts'
Require stack:
- /~/node_modules/.store/@react-native-community-cli-tools-npm-14.0.1-fb5b1d1033/package/build/prompt.js
- /~/node_modules/.store/@react-native-community-cli-tools-npm-14.0.1-fb5b1d1033/package/build/index.js
- /~/node_modules/.store/@react-native-community-cli-npm-14.0.1-d30aee3125/package/build/commands/init/errors/InvalidNameError.js
- /~/node_modules/.store/@react-native-community-cli-npm-14.0.1-d30aee3125/package/build/commands/init/validate.js
- /~/node_modules/.store/@react-native-community-cli-npm-14.0.1-d30aee3125/package/build/commands/init/init.js
```
Test Plan:
----------
n/a
> fix(cli-tools): declare dependency on `prompts`

- README.md
This PR updates the documentation and compatibility table to include the latest version of the React Native Community CLI.
- **Updated compatibility table** to include the new version `^15.0.0`, compatible with `react-native ^0.76.0`.
- General revisions to the document to maintain consistency and ensure content is up to date.
These changes keep the documentation in line with the latest versions, as well as providing a clear guide for users who are upgrading their projects to newer versions of React Native.
> docs: update table of versions react native to new version 0.76

- packages/cli/src/commands/init/init.ts
Summary:
---------
New Architecture was enabled by default for React Native 0.76, so inside `init` we should install Cocoapods with New Architecture enabled by default. 
Test Plan:
----------
2. Run `node ~/path/to/cli/packages/cli/build/bin.js init`
3. Press `y` when the prompts ask whether to install Cocoapods
4. "Installing CocoaPods dependencies with **New Architecture**" log should be visible
Checklist
----------
> fix(init): install Cocoapods with New Architecture enabled by default

- packages/cli-platform-android/src/config/__tests__/findLibraryName.test.ts
- packages/cli-platform-android/src/config/findLibraryName.ts
Summary:
---------
While working on the fix for #2542, I discovered that tests intended for build.gradle.kts were actually being run on build.gradle file, so I'm correcting this.
Test Plan:
----------
- Update tests to run correctly on build.gradle.kts files and modify them to pass successfully.
Checklist
----------
> fix: handle libraries using build.gradle.kts files

- __e2e__/config.test.ts
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/index.ts
- packages/cli-config/src/loadConfig.ts
- packages/cli-config/src/readConfigFromDisk.ts
- packages/cli-doctor/src/commands/doctor.ts
- packages/cli-doctor/src/tools/healthchecks/index.ts
- packages/cli-types/src/index.ts
- packages/cli/src/index.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/2167
Add support for ESM inside `react-native.config` file.
Test Plan:
----------
2. Create a new project and add `type: "module"` inside package ✅
3. Create a `react-native.config.mjs` with following content
```sh
export default {
commands: [
{
name: 'hello',
func: () => {
console.log('hello esm');
},
},
],
};
```
4. Run `npx react-native hello` and you should see `hello esm` log.
Checklist
----------
> feat: support ESM in `react-native.config`

- packages/cli-config/src/readConfigFromDisk.ts
Summary:
---------
`loadConfig()` failing with "missing loader for extension":
```
Error: Missing loader for extension "react-native.config.mjs".
at #validateConfig (/~/node_modules/cosmiconfig/dist/ExplorerBase.js:37:23)
at new ExplorerBase (/~/node_modules/cosmiconfig/dist/ExplorerBase.js:25:29)
at new ExplorerSync (/~/node_modules/cosmiconfig/dist/ExplorerSync.js:16:1)
at cosmiconfigSync (/~/node_modules/cosmiconfig/dist/index.js:138:26)
at readConfigFromDisk (/~/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:65:55)
```
Test Plan:
----------
This is enough to trigger the error:
```sh
node -p 'require("@react-native-community/cli").loadConfig({})'
```
Checklist
----------
> fix: `loadConfig()` failing with "missing loader for extension"

- packages/cli-config/src/readConfigFromDisk.ts
Summary:
---------
Part 2 of https://github.com/react-native-community/cli/pull/2549 because I had missed a spot, even though I thought I had tested this properly.
Test Plan:
----------
This is enough to trigger the error:
```
node -p 'require("@react-native-community/cli").loadConfig({})'
```
Checklist
----------
> fix(config): fix `loadConfig()` failing with "missing loader for extension"

- docs/projects.md
- packages/cli-config-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
- packages/cli-config-android/src/config/index.ts
- packages/cli-config-apple/src/config/index.ts
- packages/cli-config/src/schema.ts
- packages/cli-platform-android/src/commands/runAndroid/__tests__/tryLaunchAppOnDevice.test.ts
- packages/cli-types/src/android.ts
Summary:
---------
It was deprecated in 0.74 and currently automatic mechanism is collecting which components to render with old renderer.  
Test Plan:
----------
CI
Checklist
----------
> chore: remove deprecated react legacy components from config

- packages/cli-doctor/src/tools/healthchecks/__tests__/androidSDK.test.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
Summary:
---------
As highlighted in https://github.com/react-native-community/cli/issues/2221, the way some projects (like expo ones) define the `buildToolsVersion` is breaking `react-native doctor`. 
```gradle
buildscript {
ext {
buildToolsVersion = findProperty('android.buildToolsVersion') ?: '34.0.0'
minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '23')
...
```
leads to `buildToolsVersion => .b34.0.0`.
The PR is slightly tweaking the parsing to account for those cases.
Test Plan:
----------
- A new test has been added to demonstrate code is now able to properly read the `buildToolsVersion`
- Existing tests are already covering the basic ` buildToolsVersion = "a version"` syntax
Checklist
----------
- ~~[ ] Documentation is up to date to reflect these …
> fix: be able to read more complex buildToolsVersion definitions

- packages/cli-config-android/src/config/__fixtures__/android.ts
- packages/cli-config-android/src/config/__tests__/findPackageClassName.test.ts
- packages/cli-config-android/src/config/findPackageClassName.ts
Summary:
---------
`TurboReactPackage`  is [deprecated](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/TurboReactPackage.kt) and the advice is to use `BaseReactPackage`. However, the cli does not recognize `BaseReactPackage` as something that should be autolinked, so following the advice actually breaks apps with:
```
com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNCDatePicker' could not be found. Verify that a module by this name is registered in the native binary. Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["HeadlessJsTaskSupport","PlatformConstants","SourceCode","DeviceInfo","UIManager","DeviceEventManager"],"Turb …
```
> fix: support linking of BaseReactPackage subclasses

- .vscode/settings.json
- packages/cli-config/src/__tests__/index-test.ts
- packages/cli-config/src/loadConfig.ts
Summary:
---------
Selecting particular platform wouldn't work for out-of-tree platforms, as extra platforms would be added to the `config.platforms` objects anyway. This PR fixes it and adds tests.
Test Plan:
----------
Added ✅ 
Checklist
----------
> fix: config with --platform flag to work with platforms defined in multiple packages

- packages/cli-tools/package.json
- packages/cli-tools/src/runSudo.ts
- yarn.lock
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2575
Test Plan:
----------
No warnings when installing `@reacty-native-community/cli` package
Checklist
----------
> chore: replace `sudo-prompt` with `@vscode/sudo-prompt`

- packages/cli/src/commands/init/init.ts
Summary:
---------
It's also required for running with `run-ios` :)
> fix: adjust log in install Cocoapods prompt

- packages/cli-server-api/src/index.ts
- packages/cli-server-api/src/indexPageMiddleware.ts
Summary:
---------
Around #2583, I'm taking the opportunity to review the API boundary of the `cli-server-api` package.
- This PR is an opinionated narrowing of the API exported by this package.
- Functionally, `indexPageMiddleware` is moved into the middleware stack returned by `createDevServerMiddleware`.
Test Plan:
----------
✅ Builds
✅ GitHub-wide code search to look for references to these imports outside of `react-native`.
Checklist
----------
> breaking: Remove secondary exports of cli-server-api

- packages/cli/src/tools/npm.ts
Summary:
---------
fixes: #2519
Official npm registry url is hardcoded, the "cli" can't run successfully in a closed environment.
Following error is displayed when running `npx @react-native-community/cli@latest init AwesomeProject --verbose`.
```
error fetch failed.
TypeError: fetch failed
at node:internal/deps/undici/undici:13178:13
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async getTemplateVersion (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/tools/npm.js:121:16)
at async createTemplateUri (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/version.js:53:29)
at async createProject (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-nativ …
```
> fix: Remove hardcoded npm registry url 

- packages/cli-doctor/package.json
- packages/cli-doctor/src/tools/healthchecks/common.ts
- yarn.lock
Inspired by https://github.com/eslint/eslint/pull/18982
This API is built-in since node 16.11. react-native-cli already requires node 18 as of last year.
> refactor: replace strip-ansi with native module

- packages/cli-platform-apple/src/commands/runCommand/__tests__/getBuildPath.test.ts
- packages/cli-platform-apple/src/commands/runCommand/getBuildPath.ts
Summary:
---------
it appears targetBuildDir var now has `-maccatalyst` in it before it gets to this method, so no need to add it again
This was tweaked in #2312 but appears to have regressed again - are macCatalyst builds checked in CI 🤔 ?
Without this change, the path is incorrect (note the duplicate `-maccatalyst` in path):
```
Error: spawn /Users/mike/Library/Developer/Xcode/DerivedData/rnfbdemo-gsuyjvwnbefbzvbfqtovnhthepew/Build/Products/Debug-maccatalyst-maccatalyst/rnfbdemo.app/Contents/MacOS/rnfbdemo ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:284:19)
at onErrorNT (node:internal/child_process:477:16)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
at ChildProcess._handle.onexit …
```
> fix(macCatalyst): construct correct path for executable

- .github/PULL_REQUEST_TEMPLATE.md
Clarify the requirement to test CLI changes with a local `react-native` checkout for new PRs, by pointing to the existing instructions.
- This aims to reduce ambiguity / enable self-serve in more cases, e.g. https://github.com/react-native-community/cli/pull/2491.
—
> chore: Link to test setup in PR template

- packages/cli-platform-apple/src/tools/__tests__/getBuildConfigurationFromXcScheme.test.ts
- packages/cli-platform-apple/src/tools/getBuildConfigurationFromXcScheme.ts
This improves and clarifies the error message printed by React Native CLI when the shared scheme file is missing.
I recently attempted to run an app with `yarn ios`, and received an error:
```
error Could not find scheme MyApp. Please make sure the schema you want to run exists. Available schemas are: MyApp'.
```
Subsequently I spent 1h+ digging through the code and local caches etc trying to figure out where that mysterious trailing apostrophe originated from (note, it mentions `MyApp'` is available, but it is looking for `MyApp`). It was nowhere to be found. As it turned out, the issue was with how RN CLI formatted the error.
Additionally, the existing error message makes it sound like the first reference to "MyApp" is directly related to or equivalent to the second reference. That's …
> Improve and clarify error for missing scheme file

- packages/cli-config-apple/src/__tests__/pods.test.ts
- packages/cli-config-apple/src/tools/pods.ts
- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-tools/src/cacheManager.ts
Summary:
---------
Comparing only `dependencies` field from `config`'s command output takes into account only autolinked dependencies, however users can add manually Pods inside `Podfile`, in this Pull Request I added validating hash for `Podfile` and `Podfile.lock`. 
Test Plan:
----------
2. Create `react-native.config.js` and enable [automaticPodsInstallation](https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectiosautomaticpodsinstallation) 
3. Whenever `Podfile` or `Podfile.lock` content changes installation of Cocoapods should be triggered
```sh
node /path/to/react-native-cli/packages/cli/build/bin.js …
```
> fix(apple): include check if `Podfile` and `Podfile.lock` changed when deciding to install Cocoapods 

- packages/cli/src/index.ts
`@react-native/community-cli-plugin` depends on `createDevServerMiddleware` from `@react-native-community/cli-server-api`. `@react-native/community-cli-plugin` currently [declares an optional peer dependency](https://github.com/facebook/react-native/blob/bae895500052bda2f55e1832b0c8a63a1b449de3/packages/community-cli-plugin/package.json#L39-L45) on `@react-native-community/cli-server-api`, however because the latter isn't a dependency of `react-native` or the community template, the peer dependency is not available to package managers that enforce isolated node_modules - see https://github.com/facebook/react-native/issues/47309.
Rather than add an unnecessary dependency to the template (https://github.com/react-native-community/template/pull/105), my proposal is to have …
> feat: Export `createDevServerMiddleware` from `cli`

- docs/projects.md
- packages/cli-config/src/schema.ts
In https://github.com/react-native-community/cli/pull/2116 we introduced opt-in way to install Cocoapods in `run-ios` commands, this PR changes that to be opt-out.
With empty `react-native.config.js` Cocoapods should still install.
> feat: install Cocoapods by default in all projects

- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
👋, I am working on adding OOT (Out-of-tree) CLI support to `react-native-tvos`. The update went well, and the OOT will soon have `build-`, `run- `, and `log-` commands for tvos.
**However**, the wrong simulator is selected.
This bug is unique to the tvos platform. When passing the `--simulator` parameter, the **first device** is always chosen, and the simulator parameter is **ignored**.
**tl;dr**
The wrong simulator is selected when the platform is tvos.
While the fix is straightforward, testing takes a little setup. I created a sample RNTV project for testing and validating this change.
**Pre-requisites**
Xcode is installed, and at least two simulators are installed. The trick to reproducing the issue is to select a simulator that is not first in the device list. 
In this example, I have …
> fix: Use 'fallback simulator' for tvOS

- CONTRIBUTING.md
While reviewing the contributing guidelines, I noticed some minor formatting and spelling issues that could be improved:
- The numbered lists in several sections use repeated "1." instead of sequential numbering (2, 3, 4)
- "Chose" is used instead of "Choose" in the publishing workflow section
This PR fixes these small issues to improve readability of the documentation.
Documentation-only change that doesn't require functional testing. I've visually verified that the Markdown renders correctly with these changes.
*(Not applicable as this is a documentation-only change)*
> docs: fix numbered lists and spelling in CONTRIBUTING.md

- packages/cli/src/commands/init/init.ts
In #2602 we enabled installing Cocoapods by default, so it doesn't make longer sense to log an information how to enable it in `react-native.config.js`
> fix: remove cocoapods log from `init` command

- __e2e__/__snapshots__/config.test.ts.snap
- packages/cli-platform-apple/src/commands/buildCommand/buildOptions.ts
- packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts
- packages/cli-platform-apple/src/commands/runCommand/createRun.ts
- packages/cli-platform-ios/README.md
Adds `--only-pods` option
1. `yarn ios --only-pods` should just install Cocoapods`
> feat: add `--only-pods` option to `run/build-ios` commands

- docs/dependencies.md
> Update dependencies.md to mention deprecation of `.android.componentDescriptors`

- package.json
This PR adds `packageManager` field to `package.json`, allowing users of Corepack (and perhaps other tools in the future) who already use a different version of Yarn to easily start contributing to the project.
1. Enable Corepack by running `corepack enable`
2a. Try installing this repo. Latest version of Yarn is going to be used; 4.7.0 at the moment of writing.
2b. With this change applied, Corepack asks to install the latest Yarn Classic (1.22.22) and when the user agrees, it correctly installs the repository using Yarn Classic.
> chore: specify `packageManager` in `package.json`

- packages/cli-config-apple/src/tools/installPods.ts
- packages/cli-config-apple/src/tools/runBundleInstall.ts
- packages/cli-doctor/src/tools/healthchecks/androidSDK.ts
- packages/cli-doctor/src/tools/healthchecks/androidStudio.ts
- packages/cli-doctor/src/tools/healthchecks/jdk.ts
- packages/cli-doctor/src/tools/healthchecks/ruby.ts
- packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
- packages/cli-tools/src/__tests__/doclink.test.ts
This fixes some of the link that the CLI is outputting to users.
Specifically instead of pointing users to:
https://reactnative.dev/docs/environment-setup
we should point them to
https://reactnative.dev/docs/set-up-your-environment
Tests are updated
> fix: Update link to set-up-your-environment emitted by the CLI

- __e2e__/config.test.ts
- packages/cli-config-android/src/config/__fixtures__/android.ts
- packages/cli-config-android/src/config/__tests__/__snapshots__/getProjectConfig.test.ts.snap
- packages/cli-config-android/src/config/__tests__/findBuildGradle.test.ts
- packages/cli-config-android/src/config/findBuildGradle.ts
- packages/cli-config-android/src/config/index.ts
Not all apps have `app` dir and we already have a config for that, which was not used by the `findBuildGradle` helper. 
Closes https://github.com/react-native-community/cli/pull/2524
Closes https://github.com/react-native-community/cli/issues/2516
Updated tests
> fix(android): hardcoded appName when finding build.gradle

- __e2e__/__snapshots__/config.test.ts.snap
- __e2e__/config.test.ts
Config E2E tests run `init` with an unspecified version in `beforeEach`, so that they run against latest stable. But the "shows up current config" snapshot test includes the version number, so snapshot tests fail whenever a new RN version is published.
This uses the existing convention of normalising variable output to `<<REPLACED>>`, just validating that the version is a semver-stable string.
CI - snapshot test passes (🤞)
> test: Replace variable RN version in snapshot tests

- scripts/buildTs.js
This PR fixes a bug in `buildTs.js` that caused the script to crash when ran from a directory full path of which contained space(s). I discovered that when I cloned the repository to "Open source projects" directory.
1. Clone this repository to any directory full path of which contains space(s).
2. Install the repository.
2a. Without this PR, build will crash on `buildTs.js`.
2b. With this PR, build will succeed.
> chore: fix `buildTs.js` crashing on paths containing spaces

- packages/cli-config-android/src/config/findComponentDescriptors.ts
- packages/cli-config-android/src/config/findManifest.ts
- packages/cli-config-android/src/config/findPackageClassName.ts
- packages/cli-config-apple/src/config/findAllPodfilePaths.ts
- packages/cli-config/src/commands/config.ts
There are multiple parts of auto linking that are slow, so I made a quick perf pass to reduce the time CLI spends on searching for native files. The biggest gain comes from optimizing `findComponentDescriptors` to use `jsSrcsDir`. For a small project with 7 common native dependencies the linking time goes from ~300ms to ~80ms. Perf and gains are bigger with more dependencies, so it's hard to asses the raw %.
|before|after|
|--|--|
|<img width="601" alt="Screenshot 2025-06-05 at 09 48 31" src="https://github.com/user-attachments/assets/e2a21b31-8a2d-4536-8c14-6e67c5c72bc1" />|<img width="610" alt="Screenshot 2025-06-05 at 09 49 29" src="https://github.com/user-attachments/assets/f67ef5cf-aee9-46e9-9337-cddcda89e0d9" />|
Changes are scoped to smaller commits:
* cdabe1cf - remote …
> perf: improve auto linking performance 

- packages/cli-tools/src/startServerInNewWindow.ts
This PR fixes an issue on macOS where the server wasn't reliably being launched in a new terminal window. The solution involves using the `-na` flag combination with the `open` command instead of just `-a`, which ensures that a new instance of the terminal application is always created.
As per the man entry for `open`:
```man
DESCRIPTION
The open command opens a file (or a directory or URL), just as if you had double-clicked the file's icon. If no application name is specified, the default application as determined
via LaunchServices is used to open the specified files.
[...]
-n  Open a new instance of the application(s) even if one is already running.
```
The issue was identified in a [Ghostty discussion](https://github.com/ghostty-org/ghostty/discussions/4839) which pointed out that …
> fix: force server to always start in a new window on macOS

- packages/cli-config-apple/src/tools/pods.ts
- packages/cli-config-apple/src/tools/runCodegen.ts
- packages/cli/src/commands/init/init.ts
While testing RN 0.81.0-rc.2, we discovered that the CI was not outputting the code generated by codegen in the right folder.
Further exploration revealed that the problem has been there since 0.79!
This PR addresses the problem.
Tested by manually modifying the CLI code in a new project created from 0.81
> fix: output codegen'd code in the ios folder

- packages/cli-config-apple/src/tools/installPods.ts
- packages/cli-config-apple/src/tools/pods.ts
see https://github.com/react-native-community/cli/issues/2668 and https://github.com/react-native-community/cli/issues/2663 (should fix both).
This change ensures that local installed cocoapods (`bundle exec pod`) is used before system installed `pod`. 
1. make sure no cocoapods is not installed globally: `gem uninstall cocoapods`
2. `npx @react-native-community/cli@latest init MyApp`
3. press `n` for cocoa pods question
4. `cd MyApp`
5. `bundle install`
Now `bundle exec pod --version` has an 0 exit code.
`npx react-native run-ios --force-pods` will not fail nor install cocoapods globally (`pod` will have exit code > 0)
1. make sure cocoapods is installed globally: `gem install cocoapods`
2. `npx @react-native-community/cli@latest init MyApp`
3. press `n` for cocoa pods question
4. `cd …
> use pod installed by bundler if possible

- packages/cli-tools/src/startServerInNewWindow.ts
Fixes #2696. Reverts #2628.
A change was made in #2628 to work around a bug in Ghostty by forcing a new _process_ to open in the default terminal app by adding the following option to the macOS `open` command:
`-n  Open a new instance of the application(s) even if one is already running.`
This means that, in iTerm at least (and likely others), an entirely new dock icon will appear, which prevents switching between existing iTerm windows and this new one using the typical `cmd+~` keyboard shortcut.
Furthermore, iTerm has overrides that allow you to open in a tab instead of a window when the command is `open -a`, but it can't do anything to override open `open -na` because of the fact that it launches an entirely separate _process_, not just _window_. (Side note: I would love to understand …
> Return to less intrusive way of starting server in a new window on macOS
