react-native-community/cli

packages/local-cli/package.json
=> feat: restrict Node with engineStrict

packages/local-cli/link/__tests__/ios/addFileToProject-test.js
Fixes a the skipped test for `addFileToProject`.
=> Fix skipped test for add file to project

packages/cli/package.json
=> chore: use babel --copy-files flag

packages/cli/.npmignore
One more followup to #104.
I also excluded `__mocks__` from publishing for obvious reasons.
Output of `npm pack`:
<details>
```
npm notice
npm notice 📦  @react-native-community/cli@1.0.1
npm notice === Tarball Contents ===
npm notice 2.0kB   package.json
npm notice 341B    .babelrc.js
npm notice 181B    setup_env.bat
npm notice 257B    setup_env.sh
npm notice 653B    build/bin.js
npm notice 1.9kB   build/bundle/assetPathUtils.js
npm notice 2.5kB   build/bundle/buildBundle.js
npm notice 742B    build/bundle/bundle.js
npm notice 2.6kB   build/bundle/bundleCommandLineArgs.js
npm notice 1.1kB   build/bundle/filterPlatformAssetScales.js
npm notice 624B    build/bundle/getAssetDestPathAndroid.js
npm notice 520B    build/bundle/getAssetDestPathIOS.js
npm notice 637B    build/bundle/log.js
npm …
```
=> chore: don't publish src now that we build it

packages/cli/src/util/logger.js
=> feat: add logger

packages/cli/package.json, packages/cli/src/link/__tests__/link-test.js, packages/cli/src/link/ios/createGroupWithMessage.js, packages/cli/src/link/ios/unlinkAssets.js, packages/cli/src/link/link.js, packages/cli/src/link/linkAll.js, packages/cli/src/link/linkAssets.js, packages/cli/src/link/linkDependency.js, packages/cli/src/link/unlink.js
Also simplified Jest config for `cli` project
Relates to https://github.com/react-native-community/react-native-cli/issues/95
=> feat: add logger to link command

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
Add issue and PR templates.
Fixes: #70 
cc. @grabbou @thymikee
=> docs: add issue and PR templates

packages/cli/package.json, yarn.lock
=> build: update xcode version to 2.0.0

packages/cli/src/link/ios/getTargets.js
Summary:
---------
Making prettier happy C:
=> fix: make prettier happy

README.md
Summary:
---------
Adding some more information to the main README. 
`packages/cli` still needs a proper README with all commands listed, but that's not in scope of this PR
=> docs: update repository README

README.md, packages/cli/src/cliEntry.js, packages/cli/src/core/getCommands.js, packages/cli/src/core/getPlatforms.js, packages/cli/src/core/types.flow.js, packages/cli/src/index.js, packages/cli/src/install/install.js, packages/cli/src/install/uninstall.js, packages/cli/src/link/__tests__/link-test.js, packages/cli/src/link/getDependencyConfig.js, packages/cli/src/link/getProjectDependencies.js, packages/cli/src/link/link.js, packages/cli/src/link/linkAll.js, packages/cli/src/link/linkAssets.js, packages/cli/src/link/linkDependency.js, packages/cli/src/link/unlink.js, packages/cli/src/runAndroid/tryLaunchAppOnDevice.js, packages/cli/src/server/runServer.js, packages/cli/src/upgrade/upgrade.js, packages/cli/src/util/assertRequiredOptions.js, packages/cli/src/util/loadMetroConfig.js, packages/cli/src/util/logger.js
Summary:
---------
Test Plan:
----------
=> feat: better logging for install/uninstall; less spawning; fix unlinking

packages/cli/src/link/unlink.js
Summary:
---------
Fix `unlink` error from this comment: https://github.com/react-native-community/react-native-releases/issues/79#issuecomment-464082880
Test Plan:
----------
Try unlinking any dependency
=> fix: unlink not working

packages/cli/src/generator/templates.js
Summary:
---------
Fix #184 
Test Plan:
----------
The test case is now correct.
=> Allow absolute path for templates

packages/cli/setup_env.bat, packages/cli/src/cliEntry.js
Summary:
---------
Likely fixes #164 by wrapping the `spanwSync` call in a try/catch.
cc @Kielan
Test Plan:
----------
It works™
=> fix: setup_env script failure

packages/cli/src/link/link.js, packages/cli/src/link/linkAll.js
Summary:
---------
Some error messages direct the user to file a new issue. Update the URL to link to the community repository instead.
Test Plan:
----------
Did not test as it's a string replacement.
=> Update issue tracker link

.flowconfig, package.json, packages/cli/src/cliEntry.js, packages/cli/src/core/getPackageConfiguration.js, packages/cli/src/core/types.flow.js, packages/cli/src/server/util/launchChrome.js, packages/cli/src/util/loadMetroConfig.js, yarn.lock
Summary:
---------
It's usually better to be on the latest available :D 
Test Plan:
----------
Green CI
=> chore: bump flow to 0.94

packages/cli/src/commands/server/middleware/getDevToolsMiddleware.js
Summary:
---------
PR #52 were supposed to add ESLint to the project but due to [these changes](https://github.com/react-native-community/react-native-cli/pull/52/files#diff-c4b441f65f8822889a54a29511244eef) `customDebugger` function were accidentally (I guess) deleted that led to this issue: https://github.com/Microsoft/vscode-react-native/issues/936 then.
This PR reverts those changes and fixes regression. I renamed `customDebugger` to `startCustomDebugger` to avoid lint problems.
Test Plan:
----------
* `yarn flow`, `yarn lint`, `yarn test` commands show no errors/failed tests;
* I tested this on our [vscode-react-native](https://github.com/Microsoft/vscode-react-native) extension and it fixed our issue.
=> Bring back lost customDebugger function

packages/cli/src/commands/upgrade/__tests__/upgrade.test.js, packages/cli/src/commands/upgrade/upgrade.js
Summary:
---------
I tested without adding any remotes when upgrading, and it seems to be working fine, nothing I saw was affected.
It is based on #242, and it addresses #244.
Test Plan:
----------
Try to upgrade a rn project.
=> refactor: don't add purge as remote when upgrading

packages/platform-ios/src/commands/runIOS/index.js
Summary:
---------
Refactor `run-ios` for readability and better error messages:
Followup to #310 cc @lucasbento 
Test Plan:
----------
Verified that following commands work properly:
- `run-ios`
- `run-ios --device`
- `run-ios --device phone-name`
- `run-ios --uuid asd123`
=> chore: refactor `run-ios` for readability and better error messages

packages/cli/src/commands/init/__tests__/template.test.js, packages/cli/src/commands/init/init.js, packages/cli/src/commands/init/template.js, packages/cli/src/tools/packageManager.js
Summary:
---------
Installs template sources inside temporary directory and removes it after operation is done or failed.
Fixes #277
Test Plan:
----------
Tests yet to be added.
=> feat: support init inside monorepos

docs/autolinking.md
Summary:
---------
I saw someone once try do this in a Podspec, and figure this is a good place to warn about it.
=> Update autolinking.md docs for iOS

packages/cli/src/commands/init/init.js
Summary:
---------
Fixing regression after #320 
Test Plan:
----------
```
node ../path/to/cli/build/ init FromGithub --template https://github.com/Esemesek/react-native-new-template
```
=> fix: init from url

packages/cli/src/commands/init/__tests__/templateName.test.js, packages/cli/src/commands/init/init.js, packages/cli/src/commands/init/templateName.js
Summary:
---------
There's some duplication around the logic of creating from template. This PR aims to resolve it.
@Esemesek please have a close look at this one, especially around installing from version
Test Plan:
----------
Green CI.
=> fix: refactor init for less duplication; fix handling versioned templates

.prettierrc.js
Summary:
---------
vscode picks up this config but it is incomplete so I added the same one as the RN repo. I also removed the comment since it is not really relevent anymore since it is a full config.
Test Plan:
----------
N/A
=> chore: Update prettier config

packages/platform-android/src/link/warnAboutManuallyLinkedLibs.js, packages/platform-ios/src/link/warnAboutManuallyLinkedLibs.js
=> chore: fix grammar in warning

docs/autolinking.md
Summary:
---------
Used http://www.hemingwayapp.com/ to improve the readability.
=> chore(docs): simplify autolinking

packages/cli/src/commands/init/init.js, packages/cli/src/commands/init/printRunInstructions.js
=> Fix project directory name in run instructions

packages/cli/src/commands/init/printRunInstructions.js
=> fix: shorter and correct paths in init run instructions

docs/dependencies.md
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/529
=> chore: better description for `sourceDir` config

packages/platform-ios/native_modules.rb
Attempt at streaming output in ruby in the same way it is currently being done in the gradle setup.
Fixes https://github.com/react-native-community/cli/issues/576
=> fix: stream config output in ruby script

packages/platform-android/native_modules.gradle
Summary:
---------
Small update / optimization for the code generation inside the gradle script. 
Related to https://github.com/react-native-community/cli/issues/600 and https://github.com/react-native-community/cli/pull/602
Test Plan:
----------
Tested in newly initialised project and with a Kotlin project
`react-native init test && cd test && react-native run-android`
=> imp: optimize gradle code generation

docs/autolinking.md
where to use `use_native_modules`, update every pod path, and updated
example
Summary:
---------
This is for developers who are not familiar with CocoaPods.
=> docs(autolinking): Monorepos

docs/commands.md
https://github.com/react-native-community/cli/pull/588#discussion_r313600324
=> fix docstring

packages/cli/src/commands/init/banner.js
Summary:
---------
Improved colors
Test Plan:
----------
yolo
=> Update banner colors

packages/cli/package.json, yarn.lock
=> chore: Bump semver to 6.3.0

packages/cli/src/commands/doctor/healthchecks/packageManagers.js, packages/cli/src/commands/doctor/healthchecks/watchman.js, packages/cli/src/tools/brewInstall.js, packages/cli/src/tools/install.js
Summary:
---------
Try installing some packages with Homebrew. For other platforms, or if Homebrew is missing, point the user in the right direction.
Test Plan:
----------
Uninstall Yarn and Watchman, and run `doctor`. It should install both when asked.
=> feat(doctor): Try installing packages with Homebrew

packages/cli/src/tools/installPods.js
Summary:
---------
Mainly just to make it a bit more grammatically correct English
Test Plan:
----------
NOOP
=> Update user-facing message in installPods.js 

.github/ISSUE_TEMPLATE/bug_report.md
Summary:
---------
Correct `bug report` label in issue template.
Test Plan:
----------
NOOP
=> fix: change template label

package.json, packages/platform-android/src/link/index.ts, yarn.lock
Summary:
---------
Good to be on the latest, especially that nothing breaks 🎉 	
Test Plan:
----------
Green flow
=> chore: bump Flow to 0.107

packages/cli-types/package.json, packages/cli/package.json, packages/cli/tsconfig.json, packages/platform-android/package.json, packages/platform-ios/package.json
Summary:
---------
Will make it easier for folks to contribute since we need this in every PR
Test Plan:
----------
CI
=> chore: setup TS infra for cli package

packages/cli/src/cliEntry.js, packages/cli/src/tools/assertRequiredOptions.ts
Summary:
---------
Part of #683 
Converted `commands/tools/assertRequiredOptions.js` to typescript
Test Plan:
----------
`yarn test`
=> chore: convert assertRequiredOptions to TS

packages/cli/src/commands/index.ts, packages/cli/src/commands/install/install.ts, packages/cli/src/commands/install/uninstall.ts
Summary:
---------
Part of #683
Converted commands/install/* to typescript
Test Plan:
yarn test
=> chore: converted install command to typescript

docs/commands.md
Summary:
---------
Update docs according to #495
=> chore: template shorthands are no longer supported

README.md
Summary:
---------
This PR is part of https://github.com/react-native-community/.github/issues/45 to add `Lean Core Extracted` badge to packages in `react-native-community` that has been extracted from [Lean Core](https://github.com/facebook/react-native/issues/23313)
=> docs: add Lean Core Extracted badge in README

packages/platform-ios/src/link/warnAboutPodInstall.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/797
Test Plan:
----------
CI
=> fix: check for podspecPath in warnAboutPodInstall

package.json, yarn.lock
Summary:
---------
Bumping TS to latest. Seems like an easy win.
Test Plan:
----------
CI passes
=> chore: bump TS to 3.7

docs/commands.md
Summary:
---------
I haven't updated the entire documentation while removing legacy `link`. I am doing it now.
=> chore: update documentation

packages/cli/package.json
Summary:
---------
No need to make users install these deps, as they're development only for us.
Test Plan:
----------
CI passes
=> chore: move DT types to dev deps

README.md
Summary:
---------
Keeping it up to date.
Test Plan:
----------
Markdown renders correctly?
=> docs: update compatibility table

.circleci/config.yml, packages/platform-ios/native_modules.rb
As file is using `Pod`, cocoapods should be imported.
Summary:
---------
This PR might solve this issue: https://github.com/CocoaPods/Core/issues/601
=> fix: add cocoapods requirement

packages/platform-ios/src/commands/runIOS/index.ts
=> fix: better message when can not get simulator list from Xcode

__e2e__/init.test.ts, docs/commands.md, packages/cli/src/commands/init/init.ts
=> fix: respect --directory in init run instructions

packages/cli/package.json, packages/cli/src/index.ts, yarn.lock
Summary:
---------
Suggest matching commands if the user makes a typo.
closes #905 
This is how it goes:
----------
=> feat(chore): Recommend matching commands

packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Currently when building using the react-native-cli the derived data path is in the `ios/build` folder while in xcode it is in `~/Library/Developer/Xcode` by default. This means builds started from xcode and the cli don't share the same cache. This results in longer builds and more disk space usage (xcode build cache size is no joke 😄) when using both xcode and the cli.
While it is possible to have xcode build in a different directory I think it is better to use the derived data path specified in the project instead of forcing one.
Before we relied on hardcoding the path to launch the app in the simulator or on device. Now we use `xcodebuild` with `-showBuildSettings` to print the build configuration and get the `TARGET_BUILD_DIR` env variable which is the path where the …
=> Use default derived data path for runIOS command

README.md
Summary:
---------
I find quite a bunch of developers are not familiar with how lock files work. A small example should help them figure out what it takes to update a transitive dependency. I wish there was a built in way to do this through yarn and npm. Please let me know if such exist.
Test Plan:
----------
None
=> docs: improve "Updating CLI" to be less confusing

__e2e__/didYouMean.test.ts, __e2e__/validations.test.ts
Summary:
---------
Follow up of #1001 
Test Plan:
----------
Covers the test case for #960
=> chore: test case for command suggestion feature

jest/helpers.ts, package.json, packages/cli/package.json, packages/platform-android/package.json, packages/platform-ios/package.json, packages/tools/package.json, yarn.lock
Summary:
---------
v3 comes with nice runtime perf improvements
Test Plan:
----------
CI
=> chore: upgrade chalk to v3

.eslintignore, babel.config.js, package.json, packages/cli/src/tools/installPods.ts, packages/platform-ios/src/commands/runIOS/index.ts, yarn.lock
Summary:
---------
Regenerating yarn.lock with latest packages. Results in smaller builds (301MB vs 482MB)
Test Plan:
----------
Happy CI
=> chore: regenerate lock file

.vscode/extensions.json, .vscode/settings.json
Summary:
---------
Autofix is enabled by default, we don't use Flow anymore
=> chore: update vscode settings

packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
The fix is included in RN 0.61: https://github.com/facebook/react-native/commit/a162554f5dc36fa0647b5bf52119a62bd20046e3
Ref: https://github.com/react-native-community/cli/pull/489
Test Plan:
----------
cc @thecodrr
=> chore: revert temporary fix for #484

packages/cli/setup_env.sh
Summary:
---------
https://github.com/react-native-community/cli/issues/1090
=> Imp: change shebang in `setup_env.sh`

packages/cli/package.json, yarn.lock
[pretty-format](https://www.npmjs.com/package/pretty-format) provides it's own type definition.
=> chore: remove stale type definition

packages/cli/src/commands/doctor/healthchecks/__tests__/androidSDK.test.ts
Summary:
---------
On Windows CI tests could be run from the root of a disk (e.g. D:\\) and
causing permission issues. This PR uses the OS temp directory to create
a new one and use it as the project root to avoid this problem.
Test Plan:
----------
CI should be ✔, at least for the `androidSDK` tests.
=> fix: androidSDK windows tests

docs/commands.md, docs/projects.md, packages/platform-android/src/commands/runAndroid/index.ts
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/1154
Test Plan:
----------
CI
=> fix: bring back --appId flag; fix wrong appName instructions

__e2e__/init.test.ts
Summary:
---------
Follow up of #1143 
Test Plan:
----------
This PR adds a test case for the recently landed feature (CLI flag).
=> tests: e2e test case for init with --skip-install flag

packages/cli/src/tools/generator/templates.ts
Summary:
---------
`createProjectFromTemplate` no longer accepts `yarnVersion`.
Test Plan:
----------
No code changes have been done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/react-native-community/cli/1184)
=> chore: remove unused param in method documentation

packages/cli/src/commands/doctor/doctor.ts, packages/cli/src/commands/doctor/healthchecks/androidSDK.ts
Summary:
---------
Fixes #1190 caused by #1183
Test Plan:
----------
Not sure about JDK fail, but likely not related.
=> fix: detached doctor; add a warning

docs/autolinking.md
Summary:
this little PR update link `Podfile ` example,  i think version 0.60 it's very old so i change for the recent version.!
=> add new version RN Podfile link, autolinking docs.

docs/commands.md, docs/init.md, packages/cli/src/commands/init/__tests__/templateName.test.ts, packages/cli/src/commands/init/templateName.ts
Summary:
---------
closes #1163 
Test Plan:
----------
Added a unit test case.
=> feat: template option in the format of username/repo

__e2e__/unknown.test.ts
Summary:
---------
Supplying an unknown command returns an exit code of 1, updated the existing test cases.
Test Plan:
----------
Updated the existing test cases.
=> tests: assert for exit code

.eslintrc.js, package.json, packages/cli-hermes/src/profileHermes/downloadProfile.ts, packages/platform-android/src/utils/getAndroidProject.ts, packages/platform-ios/src/commands/runIOS/parseIOSDevicesList.ts, yarn.lock
Summary:
---------
Update eslint to v7 and resolve lint warnings
Test Plan:
----------
- eslint passes without error
- testcase passes
=> chore: update eslint

packages/cli/src/tools/config/__tests__/index-test.ts, packages/platform-ios/src/commands/runIOS/parseXctraceIOSDevicesList.ts
Summary:
---------
Test Plan:
----------
=> chore: fix linter warnings

docs/commands.md
Summary:
---------
Follow up of #1328
Test Plan:
----------
N/A
=> docs: update commands argument types to match source

packages/cli/src/tools/__tests__/loadMetroConfig-test.ts, packages/cli/src/tools/loadMetroConfig.ts
Summary:
---------
Cherry pick #1328 into 4.x
Test Plan:
----------
Manual testing sample app
=> feat: default to enableOptionalDependencies: true in metro config

package.json, yarn.lock
Summary:
---------
Let's be on the latest.
Test Plan:
----------
CI
=> chore: bump lerna to 3.22

packages/platform-ios/src/commands/runIOS/index.ts
this PR update iPhone simulator descriptions.!
=> chore: update iPhone simulators priority for run-ios

packages/cli/src/commands/start/watchMode.ts
Summary:
---------
Test Plan:
----------
=> fix(cli): display watch mode instructions

packages/cli/src/commands/init/editTemplate.ts, packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
Summary:
---------
After adding `_editorconfig` in the template for 0.64.0, we should have the cli move it correctly.
(We need a better way for these files than manually 😬)
Test Plan:
----------
=> add editorconfig for the template

README.md
Summary:
---------
Let's unblock 0.65 already
Test Plan:
----------
=> chore: update compat table for RN 0.65

packages/platform-ios/src/commands/runIOS/index.ts
Summary:
---------
This implements #1448
`run-ios` was not opening the Catalyst app after building.  This was due to two problems,
which are addressed in this pull request:
* app target path was incorrect (needs to include -maccatalyst)
* `ios-deploy` is the wrong tool to open a macos application
Test Plan:
----------
To test, I have activated Catalyst on a basic React-Native app and used `run-ios` to build and target my development machine by either the `--device` or `--udid` arguments.  Once the build is complete, the app is opened on the machine and the script is closed.
=> feat(cli-platform-ios): Use run-ios to open Catalyst app after building

docs/autolinking.md
Summary:
---------
this PR update link to redirect Podfile file with new version.
Test Plan:
----------
=> docs: update link redirect new Podfile file version.

README.md
Summary:
---------
Add 6.1.0 release and react native 0.66.x to compatibility table
Test Plan:
----------
Just updated README.md compatibility table
=> add 6.1.0 release to compatibility table

package.json, packages/cli-hermes/package.json, packages/cli-plugin-metro/package.json, packages/cli/package.json, packages/global-cli/index.js, packages/global-cli/package.json, packages/platform-android/package.json, packages/platform-ios/package.json, packages/tools/package.json, yarn.lock
Summary:
---------
Bump chalk to 4.x, no breaking changes except Node 10+ requirements.
I would like to help with bumping dependencies and code cleanup.
Test Plan:
----------
CI is same.
=> bump chalk to 4.x

.circleci/config.yml, .github/workflows/test.yml
Summary:
---------
Migrate Lint and Unit Test jobs to GitHub Actions. Will try to migrate e2e tests once merged.
Test Plan:
----------
Lint and Unit Test jobs will run on GitHub Actions, not Circle CI.
=> GH Actions: lint & unit tests

packages/platform-android/src/config/__tests__/findLibraryName.test.ts, packages/platform-android/src/config/findLibraryName.ts
Summary:
---------
`codegenConfig` may be missing from `package.json` and we need to account for that.
cc @cortinico 
Test Plan:
----------
Added a test case
=> fix: allow nullish codegenConfig

packages/cli/src/commands/init/editTemplate.ts, packages/cli/src/tools/generator/copyProjectTemplateAndReplace.ts
Summary:
---------
Added entries for new node-version file included in react-native project for execution and testing execution
Test Plan:
----------
Verify execution of the CLI and the tests works
=> Added entries for node-version file for execution and testing execution

package.json, packages/cli-plugin-metro/package.json, yarn.lock
Summary:
---------
cc @dmitryrykun 
Test Plan:
----------
CI
=> chore: upgrade metro to 0.71.3

packages/cli-platform-ios/package.json, yarn.lock
Summary:
---------
Removes unused `plist` and `js-yaml` deps
Test Plan:
----------
=> chore: remove unused ios deps

packages/cli-plugin-metro/package.json, yarn.lock
Summary:
---------
Followup to #1680 
cc @motiz88 @huntie
=> chore: bump metro to 0.72 in cli-plugin-metro

packages/cli-debugger-ui/package.json, yarn.lock
Summary:
---------
Makes warnings go away
Test Plan:
----------
=> chore: update browserlist and parcel-bundler

README.md
Summary:
---------
👋🏼 @adamTrz
=> Add Adam as a maintainer

.github/workflows/test.yml
Summary:
---------
Having both "push" and "pull_request" runs the tests twice, no need to do this.
Test Plan:
----------
CI
=> Optimize CI runs

packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Remove duplicated archs from archs array:
Before:
After:
Test Plan:
----------
=> chore: remove duplicates on archs array

packages/cli-platform-ios/src/commands/runIOS/index.ts
Please find the PR for [issue](https://github.com/react-native-community/cli/issues/1293)
Edit: 
Fixes #1293
=> Add Xconfig from option commandline for iOS for Xcodebuild

packages/cli-platform-android/package.json
Summary:
---------
Removed unused packages from package.json of `cli-platform-android`
Test Plan:
----------
CI
=> chore: cleanup cli-platform-android unused deps

docs/commands.md
Summary:
---------
I found that docs are not synced with code, so I fixed it 😅
Test Plan:
----------
=> docs: update default simulator & fallback simulators.

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Summary:
---------
Added Release Drafter GH Action to create nicer release notes. 
Test Plan:
----------
Once merged we need to run test release and see how it goes 💪
=> chore: added release-drafter GH Action

docs/autolinking.md
Summary:
---------
Test Plan:
----------
=> docs: add Android-rncli.cmake

.github/release-drafter.yml
Small improvements to PR autolabeler
Summary:
---------
Test Plan:
----------
=> chore: update release-drafter.yml

docs/commands.md, packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
Closes https://github.com/react-native-community/cli/issues/1265
Test Plan:
----------
2. Run `yarn react-native run-ios` with `--booted` flag
=> feat: add support for running app on all booted devices and simulators

.husky/pre-commit, package.json, yarn.lock
Summary:
---------
Closes #961 
This PR provides running `yarn lint` command on pre-commit using `husky`
https://user-images.githubusercontent.com/13985840/208865287-32ca4be1-428e-4d36-98cf-4f3767d6901c.mov
Test Plan:
----------
1. Checkout branch
2. Run `yarn install`
3. Made a change in any of packages that should occur with an error, e.g. declare unused variable `const foo = 'bar'`
4. Try to commit
=> chore: add `yarn lint` on pre-commit with husky

README.md
Summary:
---------
Updating compatibility table after releasing React Native 0.71 version
Test Plan:
----------
n/a
=> docs: update readme with version 10.0.0

jest/helpers.ts, package.json, packages/cli-doctor/package.json, packages/cli-doctor/src/commands/info.ts, packages/cli-doctor/src/tools/envinfo.ts, packages/cli-doctor/src/tools/installPods.ts, packages/cli-doctor/src/tools/runAutomaticFix.ts, packages/cli-platform-ios/src/commands/runIOS/index.ts, packages/cli-tools/package.json, packages/cli-tools/src/launchEditor.ts, yarn.lock
Summary:
---------
Added some of the missing type definitions and removed `@ts-ignore` comments where relevant. These changes do not include `metro`, as it probably requires updating types definitions in DefinitelyTyped repo first - together with @szymonrybczak we have a plan to investigate and update it as well
Test Plan:
----------
n/a
=> refactor: add missing type definitions

__e2e__/__snapshots__/config.test.ts.snap
Summary:
---------
Fix failing snapshots for e2e tests. 
Test Plan:
----------
E2E job should be green again.
=> fix: e2e tests snapshot

README.md
Summary:
---------
Make compat table up to date for RN 0.72.
=> chore: update compatibility table

packages/cli-doctor/src/tools/healthchecks/index.ts
Summary:
---------
Since the version check for Ruby isn't applicable for all platforms, moving it to `iOS` instead of `common`
Test Plan:
----------
2. Link the cli-doctor using : `yarn link`
```
(base) arushikesarwani@arushikesarwani-mbp cli-doctor % yarn link
yarn link v1.22.10
success Registered "@react-native-community/cli-doctor".
info You can now run `yarn link "@react-native-community/cli-doctor"` in the projects where you want to use this package and it will be used instead.
✨  Done in 0.04s.
```
3. In the example React Native app(Awesome Project), run `yarn link "@react-native-community/cli-doctor"`
4. Run the CLI Doctor using : `npx @react-native-community/cli doctor`
**BEFORE :**
```
(base) …
```
=> fix : moving Ruby check to iOS

__e2e__/__snapshots__/config.test.ts.snap, __e2e__/config.test.ts, __e2e__/root.test.ts
Summary:
---------
Fix e2e tests failing.
Test Plan:
----------
All tests should be green.
=> fix: e2e tests

README.md
Summary:
---------
Recently I saw that build badge in `README.md` file is getting informations from Circle CI.
Test Plan:
----------
=> docs: change build badge source

packages/cli-doctor/src/tools/healthchecks/ruby.ts, packages/cli-doctor/src/tools/healthchecks/xcodeEnv.ts
Summary:
---------
Fixes falling tests on `main`.
Test Plan:
----------
=> fix: tests

packages/cli-doctor/src/tools/healthchecks/cocoaPods.ts, packages/cli-doctor/src/tools/installPods.ts
Summary:
---------
Since we have `Gemfile` in the RN template project by default, we must have `Ruby`, so it doesn't make sense to ask users to install with `Brew`, because they need to have `Ruby` installed anyway.
Test Plan:
----------
```
node /path/to/react-native-cli/packages/cli/build/bin.js init ProjectName
```
=> fix: remove installing `cocoapods` with `brew`

packages/cli-doctor/package.json, packages/cli-doctor/src/tools/healthchecks/adb.ts, packages/cli-doctor/src/tools/healthchecks/index.ts, packages/cli-doctor/tsconfig.json, packages/cli-platform-android/src/commands/runAndroid/index.ts, packages/cli-platform-android/src/index.ts, packages/cli-tools/src/doclink.ts
Summary:
---------
Accidentally closed https://github.com/react-native-community/cli/pull/1880 , for previous comments refer to it.
Adding check for `adb devices` in doctor that will verify if the android device is attached correctly by listing the available devices and also verify if the reverse proxy for the Android device has been set through `adb reverse --list`
Issue : https://github.com/react-native-community/cli/issues/1852
Test Plan:
----------
2. Link the cli-doctor using : `yarn link`
3. In the example React Native app(Awesome Project), run `yarn link "@react-native-community/cli-doctor"`
4. Run the CLI Doctor using : `npx @react-native-community/cli doctor`
**Success:**
``` …
```
=> feat : Add adb devices and reverse proxy test in cli-doctor 

docs/autolinking.md
Summary:
---------
Fix broken links as react-native repo structure changes
Test Plan:
----------
=> docs: update react-native Podfile template link

packages/cli-doctor/src/tools/runAutomaticFix.ts, packages/cli-platform-ios/src/commands/runIOS/index.ts
Summary:
---------
- Replaces `ora` direct usage with `getLoader`.
- Fixes eslint warning with duplicate variable name.
Test Plan:
----------
- No eslint warnings.
- CI Green. ✅
=> chore: improve codebase

__e2e__/init.test.ts
Summary:
---------
Make codebase better :)
Test Plan:
----------
CI green ✅
=> chore: use slash for windows paths

packages/cli-doctor/src/commands/doctor.ts, packages/cli-doctor/src/tools/runAutomaticFix.ts
Summary:
---------
Handle and log errors in doctor cli for automatic fixes
Issue: #1936
=> fix: add logger to doctor unhandled errors

CONTRIBUTING.md
Summary: yarn link @react-native-community/cli-config
---------
Test Plan: no
----------
Checklist
----------
=> docs: CONTRIBUTING.md typo error

packages/cli-platform-ios/README.md, packages/cli-platform-ios/src/commands/buildIOS/index.ts
Summary:
---------
Make docs better :)
=> fix: typo in option description

packages/cli-doctor/src/tools/healthchecks/__tests__/jdk.test.ts, packages/cli-doctor/src/tools/versionRanges.ts
Summary:
---------
Closes #2044 
Checklist
----------
=> feat: update doctor to reflect Java >= 17

docs/platforms.md
Summary:
---------
Just a small fix in docs that adds `Android TV` to the list of possible targets.
Test Plan:
----------
Checklist
----------
=> Add AndroidTV to platforms.md docs

packages/cli-doctor/package.json, yarn.lock
Summary:
---------
Potential fix for https://github.com/react-native-community/cli/issues/2094
Test Plan:
----------
CI Green
Checklist
----------
=> bump: `envinfo` to 7.10.0

.eslintrc.js, packages/cli-clean/src/__tests__/clean.test.ts
Test Plan:
----------
No eslint warnings ✅
Checklist
----------
=> fix: remove eslint warnings

README.md
Summary:
---------
Fixes https://github.com/react-native-community/cli/issues/2030
Checklist
----------
=> feat(docs): update section related to updating CLI

jest/helpers.ts
Reverts react-native-community/cli#2061
=> Revert "chore(e2e): check for undefined code before printing fail"

packages/cli-platform-android/README.md, packages/cli-platform-android/src/commands/buildAndroid/index.ts, packages/cli-platform-android/src/commands/runAndroid/getTaskNames.ts, packages/cli-platform-android/src/commands/runAndroid/index.ts, packages/cli-platform-android/src/commands/runAndroid/listAndroidTasks.ts, packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts
Summary:
---------
Porting #2144 back to 11.x
Test Plan:
----------
Need someone to test this locally, I only cherry-picked and resolved merge conflicts
Checklist
----------
=> perf: remove Gradle task check on run-android #2144 (11.x backport)

CODEOWNERS
Summary:
---------
Adding @cipolleschi and me to the iOS/Android parts of the CLI
=> Add Android/iOS Sections to CODEOWNERS

CONTRIBUTING.md
Summary:
---------
Adds information about running CLI from source.
=> feat(docs): mention running CLI from source

.github/ISSUE_TEMPLATE/bug_report.md
Summary:
---------
In some cases it will solve people's issue, and it will stop them from creating issue.
=> feat: mention `doctor` command in issue template

__e2e__/__snapshots__/config.test.ts.snap
Summary:
---------
Major RN version was bumped, so this test needs to be updated.
Test Plan:
----------
CI green
Checklist
----------
=> test: update snapshot for e2e config test

packages/cli-platform-apple/src/__tests__/pods.test.ts, packages/cli-platform-apple/src/commands/buildCommand/buildProject.ts, packages/cli-platform-apple/src/commands/buildCommand/createBuild.ts, packages/cli-platform-apple/src/commands/buildCommand/simulatorDestinationMap.ts, packages/cli-platform-apple/src/commands/logCommand/createLog.ts, packages/cli-platform-apple/src/commands/runCommand/createRun.ts, packages/cli-platform-apple/src/commands/runCommand/getPlatformInfo.ts, packages/cli-platform-apple/src/commands/runCommand/runOnDevice.ts, packages/cli-platform-apple/src/commands/runCommand/runOnSimulator.ts, packages/cli-platform-apple/src/config/__tests__/findPodfilePath.test.ts, packages/cli-platform-apple/src/config/findPodfilePath.ts, packages/cli-platform-apple/src/config/supportedPlatforms.ts, packages/cli-platform-apple/src/tools/pods.ts, packages/cli-platform-apple/src/types.ts
Summary:
---------
This PR adds strict typing for supported platforms inside of `cli-platform-apple`.
Part of #2217 
Test Plan:
----------
CI Green
Checklist
----------
=> feat: add strict typing for supported platforms

.github/workflows/test.yml
Summary:
---------
In situations like https://github.com/react-native-community/cli/pull/2255, it would be nice to run tests too, to check if everything is fine. In this PR I also included running tests on branches which are following this syntax: `'[0-9]+.x'` (that's how we're naming release branches).
=> ci: run tests on every branch

packages/cli-doctor/package.json, packages/cli-hermes/README.md, packages/cli-hermes/package.json, packages/cli-hermes/src/profileHermes/downloadProfile.ts, packages/cli-hermes/src/profileHermes/index.ts, packages/cli-hermes/src/profileHermes/metroBundleOptions.ts, packages/cli-hermes/src/profileHermes/sourcemapUtils.ts, yarn.lock
Summary:
---------
Backports https://github.com/react-native-community/cli/pull/2299
=> fix(12.x): replace `ip` package with default value and `--host` flag

docs/healthChecks.md
Summary:
---------
Fixing syntax error in health check docs
Test Plan:
----------
n/a
Checklist
----------
=> docs: fix syntax error in health check docs

packages/cli-server-api/package.json, yarn.lock
Summary:
---------
Context: https://github.com/facebook/react-native/pull/43687
It's easier for now to downgrade inside CLI rather that make an upgrade in Core.
Test Plan:
----------
CI
Checklist
----------
=> fix: downgrade `ws` package

.github/workflows/test.yml
Reverts react-native-community/cli#2386
=> Revert "ci: skip windows e2e tests in specific scenario"

docs/init.md
Summary:
---------
Flag `--npm` is deprecated and will be removed soon
=> docs: update init.md

CONTRIBUTING.md
Summary:
---------
Document manual publish instructions.
Test Plan:
----------
@szymonrybczak approval (he recently got through the process of making his first release)
Checklist
----------
=> docs: document manual publish instructions

packages/cli/src/commands/init/init.ts
Summary:
---------
**NOTE:** I'll only land once `react-native@0.75.0-rc.1` is released.  [Track here](https://github.com/orgs/reactwg/projects/11).
[Follow up task](https://github.com/react-native-community/cli/pull/2424#pullrequestreview-2135136909) from this change.
Test Plan:
----------
Checklist
----------
=> chore: remove fix for react-native@0.75.0-rc.0

.github/workflows/nigthly-release.yml
Summary:
---------
Latest nightly failed, but we don't know the reason - let's show the debug logs and maybe it'll help us fix the reason.
Test Plan:
----------
Let's wait for the next nightly release.
Checklist
----------
=> ci: add debug logging for nightly releases

__e2e__/__snapshots__/config.test.ts.snap
Summary:
---------
Updates snapshot
Test Plan:
----------
Checklist
----------
=> test: fix e2e test for 0.76

README.md
Summary:
---------
Prepare for 16.x release targeting RN 0.77
Test Plan:
----------
Checklist
----------
=> docs: update compat table

__e2e__/__snapshots__/config.test.ts.snap
Summary:
---------
Update snapshot of e2e test that runs off RN latest
Test Plan:
----------
Checklist
----------
=> test: fix e2e test snapshot

CODEOWNERS, README.md
Changes code owners to me, as an active maintainer. 
Thanks for all the support you've made @adamTrz! I believe there's no need for GH to ping you to request your reviews for every PR.
Also included @huntie under "Maintainers" section in `README.md` file, thank you for contributions and input 🫡
=> Update maintainers to reflect current state of things

README.md
Add react-native 0.82 to README.md
=> Add react-native 0.82 to README.md
